### DISCUSSION TITLE
retrieving empty traces from jaeger

### DISCUSSION THREAD

**Discussion by sylvainOL** [kiali/kiali#3677] [Q&A] [answered]
Hello,
I've installed jaeger via jaeger operator and kiali via kiali operator:

jaeger install:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: istio
  namespace: observability
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    dependencies:
      enabled: true
      schedule: "55 23 * * *"
      sparkMaster: ""
      resources:
        requests:
          memory: "4096Mi"
        limits:
          memory: "4096Mi"
    options:
      es:
        server-urls: https://elasticsearch-es-http.observability.svc:9200
        index-prefix: jaeger
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elasticsearch-es-http-certs-public
```

kiali install:
```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  auth:
    strategy: anonymous
  istio_component_namespaces:
    prometheus: monitoring
  external_services:
    grafana:
      in_cluster_url: http://prometheus-stack-grafana.monitoring
    prometheus:
      url: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
    tracing:
      in_cluster_url: http://istio-query.observability:16686
```

everything seems OK except for traces retrieval

I see these traces (I've set kiali on debug):
```
2021-02-05T09:02:45Z DBG Prepared Jaeger query: http://istio-query.observability:16686/api/traces?limit=100&service=.keycloak&start=1612515165527000
```

the result it gives is the following (did the same request with curl):
```json
{"data":[],"total":0,"limit":0,"offset":0,"errors":null}
```

In order to have some traces, I need to add in front the servie name (not just the namespace):

`curl "http://10.43.254.84:16686/api/traces?limit=100&service=keycloak-postgresql.keycloak&start=1612515745020000"`

gives a "lot" of answers (36 elements in `.data`).

is it something I'm doing wrong?
in the about:
```
Kiali UI: 
    1.29.0 (e8935a2a7f292385bb2d4ee307caf43c8abb369c)
Kiali Server
    v1.29.0 (a86a8fcffeb002d35fc0964dfd728958295b8387)
Kiali Container
    v1.29.0

Components

Istio
    1.8.2 
Prometheus
    2.24.0 
Kubernetes
    v1.19.7 
```
