### DISCUSSION TITLE
Not handling OpenId code flow authentication: No nonce code present. Login window timed out

### DISCUSSION THREAD

**Discussion by eperdeme** [kiali/kiali#3716] [Q&A] [answered]
**General remarks**

**Describe the bug**

We've been attempting to integrate our Oauth server (ping federate) with Kiali using Authorization Code flow and exhibiting strange issues. The session only lasts 5 minutes once the user has successful logged in and can see dashboard/config in Kiali UI.

In the log we see this error after the user has completed the login.

```
INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
```

I find it strange Kiali is letting the user view config/etc but also says the login window timed out, which I guess means the auth has not been fully successful and the 5mins of usage the user gets stems from 'authentication_timeout'. 

I'm happy to accept this is something my side to configure, but I'm not sure what I'm missing here. Any clues would be much appreciated. 

```
auth:
 strategy: openid
 openid:
    client_id: "dev-kiali"
    disable_rbac: true
    issuer_uri: "https://sso.dev.corp.com"
    scopes:
    - "openid"
    - "email"
    username_claim: sub
    https_proxy: "http://webproxy:3128"
    http_proxy: "http://webproxy:3128"
```

Payload
```
{
  "sub": "nflynn@corp.co.uk",
  "aud": "dev-kiali",
  "jti": "ZKbdVusEYJLlhD7BGSwwQz",
  "iss": "https://sso.dev.corp.com",
  "iat": 1613507120,
  "exp": 1613507420,
  "auth_time": 1613505379,
  "nonce": "0c49c0aac36587219ffd8d2f6efc268d42d1738b9fd1674ca0abb4a1"
}
```
**Versions used**
Kiali:1.30.0
Istio:1.8
Kubernetes flavour and version: EKS - v1.18.9-eks-d1db3c

**To Reproduce**
1. Configure Ping Federate for the oauth app
2. Login to Kiali following the SSO
3. Get booted out after 5 minutes 

**Expected behavior**
I stay logged.
