### DISCUSSION TITLE
unknown and passthrough?

### DISCUSSION THREAD

**Discussion by dbones** [kiali/kiali#3747] [Q&A]
**General remarks**

I have a service that uses Redis, and a couple of externals sites, however, Kiali is not showing this

I believe i have setup the 2 components correctly, however im still somewhat stuck.

**Describe the issue**

- the traffic animation connecting to a passthrough
- copies of the service and app in an unknown cluster
- a link between the actual app and redis, but no animation of traffic (but the traffic on the right shows)
- link between the app and redis does not show with mTLS
- configuration looks to be correct (looked on every tab and fixed all KIA**** issues)

![image](https://user-images.githubusercontent.com/183849/109424153-62a8e780-79da-11eb-955a-1bab2a446b9f.png)

**Versions used**
Kiali: v1.29.1
Istio: 1.9 (configured with istoctl and addon kubectl apply deployments for Prometheus, Kiali, Graphana, and Jaeger)
Kubernetes flavour and version: 1.19 running on Scaleway with Flannel CNI (same issue for Cilium)

**To Reproduce**

Redis

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    istio-injection: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: data
  name: cache
  labels:
    app: cache
    component: cache
    version: v1
spec:
  selector:
    matchLabels:
      component: cache
  template:
    metadata:
      labels:
        component: cache
        app: cache
        version: v1
    spec:
      containers:
      - name: cache
        image: redis:alpine
        resources: {}
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  namespace: data
  name: cache
  labels:
    app: cache
spec:
  selector:
    app: cache
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: tcp
```

App Setup

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: chatterbot
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: chatterbot
  name: service

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: chatterbot
  name: serviceconfig
data:
  svcconfig: |-
    {
      "Redis":{
        "ConnectionString": "cache.data"
      },
      
      "Jaeger": {
        "Enabled":  true, 
        "AgentHost": "jaeger-agent.istio-system"
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chatterbot
  name: chatterbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatterbot
      version: v1
  template:
    
    metadata:  
      labels:
        app: chatterbot
        version: v1
      
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.1.1.1/32
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-values: location-to-secrests/app
        vault.hashicorp.com/agent-inject-template-values: |-
          {{- with secret "location-to-secrests/app" -}}
              {{ range $k, $v := .Data.data }}
                  {{ $k }}: {{ $v }}
              {{ end }}
          {{ end }}
    
    spec:
      serviceAccountName: service
      
      containers:
      - image: registry/chatterbot:v123
        imagePullPolicy: IfNotPresent
        name: chatterbot
        resources: {}
        volumeMounts:
          - name: config
            mountPath: /app/env
        ports:
        - containerPort: 1337 #see comment below

      volumes:
        - name: config
          configMap:
            name: serviceconfig
            items:
              - key: svcconfig
                path: appSettings.json
---

#according to istio docs, this is required, even if we do not expose a port
apiVersion: v1
kind: Service
metadata:
  namespace: chatterbot
  name: chatterbot
  labels:
    app: chatterbot 
spec:
  selector:
    app: chatterbot
  ports: 
  - port: 1337
    targetPort: 1337
    protocol: TCP
    name: http
    
---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  namespace: chatterbot
  name: discord.com
spec:
  location: MESH_EXTERNAL
  hosts:
    - discord.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS

```

**Expected behavior**

- unknown cluster is not present
- traffic animation between redis and the app
- there is no passthrough traffic
