### DISCUSSION TITLE
Not getting https enabled by default via CR as described

### DISCUSSION THREAD

**Discussion by somejfn** [kiali/kiali#3867] [General]
Hi,

Using latest operator/kiali image v1.32 on k8s 1.19,  I was expecting to get https enabled by default as described in the reference CR and leaving the spec.identity undefined but whatever I do,  the operator translate this into the empty string cert_file/private_key_file disabling https.  

I.e. the CR:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    helm.sh/chart: kiali-operator-1.32.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.32.0"
    app.kubernetes.io/version: "v1.32.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
annotations:
  ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  api:
    namespaces:
      exclude:
      - "istio-operator"
      - "kube.*"
      - "default"
  deployment:
    logger:
      log_level: debug
    accessible_namespaces:
    - '**'
    image_version: "v1.32.0"
    ingress_enabled: true
  identity: {}
```

But the Kiali configmap generated still has the empty strings:

```
    identity:
      cert_file: ''
      private_key_file: ''
```

And thus https disabled:
```
$ k logs kiali-5f6d64ddcd-q9dxj -n istio-system  
2021-04-12T15:03:12Z INF Kiali: Version: v1.32.0, Commit: 166ffcc9edfc6fdd8c6ce8e74eb5670414b949f5

2021-04-12T15:03:12Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2021-04-12T15:03:12Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2021-04-12T15:03:12Z INF Using authentication strategy [openid]
2021-04-12T15:03:12Z INF Kiali: Console version: 1.32.0
2021-04-12T15:03:12Z INF Updating base URL in index.html with [/kiali]
2021-04-12T15:03:12Z DBG Base URL has been updated to [<base href="/kiali/"]
2021-04-12T15:03:12Z INF Generating env.js from config
2021-04-12T15:03:12Z DBG The content of /opt/kiali/console/env.js will be:
window.WEB_ROOT='/kiali';

2021-04-12T15:03:12Z INF Server endpoint will start at [:20001/kiali]
2021-04-12T15:03:12Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-04-12T15:03:12Z INF Starting Metrics Server on [:9090]
```

What am I doing wrong ?

thanks !

**Comment by jmazzitelli** [comment]
Ah.. I think [the example kiali_cr.yaml docs](https://github.com/kiali/kiali-operator/blob/v1.32.0/deploy/kiali/kiali_cr.yaml#L635-L650) are outdated. It used to be that Istio would create certs that Kiali would use, but it no longer does. So if you are not on OpenShift but rather some other k8s environment, the default is empty string (see [here](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L319-L328)). ([On OpenShift, certs can be automatically created](https://github.com/kiali/kiali-operator/blob/v1.32.0/roles/default/kiali-deploy/templates/openshift/service.yaml#L13), thus Kiali can use those.) But since Istio no longer by default generates the certs, you have to get them yourself in some cluster-specific way (e.g. your specific k8s cluster environment may provide you with a service annotation you can specify that tells it to create the certs - you can [put that service annotation on the kiali service](https://github.com/kiali/kiali-operator/blob/v1.32.0/deploy/kiali/kiali_cr.yaml#L345-L347) and then set this CR identity field appropriately).

Note that most people don't use the Kiali https endpoint anyway - they access Kiali over an Istio Gateway or a k8s Ingress and they enable https at that point - but then going to Kiali itself over http. See the Istio docs on this here: https://istio.io/latest/docs/tasks/observability/gateways/

**Reply by jmazzitelli** [reply]
PR to fix the kiali_cr docs: https://github.com/kiali/kiali-operator/pull/285

**Reply by somejfn** [reply]
thank you !  I went the ingress + tls way and Kiali is https enabled...  but now I have an issue with openid authentication with keycloak.  I thought my issue was having Kiali over http vs keycloak https but seems I have the same problem.

I've setup keycloak as shown [here](https://kiali.io/documentation/latest/configuration/authentication/openid/#_using_with_keycloak) but whenever I authenticate successfully,  the redirection sends me back to the Kiali login page.  In kiali's logs I only get this (raw token truncated):

```
2021-04-12T15:40:53Z INF Not handling OpenId code flow authentication: State parameter is empty or invalid.
2021-04-12T15:41:45Z DBG Raw token to validate: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaSnNKTVRrUF84RkhWUTWDW1p5eKV0Ol3SpL4vxS5LSGk9q1Tebbfa...
2021-04-12T15:41:45Z INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
```

My full Kiali CR:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    helm.sh/chart: kiali-operator-1.32.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.32.0"
    app.kubernetes.io/version: "v1.32.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
annotations:
  ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  api:
    namespaces:
      exclude:
      - "istio-operator"
      - "kube.*"
      - "default"
  auth:
    strategy: "openid"
    openid:
      client_id: "kiali-lab"
      issuer_uri: "https://keycloak-001.kd.io/auth/realms/kubernetes"
      insecure_skip_verify_tls: true
      username_claim: "email"
      disable_rbac: true
      scopes: ["openid", "groups", "email"]
  deployment:
    logger:
      log_level: debug
    accessible_namespaces:
    - '**'
    image_version: "v1.32.0"
    ingress_enabled: true
    override_ingress_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: my-nginx-ingress
          nginx.ingress.kubernetes.io/secure-backends: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
          nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
      spec:
        tls:
        - hosts:
          - kiali.my-nginx-ingress.lab01.kd.io
          secretName: kiali-tls
        rules:
        - host: kiali.a1-nginx-ingress.lab01.kd.io
          http:
            paths:
            - path: /kiali
              backend:
                serviceName: kiali
                servicePort: 20001
```


Any idea how I can troubleshoot this further ?
