### DISCUSSION TITLE
VirtualService is pointing to a non-existent gateway message

### DISCUSSION THREAD

**Discussion by somejfn** [kiali/kiali#3883] [General]
Hi,

Under my operator deployed Kiali v1.32,  I have everything under the istio-system namespace (istiod, ingress gateway, kiali, prometheus and grafana)

Application in user namespaces are using the ingress gateway in the istio-system namespace,  but Kiali complains the gateway can't be found:  "VirtualService is pointing to a non-existent gateway"

The gateway "ingress-gateway" has the default labels  app=istio-ingressgateway

The virtualservice in the user namespace "doo"
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - frontend.doo.svc.cluster.local
  gateways: 
  - mesh
  - istio-system/ingress-gateway      <----- Kiali highlighting this line 
  http:
  - name: frontend
    route:
    - destination:
        host: frontend.doo.svc.cluster.local
```

Something I can fix in Kiali configuration ?

Adding those in Kiali  CR had no effect:

```
  istio:
    component_status:
      enabled: true
      components:
      - app_label: istiod
        is_core: true
        namespace: istio-system
      - app_label: istio-ingressgateway
        is_core: true
        namespace: istio-system
      - app_label: istio-egressgateway
        is_core: false
        namespace: istio-system
```

**Comment by lucasponce** [comment]
But "istio-system/ingress-gateway" is a Istio Gateway configuration in your environment ?

**Reply by lucasponce** [reply]
In case it helps, I'm still using these gateways as examples for the addons:

https://istio.io/latest/docs/tasks/observability/gateways/

And I see them correctly defined in Kiali as well.

Let me know if it helps.

**Reply by somejfn** [reply]
Here's my ingress gateway deployed in istio-system.  It is working for the vs above and looks all ligit to me so I wonder what is the actual validation done that fails. Wonder if it's not the wildcard in the host that is causing the config error. 

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.a9igw.lab01.kd.io"
   
```
