### DISCUSSION TITLE
cannot use kiali and gcp/google openid

### DISCUSSION THREAD

**Discussion by jonbcampos-alto** [kiali/kiali#3889] [Q&A]
**General remarks**
I am running what should be the appropriate versions of kiali to use Google openid successfully but can't make it happen. I am setting up the credentials in GCP and setup kiali and just can't make it work.

**Describe the bug**
After logging in/auth-ing with Google/GCP oauth2 flow I get the following visible error on the kiali login screen: `Login unsuccessful: the OpenID token was rejected`

In the javascript console I see `POST http://localhost:20001/kiali/api/authenticate 403 (Forbidden)`.

**Versions used**
Kiali: v1.32
Istio: v1.9.2
Kubernetes flavour and version: GKE 1.18.16-gke.502

**To Reproduce**
1. Setup Kiali Operator
2. Add openid to authentication
```
    openid:
#      api_proxy: ""
#      api_proxy_ca_data: ""
      authentication_timeout: 300
      authorization_endpoint: "https://accounts.google.com/o/oauth2/auth"
      client_id: "<client-id>.apps.googleusercontent.com"
      disable_rbac: true
#      http_proxy: ""
#      https_proxy: ""
#      insecure_skip_verify_tls: false
      issuer_uri: "https://www.googleapis.com/oauth2/v1/certs"
      scopes: ["openid", "email"]
      username_claim: "sub"
```
3. Add a secret with `oidc-secret`
4. Restart pods
5. run `istioctl dashboard kiali`
6. Try to login
7. see error on response

Logs show the following lines:
`Not handling OpenId code flow authentication: No nonce code present. Login window timed out.`
`Error when fetching OpenID provider's metadata: cannot fetch OpenId Metadata (HTTP response status = 404 Not Found)`
`Not handling OpenId code flow authentication: No nonce code present. Login window timed out.`
`Error when fetching OpenID provider's metadata: cannot fetch OpenId Metadata (HTTP response status = 404 Not Found)`

**Expected behavior**
Be able to login.
