### DISCUSSION TITLE
Resource limits for kiali aren't set

### DISCUSSION THREAD

**Discussion by psibi** [kiali/kiali#4052] [Q&A] [answered]
**Describe the bug**

I use the helm chart to install kiali and it produces the following Kiali CR (putting only the relevant parts here):

``` yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
spec:
  deployment:
    accessible_namespaces:
    - '**'
    ingress_enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 100Mi
```

Now if I describe the kaili resource, I see that it has proper resource limits in it (pasting only the relevant parts):

``` shellsession
$ kubectl describe kiali -n istio-system
Name:         kiali
Namespace:    istio-system
Labels:       app=kiali-operator
API Version:                                   kiali.io/v1alpha1
Kind:                                          Kiali
Spec:
  API:
    Namespaces:
      Exclude:
        istio-operator
        kube-system
        kube-public
        kube-node-lease
  Auth:
    Strategy:  header
  Deployment:
    accessible_namespaces:
      **
    ingress_enabled:  false
    Resources:
      Limits:
        Cpu:     200m
        Memory:  100Mi
      Requests:
        Cpu:     200m
        Memory:  100Mi
...
```

Now if I check the actual deployment (or it's associated pod), I don't see any resource limits being set:

``` shellsession
$ kubectl describe pods/kiali-5b7bc94c9f-rmgt6 -n istio-system | rg Limits
```

**Versions used**

Kiali: "quay.io/kiali/kiali-operator:v1.33"
Istio: 1.9
Kubernetes: 1.19 (EKS)

**To Reproduce**

1. Install kaili with it's CR's deployment to some resource request and limits:

``` shellsession
resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 200m
    memory: 100Mi
```

2. Apply the Kiali kind manifest.
3. Check the kiali pod (not the kiali's operator pod) and you will be able to see that it won't have resource requests or limits set.

**Expected behavior**

The deployment and pod's resource request and limit should be set.
