### DISCUSSION TITLE
Kiali unable to get service details and health information

### DISCUSSION THREAD

**Discussion by shashanksapre** [kiali/kiali#4239] [General]
**Describe the bug**
Kiali gives error when accessing dashboard and opening services tab.

2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: ingress-nginx-controller-84ff66d54c-4kbns]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: ingress-nginx-controller-84ff66d54c-4kbns]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z ERR unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port

For UI issues please also add a screenshot that shows the issue.
Services Tab
![image](https://user-images.githubusercontent.com/6241313/127290642-9aeb8286-3fa3-49ed-acf2-ce625a4d4f47.png)
Other Tabs
![image](https://user-images.githubusercontent.com/6241313/127291209-8e8d927c-15cc-49bd-8b6f-0bf80f6449a4.png)

**Versions used**
Kiali: 1.36.2
Istio: 1.10.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) (1.21.3) (minikube)

**To Reproduce**
Install istio using helm chart
Install kiali-server using helm chart with following values:

```
values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.36.2
      version_label: v1.36.2
      pod_annotations:
        sidecar.istio.io/inject: "false"
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      ingress_enabled: true
      logger:
        log_level: "debug"
      override_ingress_yaml:
        metadata:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/service-upstream: "true"
            nginx.ingress.kubernetes.io/upstream-vhost: kiali.istio-system.svc.cluster.local
      secret_name: kiali
    istio_namespace: istio-system
    server:
      port: 20001
      metrics_enabled: true
      metrics_port: 80
      web_root: /kiali
      web_fqdn: kiali.local
    external_services:
      prometheus:
        url: http://prometheus-server.istio-system
      custom_dashboards:
        enabled: true
```

**Expected behavior**
opening kiali dashboard should run without any errors

**Comment by xeviknal** [comment]
Hello there,

it looks like your KubeAPI doesn't have access to your control plane namespace. Kiali does a PodProxy or PortForward from kiali pod to istiods. This call goes through the KubeAPI. If you have some protection between the KubeAPI and the istiod pods, kiali can't fetch certain information.

Check the FAQ entry we have with regards to this specific situation: https://kiali.io/documentation/latest/faq/#google-cloud-private-cluster

Can you please clarify which Kubernetes flavour and version are you using? are you using minikube with openshift?

**Comment by shashanksapre** [comment]
Thank you @xeviknal for the response,

Well I am testing everything locally via minikube running as docker container on a ubuntu machine. kubernetes version is 1.21.3

I looked at the docs and it's specific to GKE. Where can I find a bit more generalised documentation or installation guide?

**Comment by xeviknal** [comment]
Does this work for you?

```
kubectl port-forward -n istio-system ${ISTIOD_POD} 15014
curl http://localhost:15014/debug/syncz
```

**Comment by shashanksapre** [comment]
Hi @xeviknal 

Yes, it does.

It gives info of the two pods that are running with istio sidecar

**Comment by shashanksapre** [comment]
I noticed that this doesn't happen if I use the kiali addon file for istio

[kiali.yaml](https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/kiali.yaml)

**Comment by xeviknal** [comment]
How did you install the previous non-working kiali? It might be because of lack of permissions for kiali to use the `pod/port-forward` subresource.

**Comment by shashanksapre** [comment]
Using flux.

Setting the chart's source referencing to the github repo

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  # The interval at which to check the upstream for updates
  interval: 30m
  # The repository URL, can be a HTTP/S or SSH address
  url: https://github.com/kiali/helm-charts
  # The Git reference to checkout and monitor for changes
  # (defaults to master)
  # For all available options, see:
  # https://toolkit.fluxcd.io/components/source/api/#source.toolkit.fluxcd.io/v1beta1.GitRepositoryRef
  ref:
    branch: master
```

Then creating a helmrelease.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  releaseName: kiali
  chart:
    spec:
      chart: ./kiali-server
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  - name: ingress-nginx
    namespace: default
  - name: prometheus
  interval: 5m
  values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.36.0
      version_label: v1.36.0
      pod_annotations:
        sidecar.istio.io/inject: "false"
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      ingress_enabled: false
      logger:
        log_level: "debug"
      override_ingress_yaml:
        metadata:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/service-upstream: "true"
            nginx.ingress.kubernetes.io/upstream-vhost: kiali.istio-system.svc.cluster.local
      secret_name: kiali
    istio_namespace: istio-system
    kubernetes_config:
      excluded_workloads:
      - "CronJob"
      - "DeploymentConfig"
      - "ReplicationController"
    server:
      port: 20001
      metrics_enabled: true
      metrics_port: 9090
      web_root: /kiali
      # web_fqdn: kiali.local
    external_services:
      prometheus:
        url: http://prometheus-server.istio-system:9090
      custom_dashboards:
        enabled: true
```

**Comment by xeviknal** [comment]
I am not familiar with this installation process. Right now, the ones supported are these ones here: https://kiali.io/documentation/latest/installation-guide/#_installation

However, I think that some cluster permissions have to be missing for the kiali pod. Could you retrieve the clusterrole for kiali and share it in the issue? There should be the `logs/portforward` with `create` and `post` permissions. Won't work otherwise.

**Reply by shashanksapre** [reply]
```
kubectl describe clusterrole kiali
Name:         kiali
Labels:       app=kiali
              app.kubernetes.io/instance=kiali
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kiali
              app.kubernetes.io/part-of=kiali
              app.kubernetes.io/version=v1.36.0
              helm.sh/chart=kiali-server-0.0.0
              helm.toolkit.fluxcd.io/name=kiali
              helm.toolkit.fluxcd.io/namespace=istio-system
              version=v1.36.0
Annotations:  meta.helm.sh/release-name: kiali
              meta.helm.sh/release-namespace: istio-system
PolicyRule:
  Resources                            Non-Resource URLs  Resource Names  Verbs
  ---------                            -----------------  --------------  -----
  pods/portforward                     []                 []              [create post]
  tokenreviews.authentication.k8s.io   []                 []              [create]
  experiments.iter8.tools              []                 []              [get list watch create delete patch]
  *.networking.istio.io                []                 []              [get list watch create delete patch]
  *.security.istio.io                  []                 []              [get list watch create delete patch]
  namespaces                           []                 []              [get list watch patch]
  pods                                 []                 []              [get list watch patch]
  replicationcontrollers               []                 []              [get list watch patch]
  services                             []                 []              [get list watch patch]
  deploymentconfigs.apps.openshift.io  []                 []              [get list watch patch]
  daemonsets.apps                      []                 []              [get list watch patch]
  deployments.apps                     []                 []              [get list watch patch]
  replicasets.apps                     []                 []              [get list watch patch]
  statefulsets.apps                    []                 []              [get list watch patch]
  cronjobs.batch                       []                 []              [get list watch patch]
  jobs.batch                           []                 []              [get list watch patch]
  daemonsets.extensions                []                 []              [get list watch patch]
  deployments.extensions               []                 []              [get list watch patch]
  replicasets.extensions               []                 []              [get list watch patch]
  statefulsets.extensions              []                 []              [get list watch patch]
  configmaps                           []                 []              [get list watch]
  endpoints                            []                 []              [get list watch]
  pods/log                             []                 []              [get list watch]
  projects.project.openshift.io        []                 []              [get]
  routes.route.openshift.io            []                 []              [get]

```

**Comment by jmazzitelli** [comment]
There must be something your custom installation process is doing differently that is causing the failure. The fact it works for you when you run with the Istio addon yaml for Kiali (which is built directly from the Kiali helm chart) says that there is something else your installation process is doing that is incorrect.

Compare your installation procedures versus installing directly via the Kiali server helm chart (e.g. look at the resulting resources) and you'll probably find the problem.

As @xeviknal says, we don't support all the possible different customized installation procedures out there - if you follow one of the install mechanisms mentioned in the [docs here](https://kiali.io/documentation/latest/installation-guide/#_installation) and you see the same problem, that would be important to know.

I can tell you one thing I see already that doesn't look right. You are forcing the Kiali image to be 1.36.0:

```
      image_version: v1.36.0
```

but yet your customized installation mechanism is pulling the helm chart from the master branch:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  # The interval at which to check the upstream for updates
  interval: 30m
  # The repository URL, can be a HTTP/S or SSH address
  url: https://github.com/kiali/helm-charts
  # The Git reference to checkout and monitor for changes
  # (defaults to master)
  # For all available options, see:
  # https://toolkit.fluxcd.io/components/source/api/#source.toolkit.fluxcd.io/v1beta1.GitRepositoryRef
  ref:
    branch: master
```

You can't mix-and-match helm charts with image versions. It is very likely the master branch of the helm chart will NOT set up the environment correctly for an older version of the Kiali image. You must install with the correct version of the helm chart.
