### DISCUSSION TITLE
Openid: "the OpenID token was rejected: the OpenId token is missing the kid header claim"

### DISCUSSION THREAD

**Discussion by 0xgui** [kiali/kiali#4253] [Q&A] [answered]
Hello Kiali Team, 

I have been trying to setup Kiali with OpenID authentication.
After clicking in the Log in with OpenID button in Kiali UI, I'm redirected fine and I am able to input my credentials in the openid server. After submitting them I'm redirected back again to Kiali and after a few seconds I get the following error: the OpenID token was rejected: the OpenId token is missing the kid header claim

I´m using Grafana authentication with the same OpenID server and it works fine.

Do you have any clue on what I'm missing here ?

Logs: 
2021-08-03T16:09:58Z INF Using authentication strategy [openid]
2021-08-03T16:09:58Z INF Kiali: Console version: 1.36.0
2021-08-03T16:09:58Z INF Server endpoint will start at [:20001/kiali]
2021-08-03T16:09:58Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-08-03T16:09:58Z INF Starting Metrics Server on [:9090]
2021-08-03T16:10:56Z INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
2021-08-03T16:10:57Z DBG The AES cookie is mising.
2021-08-03T16:11:29Z ERR the OpenID token was rejected: the OpenId token is missing the kid header claim
2021-08-03T16:11:29Z INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
2021-08-03T16:16:59Z INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
2021-08-03T16:17:00Z DBG The AES cookie is mising.

Kiali CR (using Kiali Operator): 
```
spec:
    auth:
      openid:
        additional_request_params:
          prompt: login
        client_id: kiali-client
        disable_rbac: true
        issuer_uri: https://custom.openid.server
        scopes:
        - openid
        - profile
        username_claim: sub
      strategy: openid
    deployment:
      accessible_namespaces:
      - '**'
      affinity:
        node:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - system
      logger:
        log_level: trace
    external_services:
      grafana:
        auth:
          insecure_skip_verify: true
          type: none
        enabled: false
        in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
        url: ""
      istio:
        component_status:
          components:
          - app_label: istiod
            is_core: true
          - app_label: istio-ingressgateway
            is_core: true
          - app_label: istio-egressgateway
            is_core: false
          enabled: true
        config_map_name: istio
        istio_identity_domain: svc.cluster.local
        istio_injection_annotation: sidecar.istio.io/inject
        istio_sidecar_annotation: sidecar.istio.io/status
        url_service_version: ""
      prometheus:
        url: http://prometheus-operated.istio-system.svc.cluster.local:9090
      tracing:
        auth:
          insecure_skip_verify: true
          type: none
        enabled: false
        in_cluster_url: ""
    istio_namespace: istio-system
```

If you need anything else let me know. 
Thanks,
