### DISCUSSION TITLE
Kiali failing to display Applications / Workloads due to failed cache building

### DISCUSSION THREAD

**Discussion by kencieszykowski** [kiali/kiali#4402] [Q&A] [answered]
We're implementing Istio across our EKS clusters and have found Kiali to be a fantastic way to visualize traffic and data.  However, I'm currently running into an issue here;

Environment:
EKS // Kubernetes v1.18
Kiali // v1.40.0
Istio // v1.11
Both Istio and Kiali are deployed using respective CRs and Operators

Behavior:
The 'Applications' tab does not show anything; looking at container logs shows:
```
2021-09-30T17:44:17Z ERR Error fetching Istio requestauthentications per namespace foo: Kiali cache doesn't support [resourceType: requestauthentications]
2021-09-30T17:44:17Z ERR Error fetching Istio sidecars per namespace foo: Kiali cache doesn't support [resourceType: sidecars]
2021-09-30T17:44:17Z ERR Error fetching Istio peerauthentications per namespace foo: Kiali cache doesn't support [resourceType: peerauthentications]
2021-09-30T17:44:17Z ERR Error fetching Istio envoyfilters per namespace foo: Kiali cache doesn't support [resourceType: envoyfilters]
```

In addition, on the Kiali CR, we have the following configured:
```
spec:
  kubernetes_config:
    cache_istio_types:
    - DestinationRule
    - Gateway
    - ServiceEntry
    - VirtualService
```

I'm nearly at my wits' end here as I can't find anything suggesting this problem and I'm not 100% clear whether the cache is pulling from Prometheus or the Kubernetes API directly. 

Any help or suggestions would be much appreciated!

**Comment by lucasponce** [comment]
This is weird, could you please describe how did you install Istio and Kiali with detail ?
I'd try to investigate with minikube to see if I can get same error.

**Reply by kencieszykowski** [reply]
> This is weird, could you please describe how did you install Istio and Kiali with detail ? I'd try to investigate with minikube to see if I can get same error.

Sure-- let me post some CRDs.  Since we deploy this to each of our clusters, some of the values are parameterized via Helm, but the CR only has the fields we care about / change from default.

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  istio_component_namespaces:
    prometheus: kube-system
  istio_namespace: istio-system
  kubernetes_config:
    burst: 200
    cache_duration: 300
    cache_istio_types:
    - DestinationRule
    - Gateway
    - ServiceEntry
    - VirtualService
  api:
    namespaces:
      exclude:
      - "istio-operator"
      - "kiali-operator"
  auth:
    {{- if .Values.auth.enabled }}
    strategy: openid
    openid:
      client_id: {{ .Values.auth.client_id }}
      disable_rbac: {{ .Values.auth.disable_rbac | default "true" }}
      issuer_uri: "[[redacted]]"
      username_claim: "email"
    {{- end }}
  deployment:
    accessible_namespaces: "**"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1"
    hpa:
      spec:
        maxReplicas: 3
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
    {{- if .Values.ingress.enabled }} 
    service_type: NodePort 
    {{- else  }}
    service_type: ClusterIP
    {{- end }}
    view_only_mode: {{ .Values.options.view_only_mode | default "true" }}
    ingress_enabled: {{ .Values.ingress.enabled | default "false" }}
    override_ingress_yaml:
      metadata:
        annotations:
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.sg }}
          alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.cert }}
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      spec:
        rules:
          - http:
              paths:
                - path: /*
                  backend:
                    serviceName: ssl-redirect
                    servicePort: use-annotation
                - path: 
                  backend:
                    serviceName: kiali
                    servicePort: 20001
            host: {{ .Values.ingress.host }}
    logger:
      log_level: debug
  external_services:
    prometheus:
      url: http://kube-prometheus-stack-prometheus.kube-system:9090
```

And Istio is installed via the Operator via a CR as well.  Not changing a whole lot here from default:

```

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyAdminPort: 15000
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-system
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
```

At this point I'm taking a look at our Prometheus deployment; since I didn't work with that and have little idea how it is currently functioning in our env.  When I was ripping through the install via Minikube there didn't seem to be any issues and everything displayed just fine.  Thanks for the reply and please let me know if you'd like any further info!
