### DISCUSSION TITLE
Unable to have the custom configuration of clusterrole

### DISCUSSION THREAD

**Discussion by sskmail14** [kiali/kiali#4495] [Q&A] [answered]
Hai All,

Version Details
Kiali: v1.42.0
Istio : 1.11.4

Am facing an issue that allows user to edit `Istio Config` from Kiali. Even if I override with my custom yaml its getting overrided with the kiali-operator config after sometime.

I have tried istalling kiali with helm , kiali-operator as desribed in the installation page. [Kiali Docs](https://kiali.io/docs/installation/installation-guide/install-with-helm/)

```
helm repo add kiali https://kiali.org/helm-charts
helm repo update

kubectl create secret generic kiali --save-config --dry-run=client --from-literal="oidc-secret=$kiali_cs" -n $namespace -oyaml | kubectl apply -f -

envsubst < configfiles/addons/kiali_bo_values.yaml | helm upgrade --install\
    --set cr.create=true \
    --set cr.namespace=istio-system \
    -f - \
    --namespace kiali-operator \
    --create-namespace \
    kiali-operator \
    kiali/kiali-operator \
    --version ${kiali_image_version}
```

I would like to remove all create,patch,delete operations as part of clusterrole. Reference - [Clusterrole of Kiali-Opertor helm](https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/clusterrole.yaml)

Kindly suggest if there is a way to override the helm configs.

**Comment by jmazzitelli** [comment]
> Kindly suggest if there is a way to override the helm configs.

You can do this by using these settings (what you are asking for is the onlyViewOnlyMode helm setting, but the other one is probably one you will want to use, too - clusterRoleCreator)

* https://github.com/kiali/helm-charts/blob/v1.42.0/kiali-operator/values.yaml#L36-L39
* https://github.com/kiali/helm-charts/blob/v1.42.0/kiali-operator/values.yaml#L50-L52

```yaml
# Set to true if you want the operator to be able to create cluster roles. This is necessary
# if you want to support Kiali CRs with spec.deployment.accessible_namespaces of '**'.
# Note that this will be overriden to "true" if cr.create is true and cr.spec.deployment.accessible_namespaces is ['**'].
clusterRoleCreator: true

# Set to true if you want to allow the operator to only be able to install Kiali in view-only-mode.
# The purpose for this setting is to allow you to restrict the permissions given to the operator itself.
onlyViewOnlyMode: false
```
