### DISCUSSION TITLE
Kiali throws error when value of accessible_namespaces is changed in CR.

### DISCUSSION THREAD

**Discussion by bj-1795** [kiali/kiali#4607] [Q&A]
I have multi-env cluster, where i want to install kiali in per namespace of application. I have tried to use lablel and accesible_namespaces in CR for this purpose but getting below error:

Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \\"system:serviceaccount:kiali-operator:kiali-operator\\" cannot create resource \\"namespaces\\" in API group \\"\\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}\n'

Kiali CR:
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  istio_namespace: istio-system
  version: "default"
  namespaces:
    exclude:
      - "istio-operator"
      - "kube-.*"
      - "openshift.*"
      - "ibm.*"
    label_selector: kiali=enabled
  auth:
    strategy: "anonymous"
  deployment:
    hpa:
      spec:
        maxReplicas: 4
        minReplicas: 2
        targetCPUUtilizationPercentage: 80
    ingress:
      enabled: true
      class_name: "aws-load-balancer"
      override_yaml:
        metadata:
          annotations:
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:917596758507:certificate/ce26aef4-5fe6-419b-9456-9d20101fbee9
            alb.ingress.kubernetes.io/group.name: scb-kiali-poc-internal-ingress
            alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
            alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8,192.168.0.0/16
            alb.ingress.kubernetes.io/ip-address-type: ipv4
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/success-codes: '200,404,302'
            alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=false
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
            alb.ingress.kubernetes.io/subnets: subnet-07cbe15ecd89a4ae5,subnet-002dbd98d22fce42c,subnet-054c2e9ff2ba38075
            alb.ingress.kubernetes.io/tags: Company=aella,Project=kiali-poc,Environment=sandbox
            alb.ingress.kubernetes.io/target-type: ip
      spec:
        rules:
        - http:
            paths:
            - path: /kiali
              backend:
                serviceName: kiali
                servicePort: 20001
        
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
  server:
    web_fqdn: "sandbox-kiali.aella-play.net" '
'''

**Comment by jmazzitelli** [comment]
This is not a bug - moving this to github discussions and removing the bug label

**Comment by jmazzitelli** [comment]
Your YAML is invalid in several places. First, I suggest you look at our example kiali_cr.yaml and read the comments at the top so you can see how it is documented and what the Kiali CR should look like (note that you can delete the "#" in a line to uncomment it as seen in the example cr.). The example CR is here: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml

1. This is not correct:

```yaml
spec:
  namespaces:
    exclude:
...
```

You are missing the parent `api` group. Please see: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L82-L104

2. This is not correct:

```yaml
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
```

The parent "resources:" is missing (see https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L429-L432). So you want this under:

```yaml
spec:
  deployment:
    resources:
      ...your requests and limits here...
```

3. Unless you know what you are doing, you most likely do NOT want to set label_selector. Remove this unless you have an explicit reason for doing this (and if so, I would be interested in hearing what the reason is):
```
    label_selector: kiali=enabled
```

4. Your ingress override spec section is not indented correctly - so this is incorrect:
```yaml
    ingress:
      enabled: true
      class_name: "aws-load-balancer"
      override_yaml:
        metadata:
          annotations:
...
      spec:
        rules:
        - http:
```

`spec` should be under `override_yaml`. Please see: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L338-L358

5. I don't see `spec.deployment.accessible_namespaces` set here - so it will pick up the default (which is every namespace in your cluster, minus some system namespaces). Please see: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L195

Finally, the error you are getting:

`User \"system:serviceaccount:kiali-operator:kiali-operator\" cannot create resource \"namespaces\" in API group \"\" at the cluster scope`

is odd to me. The operator doesn't create namespaces. I don't see where its getting a name of `namespaces`... so this is really strange to me. I would need to know what version of the operator you have and how you installed the operator (what is the command you used to install the operator).

**Comment by bj-1795** [comment]
Hi John,

Thanks for the recommendation, will work on updating the CR file I am looking for a way to tell kiali to watch only specific namespaces, but not sure how to do it so i was trying with labelled the namespaces , could you please suggest me how to do that.

**Reply by jmazzitelli** [reply]
> I am looking for a way to tell kiali to watch only specific namespaces

That's exactly what `spec.deployment.accessible_namespaces` is for. See: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L187-L195

See also our docs here: https://kiali.io/docs/configuration/namespace-management/

**Comment by bj-1795** [comment]
Whenever i am trying any other value other than “**” for accessible_namespaces for eg
accessible_namespace: “test_ns” i am getting below error.

Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:kiali-operator:kiali-operator\" cannot create resource \"namespaces\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}\n'

**Reply by jmazzitelli** [reply]
can you give me details on how exactly you installed the operator?

**Reply by jmazzitelli** [reply]
I don't understand the error because the operator does not create namespaces. Where are you seeing this error? You never say WHERE this error is located. I assumed it is in the operator pod logs, but now I am not sure.

So I need more details. How did you install the operator (what is the command line or did you use OLM)? Where are you seeing this error? What does the Kiali CR look like exactly?

**Comment by bj-1795** [comment]
I have installed kiali operator via helm

```
 helm install \
    --namespace kiali-operator \
    --create-namespace \
    kiali-operator \
    kiali/kiali-operator
```

kiali-operator  kiali-operator  1               2021-11-30 17:34:59.0311171
+0530 IST   deployed        kiali-operator-1.43.0
                   v1.43.0
Kiali-CR
```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  istio_namespace: istio-system
  version: "default"
  namespaces:
    exclude:
      - "istio-operator"
      - "kube-.*"
      - "openshift.*"
      - "ibm.*"
  auth:
    strategy: "anonymous"
  deployment:
    accessible_namespaces : "**"
    hpa:
      spec:
        maxReplicas: 4
        minReplicas: 2
        targetCPUUtilizationPercentage: 80
    ingress:
      enabled: true
      class_name: "aws-load-balancer"
      override_yaml:
        metadata:
          annotations:
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/certificate-arn:
arn:aws:acm:ap-southeast-1:917596758507:certificate/ce26aef4-5fe6-419b-9456-9d20101fbee9
            alb.ingress.kubernetes.io/group.name:
scb-kiali-poc-internal-ingress
            alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
            alb.ingress.kubernetes.io/inbound-cidrs:
10.0.0.0/8,192.168.0.0/16
            alb.ingress.kubernetes.io/ip-address-type: ipv4
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/success-codes: '200,404,302'
            alb.ingress.kubernetes.io/load-balancer-attributes:
access_logs.s3.enabled=false
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
            alb.ingress.kubernetes.io/subnets:
subnet-07cbe15ecd89a4ae5,subnet-002dbd98d22fce42c,subnet-054c2e9ff2ba38075
            alb.ingress.kubernetes.io/tags:
Company=aella,Project=kiali-poc,Environment=sandbox
            alb.ingress.kubernetes.io/target-type: ip
      spec:
        rules:
        - http:
            paths:
            - path: /kiali
              backend:
                serviceName: kiali
                servicePort: 20001

    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
  server:
    web_fqdn: "sandbox-kiali.aella-play.net"
```

Sent from my iPhone

On 16-Dec-2021, at 8:56 PM, John Mazzitelli ***@***.***>
wrote:

﻿

I am looking for a way to tell kiali to watch only specific namespaces

That's exactly what spec.deployment.accessible_namespaces is for. See:
https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L187-L195

See also our docs here:
https://kiali.io/docs/configuration/namespace-management/

—
Reply to this email directly, view it on GitHub
<https://github.com/kiali/kiali/discussions/4607#discussioncomment-1824320>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/ASRNG5ZPQL64KNZERXOYE2DURIAKNANCNFSM5KGQKOJA>
.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

You are receiving this because you authored the thread.Message ID:
***@***.***>

[UPDATED by @jmazzitelli to better format the yaml and command so its easier to understand]

**Comment by bj-1795** [comment]
Got this error from below command
--
kubectl describe kiali -n istio-system

**Comment by jmazzitelli** [comment]
OK, so the error you are seeing is in the Kiali CR somewhere. must be in the status field. This is very hard for me because I still don't understand where this error is actually being spit out (I think it is coming from the operator, but I don't understand why because the operator is not creating namespaces, or it should never be doing that). And your Kiali CR still has those errors I mentioned before and you did not correct them, along with another error - specifically your accessible_namespaces is not correct.

Again, please read the docs and example Kiali CR:

* https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L187-L195
* https://kiali.io/docs/configuration/namespace-management/

This accessible_namespaces setting is a list, as the docs mention, not a string. You have it just as a single string name. This is wrong.

You have this:
    `accessible_namespaces : "**"`
and it should be this
   `accessible_namespaces: ["**"]` (or something like this `accessible_namespaces: [ "test_ns", "my_other_ns" ]`

There is so much wrong in this Kiali CR that you really need to clean it up before you try to debug this. Start with a very small Kiali CR and go from there. Most of this stuff you don't need because it is the defaults. For example, get rid of this, you don't need it - its the default (and the way you have it declared is wrong anyway):

```
  istio_namespace: istio-system
  version: "default"
  namespaces:
    exclude:
      - "istio-operator"
      - "kube-.*"
      - "openshift.*"
      - "ibm.*"
```

Your ingress is incorrect and your resource limits are incorrect (as I mentioned earlier) - get rid of all of that for now just to see if you can get the kiali server deployed correctly. Then start adding back in those configs you want (but add them correctly - use the example Kiali CR as a guide).
