### DISCUSSION TITLE
Configuring OpenID on Azure

### DISCUSSION THREAD

**Discussion by Vineeth-varma** [kiali/kiali#4708] [Q&A]
I am using Kiali-operator deployment. I just want to know how to make it https as for AzureAD integration we need https://<URL>:<Port>. I am not using Openshift. I am using k8's.

Help would be really appreciated.

**Comment by jmazzitelli** [comment]
(this is not a bug - moving to Q&A Discussions)

Take a look at the `spec.server` settings in the Kiali CR.

**Reply by jmazzitelli** [reply]
Also, you want to look at the `spec.identity` section. https://github.com/kiali/kiali-operator/blob/v1.45.1/deploy/kiali/kiali_cr.yaml#L778-L795

The custom_secrets section may also be useful: https://github.com/kiali/kiali-operator/blob/v1.45.1/deploy/kiali/kiali_cr.yaml#L215-L229

**Comment by Vineeth-varma** [comment]
(jmazzitelli updated this to add the triple-backticks to properly format the yaml below)

yes SSL is working fine. But I am facing issue with Azure AD. My Azure AD spec is:
```yaml
    auth:
      strategy: "openid"
      openid:
        client_id: "<client_ID>"
        issuer_uri: "https://login.microsoftonline.com/<tenant_ID>/v2.0"
        api_token: access_token
        authentication_timeout: 300
        username_claim: "preferred_username"
        scopes:
        - "openid"
        - "profile"
        - "email"
        password: secret:kiali:oidc-secret
```
I am facing issue like "Authentication failed: Token is not valid or is expired: Unauthorized"
