### DISCUSSION TITLE
How does Kiali multi clusters work?

### DISCUSSION THREAD

**Discussion by zijianz** [kiali/kiali#4779] [Multicluster]
1. How does Kiali get workload information, via kube api server or IstioD?
According to [this](https://github.com/kiali/kiali/discussions/3963), Kiali talks to kube api server directly to get workloads. 
But according to this [demo](https://www.youtube.com/watch?v=pvVER_kqHCM&list=PLgwrCYrAkQYOHIeGukEZUmNRGbqI9uwpi&index=16), Kiali uses Istio endpoints discovery to find workloads, which sounds like talking to kube api server through IstioD.

Does Kiali talk to Kube API server directly or via Istiod? 

2.  This [demo](https://www.youtube.com/watch?v=qOvJ1YOWenU&t=1020s) shows after enabling multi cluster, you will see a list of clusters on your Kiali UI. By clicking each cluster will launch another Kiali UI for the cluster you have chosen. 

Since we have one Kiali instance on each cluster, does it mean when I click on a cluster, a new Kiali UI will be created for the Kiali backend on the cluster I have just chosen? 

3. At the end of this [readme](https://github.com/kiali/kiali), section `Observing a Remote Cluster`. 
3.1 Is this section still valid?
3.2 Why do we need this secret? Correct me if I am wrong. Assume I am running Kiali on Cluster A and I click to switch to Cluster B. 
Kiali on Cluster A will use the token in that secret to talk to kube API server on Cluster B to find the Kiali instance on Cluster B. After that a new Kiali UI will be created for the Kiali backend on Cluster B. Is it right?

4. No matter what deployment model we use, we always need to install one Kiali instance per cluster, is this right? 

Sorry for some of the naive questions since we have really few documents for this multicluster scenario. Thanks a lot!!

**Comment by israel-hdez** [comment]
Hi @zijianz 

Multi-cluster is a complex topic, so you don't need to sorry.
In general, multi-cluster support in Kiali is experimental and is far from being complete. I'd even say that whatever multi-cluster features that Kiali has are the result of exploratory efforts. So, don't expect a robust feature set around multi-cluster.

1. Kiali uses both the kube api and IstioD to get workload information. For the lists that you can see in the "Applications", "Workloads" and "Services" pages, kube api is the main source (so, Kiali talks directly to it). Once you start looking at more specific features, IstioD becomes used more frequently because it offers some data that can be used to correlate Istio configs and other resources. For example, the [validations](https://kiali.io/docs/features/validations/) use the IstioD registry extensively. This combination of data sources was mainly developed around single cluster setups. So, once you go from single-cluster to multi-cluster, it can have an impact on the stability/accuracy of Kiali, because it hasn't been thoroughly tested on those situations.

2. I'm not sure what you mean with _"a new Kiali UI will be created"_. What I can reply is that if you click on a cluster nothing new is deployed. It will simply redirect you to the other Kiali installation, so that you don't have to type the URL manually in your browser.

3. The "Observing a Remote Cluster" was a feature contributed by somebody from community. It was supposed to cover [Istio's External Control Plane setup](https://istio.io/latest/docs/setup/install/external-controlplane/). It is closely related to the "Primary-remote" multi-cluster setup. I think the only difference is the fact that the former approach does not allow workloads in the cluster where the control plane is running, while the later does. Kiali's "Observing a Remote Cluster" feature got stalled quickly, so we are uncertain if it still works. Anyway, the secret is needed because since Kiali would be installed in the "Control Plane" cluster, that cluster does not have available the workloads. So a secret was needed to gain access to the "Data plane" cluster to fetch workloads/services and get the full picture of the Mesh that Kiali needs to work correctly. And that's all, the secret is only used to read data, not to create something in the remote cluster.

4. Yes. We have only tested [Istio's Multi-primary model](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/), where everything is replicated to all clusters that are part of the mesh. This is why we tell that you need one Kiali per cluster (or per Istio control-plane).

**Reply by zijianz** [reply]
Hi Edgar
Thank you so much for your reply!! I just realized that you were the person presenting in the two demos I have referenced. 

Can I ask a few more questions?

1. in question 4 above, you have mentioned that `the former approach does not allow workloads in the cluster where the control plane is running`. Does it mean that one Kiali backend can only talk to one kube api server at a time? It can not scrape the api servers in both cluster A and cluster B at the same time then merge the workloads together to present in the UI, even with cluster A and B are in the same network.

2. If `one Kiali backend can only talk to one kube api server at a time` is true, does it mean that in the primary-remote setup above, we can only monitor one remote cluster, not many? For example I have 3 clusters, called Management cluster(primary), Application cluster, and DMZ cluster. With my Kiali running on the Management cluster, I can only monitor either Application or DMZ cluster but never both?
 
3. Can you share more details about you setup in [sprint 51 demo ](https://www.youtube.com/watch?v=pvVER_kqHCM&list=PLgwrCYrAkQYOHIeGukEZUmNRGbqI9uwpi&index=17)? 

I have two clusters, Kukulcan and Tzotz, both with Kiali installed in namespace `kiali-ns`.

Then I will do 
```
istioctl x create-remote-secret --context=Tzotz --name=tzotz | kubectl apply -f - --context=Kukulcan
istioctl x create-remote-secret --context=Kukulcan --name=Kukulcan | kubectl apply -f - --context=tzotz
```
Can I put both the secret and Kiali instance in namespace `kiali-ns` or do I have to put them into `istio-system`?

4. How do we mount those secrets? Do we mount the secret in `/kiali-remote-secret/kiali` or `/kiali-remote-secret/`? Is it alright if we mount more than one secret into that path?

Thanks a lot!!

**Reply by israel-hdez** [reply]
Hi @zijianz 
Yes I was the presenter of the multi-cluster features on those demos :-)

About your questions:

1. Well, I mentioned that, because what I understand is that the underlying idea behind the "External Control plane setup" is that you have a cluster dedicated *only* for the control plane (which would be managed by peopled called mesh operators), and another cluster (or several ones) dedicated to the workloads (which would be managed by people called mesh admins) promoting separation of duties. On the other hand, the "Primary-Remote setup" does not make this distinction and allows workloads to run on any cluster. It is more an Istio model than something imposed by Kiali. Regardless of Istio models, you are right that currently Kiali can only scrape a single kube api server (even if the other cluster is on the same network)

2. Unfortunately, what you say is true: in the "Primary-Remote" setup, Kiali is only capable of monitoring "one cluster". It's even **not** capable of monitoring the primary _and_ the remote. You would need to choose if you want to monitor the primary or a remote. Just keep in mind that the "Observing a Remote Cluster" setup mentioned in Kiali's readme hasn't been tested for along time (so we are uncertain that it still works).

3. Check this gist that I wrote some time ago: https://gist.github.com/israel-hdez/6e1be3b1ddb372dd1985db68470737b0. Read the comments on the "[minikube-istio-multi-cluster.bash](https://gist.github.com/israel-hdez/6e1be3b1ddb372dd1985db68470737b0#file-minikube-istio-multi-cluster-bash)" file. It is for an older version of Istio but I recently did a setup based on that script and I'm almost sure that it may work for the latest Istio version (it is on my TODO list to update the gist).
  - The `istioctl x create-remote-secret` command will create the secrets on the `istio-system` namespace. I think this is how Istio requires it and probably cannot be changed. About Kiali, you can deploy it to any namespace you like.

4. If you are using Istio's "Multi-Primary setup" (like in the gist I shared) you don't need to mount the secrets into Kiali, because Kiali will read the secrets through the kube api. However, if you want to try the "Observing a Remote Cluster" setup mentioned in Kiali's readme, you definitely need to mount the secret in `/kiali-remote-secret/kiali` and you can provide only a single one.

**Reply by zijianz** [reply]
Hi Edgar

Thanks so much for the answers!! This is just one thing left I can't figure out. 

Would you mind to share the kiali config or the kiali CR you were using? I have my Kiali CR with
```
# On cluster 1
kiali_feature_flags:
    clustering:
      enabled: true
    certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
        - istio-remote-secret-cluster2
# On cluster 2
kiali_feature_flags:
    clustering:
      enabled: true
    certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
        - istio-remote-secret-cluster1
```

As the result, in my config I have 
```
kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
        - istio-remote-secret-cluster2
      clustering:
        enabled: true
```

In `kubectl -n istio-system get role/kiali-controlplane -o yaml` I do have 
```
- apiGroups:
  - ""
  resourceNames:
  - cacerts
  - istio-ca-secret
  - istio-remote-secret-cluster2
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

When I do port-forwarding to test on one cluster, there is no "Mesh" option on the left menu. Is there any other fields I need to enable to activate multi-clusters feature? Thanks!!

**Reply by israel-hdez** [reply]
@zijianz I usually install Kiali normally without any additional configuration on the Kiali CR. This is what I have in the setup that I currently have and is working OK with the "Multi-primary" deployment model:

```yaml
spec:
  auth:
    strategy: anonymous
  deployment:
    image_name: quay.io/edgarhz/kiali
    image_pull_policy: Always
    image_version: dev
    ingress:
      enabled: true
    namespace: istio-system
    service_type: LoadBalancer
```

I am using a different `image_name` and `image_version` because it is a dev setup. But almost everything else is using the defaults. As long as Istio is correctly configured using the "multi-primary" deployment, the "Mesh" option should automatically appear.
