### DISCUSSION TITLE
How to  pass multiple log levels to Kiali

### DISCUSSION THREAD

**Discussion by Vineeth-varma** [kiali/kiali#4883] [Q&A]
Hello Team,

I am using kiali-operator deployment. I see in kiali-cr we can pass the logs we want like shown in the below example
```
spec:
  deployment:
    logger:
      # Supported values are "trace", "debug", "info", "warn", "error" and "fatal"
      log_level: error  
      # Supported values are "text" and "json".
      log_format: json  
      time_field_format: "2006-01-02T15:04:05Z07:00"
```
But for the log_level field if I wish to pass multiple values like log_level: error, info, warn. Can I pass them, If yes , How?
