### DISCUSSION TITLE
Configuration of openid with Okta

### DISCUSSION THREAD

**Discussion by santiago-diaz-paack** [kiali/kiali#5377] [Q&A]
Hello everyone,

I have configured openid kiali with Okta and want to configure view access for some groups and modification access for others. However, when configuring `disable_rbac: false`  my kiali throws this error:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/96438924/183625063-6aa73fbf-b695-4fe0-9617-f9513c08a02c.png">

Could anyone help me configure this, please? I've been following different suggestions from the internet but there is not a lot of documentation of this case.

My setup is:

- GKE: private cluster version 1.24
- Idp: Okta
- openid config:

```
auth:
  openid:
    authentication_timeout: 120
    claims:
      display_name: name
      email: email
      family_name: family_name
      given_name: given_name
      groups: groups
      sub: sub
    client_id: something
    disable_rbac: false
    issuer_uri: https://something.okta.com
    scopes:
    - openid
    - email
    - profile
    - groups
    username_claim: email
  openshift:
    client_id_prefix: kiali
  strategy: openid
```
I also created the secret with the client_secret from Okta.

Many thanks.
