### DISCUSSION TITLE
Multicluster and multinetwork Kiali deployment discovery

### DISCUSSION THREAD

**Discussion by bserracanta** [kiali/kiali#5471] [Q&A]
Hello!

I'm new to Kiali and I was following the deployment of the [Online Boutique in a multicluster and multinetwork environment](https://cloud.google.com/architecture/building-a-multi-cluster-service-mesh-on-gke-using-replicated-control-plane-architecture).

I have deployed Istio 1.15 and used
`kubectl --context west apply -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/addons/kiali.yaml` to install kiali on each cluster and can access both Kiali dashboards without any issue after exposing the port. 

From the dashboard from one cluster (A) I cannot access information generated on the other cluster (B), such as the other Istio Gateway (the traffic is directly linked to cluster B services, app traces or nodes from B that are not interacting with cluster A. 

How can I discover both Kiali instances? I have seen in [4039](https://github.com/kiali/kiali/issues/4039) that is necessary to add `web_fdqn`. I have modified the `/istio-1.15.0/samples/addons/kiali.yaml` file and added the last line shown here:

```
# Source: kiali-server/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    helm.sh/chart: kiali-server-1.55.1
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.55.1"
    app.kubernetes.io/version: "v1.55.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
data:
  config.yaml: |
    […]
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
      web_fqdn: kiali.istio-system.svc.cluster.local:20001
```

And then applied the configuration with `kubectl apply -f kiali.yaml`. I know I am still missing some steps because on the dashboard i get the error:  **Not all remote clusters have reachable Kiali instances.** Any pointers on what I'm missing?

I would also like know if it is possible to see the whole mesh: all nodes from one cluster sending traffic to their gateway and the other cluster gateway receiving it and delivering it to the appropriate nodes.

Thank you very much for the help, I leave some pictures that might help with my explanation:

The mesh tab, in the Kiali column I see both deployments but I cannot navigate from one to the other:
<img width="1265" alt="Screenshot 2022-09-15 at 13 50 32" src="https://user-images.githubusercontent.com/103190090/190397543-e945b4ea-e5ab-43c4-83ec-243938c652e1.png">

View from one cluster:
<img width="1266" alt="Screenshot 2022-09-15 at 13 31 16" src="https://user-images.githubusercontent.com/103190090/190397746-b47a03d9-54e2-451e-baf9-7060c0d3db42.png">

View from the other one:
<img width="1266" alt="Screenshot 2022-09-15 at 13 33 08" src="https://user-images.githubusercontent.com/103190090/190397765-b3b22bfb-3d91-4cec-8299-8916edb63107.png">

Berta
