### DISCUSSION TITLE
How could i use oauth without RBAC and grant all users Admin access?

### DISCUSSION THREAD

**Discussion by oujonny** [kiali/kiali#5697] [Q&A]
hey

In the documentation it says [here](https://kiali.io/docs/configuration/authentication/openid/) 

> As RBAC is disabled, all users logging into Kiali will share the same cluster-wide privileges. 

If I currently log in with oauth2 I'm only able to read stuff. How could I grant Admin privileges by default without enabling RBAC for the cluster, because this is not an option.

Thanks for your answers!

**Comment by israel-hdez** [comment]
Hi, @oujonny 

Since a recent release, the Kiali ServiceAccount is now read-only by default and these are the privileges that users get when RBAC is turned off. This new default was put in place with the rationale of following the "Least privilege principle" and since we thought people would always prefer to enable RBAC.

You can still enable write privileges. Weirdly, this is documented on the `anonymous` auth strategy page: https://kiali.io/docs/configuration/authentication/anonymous/#view-only. Set that `view_only_mode` config to `false` and you should get what you need.

**Reply by oujonny** [reply]
hi @israel-hdez 
Thanks for your super quick response. The view_only_mode made the difference, but I noticed an issue with the helm chart.

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if or (.Values.deployment.view_only_mode) (ne .Values.auth.strategy "anonymous") }}
  name: {{ include "kiali-server.fullname" . }}-viewer
  {{- else }}
  name: {{ include "kiali-server.fullname" . }}
  {{- end }}
```
Source: https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/rolebinding.yaml#L12 

This it condition is always true if the auth strategy is openeid, isn't it?

**Reply by jmazzitelli** [reply]
> This it condition is always true if the auth strategy is openeid, isn't it?

Yes. That was the change we did in a recent release. The roles that Kiali will create (created by either the operator or the helm chart) will always have the ServiceAccount roles "view-only" when auth strategy is anything other than anonymous. That means, yes, if you are using openid, then the ServiceAccount roles will always be view-only. The user's own RBAC will determine what that user can do, but Kiali's own ServiceAccount will be view-only.

We will not enable a "ignore RBAC - support Admin for all users everywhere" for anything other than "anonymous" mode (anonymous mode is basically a demo mode that requires no user login). To support something like that for, say, token or OpenID auth strategy would open a security hole that the Kiali team is not willing to risk (we don't want to be responsible for all the bad things that could happen :) )

**Reply by israel-hdez** [reply]
@jmazzitelli I think @oujonny is right into thinking that it looks more like a bug in the chars/operator. In OpenID auth you can turn off RBAC, as not everybody has the required tight integration to successfully enable it. When RBAC is turned off, all users get the privileges of the Kiali SA. But, then, the charts nor the operator have a way to enable write privileges because the expicit override of the `view_only_mode` is ignored...

So, @oujonny I think I was wrong when suggesting switching off the `view_only_mode` config. So, perhaps the way to proceed in latest Kiali versions is to manually create the following Role or ClusterRole and bind it to the Kiali SA to add the needed Write privileges:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # or Role
metadata:
  name: kiali-write-privs
  namespace: istio-system # Or your Kiali installation Namespace
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - patch
- apiGroups: ["extensions", "apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - patch
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs:
  - patch
- apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - gateway.networking.k8s.io
  resources: ["*"]
  verbs:
  - create
  - delete
  - patch
```

(I wrote it without validating it, so fix it if needed)

I see you already ask about it in the title of the ticket, but as Mazz is telling, just be sure you really want to give write privileges to all users.

We will talk/think a little bit about if the explicit override of `view_only_mode` should be honored.
