### DISCUSSION TITLE
ERR Not handling OpenId code flow authentication: no authorization code is present

### DISCUSSION THREAD

**Discussion by im-Amitto** [kiali/kiali#5977] [Q&A]
Kiali Version: 1.63.2
Cluster: AWS EKS

<img width="595" alt="image" src="https://user-images.githubusercontent.com/29653282/229512598-83949075-42f3-4bf6-8716-aaffbdb69f51.png">

Config:
```
strategy: "openid"
openid:
  authentication_timeout: 300
  client_id: "<client-id>.apps.googleusercontent.com"
  disable_rbac: true
  issuer_uri: "https://accounts.google.com"
  scopes: ["openid", "email"]
  username_claim: "sub"
  .
  .
  .
 login_token:
   signing_key: <16 byte token>
server:
  metrics_enabled: true
  metrics_port: 9090
  port: 20001
  web_root: /kiali
  web_port: 80
```
I can see that OAuth is redirecting fine and have the needed code in the param but Kiali is still throwing `ERR Not handling OpenId code flow authentication: no authorization code is present`
```
http://example.com/kiali?state=<state>&**code=<code>**&scope=email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&hd=example.com&prompt=none
```
