### DISCUSSION TITLE
How i can display the full Istio ServiceEntry host in the UI ?

### DISCUSSION THREAD

**Discussion by ihatemodels** [kiali/kiali#6183] [Q&A] [answered]
Hello,

I'm currently having difficulty navigating the source code and haven't had any luck. Until a few weeks ago, I was able to see the full host of the ServiceEntry in the UI, but that's no longer the case.

Here's an example of the ServiceEntry I'm using:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: vault.uat.mydomain
  namespace: istio-system
spec:
  hosts:
    - vault.uat.mydomain
  ports:
    - name: https
      number: 443
      protocol: TLS
``` 

This is what is currently shown in the UI:

![image](https://github.com/kiali/kiali/assets/47652045/aef39085-51e1-4a08-b3c6-b1333d47a2b1)

With this behaviour, it's challenging to differentiate between different ServiceEntries with the same domain. For example:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: vault.prd.mydomain
  namespace: istio-system
spec:
  hosts:
    - vault.prd.mydomain
  ports:
    - name: https
      number: 443
      protocol: TLS
```
