### DISCUSSION TITLE
I can't see gateway in graph when an installation is made from helm chart

### DISCUSSION THREAD

**Discussion by gigi206** [kiali/kiali#6500] [General]
I installed base and istiod from official istio chart and kialia via helm chart too.

I installed the bookinfo application and send traffic on it, but I don't see the ingress gateway from Graph
![no gateway](https://i.ibb.co/wwxb9XN/Capture-d-cran-du-2023-08-21-23-07-17.png)

If I install directly from istioctl I can see the gateway:
![with gateway](https://i.ibb.co/mCPStbY/Capture-d-cran-du-2023-08-21-18-29-10.png)

Istio is installed in istio-system namespace et the istio ingress is installed in the istio-ingress namespace.

Values.yaml:
```yaml
server:
  web_fqdn: kiali.gigix
auth:
  strategy: anonymous
istio_namespace: istio-system
external_services:
  prometheus:
    url: http://prometheus-stack-kube-prom-prometheus.prometheus-stack:9090/
  server:
    web_root: /
  tracing:
    enabled: true
    in_cluster_url: 'http://jaeger-query.jaeger.svc.cluster.local:16685'
    use_grpc: true
    url: 'https://jaeger.gigix'
  istio:
    root_namespace: istio-system
    component_status:
      components:
      - app_label: "istiod"
        is_core: true
        is_proxy: false
      - app_label: "istio-ingress"
        is_core: true
        is_proxy: true
        namespace: istio-ingress
      enabled: true
  grafana:
    enabled: true
    auth:
      type: "basic"
      username: "admin"
      password: "prom-operator"
      use_kiali_token: false
    dashboards:
    - name: "Istio Service Dashboard"
      variables:
        namespace: "var-namespace"
        service: "var-service"
    - name: "Istio Workload Dashboard"
      variables:
        namespace: "var-namespace"
        workload: "var-workload"
    - name: "Istio Mesh Dashboard"
    - name: "Istio Control Plane Dashboard"
    - name: "Istio Performance Dashboard"
    - name: "Istio Wasm Extension Dashboard"
    in_cluster_url: "http://prometheus-stack-grafana.prometheus-stack"
    is_core: false
    url: "http://grafana.gigix"
```

Do you know how to fix this issue ?

PS: Don't worry about the service status, it is because Jaeger is rebooting

**Comment by jmazzitelli** [comment]
The first one, it doesn't seem like any traffic is coming from ingress - are you sending requests directly from the producpage pod?

So, the question I would have is - when you say you are sending traffic, HOW are you sending traffic? What command are you using? What URL are you sending requests to?

**Comment by gigi206** [comment]
> The first one, it doesn't seem like any traffic is coming from ingress - are you sending requests directly from the producpage pod?

Yes, if I select the namespace istio-ingress I can see the traffic
![](https://i.ibb.co/qpx7MT2/Capture-d-cran-du-2023-08-22-00-24-00.png)

> So, the question I would have is - when you say you are sending traffic, HOW are you sending traffic? What command are you using? What URL are you sending requests to?

```bash
kubectl get svc -n istio-ingress 
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                                      AGE
istio-ingress   LoadBalancer   10.43.112.100   192.168.122.204   15021:30615/TCP,80:30072/TCP,443:30720/TCP   7m49s
```

```bash
while true; do curl -sH "Host:bookinfo.gigix" "http://192.168.122.204/productpage"; done
```

**Reply by jmazzitelli** [reply]
That first graph looks like it represents different traffic... notice how you have no traffic entering the productpage service (the triangle) - you only have traffic leaving the productpage app (the rectangle).:

![image](https://github.com/kiali/kiali/assets/2029470/a2c63963-88ba-4f80-8d09-fb38502816f5)

That tells me there was no traffic going into productpage from ingress (or any client for that matter).

We would need replication procedures to determine what is going on. Commands used to install istio and kiali and commands used to push requests through the bookinfo demo, as well as what are the settings you have in the "Display" dropdown of Kiali (showing the Kiali URL would help).

**Comment by gigi206** [comment]
> That first graph looks like it represents different traffic... notice how you have no traffic entering the productpage service (the triangle) - you only have traffic leaving the productpage app (the rectangle).

True, but if I select the namespace `istio-ingress` I can see the traffic
![](https://i.ibb.co/qpx7MT2/Capture-d-cran-du-2023-08-22-00-24-00.png)

I use ArgoCD to install:
- [prometheus-stack](https://github.com/gigi206/k8s/blob/main/argocd/prometheus-stack/prometheus-stack.yaml)
- [istio base + istiod](https://github.com/gigi206/k8s/blob/main/argocd/istio-system/istio-system.yaml)
- [istio ingress](https://github.com/gigi206/k8s/blob/main/argocd/istio-ingress/istio-ingress.yaml)
- [kiali](https://github.com/gigi206/k8s/blob/main/argocd/istio-kiali/istio-kiali.yaml)
- [jaeger](https://github.com/gigi206/k8s/blob/main/argocd/jaeger/jaeger.yaml)

```bash
kubectl get svc -n istio-ingress 
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)                                      AGE
istio-ingress   LoadBalancer   10.43.231.75   192.168.122.204   15021:30591/TCP,80:31052/TCP,443:30297/TCP   22d
```

```bash
curl -IsH "Host:bookinfo.gigix" http://192.168.122.204/productpage
HTTP/1.1 200 OK
server: istio-envoy
date: Tue, 22 Aug 2023 15:12:22 GMT
content-type: text/html; charset=utf-8
content-length: 4294
x-envoy-upstream-service-time: 11
```

URL: http://kiali.gigix/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=bookinfo&duration=60&refresh=10000&animation=true&badgeSecurity=true&edges=responseTime%2Crt95%2Cthroughput%2CthroughputRequest%2CtrafficDistribution%2CtrafficRate&layout=kiali-dagre&namespaceLayout=kiali-dagre&idleEdges=true&idleNodes=true&operationNodes=true&rank=true&rankBy=inboundEdges%2CoutboundEdges

![](https://i.ibb.co/MgMPhrs/Capture-d-cran-du-2023-08-22-17-20-36.png)

**Reply by jmazzitelli** [reply]
I always thought that any ingress traffic (even from a different namespace not selected) would show up in the graph. I don't know if this behavior changed in recent versions. I will defer to someone more knowledgeable in the graph generator (the one person I am thinking of who would probably know the answer is on vacation; he'll be back Monday).

**Comment by gigi206** [comment]
Ok thank you for your feedback :+1: 
Note that istioctl use version **1.67.0** and with helm I use the last **1.72.0**.

I will be on vacation from Monday but I think this is an abnormal behavior that I don't have when I install with istioctl (operator).

**Reply by jmazzitelli** [reply]
AFAIK, this behavior is not seen in testing. I would suggest you try to do a  simple Kiali helm installation (e.g. don't use ArgoCD - we have no idea what they are doing or how they install/configure Kiali). See if you get the same behavior.

For example, just do something as simple as this helm install and see what happens (you could even try it for 1.68, 1.69, 1.70 and 1.71 also - just to see where it starts behaving differently, if it does).

```
helm upgrade --install --version 1.72.0 --namespace istio-system --repo https://kiali.org/helm-charts --set auth.strategy=anonymous kiali kiali-server
```

I do see some code changes between 1.67 and 1.72 in the graph generator - I do not know if anything here would be the cause of this: `git diff origin/v1.67...origin/v1.72 -- graph/ ` -- however, my quick testing right now shows the graph is working fine in 1.72 using Istio 1.18:

![image](https://github.com/kiali/kiali/assets/2029470/b923dc8d-63be-40eb-a7f5-0ff413d4c443)

![image](https://github.com/kiali/kiali/assets/2029470/a59ec977-b349-4110-9d28-26ec604d60b8)

**Comment by jmazzitelli** [comment]
And I see good graph in 1.71 as well:

![image](https://github.com/kiali/kiali/assets/2029470/4a34f51a-f05b-4f02-81c3-d933e5285078)


![image](https://github.com/kiali/kiali/assets/2029470/c3e9824d-e28f-4252-b4b4-f47aa389f076)

**Comment by gigi206** [comment]
I don't know if there is any impacts but my istio gateway is installed in the `istio-ingress` namespace and kiali is installed in the `istio-kiali` namespace.

**Reply by nrfox** [reply]
What are the labels on the ingress gateway? Do they include: `app: "istio-ingress`?

**Comment by gigi206** [comment]
```
kubectl get pod -n istio-ingress -l app=istio-ingress
NAME                             READY   STATUS    RESTARTS   AGE
istio-ingress-7c9c597ccb-5f7q8   1/1     Running   0          3h55m
```

**Comment by gigi206** [comment]
Perhaps there is an issue on how kiali detect my istio ingress ?

**Reply by nrfox** [reply]
There could be... try this. Add this label to your gateway deployment: `operator.istio.io/component: IngressGateways` and see if Kiali picks it up then.

**Reply by jmazzitelli** [reply]
but doesn't the graph generator get this information directly from the Prometheus telemetry? Or does it treat ingress objects different (my ignorance is showing again wrt the graph generator:) ?

**Reply by jmazzitelli** [reply]
FWIW, my ingress labels are as follows
```
$ kubectl get pods -n istio-system istio-ingressgateway-748997f754-5q68t -o jsonpath={.metadata.labels} | jq
{
  "app": "istio-ingressgateway",
  "chart": "gateways",
  "heritage": "Tiller",
  "install.operator.istio.io/owning-resource": "unknown",
  "istio": "ingressgateway",
  "istio.io/rev": "default",
  "operator.istio.io/component": "IngressGateways",
  "pod-template-hash": "748997f754",
  "release": "istio",
  "service.istio.io/canonical-name": "istio-ingressgateway",
  "service.istio.io/canonical-revision": "latest",
  "sidecar.istio.io/inject": "false"
}
```

**Reply by nrfox** [reply]
I don't know for sure but if it is a bug then I'm guessing it's just not being decorated as a gateway by the appender that's supposed to do that since traffic is showing up when the `istio-ingress` namespace is included.

Looking at this snippet makes me think that there may be some specific labels kiali looks for to determine whether or not the node is a gateway:
https://github.com/kiali/kiali/blob/d7f90cf03159a79c531f573d82b0242daaf7d4d2/graph/telemetry/istio/appender/istio_details.go#L372-L379

**Comment by gigi206** [comment]
> There could be... try this. Add this label to your gateway deployment: operator.istio.io/component: IngressGateways and see if Kiali picks it up then.

I add the label `operator.istio.io/component: IngressGateways` to my gateway deployment.
```bash
kubectl get pods -n istio-ingress istio-ingress-6d46f88dbb-lbz88 -o jsonpath={.metadata.labels} | jq
{
  "app": "istio-ingress",
  "istio": "ingress",
  "operator.istio.io/component": "IngressGateways",
  "pod-template-hash": "6d46f88dbb",
  "service.istio.io/canonical-name": "istio-ingress",
  "service.istio.io/canonical-revision": "latest",
  "sidecar.istio.io/inject": "true"
}
```

But no change happens, I don't see the gateway on the graph

**Comment by jmazzitelli** [comment]
If @jshaughn was here he'd probably answer in 10 seconds, "Oh, that's simple. It is because .... yadda yadda yadda". He'll be around Monday. If it's a problem or simply a misconfiguration, he'll most likely know.

**Comment by jshaughn** [comment]
In that first scenario, it's weird.  As mentioned above the helm install is not being picked up as a gateway, just a standard app.  And for some reason productpage does not seem to be generating the destination telemetry for the requests coming in, only source telemetry.  To me it looks maybe like an istio telemetry issue.  We'd have to look at the prometheus data to explore further.

It may be worth us trying to recreate this.  Can you give us the specific steps you used to create that first scenario?

**Comment by gigi206** [comment]
Sorry for the delay, I come back today from my holidays.

Note that prometheus is already installed with `prometheus-stack` and I use `ServiceMonitor` and `PodMonitor`.
Jaeger is also installed and works.
I can send you the helm values for prometheus-stack and Jaeger if needed.

I extract my process from ArgoCD with helm below.

Create file `istio-values/istiod.yaml`:
```yaml
meshConfig:
  enablePrometheusMerge: false
  enableTracing: true
  defaultConfig:
    tracing:
      sampling: 100.0
      zipkin:
        address: jaeger-collector.jaeger.svc.cluster.local:9411
  defaultProviders:
    metrics:
    - prometheus
    tracing:
    - jaeger
  extensionProviders:
  - name: jaeger
    zipkin:
      service: jaeger-collector.jaeger.svc.cluster.local
      port: 9411
```

Create file `istio-values/kiali.yaml`:
```yaml
istio_namespace: istio-system
auth:
  strategy: anonymous
deployment:
  ingress:
    enabled: true
    class_name: nginx
server:
  web_fqdn: kiali.gigix
external_services:
  server:
    web_root: /
  tracing:
    enabled: true
    in_cluster_url: 'http://jaeger-query.jaeger.svc.cluster.local:16685'
    use_grpc: true
    url: 'https://jaeger.gigix'
  istio:
    root_namespace: istio-system
    component_status:
      components:
      - app_label: "istiod"
        is_core: true
        is_proxy: false
      - app_label: "istio-ingress"
        is_core: true
        is_proxy: true
        namespace: istio-ingress
      - app_label: "istio-egress"
        is_core: true
        is_proxy: true
        namespace: istio-egress
      enabled: true
  prometheus:
    url: 'http://prometheus-stack-kube-prom-prometheus.prometheus-stack:9090/'
  grafana:
    enabled: true
    auth:
      type: "basic"
      username: "admin"
      password: "prom-operator"
      use_kiali_token: false
    in_cluster_url: "http://prometheus-stack-grafana.prometheus-stack"
    is_core: false
    url: "http://grafana.gigix
```

The run the following scripts:
```bash
#!/usr/bin/env bash
helm install --create-namespace -n istio-system --repo https://istio-release.storage.googleapis.com/charts istio-base base --version 1.19.0
helm install --create-namespace -n istio-system --repo https://istio-release.storage.googleapis.com/charts istio-istiod istiod --version 1.19.0 -f istio-values/istiod.yaml
helm install --create-namespace -n istio-ingress --repo https://istio-release.storage.googleapis.com/charts istio-ingress gateway --version 1.19.0
helm install --create-namespace -n istio-egress --repo https://istio-release.storage.googleapis.com/charts istio-egress gateway --version 1.19.0 --set service.type=ClusterIP
helm install --create-namespace -n istio-kiali --repo https://kiali.org/helm-charts istio-kiali kiali-server --version 1.73.0 -f istio-values/kiali.yaml

# Patch to work with prometheus-stack
kubectl apply -k github.com/gigi206/k8s/argocd/istio-system/kustomize/base/

# bookinfo app
kubectl create ns bookinfo
kubectl label namespace bookinfo istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml -n bookinfo

export INGRESS_NAME=istio-ingress
export INGRESS_NS=istio-ingress
export INGRESS_HOST=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export TCP_INGRESS_PORT=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.spec.ports[?(@.name=="tcp")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

curl -sL https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/networking/bookinfo-gateway.yaml | sed -e "s@istio: ingressgateway@istio: $(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.metadata.labels.istio}')@g" -e "s@number: 8080@number: $(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath="{.spec.ports[?(@.name=='http2')].port}")@g" | kubectl apply -n bookinfo -f -

kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/networking/destination-rule-all.yaml -n bookinfo

echo ">>> http://$GATEWAY_URL/productpage"
while true; do curl -Is http://$GATEWAY_URL/productpage; done
```
