### DISCUSSION TITLE
OIDC Authorization Error

### DISCUSSION THREAD

**Discussion by noor-muradi** [kiali/kiali#6910] [Q&A]
Hello,

I am trying to secure my Kiali access using OpenID strategy, I have created OAuth client id and secret id in GCP and passed it in Kiali configmap, if enable RBAC the authorization does not work, and I get "token expired- uauthorized" in browser, but I when disable the RBAC it works with any user in allowed domains, but I want certain users to have access to Kiali.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    [helm.sh/chart](http://helm.sh/chart): kiali-server-1.67.0
    app: kiali
    [app.kubernetes.io/name](http://app.kubernetes.io/name): kiali
    [app.kubernetes.io/instance](http://app.kubernetes.io/instance): kiali
    version: "v1.67.0"
    [app.kubernetes.io/version](http://app.kubernetes.io/version): "v1.67.0"
    [app.kubernetes.io/managed-by](http://app.kubernetes.io/managed-by): Helm
    [app.kubernetes.io/part-of](http://app.kubernetes.io/part-of): "kiali"
data:
  config.yaml: |
    auth:
      openid:
        allowed_domains:
        - xxx.com
        - yyy.com
        additional_request_params:
          prompt: login
      openshift:
        client_id_prefix: kiali
      strategy: "openid"
      openid:
        client_id: "xxxxxx.apps.googleusercontent.com"
        disable_rbac: true
        issuer_uri: "https://accounts.google.com/"
        scopes: "email"
        username_claim: "email"
    deployment:
      accessible_namespaces:
      - '**'
```

**Comment by jmazzitelli** [comment]
(_moving to Q&A discussion as this is a question regarding OpenID config_)

**Reply by jmazzitelli** [reply]
Did you edit the configmap manually? Because I see two "openid" sections which shouldn't be. If you use the Kiali Server Helm chart, You should apply the modifications to your Kiali config via helm settings/values files - do not edit the configmap manually.

Notice in the yaml you provided:

```yaml
    auth:
      openid:
        allowed_domains:
        - xxx.com
        - yyy.com
        additional_request_params:
          prompt: login
...
      openid:
        client_id: "xxxxxx.apps.googleusercontent.com"
        disable_rbac: true
        issuer_uri: "https://accounts.google.com/"
        scopes: "email"
        username_claim: "email"
```

That seems odd to me, but perhaps that (or something else caused by manually editing the config) is causing the problem?

**Reply by noor-muradi** [reply]
I have not deployed the Kiali using helm, actually I have installed the Istio using the istioctl, and the kiali addon using the manifest "kaili.yaml" in the sample folder of the istio. [istio-1.18.2](https://github.com/istio/istio/releases/download/1.18.2/istio-1.18.2-linux-amd64.tar.gz).
 I wanted to utilize the OIDC for authentication into Kiali, therefore I need to pass the the GCP Oauth client ID in kiali deployment so I edited the configmap and below is the updated configmap. as mentioned before if enable RBAC `disable_rbac=false` the authentication does not work, (it gets redirected to "accounts.google.com" I sign in, it redirects back to my Kiali login page and gives below screenshot error) but if I disable the rbac `disable_rbac=true` the authentication works.

note: I have created the required rolebinding for the google user for the "kiali" cluster role.

`kubectl create rolebinding noor-openid-binding --clusterrole=kiali --user="noor@mydomain.com" --namespace=itsnoor`

 
 ```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    helm.sh/chart: kiali-server-1.67.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.67.0"
    app.kubernetes.io/version: "v1.67.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
data:
  config.yaml: |
    auth:
      openid:
        allowed_domains:
        - xxx.com
        - yyy.com
        additional_request_params:
          prompt: login
        client_id: "xxxx.apps.googleusercontent.com"
        disable_rbac: false
        issuer_uri: "https://accounts.google.com"
        scopes: ["email"]
        username_claim: "email"
      strategy: "openid"
    deployment:
      accessible_namespaces:
      - '**'
```

![image](https://github.com/kiali/kiali/assets/24589033/3ae3a007-9468-4b49-b4d5-d44db7119874)
