### DISCUSSION TITLE
Problem with Istio components (istio-ingressgateway not found) and can't see traces from Jaeger

### DISCUSSION THREAD

**Discussion by pavelzag** [kiali/kiali#7126] [Q&A]
Hello good folks!
I installed Kiali last week and was thoroughly impressed by its' features but a couple of troubles are hindering my further exploration of it.

1. First thing is Kiali cannot find istio-ingressgateway..
The way I install Kiali is using a deployment.yaml, here's the content of the config.yaml that is translated into a configmap:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
data:
  config.yaml: |
    spec:
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    istio_namespace: istio-system
    deployment:
      accessible_namespaces:
      - '**'
      additional_service_yaml: {}
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      configmap_annotations: {}
      custom_secrets: []
      host_aliases: []
      hpa:
        api_version: autoscaling/v2beta2
        spec: {}
      image_digest: ""
      image_name: quay.io/kiali/kiali
      image_pull_policy: Always
      image_pull_secrets: []
      image_version: v1.59
      ingress:
        additional_labels: {}
        class_name: nginx
        override_yaml:
          metadata: {}
      ingress_enabled: false
      instance_name: kiali
      logger:
        log_format: text
        log_level: info
        sampler_rate: "1"
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: istio-system
      node_selector: {}
      pod_annotations: {}
      pod_labels:
        sidecar.istio.io/inject: "false"
      priority_class_name: ""
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      secret_name: kiali
      security_context: {}
      service_annotations: {}
      service_type: ""
      tolerations: []
      version_label: v1.61.0
      view_only_mode: false
    external_services:
      grafana:
        enabled: true
        in_cluster_url: 'http://grafana.grafana:3000/'
      prometheus:
        url: http://pavel-prometheus-server.monitoring
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: istio-system
        component_status:
          enabled: true
          components:
          - app_label: istiod
            is_core: true
          - app_label: istio-ingressgateway
            is_core: true
            is_proxy: true
            namespace: istio-ingress
      tracing:
        enabled: true
        url: http://test-jaeger.internal:16686
        in_cluster_url:  http://jaeger.tracing:16686
        use_grpc: false
    identity:
      cert_file: ""
      private_key_file: ""
    kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
      clustering:
        enabled: true
      disabled_features: []
      validations:
        ignore:
        - KIA1201
    login_token:
      signing_key: CHANGEME00000000
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
```
The deployment.yaml is:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: kiali
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: kiali
      labels:
        app: kiali
        app.kubernetes.io/name: kiali
        app.kubernetes.io/instance: kiali
    spec:
      serviceAccountName: kiali
      containers:
        - image: "quay.io/kiali/kiali:v1.80.0"
          imagePullPolicy: Always
          name: kiali
          command:
            - "/opt/kiali/kiali"
            - "-config"
            - "/kiali-configuration/config.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: api-port
              containerPort: 20001
            - name: http-metrics
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          env:
            - name: ACTIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "text"
            - name: LOG_TIME_FIELD_FORMAT
              value: "2006-01-02T15:04:05Z07:00"
            - name: LOG_SAMPLER_RATE
              value: "1"
          volumeMounts:
            - name: kiali-configuration
              mountPath: "/kiali-configuration"
            - name: kiali-cert
              mountPath: "/kiali-cert"
            - name: kiali-secret
              mountPath: "/kiali-secret"
            - name: kiali-cabundle
              mountPath: "/kiali-cabundle"
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: kiali-configuration
          configMap:
            name: kiali
        - name: kiali-cert
          secret:
            secretName: istio.kiali-service-account
            optional: true
        - name: kiali-secret
          secret:
            secretName: kiali
            optional: true
        - name: kiali-cabundle
          configMap:
            name: kiali-cabundle
            optional: true
```
Here's the log I see in Kiali:

```
2024-02-18T08:38:47Z INF Kiali: Version: v1.80.0, Commit: 3a1118fa7fd23a155d19a250c11a4574bf0c094e, Go: 1.20.10
2024-02-18T08:38:47Z INF Using authentication strategy [anonymous]
2024-02-18T08:38:47Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2024-02-18T08:38:47Z INF Some validation errors will be ignored [KIA1201]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2024-02-18T08:38:47Z INF Initializing Kiali Cache
2024-02-18T08:38:47Z INF [Kiali Cache] Waiting for cluster-scoped cache to sync
2024-02-18T08:38:47Z INF [Kiali Cache] Started
2024-02-18T08:38:47Z INF [Kiali Cache] Kube cache is active for cluster: [Kubernetes]
2024-02-18T08:38:47Z INF [Prom Cache] Enabled
2024-02-18T08:38:47Z INF Create Tracing HTTP client http://jaeger.tracing:16686
2024-02-18T08:38:47Z INF Server endpoint will start at [:20001/kiali]
2024-02-18T08:38:47Z INF Server endpoint will serve static content from [/opt/kiali/console]
2024-02-18T08:38:47Z INF Starting Metrics Server on [:9090]
2024-02-18T08:39:24Z ERR grafana URL is not set in Kiali configuration

```

Jaeger itself works fine and I can definitely see the traces in its' own UI.
Thanks a lot for the project! Once fully configured it'll be truly a remarkable value for us!

**Comment by jshaughn** [comment]
@pavelzag It seems this discussion was missed, sorry about that.  Are you still having the same issues?

**Comment by hamnsk** [comment]
i have some problem with config:
```
istio:
        component_status:
          enabled: true
          components:
          - app_label: istiod
            is_core: true
          - app_label: istio-ingress
            is_core: true
            is_proxy: true
            namespace: istio-ingress
        config_map_name: "istio"
        istio_api_enabled: true
        istio_identity_domain: "svc.cluster.local"
        istio_injection_annotation: "sidecar.istio.io/inject"
        istio_sidecar_annotation: "sidecar.istio.io/status"
        istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
        istiod_deployment_name: "istiod"
        istiod_pod_monitoring_port: 15014
        root_namespace: istio-system
        ingress_gateway_namespace: "istio-ingress"
```

**Reply by hamnsk** [reply]
Resolved with changes: 
```
...
  istio:
    component_status:
      enabled: true
    config_map_name: "istio"
    egress_gateway_namespace: ""
    envoy_admin_local_port: 15000
    gateway_api_classes: []
    ingress_gateway_namespace: "istio-ingress"
    istio_api_enabled: true
    istio_identity_domain: "svc.cluster.local"
    istio_injection_annotation: "sidecar.istio.io/inject"
    istio_sidecar_annotation: "sidecar.istio.io/status"
    istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
    istiod_deployment_name: "istiod"
    istiod_pod_monitoring_port: 15014
    root_namespace: ""
    url_service_version: ""
...
istio_labels:
  app_label_name: "app"
  egress_gateway_label: "istio=egress"
  ingress_gateway_label: "istio=ingress"
  injection_label_name: "istio-injection"
  injection_label_rev: "istio.io/rev"
  version_label_name: "version"
```
