### DISCUSSION TITLE
401 Error: Unable to Authenticate Kiali with External Grafana

### DISCUSSION THREAD

**Discussion by llTimKramer** [kiali/kiali#7470] [Q&A]
Hi,

I'm experiencing an issue with connecting Kiali to an external Grafana instance, which is publicly accessible but located in a different Kubernetes cluster. When authentication is enabled in Grafana, I receive a status 401 error. However, with anonymous access, everything works correctly. I’ve tried both basic authentication and bearer token methods, but both result in the same 401 error:

`logger=context userId=0 orgId=0 uname= t=2024-06-25T16:54:51.778872076Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=<IP> traceID=`

`logger=context userId=0 orgId=0 uname= t=2024-06-25T16:54:51.778958955Z level=info msg="Request Completed" method=GET path=/api/frontend/settings status=401 remote_addr=<IP> time_ms=0 duration=217.938µs size=102 referer= handler=/api/frontend/settings/ status_source=serve`

Kiali is deployed with the Kiali-operator. The Operator was installed with helm with default values.

Here are the relevant spec fields in the Custom Resource (CR):
_([jmazzitelli] I updated this by wrapping in triple-ticks so github will format the yaml properly, thus we can see the indentation and the values easier)_
```yaml
spec:
  auth:
    strategy: token
  deployment:
    accessible_namespaces:
    - '**'
  external_services:
    grafana:
      auth:
        password: secret:grafana-pw:password
        type: basic
        username: kiali
      dashboards:
      - name: Istio Service Dashboard
        variables:
          namespace: var-namespace
          service: var-service
      - name: Istio Workload Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
      - name: Istio Mesh Dashboard
      - name: Istio Control Plane Dashboard
      - name: Istio Performance Dashboard
      - name: Istio Wasm Extension Dashboard
      enabled: true
      url: https://<grafana-url>
```

I successfully queried the Grafana API within the cluster using both basic authentication and a bearer token. Despite this, I still encounter the 401 error when accessing through Kiali with authentication enabled.

Could you please assist in identifying the cause of this error and suggest a solution?

Thank you!
Tim
