### DISCUSSION TITLE
Why External Links didn't appear in my Custom Dashboard?

### DISCUSSION THREAD

**Discussion by jmueducn** [kiali/kiali#7630] [Q&A] [answered]
I am testing Kiali's custom dashboard. 
Information:
Kiali
v1.67.0 (e150adeb70aed909c41d3e964bc15b2b9ee7cccd)
Kiali Container
v1.67.0
Service Mesh
Istio 1.18.0
Components
Istio
1.18.0
Prometheus
2.43.0
Kubernetes
v1.23.8+k3s1

![g1](https://github.com/user-attachments/assets/93ac7a74-fd01-45b7-982b-49c1d5407f1e)
kiali CR:
```
 custom_dashboards:
  - discoverOn: envoy_server_uptime
    externalLinks:
    - name: newdashboard
      type: grafana
    items:
    - chart:
        dataType: raw
        metricName: envoy_server_uptime
        name: Pods uptime
        spans: 12
    name: grafana-test
    runtime: GRAFANA
    title: Grafana metrics
```
/kiali/api/grafana:
```
{
    "externalLinks": [
        {
            "url": "http://xxxxx:4000/d/Jujamcyn/oneboxistio-service-dashboard",
            "name": "oneboxIstio Service Dashboard",
            "variables": {
                "namespace": "var-namespace",
                "service": "var-service"
            }
        },
        {
            "url": "http://xxxxx:4000/d/UbsSZTDik/istio-workload-dashboard",
            "name": "Istio Workload Dashboard",
            "variables": {
                "namespace": "var-namespace",
                "workload": "var-workload"
            }
        },
        {
            "url": "http://xxxxx:4000/d/G8wLrJIZk/istio-mesh-dashboard",
            "name": "Istio Mesh Dashboard",
            "variables": {}
        },
        {
            "url": "http://xxxxxx:4000/d/1813f692a8e4ac77155348d4c7d2fba8/istio-control-plane-dashboard",
            "name": "Istio Control Plane Dashboard",
            "variables": {}
        },
        {
            "url": "http://xxxxx:4000/d/vu8e0VWZk/istio-performance-dashboard",
            "name": "Istio Performance Dashboard",
            "variables": {}
        },
        {
            "url": "http://xxxxx:4000/d/ddrtf4knddzwgc/graph1",
            "name": "Graph1",
            "variables": {}
        },
        {
            "url": "http://xxxxx:4000/d/adurix7gdunlse/newdashboard",
            "name": "newdashboard",
            "variables": {}
        }
    ]
}
```
I added annotations on the statefulsets:
kiali.io/dashboards: grafana-test
However, there is no external Link found in the dashboard
