### DISCUSSION TITLE
How to integrate Kiali with Prometheus in different namespaces?

### DISCUSSION THREAD

**Discussion by seikyo-cho-lvgs** [kiali/kiali#7640] [Q&A] [answered]
I installed Prometheus in monitoring namespace by operator:

    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace

Then installed kiali by Istio addon example:

    kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.23/samples/addons/kiali.yaml

The source:

    https://github.com/istio/istio/blob/master/samples/addons/kiali.yaml#L392-L393

But I got this error in kiali pod's log:

    Error fetching health per service kubernetes: Post "http://prometheus.istio-system:9090/api/v1/query": dial tcp: lookup prometheus.istio-system on 10.43.0.10:53: no such host

The real prometheus url is http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090. How to use the current one?

And is it necessary to config current prometheus to scrape kiali(istio) metrics? If so, how to do?

**Comment by jmazzitelli** [comment, marked as answer]
See Kiali docs: https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/

You are using the Istio addon yaml, which is meant only for "kick the tires" demos, and not easily re-configurable. In your case, you need to update the Kiali ConfigMap that the addon yaml creates. There are no docs for that. But the settings you see in the docs are similar (they are just moved over to the ConfigMap for the most part).

As for the question `is it necessary to config current prometheus to scrape kiali(istio) metrics? If so, how to do?` ... note that the metrics aren't "Kiali" metrics - Kiali simply reads the Istio metrics that Istio stores in Prometheus. You need to refer to the Istio docs for how to integrate your own Prometheus so it can scrape Istio components for their metrics. For that, see https://istio.io/latest/docs/ops/integrations/prometheus/#configuration

**Reply by seikyo-cho-lvgs** [reply]
@jmazzitelli 

Thank you. It works:

## Prometheus

```
# values.yaml
prometheus:
  enabled: true
  prometheusSpec:
    additionalScrapeConfigs: |
      - job_name: 'istiod'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - istio-system
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: istiod;http-monitoring
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: '.*-envoy-prom'
```

```
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring -f values.yaml
```

## Kiali

```
# values.yaml
cr:
  spec:
    external_services:
      prometheus:
        url: 'http://kube-prometheus-stack-prometheus.monitoring:9090/'
```

```
helm install \
  --set cr.create=true \
  --set cr.namespace=istio-system \
  --set cr.spec.auth.strategy="anonymous" \
  --namespace kiali-operator \
  --create-namespace \
  kiali-operator \
  kiali/kiali-operator \
  -f values.yaml
```
