### DISCUSSION TITLE
Grafana Mimir and Kiali setup for multi-cluster

### DISCUSSION THREAD

**Discussion by moore-nathan** [kiali/kiali#7718] [Q&A]
I am attempting to use Grafana Mimir as my external prometheus endpoint for a mult-cluster setup, but I am running into issues. I have two clusters, both running prometheus on kubernetes, that are remote-writing to Grafana Mimir. The way I am differentiating them is with relabeling like so 
```yaml
writeRelabelConfigs:
            - sourceLabels: [__address__]
              targetLabel: cluster
              replacement: test-cluster-1
            - sourceLabels: [__address__]
              targetLabel: mesh_id
              replacement: test-mesh
```
and then the other cluster would be `test-cluster-2`. This works in that I can query mimir and see the data in Grafana with them being differentiated by the label added.

The issues I am seeing seem to be around how I am configuring Kiali to use the Grafana Mimir Prometheus endpoint. Using the kiali-operator helm chart I have it setup like so
```yaml
cr:
  create: true
  spec:
    external_services:
      grafana:
        enabled: false
      prometheus:
        url: "http://mimir-ingress-url:80/prometheus"
        health_check_url: "http://mimir-ingress-url:80"
        query_scope:
          mesh_id: test-mesh
    auth:
      strategy: anonymous
```
Kiali is shows that it successfully reaches the Mimir, but shows Prometheus version unknown and all of the metric graphs are empty. I've read the docs on this part here [kiali prometheus docs](https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#:~:text=Kiali%20may%20show%20empty%20metrics%20if%20the%20TSBD%20does%20not%20implement%20the%20/api/v1/status/config) and I'm wondering if this is even possible with mimir and/or if anyone has done this before.

- Istio
- - App Version `1.22`
- - Helm chart `istio-base`, `istio-d`  version `1.22`
- Kiali
- - App Version `v1.89.0`
- - Helm chart `kiali-operator` version `1.89.0`
- Grafana Mimir
- - App Version `2.13.0`
- - Helm chart `mimir-distributed` version `5.4.1`
- Prometheus
- - App Version `v0.75.1`
- - Helm chart `kube-prometheus-stack` version `61.3.2`
