### DISCUSSION TITLE
operator fails with "string indices must be integers" and "cannot load parse_selectors"

### DISCUSSION THREAD

**Discussion by jmazzitelli** [kiali/kiali#7845] [Q&A] [answered]
Using the new Kiali 2.x discovery selectors, when I specify a single matchExpressions, the operator gets a weird error:

```
TASK [default/kiali-deploy : Find namespaces selected by the discovery selectors] ***

fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred
on ({{ discovery_selectors | parse_selectors }}): string indices must be integers.
string indices must be integers"}
...
Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while
templating string: Could not load \"parse_selectors\": 'parse_selectors'. String:
Unexpected templating type error occurred on ({{ discovery_selectors | parse_selectors }}):
string indices must be integers. string indices must be integers. Could not load
\"parse_selectors\": 'parse_selectors'\n\nThe error appears to be in
'/opt/ansible/playbooks/kiali-deploy.yml': line 14, column 5, but may\nbe elsewhere in
the file depending on the exact syntax problem.\n\nThe offending line appears to
be:\n\n\n  - name: Kiali CR status\n    ^ here\n"}
```

My discovery selector is:

```yaml
spec:
  deployment:
    discovery_selectors:
      default:
      - matchExpressions:
          key: istio-injection
          operator: Exists
```

**Comment by jmazzitelli** [comment, marked as answer]
The discovery_selectors follow the same syntax as [Istio discovery selectors](https://istio.io/latest/blog/2021/discovery-selectors/).

In this case, make sure "matchExpressions" is a list, even if you only have one expression to define. If you do not make it a list, you will get errors. In this case, add a dash (`-`) before the `key`. i.e.:
```yaml
spec:
  deployment:
    discovery_selectors:
      default:
      - matchExpressions:
        - key: istio-injection
      # ^ use dash up here to make this the first list item
          operator: Exists
```
