### DISCUSSION TITLE
RBAC ClusterRole and ClusterRoleBinding not working. Need help.

### DISCUSSION THREAD

**Discussion by angelosanramon** [kiali/kiali#8104] [General]
I am trying to setup ClusteRole and ClusteraRoleBinding permission with OIDC authentication. Login is working fine when `disable_rbac: false`. When `disable_rbac: true`, I get the error: `2025-01-30T16:15:35Z ERR Error fetching Namespaces for local cluster [Kubernetes]: Unauthorized`. Kiali version is v2.2.0.

Here's the ClusterRole and ClusterRoleBinding settings:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - post
- apiGroups:
  - extensions
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - gateway.networking.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kiali-admins
```

Here's the KialiCR:
```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali
spec:
  auth:
    openid:
      client_id: kiali
      insecure_skip_verify_tls: true
      issuer_uri: http://keycloak.mydomain.com/auth/realms/myrealm
      scopes:
      - profile
      - email
      - roles
      - web-origins
      - groups
      username_claim: email
    strategy: openid
  deployment:
    cluster_wide_access: true
    host_aliases:
    - hostnames:
      - keycloak.mydomain.com
      ip: 10.109.132.20
    logger:
      log_level: debug
    pod_annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
  external_services:
    grafana:
      auth:
        password: **********
        type: basic
        username: grafana-admin
      enabled: true
      external_url: http://grafana.mydomain.com
      internal_url: http://grafana.grafana.svc.cluster.local
    istio:
      egress_gateway_namespace: istio-egress
      ingress_gateway_namespace: istio-ingress
    prometheus:
      url: http://prometheus-server.prometheus.svc.cluster.local
  istio_namespace: istio-system
  server:
    web_fqdn: kiali.mydomain.com
    web_port: 443
    web_schema: https
```

Here's the JWT token from Keycloak:
```json
{
  "exp": 1738252724,
  "iat": 1738252424,
  "jti": "0907f036-80fd-4ad5-adb7-b2bcd406522e",
  "iss": "https://keycloak.mydomain.com/auth/realms/myrealm",
  "aud": "account",
  "typ": "Bearer",
  "azp": "kiali",
  "sid": "56f4a6a0-2b56-4e57-8a60-bfbd4bae2328",
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-myrealm",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile groups",
  "email_verified": false,
  "name": "Alice Aliceberg",
  "groups": [
    "kiali-admins"
  ],
  "preferred_username": "kiali-admin",
  "given_name": "Alice",
  "family_name": "Aliceberg",
  "email": "alice@mydomain.com"
}
```
