### DISCUSSION TITLE
Kiali Operator  - Ignores Kiali CR Resource Settings

### DISCUSSION THREAD

**Discussion by coffee-time-design** [kiali/kiali#8168] [Q&A]
### Describe the bug
Not sure if I am mis-understanding how Kiali gets deployed, but it appears the Kiali Operator doesn't seem to create the Kiali Deployment with the Resources Specified in the CR.
```
kubectl describe kiali -n istio-system
  Resources:
    Limits:
      Memory:  256Mi
    Requests:
      Cpu:     10m
      Memory:  32Mi

kubectl describe deployment kiali -n istio-system
  Containers:
   kiali:
    Image:       quay.io/kiali/kiali:v2.5.0
    Ports:       20001/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /opt/kiali/kiali
      -config
      /kiali-configuration/config.yaml
    Limits:
      memory:  1Gi
    Requests:
      cpu:      10m
      memory:   64Mi
```

### Expected Behavior
I expected it to deploy as per the settings in the CR.

### What are the steps to reproduce this bug?
For me, I deploy the Kiali Operator Helm Chart, then using the following override values:

```
cr:
  create: true
  namespace: "istio-system"
  spec:
    auth:
      strategy: anonymous
    deployment:
      view_only_mode: true
      accessible_namespaces:
      - '**'
    cluster_wide_access: true
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        memory: "256Mi"
```

### Environment

- **Kiali Operator Chart: 2.5.0**
- **Istio version: 1.24.3**
- **Kubernetes impl: k3s** 
- **Kubernetes version: v1.31.5+k3s1**
