### DISCUSSION TITLE
Authentication rejected: request failed 401 Unauthorized

### DISCUSSION THREAD

**Discussion by juliusoh** [kiali/kiali#8177] [Q&A]
### Describe the bug

Getting errors when trying to setup OpenID strategy
2025-02-20T08:58:23Z WRN Could not read the session: session not found: cookie kiali-token-Kubernetes does not exist in request
2025-02-20T08:58:24Z WRN Authentication rejected: request failed (HTTP response status = 401 Unauthorized)
2025-02-20T08:58:25Z WRN Authentication rejected: request failed (HTTP response status = 401 Unauthorized)
2025-02-20T08:58:25Z WRN Could not read the session: session not found: cookie kiali-token-Kubernetes does not exist in request

_(jmazzitelli updated the below yaml by simply wrapping it with the **```yaml** marker for it to be formatted correctly)_
```yaml
auth:
  strategy: "openid"
  openid:
    api_token: "access_token"
    authentication_timeout: 300
    client_id: "${client_id}"
    disable_rbac: true
    insecure_skip_verify_tls: false
    issuer_uri: "https://login.microsoftonline.com/${tenant_id}/v2.0"
    scopes:
      - "openid"
      - "profile"
      - "email"
    username_claim: "preferred_username"
  secret_name: "kiali"
  session:
    cookie:
      name: "kiali-token-kubernetes"
```
Microsoft AD App is has redirect urls for example.com/kiali url

**Comment by jmazzitelli** [comment]
_(Converting to Q&A Discussion as this is a question about setting up OpenID on Microsoft AD)_

**Comment by jmazzitelli** [comment]
I don't know what `auth.openid.session.cookie` is - that is not valid Kiali CR config as per the docs: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.auth.openid

To check the validity of your Kiali CR, please run the validation tool on it - you can find instructions on how to do this here: https://kiali.io/docs/configuration/kialis.kiali.io/#validating-your-kiali-cr

Also, AFAIK, the Kiali Server does not recognize env vars embedded in values - so `${tenant_id}` and `${client_id}` isn't doing what you think it might be doing.

**Comment by jmazzitelli** [comment]
Here's the OpenID docs: https://kiali.io/docs/configuration/authentication/openid/

**Reply by sarditi** [reply]
Followed https://kiali.io/docs/configuration/authentication/openid/ - got to the same error as @juliusoh 
Checked the secret is loaded, redirect_uri etc. 
Without openid kiali functions smoothly

**Comment by juliusoh** [comment]
auth:
  strategy: "openid"
  openid:
    api_token: "access_token"
    authentication_timeout: 300
    client_id: ""
    disable_rbac: true
    insecure_skip_verify_tls: false
    issuer_uri: "https://login.microsoftonline.com//v2.0"
    scopes:
      - "openid"
      - "profile"
      - "email"
    username_claim: "preferred_username"


Even with these configs I am still getting

2025-02-20T17:43:11Z WRN Authentication rejected: request failed (HTTP response status = 401 Unauthorized)
2025-02-20T17:43:12Z WRN Could not read the session: session not found: cookie kiali-token-Kubernetes does not exist in request

**Reply by juliusoh** [reply]
I also have the secret defined
resource "kubectl_manifest" "kiali_azure_secret" {
  yaml_body = <<YAML
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
  data:
  - secretKey: oidc-secret
    remoteRef:
      key: ${local.aws_secrets_name}
      property: azure-client-secret
  - secretKey: client-id
    remoteRef:
      key: ${local.aws_secrets_name}
      property: azure-client-id
  - secretKey: tenant-id
    remoteRef:
      key: ${local.aws_secrets_name}
      property: azure-tenant-id
YAML
}

**Reply by juliusoh** [reply]
@jmazzitelli 

Basically I see the microsoft screen to approve the kiali app and then see this after
![image](https://github.com/user-attachments/assets/7bc48b9e-aa31-4cff-b78f-75a7d76e940d)

**Comment by iamhritik** [comment]
any update on this issue ?

**Comment by gwyn-bleidd** [comment]
Hi, I had the same issue with kiali-server and keycloak auth.

Logs were just like yours Could not read the session: session not found: cookie kiali-token-Kubernetes does not exist in request

Go to developer console in browser, open Application tab, and look which name of cookie appear when you click "Log in"

For me it was "kiali-token-nonce-kubernetes"

So I added it to config

```
auth:
  openid:
    client_id: "kiali-istio"
    issuer_uri: "https://iam-domain/realms/myrealm"
    disable_rbac: true
    password: secret:secrets-kiali:oidc-secret
    insecure_skip_verify_tls: true
  strategy: "openid"
  session:
    cookie:
      name: "kiali-token-nonce-kubernetes"
```

After helm upgrade everything start working.
