### DISCUSSION TITLE
Default Namespaces not appearing in dashboard

### DISCUSSION THREAD

**Discussion by odellem** [kiali/kiali#8298] [Q&A]
### Describe the bug

I cannot see the default namespaces in kiali even if i am a cluster-admin

### Expected Behavior

I should see every namespace from the dropdown if I am a cluster admin

### What are the steps to reproduce this bug?

1. Install kiali
2. access the dashboard/ui
3. Open the dropdown for namespaces

### Environment

- **Kiali version: v2.5.0**
- **Istio version: 1.23.0**
- **Kubernetes impl: kind** 
- **Kubernetes version: v1.32.2**

**Comment by odellem** [comment]
It works if you provide a generic discovery selector but this should be in the docs:
Example:
```yaml
spec:
    discovery_selectors:
        default:
        - matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: Exists
```
