### ISSUE TITLE
Run kiali behind the proxy application just like kubectl proxy

### ISSUE THREAD

**Issue by inyee786** [kiali/kiali#1059]
**Describe the bug**
I have an application which works like a kubeclt proxy, when I run kiali behind the application proxy the UI is not coming up because the `base href` is point to incorrect path

So when i hit the kiali service  url
ie: `https://xyz.com/abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali/` 

in the index.html file the base tag  `<base href="/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali/" />` is point the incorrect path

and it can't able to load all the other file(env.js manifest.json etc) because of the incorrect path in `base tag`

**Versions used**
Kiali: 0.16
Istio: 1.1.5
Kubernetes flavour and version: GKE v1.9.7-gke.7

**Expected behavior**

base href tag should point to
`abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali`

**Comment by jmazzitelli** [comment]
Can you provide your kiali configuration? Specifically, the kiali configmap found in istio-system namespace: `kubectl get configmap kiali -n istio-system -o yaml`

I assume you installed Kiali using the upstream helm chart - if that is correct, what was the command you used to install Kiali and what is the values.yaml (if you changed it?). If you used the Kiali operator, what does your Kiali CR look like (`kubectl get kiali kiali -n kiali-operator -o yaml`).

All of this is to figure out what you set the kiali web_root configuration setting to.

**Comment by inyee786** [comment]
Download the latest binary from istio repo
there was istio-demo.yaml inside `istio-1.1.5/install/kubernetes/istio-demo.yaml` which i applied

kiali config map
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
data:
  config.yaml: |
    istio_namespace: istio-system
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: 
      grafana:
        url: 
```

**Comment by jmazzitelli** [comment]
Look in your deployment yaml:

```
 - name: SERVER_WEB_ROOT
   value: /kiali
```

Your Kiali is bound to base context root path of `/kiali` which is the default. This means Kiali is assumed to be accessible at some URL `<protocol>://<server>:<port>/kiali`. If your context root path is different, you will need to change that value.

When you install using that demo profile of upstream Istio helm chart, you tell Kiali what you want this context root to be by setting the helm setting `--set kiali.contextPath=/your/root/here` as you see here in the [helm chart values.yaml file](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/values.yaml#L8). That is where see the default value of `/kiali` is defined for that SERVER_WEB_ROOT env variable - so you will want to override it via `--set kiali.contextPath` when you run the helm apply/helm install. Or you can go right in the deployment after you install and change the SERVER_WEB_ROOT value.

As a side note, in later versions of Kiali, this value is obtained directly in the `web_root` config setting in the operator's Kiali CR - but you are using the version of Kiali that comes with upstream Istio so the SERVER_WEB_ROOT env var setting in the deployment is where this setting is found.

**Comment by inyee786** [comment]
So you are saying in deployment yaml i should write the below comfig
```
- name: SERVER_WEB_ROOT
  value: abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali
```

but in the above case it failed the regex test with only allow alphanumeric text

**Comment by jmazzitelli** [comment]
> So you are saying in deployment yaml i should write the below comfig

Yes.

> value: abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali

Then that will need to be changed in the kiali code since kiali does not accept any non-alphanumeric chars in the path. This line needs to change: https://github.com/kiali/kiali/blob/master/kiali.go#L189

The only way around this for you is you would need to define an alias in your proxy so that long path of yours (`abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali`) is aliased to something without the ":" in it (`:80`) and set that alias to the kiali deployment's WEB_ROOT.

**Comment by jmazzitelli** [comment]
I created a JIRA for the kiali team to track this. This is an easy one to fix: https://issues.jboss.org/browse/KIALI-2836

**Comment by inyee786** [comment]
Just for the information previously, I went inside the `Pod` and edited the index.html base herf to `abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali` but when i open the kiali ui  `api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali` path is added at the end of base href.
The overal base url become 
```
abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali
```

**Comment by inyee786** [comment]
i have commented out the line to bypass the check https://github.com/kiali/kiali/blob/master/kiali.go#L189 bad build the docker image

after that my base herf is changed to `abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali` but when i try to open the ui i am getting 404 error

The url which i tried

`https://xyz.com/abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali`
`https://xyz.com/abc/clustername/api/v1/namespaces/istio-system/services/kiali:80/proxy/kiali/consloe`

**Comment by inyee786** [comment]
my question is can we run kiali in reverse proxy?

**Comment by inyee786** [comment]
@jmazzitelli thanks for the above pr,

can you tell me what is the best way run kiali in my local development server so that kiali use the local kube config??

and another question is can we run kiali behind the reverse proxy?

**Comment by israel-hdez** [comment]
@inyee786 

> can you tell me what is the best way run kiali in my local development server so that kiali use the local kube config??

Try to follow https://github.com/kiali/kiali#running
Or do you have a different setup?

> my question is can we run kiali in reverse proxy?

It should be possible. The reverse proxy should be setup to pass the full request_uri to kiali. AFAIK, reverse proxies can be setup to one of these configs:

* User access http://reverse_proxy_host/path_to_kiali/, and the proxy forwards the request to http://kiali_host/
* User access http://reverse_proxy_host/path_to_kiali/, and the proxy forwards the request to http://kiali_host/path_to_kiali/
* User access http://reverse_proxy_host/path_to_kiali/, and the proxy forwards the request to http://kiali_host/custom_path/
* ...and any other configs the reverse proxy may allow

Kiali needs the reverse proxy configured with second approach. Else, most likely you will get the 404 errors you are commenting.

**Comment by inyee786** [comment]
found an interesting thing i was running kiali using `kubectl proxy`

with the new config having `auth strategy = anonymous` with the latest kiali build

when accessing it on web
with the url
`http://127.0.0.1:8001/api/v1/namespaces/istio-system/services/kiali:20001/proxy/kiali/` which redirects to `http://127.0.0.1:8001/kiali/console/overview?duration=60&pi=15000` which is wrong
 
kiali config
```
apiVersion: v1
data:
  config.yaml: "istio_namespace: istio-system\nserver:\n  port: 20001\nauth:\n  strategy:
    anonymous\nexternal_services:\n  istio:\n    url_service_version: http://istio-pilot:8080/version\n
    \ jaeger:\n    url: \n  grafana:\n    url: \n"
kind: ConfigMap
metadata:
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  name: kiali
  namespace: istio-system

```

**Comment by inyee786** [comment]
@israel-hdez 
The step which I follow the run kiali in local
i follow the step from here

```
cd gopath/kiali
git clone https://github.com/kiali/kiali.git
make install
make run
```

after following the above step got the below error and i got the same error when i run the binary of kiali
```
Running...
I0516 00:33:13.893754    7649 kiali.go:67] Kiali: Version: v0.20.0-SNAPSHOT, Commit: c8e23fd382b725054431c8b739315e90454ab75c
I0516 00:33:13.893814    7649 kiali.go:68] DEBUG: Kiali: Command line: [/home/inyee/GoWorkspace/bin/kiali -v 4 -config config.yaml]
I0516 00:33:13.893834    7649 config.go:461] DEBUG: Reading YAML config from [config.yaml]
I0516 00:33:13.894217    7649 kiali.go:203] Using authentication strategy [login]
E0516 00:33:13.894243    7649 kiali.go:237] Failed to determine console version from file [/opt/kiali/console/version.txt]. error=open /opt/kiali/console/version.txt: no such file or directory
I0516 00:33:13.894252    7649 kiali.go:88] Kiali: Console version: unknown
E0516 00:33:13.894371    7649 kiali.go:106] Jaeger is not available : Get http:///api/services: http: no Host in request URL
I0516 00:33:13.898017    7649 server.go:49] Server endpoint will start at [localhost:8000/]
I0516 00:33:13.898048    7649 server.go:50] Server endpoint will serve static content from [/opt/kiali/console]
I0516 00:33:13.898121    7649 metrics_server.go:18] Starting Metrics Server on [localhost:9090]
W0516 00:33:21.899352    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0516 00:33:31.900458    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0516 00:33:41.901710    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0516 00:33:51.903017    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
I0516 00:33:53.251310    7649 authentication.go:101] DEBUG: (Re-)authentication was asked. Validation of old token failed with: token contains an invalid number of segments
I0516 00:33:53.585710    7649 discover.go:37] DEBUG: Kiali is looking for Tracing/Jaeger service ...
E0516 00:33:53.585789    7649 config.go:101] Failed to fetch Prometheus configuration: Get http://prometheus.istio-system:9090/api/v1/status/config: dial tcp: lookup prometheus.istio-system on 127.0.0.53:53: no such host
I0516 00:33:53.585861    7649 discover.go:47] DEBUG: Kiali not found Tracing/Jaerger
E0516 00:33:53.588824    7649 config.go:101] Failed to fetch Prometheus flags: Get http://prometheus.istio-system:9090/api/v1/status/flags: dial tcp: lookup prometheus.istio-system on 127.0.0.53:53: no such host
E0516 00:33:53.889640    7649 namespaces.go:16] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
W0516 00:34:01.904142    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
E0516 00:34:08.839129    7649 namespaces.go:16] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
W0516 00:34:11.905183    7649 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
```

below is the kiali config
```
server:
  address: localhost
  port: 8000

  # Uncomment credentials to enable basic authentication for server
  # If you are deploying Kiali in Kubernetes or Openshift, to enable authentication you should use Secrets
  # and pass credentials through environment variables.
  credentials:
    username: admin
    passphrase: admin

  # Web context path to serve Kiali API and frontend from.
  # Default is /
  # web_root: /kiali

  # Uncomment static_content_root_directory to set up a different directory for static front-end content.
  # Default is /opt/kiali/console
  # static_content_root_directory: /static-files

  # Uncomment cors_allow_all to allow serving front-end from a different host (mainly for development)
  # Default is false
  # cors_allow_all: true
external_services:
  prometheus_service_url: http://prometheus-istio-system.127.0.0.1.nip.io
  # Uncomment istio_identity_domain to set a different value. This value must match the Istio configuration.
  # Default is "svc.cluster.local" (which matches Istio's default)
  # istio_identity_domain: svc.cluster.local
  jaeger:
    url: http://jaeger-query-istio-system.127.0.0.1.nip.io
  grafana:
    url: http://grafana-istio-system.127.0.0.1.nip.io
  # Uncomment grafana_service_url, used to generate links to Grafana
  # If unset, the Grafana service URL will be looked up from Kubernetes Grafana service. It may not always be available.
  # grafana_service_url: http://grafana-istio-system.127.0.0.1.nip.io

# Uncomment in_cluster to set a different value.
# Default is true (which matches Kiali default configuration to run inside a pod running on kubernetes)
# in_cluster: true

# Uncomment to use another istio labels
#istio_labels:
  # Uncomment app_label_name to set up a different label name for grouping all resources of an app.
  # Default is "app"
  # app_label_name: app

  # Uncomment service_label_name to set up a different label name for grouping all resources of an app version.
  # Default is "version"
  # version_label_name: version
```

**Comment by israel-hdez** [comment]
@inyee786 
> found the solution of secret error create a secret folder /kiali-secret and added two files for username(put username) and passphrase(put password) but from the config file it is not working

Sorry for that trouble. Support to specify credentials through environment variables and from the config.yaml file was removed in PR #883.

I'll make sure that the sample config.yaml is updated to remove those lines and avoid future confusion.

> when accessing it on web
with the url
http://127.0.0.1:8001/api/v1/namespaces/istio-system/services/kiali:20001/proxy/kiali/ it redirects to http://127.0.0.1:8001/kiali/console/overview?duration=60&pi=15000 which is wrong

Ok, I'll further investigate this. It's indeed a weird redirection.
BTW, is the provided kiali config truncated in https://github.com/kiali/kiali/issues/1059#issuecomment-492773697? I do't see the place where you are setting the SERVER_WEB_ROOT variable.

**Comment by inyee786** [comment]
The above config i use it for my local development

> Ok, I'll further investigate this. It's indeed a weird redirection.
> BTW, is the provided kiali config truncated in [#1059 (comment)](https://github.com/kiali/kiali/issues/1059#issuecomment-492773697)? I do't see the place where you are setting the SERVER_WEB_ROOT variable.

I am setting the env Inside the deployment 
```
        - name: SERVER_WEB_ROOT
          value: /kiali
```

**Comment by inyee786** [comment]
how to resolve the below problem for local development

`E0516 00:34:08.839129    7649 namespaces.go:16] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
`

**Comment by israel-hdez** [comment]
If I'm not wrong, you should set them as environment variables:

```bash
export KUBERNETES_SERVICE_HOST={your kubernetes cluster ip}
export KUBERNETES_SERVICE_PORT={your kubernetes cluster port}
make run
```

**Comment by inyee786** [comment]
so i have put for KUBERNETES_SERVICE_HOST: ingress ip and for KUBERNETES_SERVICE_PORT i have put the ingress port
but when it tried to loign in am getting the below erro
I0517 11:11:27.292181   14008 authentication.go:101] DEBUG: (Re-)authentication was asked. Validation of old token failed with: token contains an invalid number of segments

**Comment by israel-hdez** [comment]
For the KUBERNETES_* vars you should use the cluster API host and port. You can find this with `kubectl cluster-info`. The first line I get is:

```
Kubernetes master is running at https://127.0.0.1:8443
```

I would need to use ip 127.0.0.1 and port 8443. Most likely, ingress have the same IP, but port may be different. It is worth that you check.

The "(Re-) authentication" message is not an error, but just a "debug" message. Authentication should continue after that and that message should not block login. Please, check if there are any other error messages that may be preventing Kiali to work.

**Comment by inyee786** [comment]
it is preventing me from login
![Screenshot from 2019-05-18 10-51-15](https://user-images.githubusercontent.com/20504600/57964956-f969f880-795a-11e9-8eed-3a5a88e9ddd9.png)
![Screenshot from 2019-05-18 10-51-37](https://user-images.githubusercontent.com/20504600/57964957-f969f880-795a-11e9-881e-cddf8050f165.png)

**Comment by israel-hdez** [comment]
Hi @inyee786 
The debug message is not the issue.

Please, check that you are typing the username and password exactly as in the kiali-secret files.
Also, make sure that the secret files are trimmed - having a new line in the file will make authentication to fail since "admin" is not the same as "admin\n".

**Comment by inyee786** [comment]
i solve the issue for reverse proxy i will send a pr for that

**Comment by inyee786** [comment]
@israel-hdez  should I create a new issue for this 

> @jmazzitelli @israel-hdez
> Found an interesting thing i was running kiali using `kubectl proxy`
> 
> with the new config having `auth strategy = anonymous` with the latest kiali build
> 
> when accessing it on web
> with the url
> `http://127.0.0.1:8001/api/v1/namespaces/istio-system/services/kiali:20001/proxy/kiali/` it redirects to `http://127.0.0.1:8001/kiali/console/overview?duration=60&pi=15000` which is wrong
> 
> kiali config
> 
> ```
> apiVersion: v1
> data:
>   config.yaml: "istio_namespace: istio-system\nserver:\n  port: 20001\nauth:\n  strategy:
>     anonymous\nexternal_services:\n  istio:\n    url_service_version: http://istio-pilot:8080/version\n
>     \ jaeger:\n    url: \n  grafana:\n    url: \n"
> kind: ConfigMap
> metadata:
>   labels:
>     app: kiali
>     chart: kiali
>     heritage: Tiller
>     release: istio
>   name: kiali
>   namespace: istio-system
> ```

**Comment by israel-hdez** [comment]
@inyee786 Yes, please

**Comment by rvennam** [comment]
We are trying to log in to Kiali under kubectl proxy and seeing similar behavior. 
1. Install Istio 1.1.x with kiali add-ons
2. `kubectl proxy`
3. Visit: http://localhost:8001/api/v1/namespaces/istio-system/services/kiali:http-kiali/proxy/kiali/
4. Log in:
![image](https://user-images.githubusercontent.com/5502967/59793346-54697500-92a4-11e9-979b-5c5445818af3.png)

**Comment by israel-hdez** [comment]
Hi @rvennam 
Is `kube proxy` the only setup you did to expose Kiali?
What's the contents of your config map?

**Comment by rvennam** [comment]
@israel-hdez Yes - kube proxy is the only setup. Rest is coming directly from istio installation.

```
apiVersion: v1
data:
  config.yaml: "istio_namespace: istio-system\nauth:\n  strategy: \"login\"\nserver:\n
    \ port: 20001\n  web_root: /kiali\nexternal_services:\n  tracing:\n    url: \n
    \ grafana:\n    url: \n  prometheus:\n    url: http://prometheus:9090\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"istio_namespace: istio-system\nauth:\n  strategy: \"login\"\nserver:\n  port: 20001\n  web_root: /kiali\nexternal_services:\n  tracing:\n    url: \n  grafana:\n    url: \n  prometheus:\n    url: http://prometheus:9090\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","chart":"kiali","heritage":"Tiller","release":"istio"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: 2019-04-16T21:01:38Z
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  name: kiali
  namespace: istio-system
  resourceVersion: "14122325"
  selfLink: /api/v1/namespaces/istio-system/configmaps/kiali
  uid: d3b6ed52-608a-11e9-b3f0-ca434b166278
```

**Comment by israel-hdez** [comment]
Hi again @rvennam 

I've tried your setup and I get the same issue.

What I see is that `kubectl proxy`, apparently, all queries to any path under http://localhost:8001/ are being modified by the proxy to inject additional `Authorization` HTTP headers. Apparently, the proxy is injecting the headers to let you use the Kubernetes API without manually providing the authentication.

However, when you try to access Kiali, apparently, a conflict occurs because Kiali also uses `Authentication` HTTP headers to handle the login and the session credentials. While Kiali is expecting the login credentials, the `kubectl proxy` is modifying the request to instead pass the Kubernetes credentials turning Kiali inaccesible.

I'm checking what is in the docs. In https://istio.io/docs/tasks/telemetry/kiali/#generating-a-service-graph it's stated that you should run the following command:

`kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=kiali -o jsonpath='{.items[0].metadata.name}') 20001:20001`

and access Kiali at http://localhost:20001/kiali/console.

Alternatively, if you are already using helm, you may use the following values to build your template:

```yaml
kiali:
  enabled: true
  createDemoSecret: true
  ingress:
    enabled: true
    hosts: null
```

And you will be able to access Kiali using your ingress at http://{your_ingress_url}/kiali.

Please try these and let me know if any works for you.
