### ISSUE TITLE
[helm chart] enable more granular configurations

### ISSUE THREAD

**Issue by draeron** [kiali/kiali#1104]
**Describe the bug**

Right now, if you're using kiali as part of Istio's chart installation, you're very limited in options for configuration. For example, in our case, we need authentication for accessing grafana.

Chart template : 
```yaml
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}
```

**Versions used**
Kiali appVersion: v0.16
Istio Chart: v1.10

**Expected behavior**

Either expose all current configurations (lot of maintenance) or enable to mount a custom configmap which can be either created through a value in the chart or completely outside the chart.

I would expect something like this to be available in 
```yaml
configs:
  customPath: my-kiali-config # created outside the chart
```

or

```yaml
configs: # content of data will be set for the key config.yaml in the configmap
  data: |
    istio_namespace: istio-system
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: https://some-jaeger.com
      grafana:
        service: grafana
        service_namespace: monitoring
        api_key: 0xbaadf00d
        url: https://my-grafrana.com
```

**Side note**

This could be seperated bug, if you need to use a `api_key` or login/password with grafana, those values will get stored into a `configmaps` and won't be secured.
