### ISSUE TITLE
Mesh expansion not properly visualized

### ISSUE THREAD

**Issue by sfudeus** [kiali/kiali#1109]
**Describe the bug**

I am currently playing around with outbound mesh expansion in Istio. 
So I added two machines, installed the istio-proxy on them and added them as ServiceEntries to the ControlPlane, as described [here](https://istio.io/docs/setup/kubernetes/additional-setup/mesh-expansion/). Additionally, I added a VirtualService and made it available from an ingress gateway. The two service entries, which make up a common workload (together with the virtual service), are not visualized as such (see screenshot). 

**Versions used**
Kiali: 0.19
Istio: 1.1.6
Kubernetes flavour and version: vanilla kubernetes 1.14.1

**To Reproduce**

Add two mesh expansion nodes to an existing istio control plane. 
e.g. with the following spec. The second node might have a different version label. 
```
spec:
  hosts:
    - po-istio-meshtest-qa-bs01.ams-istio-dev.svc.cluster.local
  ports:
    - name: http
      number: 80
      protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
    - address: 10.90.22.53
      labels:
        app: po-istio-meshtest-qa
        version: v1
      ports:
        http: 80
```

Add a virtual service aggregating those dedicated hosts:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshtest
spec:
  hosts:
  - "po-istio-meshtest-qa.ams-istio-dev.svc.cluster.local"
  - "meshtest.istio.fe-sandbox-iz1-bs.myexternaldomain"
  gateways:
  - istio-system/default-gateway
  - mesh
  http:
  - route:
    - destination:
        host: po-istio-meshtest-qa-bs01
      weight: 40
    - destination:
        host: po-istio-meshtest-qa-bs02
      weight: 60
    fault:
      abort:
        percent: 1
        httpStatus: 418
```
 
**Expected behavior**

As for in-mesh services, I'd expect a visualization of the workload identified by the app label with attached virtual service and each expansion node would either be grouped into a single versioned app (when having the same version label) or be a dedicated versioned app, as e.g. available for the bookinfo sample app (see screenshot). The orange color of the expansion workload comes from the 1% injected http 418. 

<img width="1104" alt="Bildschirmfoto 2019-05-31 um 17 41 01" src="https://user-images.githubusercontent.com/8386006/58745173-becd8900-844d-11e9-8203-c31ee2b4b840.png">

I am as well surprised that the expansion nodes are displayed as Service, not as ServiceEntry. 

PS: Maybe a different bug but is highly affected by this: 
The two expansion nodes don't reliably show up in the graph, sometimes only a single node is shown, despite both nodes getting constant traffic (aggregated 5 qps). See screenshot below (now even with unused nodes enabled and still no display):
<img width="1105" alt="Bildschirmfoto 2019-06-01 um 09 27 09" src="https://user-images.githubusercontent.com/8386006/58745294-79aa5680-844f-11e9-8284-b98d713bfc83.png">

I'll gladly provide any additional details or apply config changes you might need for debugging this.
