### ISSUE TITLE
Missing graph edge kubernetes services

### ISSUE THREAD

**Issue by varungbt** [kiali/kiali#1151]
Graph edges are not shown in the Kiali console

![image](https://user-images.githubusercontent.com/4632477/59533602-a29c0400-8eb1-11e9-8d04-55cb25a52e9b.png)

**Versions used**
Kiali:v0.20
Istio: 1.1.7
Kubernetes flavour and version: GKE 1.12.7-gke.10

In this setup, first the istio ingress gateway relays the incoming traffic to nginx ingress controller. Then the nginx ingress controller forwards this traffic to the speedtest service. 

I am able to get this setup up and running, however the Kiali console does not show the required edges between the nginx ingress controller and the speedtest service.  Additionally the speedtest deployments involves a k8s service and this is not being shown in the graph console as well.

Any hints on why I do not see the required edges ?

**Comment by jshaughn** [comment]
Is the speedtest service an external serviceEntry?   Sometimes this lack of telemetry is caused by the outbound traffic policy being set to ALLOW_ANY.  You may need to set to REGISTRY_ONLY. 
 See https://istio.io/docs/tasks/traffic-management/egress/.

**Comment by varungbt** [comment]
Thanks for your reply.
Is an service entry even if all the services are in the same cluster? Both Nginx ingress  controller and the speedtest services have sidecars injected.

**Comment by abonas** [comment]
> Is a service entry required even if all the services are in the same cluster

@varungbt is speedtest service also a pod running in the same k8s cluster or is running outside of the clusteR? also, can you please paste the yaml definition of speedtest service? and elaborate how the nginx ingress controller forwards this traffic to the speedtest service? perhaps the envoy is bypassed?

**Comment by jshaughn** [comment]
A serviceEntry is not required, it is used only to reach services outside the mesh.  If speedtest is a service you defined and deployed, and it does have a sidecar injected, then I agree with @abonas, perhaps the way it is being requested is somehow not involving the sidecar proxy.  I can see from the graph above that nginx and speedtest seem to both be in the default namespace, and that they are both interacting with Istio components.  But there must be something about the way nginx is making requests to speedtest such that it is not being routed through the proxy.

**Comment by varungbt** [comment]
# istio-ingress gateway 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http2
    nodePort: 31380
    port: 80
    protocol: TCP
    targetPort: 80


```


# gateway

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP



```





# virtual-service 

```

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtual-service
  namespace: default
spec:
  gateways:
  - nginx-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-ingress-controller
        port:
          number: 80
    timeout: 86400s

```



# nginx ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app: vbergbauer-speedtest
  name: speedtest-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: speedtest-vbergbauer-speedtest
          servicePort: 8903
        path: /(speedtest)/?(.*)

```



Speedtest pods have envoy proxy injected
```

$ kubectl get pods
speedtest-vbergbauer-speedtest-dc4b589fc-ztz74   2/2       Running     0          
```



$ kubectl get logs speedtest-vbergbauer-speedtest-dc34adge-dgfd  -c istio-proxy

[2019-06-17T16:50:08.174Z] "GET / HTTP/1.1" 200 - "-" 0 1537 1 0 "-" "kube-probe/1.12+" "ddf59c27-9b5b-4af1-97e5-c3c461768a5c" "10.64.0.12:80" "127.0.0.1:80" inbound|8903|http|speedtest-vbergbauer-speedtest.default.svc.cluster.local - 10.64.0.12:80 10.64.0.1:43668 -



In the logs you can see that the incoming traffic to the pod passes via the istio envoy proxy. That means envoy is able to intercept the traffic and pass it on. In spite of the envoy proxy being able to intercept the traffic, a correpsonding edge in the graph is not shown
