### ISSUE TITLE
Feature Request: Traffic Aggregation by Node Labels

### ISSUE THREAD

**Issue by robinpercy** [kiali/kiali#1168]
Most cloud providers have the concept of "availability zones" in their networking tier. These zones are each an independent failure domain and it is generally recommended to spread a single Kubernetes clusters across multiple zones. However, networking transit across these zones incurs a cost. So it would be very useful to be able to visualize traffic as it crosses zone boundaries.

Zone information is added as a label to Kubernetes Nodes, so the general feature would be to visualize traffic aggregated by one or more node labels. 

Happy to provide more context if needed.

**Comment by robinpercy** [comment]
@lucasponce @israel-hdez  Looks like I don't have the ability to add an FR label

**Comment by israel-hdez** [comment]
@robinpercy Label added :)

**Comment by jotak** [comment]
@robinpercy looks like an interesting feature, we certainly want to know a bit more about the setup.
 The problem that we may be hitting is to not have the zone information propagated as prometheus labels in the istio metrics. To be honest, I don't know if istio provides some setup with adapted telemetry to identify zones. In the usual setup (the one that we consider for Kiali), metrics are aggregated at the workload level (ie. deployment in most cases) and we cannot get finer grain.

Do you have by chance the possibility to post here an example of istio metric with labels, for instance using the prometheus console, that you have in a multi-zone setup? (would be something like `istio_requests_total{destination_workload=foo (etc.)`)

**Comment by jshaughn** [comment]
This is an interesting feature idea but it's not a straightforward addition.   The graph types that exist today: workload, app, versioned-app, and service, are all doable because of the telemetry provided by Istio, as @jotak points out.  Even with Service as a 1st-class entity, generating the aggregate service graph is tricky.

It will be important to have a very well-defined proposal here, before anyone can really move forward with it.  We might want to start with a diagram of what the desired graph may look like, and what has been labeled that may help us understand how we may be able to put it together.

**Comment by lucasponce** [comment]
I agree this feature should start with a high level diagram.
And from that subtasks and next minor steps can be identified.

I understand that GKE provide specific labels for this scenario.

Labels from Pod are not by default used in prometheus metrics (whith are the main source for discovering the topology showed in the Graph).

So, a first experiment that @robinpercy can also play, if trying to bring these metrics into his cluster, adjusting the default templates:

```
---
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestcount
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
spec:
  value: "1"
  dimensions:
    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source", "destination")
    source_workload: source.workload.name | "unknown"
    source_workload_namespace: source.workload.namespace | "unknown"
    source_principal: source.principal | "unknown"
    source_app: source.labels["app"] | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_workload: destination.workload.name | "unknown"
    destination_workload_namespace: destination.workload.namespace | "unknown"
    destination_principal: destination.principal | "unknown"
    destination_app: destination.labels["app"] | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    destination_service: destination.service.host | "unknown"
    destination_service_name: destination.service.name | "unknown"
    destination_service_namespace: destination.service.namespace | "unknown"
    request_protocol: api.protocol | context.protocol | "unknown"
    response_code: response.code | 200
    response_flags: context.proxy_error_code | "-"
    permissive_response_code: rbac.permissive.response_code | "none"
    permissive_response_policyid: rbac.permissive.effective_policy_id | "none"
    connection_security_policy: conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
  monitored_resource_type: '"UNSPECIFIED"'
---
```

Istio allows to modify these metrics, I wonder how would look like if you add this specific label from the pod defining the zone.

This is just an experiment, but it would help us, to see how easy/difficult would be to add that extra info in the telemetry.
