### ISSUE TITLE
Service port and deployment port do not match

### ISSUE THREAD

**Issue by alexanderbuhler** [kiali/kiali#1228]
**Describe the bug**

Probably not really a bug, but something is obviously wrong with my configuration.
Kiali says the port configuration of my service is not valid.

<img width="406" alt="kiali_invalid_port_config" src="https://user-images.githubusercontent.com/5637707/60877617-77050300-a23e-11e9-97ad-6684fb32ede6.png">

I mean obviously, the service and container port don't match, but that's what a service is for at the end? Why is it a problem from kialis point of view?

So the service is configured to listen on port 80 TCP. Port ist named http. Mapped to targetPort 8080.
```yaml
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
```
The corresponding pod listens on 8080.

```yaml
        ports:
        - containerPort: 8080
```

**Versions used**
Kiali: 0.20.0
Istio: 1.2.2
Kubernetes flavour and version: 1.13.7

**To Reproduce**

1. Visit "Services" in the UI
2. View details of a service

**Expected behavior**
Port configuration is recoginzed as valid.
