### ISSUE TITLE
GRPC errors, response_flags non-empty, graph looks green

### ISSUE THREAD

**Issue by toothbrush** [kiali/kiali#1235]
**Describe the bug**

Hi.  I have a deployment of Istio 1.2.2, and i've bumped Kiali to tag v0.21.  I've deployed a service which is supposed to serve GRPC on a particular port, but it doesn't.  I'd expect to see the edge or the node in Kiali go red, but instead it stays green.  In the sidebar it correctly reports Envoy's `response_flags`, but flags indicate errors and (IMHO) should be visualised as such.

![](https://user-images.githubusercontent.com/423357/61019076-3f33c200-a3dc-11e9-89ae-f0bac3c7fc13.png)

**Versions used**
Kiali: v0.21
Istio: 1.2.2
Kubernetes flavour and version: Amazon EKS 1.13

**To Reproduce**

Deploy the following services and such:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world-service
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-service
      env: development
  template:
    metadata:
      labels:
        app: hello-world-service
        version: latest
        env: development
    spec:
      containers:
      - name: hello-world-service
        image: debian
        command: ["bash", "-c", "while true; do echo hullo; sleep 30; done"]
        env:
          - name: PORT
            value: "50051"
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  ports:
    - name: grpc-hello-world
      port: 50051
      targetPort: 50051
  selector:
    app: hello-world-service
    env: development
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway-hello-world
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "hello-world.scratchpro.link"
    port:
      name: grpc-50051-hello-world-service-platform-dev # this must be unique
      number: 50051
      protocol: grpc # https://github.com/istio/istio/issues/7843#issuecomment-413622721
    # tls:
    #   credentialName: cert-hello-world.scratchpro.link
    #   mode: SIMPLE
    #   privateKey: sds # this value can probably be omitted.
    #   serverCertificate: sds # this value can probably be omitted.
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-service-dev
  namespace: default
spec:
  hosts:
  - "hello-world.scratchpro.link"
  gateways:
  - my-gateway-hello-world
  http:
  - route:
    - destination:
        host: hello-world-service
        port:
          number: 50051
```

Go to Kiali Graph > workload graph > find the hello-world-service.  I expect that grpc edge to go red, indicating the upstream failures.  Instead, it stays green.  In the sidebar, response codes, you see the URX flag.  See https://github.com/istio/istio/issues/15400 for more context on my issue.

**Expected behavior**

I expect the edge to go red, indicating that upstream is failing.
