### ISSUE TITLE
operator: port name for service is incorrect when https is disabled

### ISSUE THREAD

**Issue by mikebryant** [kiali/kiali#1259]
**Describe the bug**

I wanted to use the operator to install kiali, with no backend https, but mtls and a virtualservice.

The resulting service is:
```
  spec:
    clusterIP: 172.20.48.68
    ports:
    - name: tcp
      port: 20001
      protocol: TCP
      targetPort: 20001
    selector:
      app: kiali
      version: v1.1.0
    sessionAffinity: None
    type: ClusterIP
```

This means istio isn't able to route traffic correctly, as the port should be named http not tcp

**Versions used**
Kiali: 1.1.0
Istio: 1.1.9
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) EKS 1.11

**To Reproduce**
```
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: "**"
    image_version: v1.1.0
    namespace: kiali
    service_type: ClusterIP
    view_only_mode: true
  external_services:
    grafana:
      url: ""
    jaeger:
      url: ""
  identity:
    cert_file: ""
    private_key_file: ""
  istio_labels:
    app_label_name: app.kubernetes.io/name
    version_label_name: app.kubernetes.io/version
  istio_namespace: istio-system
  server:
    web_root: /
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: kiali
spec:
  gateways:
  - gateway.blah...
  hosts:
  - kiali.url...
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kiali.kiali.svc.cluster.local
        port:
          number: 20001
```

**Expected behavior**
When backend https is disabled I expected the port name to be http so it can be used with istio
