### ISSUE TITLE
[Troubleshooting] Add more links to Grafana dashboards

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1268]
We can increase the number of "bridges" to Grafana:

Make customizable links to self-defined dashboards, keeping workload/service context (would need to investigate how we would make that configurable)

Follow-up subtasks:
- #1676 : Similar links from runtimes / MonitoringDashboard CR
- #1677 : Links to Grafana within the Graph nodes contextual menu

**Comment by jotak** [comment]
Adding to backlog, as it supersedes https://github.com/kiali/kiali/issues/1322

**Comment by jotak** [comment]
Example of how the config could look like:

In Kiali config:

```yml
# ...
grafana:
  dashboards:
  - name: "Istio Workload Dashboard"
    variables:
      namespace: "var-namespace"
      workload: "var-workload"
  - name: "Istio Service Dashboard"
    variables:
      namespace: "var-namespace"
      service: "var-service"
  - name: "My Custom Dashboard"
    variables:
      namespace: "ns"
      service: "svc"
```

In Runtime Dashboard CR (e.g. node.js dashboard), same format but different variables:

```yml
# ...
dashboards:
- name: "My Node.js Dashboard"
  variables:
    namespace: "ns"
    app: "app"
    version: "version"
```
