### ISSUE TITLE
Incorrect warning about duplicate host/port config on Gateways

### ISSUE THREAD

**Issue by toothbrush** [kiali/kiali#1272]
**Description**

I have one `Gateway`, configured as follows:

```yaml
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: xyz-admin-gateway
  namespace: default
  selfLink: >-
    /apis/networking.istio.io/v1alpha3/namespaces/default/gateways/xyz-admin-gateway
spec:
  servers:
    - hosts:
        - web-admin-bff.xyz.mydev.io
        - xyz.mydev.io
      port:
        name: https-443-web-admin-ui-platform-dev
        number: 443
        protocol: https
      tls:
        credentialName: cert-star.xyz.mydev.io
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
  selector:
    istio: ingressgateway
```

Kiali still reports on this one `Gateway` that there is "More than one gateway for the same host port combination".

I had a quick look at the code, and i think the error might be in this line:

https://github.com/kiali/kiali/blob/2c10cc9bae44037f21d811c141089fb6e9cf02ee/business/checkers/gateways/multi_match_checker.go#L128

If i understand correctly, we're regex matching host A against host B, both directions.  When one of the hostnames is a substring of the other one, it'll give a false positive.

A possible fix might be to wrap the match string in `^....$` to force matching the entire string, but that feels hacky.

Or, maybe i'm misunderstanding, and my configuration as pasted above is actually problematic?  It seems to work fine for me.

**Versions used**
Kiali: `quay.io/kiali/kiali:v0.21`
Istio: v1.2.2
Kubernetes flavour and version: Amazon EKS 1.13, nodes running `v1.13.7-eks-c57ff8`

**To Reproduce**
1. Deploy a `Gateway` object as above
1. Observe Kiali giving a warning on http://localhost:20001/kiali/console/namespaces/default/istio/gateways/xyz-admin-gateway

**Expected behavior**
There should be no warning about a duplicate host/port combination.
