### ISSUE TITLE
Kiali trying to fetch a deleted namespace

### ISSUE THREAD

**Issue by omerlh** [kiali/kiali#1276]
**General remarks**

**Describe the bug**
I deployed Kiali using the operator, and it worked perfectly. Today I opened it again, and I noticed a new error:
```
Could not fetch namespace list, Error: [ namespaces <> is forbidden: User "system:serviceaccount:infrastructure:kiali-service-account" cannot get resource "namespaces" in API group "" in the namespace <> ]
```
So I checked with `kubectl get ns` and I noticed the namespace that kiali complained about doesn't exist - I think it was deleted today and I guess this is why Kiali has this error. I tried to search in the code, but couldn't find where it is thrown. Restarting Kiali pod did not help. 

**Versions used**
Kiali: `kiali/kiali:v1.1`
Istio: 2.2
Kubernetes flavour and version: AKS engine (Azure), 1.12.7

**To Reproduce**
(I think this is the flow, although I'm not sure)
1. Deploy Kiali
2. Delete a namespace

**Expected behavior**
Kiali handle the namespace deletion without errors

**Comment by abonas** [comment]
Hi @omerlh , thanks for filing this. Does your setup list perhaps the deleted namespace in the Kiali config in the "accessible_namespaces" section?

**Comment by omerlh** [comment]
No, this is the CRD:
```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: <>
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  istio_namespace: "istio-system"
  api:
    namespaces:
      exclude:
      - "istio-system"
      - "kube.*"
      label_selector: kiali.io/visible=true
  auth:
    strategy: <>
  deployment:
    accessible_namespaces: ["^((<>)).*$"]
    image_name: "kiali/kiali"
    image_version: "v1.1"
    ingress_enabled: false
    namespace: "<>"
    service_type: "ClusterIP"
  external_services:
    prometheus:
      url: <>
    tracing:
      url: <>
```
