### ISSUE TITLE
Multi-cluster: Versioned graph support for virtual service routing (multiple control plane)

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1364]
In a multi-cluster setup with multiple control planes, it is possible to load balance traffic using virtual services. Load-balancing can route traffic to _local_ and _remote_ services using a VS alike this rules:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
      weight: 75
    - destination:
        host: details.bookinfo.global
      weight: 25
```

Currently, in some cases, the graph creates good connections but there are cases where the graph is creating edges in a non-desired way. For example, in the following image:

![image](https://user-images.githubusercontent.com/23639005/63559528-b13d1200-c517-11e9-8056-9bfcaec3ea75.png)

the traffic to the local reviews service and the remote reviews-small service is resolved correctly. However, traffic to local details and remote details-small services are wrong.

_The issue is present only when Service nodes are displayed._

The goal is to adequately and consistently resolve traffic to, both, local and remote services when a VirtualService is involved.
