### ISSUE TITLE
Add Kiali validations for Istio Rules

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1373]
As an admin I want to validate if Istio Rules are pointing to existing adapters/templates.
In the example,
```
match: ~
actions:
  - handler: handler.kubernetesenv
    instances:
      - attributes.kubernetes
```

Kiali could check if "handler.kubernetesenv" and "attributes.kubernetes" exists.
In case that a future modification changes a rule, I would like to have some logic to prevent potential problems.

JIRA:
https://issues.jboss.org/browse/KIALI-1964
