### ISSUE TITLE
Routing wizard should for mTLS also set up a policy object

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1381]
[12:17:29] <pilhuhn>	lponce I have in the routing wizard mTLS usage enabled. And the DR also correctly reflects that. Now I wonder if we shouldn't also create Policy objects for the destinations that are supposed to be talked to via mTLS
[12:18:14] <lponce>	pilhuhn, probably, could you open me a JIRA with the details of the Policy objects needed in a normal scenario ?
[12:18:20] <pilhuhn>	if the global setting is "permissive", it should not matter, but I am not sure if that couldn't also be strict in which case only enabling it in the DR is not enough
[12:18:28] <lponce>	I'd like to add it to leave the Wizards in a good state
[12:18:55] <pilhuhn>	Tbh. I am a bit unsure at the moment 
[12:19:13] <pilhuhn>	Yes, will open a jira. I think Xavier may also have some insights
[12:20:06] <lponce>	if the Policies is just to create a new object more we can add it, but I need to review how it plays with some use cases (wizard also handle 'updates')

I've written about mTLS here:
https://itnext.io/musings-about-istio-with-mtls-c64b551fe104

Scroll down to "Setting up mTLS for a single connection between two services" to see the policy object.

cc Xavier Canal Masjuan

JIRA:
https://issues.jboss.org/browse/KIALI-2914

**Comment by lucasponce** [comment]
Not similar, but probably related to #1847.

**Comment by abonas** [comment]
duplicate of #2041 and/or #1497 ?

**Comment by lucasponce** [comment]
cc @xeviknal this issues is an old one but worth to see if it's still valid and/or may need a change in how the wizards generate Istio config.

**Comment by xeviknal** [comment]
What we can do here is to create a PeerAuthentication object for both wizards. We can be a bit smart and only create the PeerAuthentication when is necessary. It would be 100% safe to create an object always thought.

The idea would be to create an object like the following one:

```
ApiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: foo
spec:
  selector:
    matchLabels:
      app: reviews
  mtls:
    mode: STRICT
```
When the ISTIO_MUTUAL option is selected but no mTLS is enabled within the namespace.

Similarly, we need a PeerAuthentication object when STRICT mTLS is expected but the user selects DISABLE method:

```
ApiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: foo
spec:
  selector:
    matchLabels:
      app: reviews
  mtls:
    mode: DISABLE
```
