### ISSUE TITLE
Add validation for repeating subset in VS

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1515]
Need to add a validation for repeating subset in VS
Today if user specifies the same subset more than once in VS, for example with different weights, the config is green but the mesh goes crazy 
It turns red, etc which is expected given contradictory configuration.
Attached example.

JIRA:
https://issues.jboss.org/browse/KIALI-2905

**Comment by lucasponce** [comment]
I think this is outdated for Istio 1.4 as Galley take care of it.
Please @xeviknal feel free to reopen if you think I missed something.

**Comment by xeviknal** [comment]
Galley doesn't do the checking. However, the mesh doesn't get broken.
Reopening it again. Adding this validation as warning should be the right approach.

The following VS generates the graph right after:
```yaml
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: 80
        - destination:
            host: reviews
            subset: v1
          weight: 20
```

![Screenshot of Kiali Console - 2020-01-30T152711 035](https://user-images.githubusercontent.com/613814/73458176-2a694c80-4375-11ea-828b-5bce0aade62d.jpg)
