### ISSUE TITLE
Allow to configure which annotations should be displayed per entity in UI

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1564]
Allow to configure which annotations should be displayed per entity in UI.
Based on discussion here
https://github.com/kiali/kiali/issues/1299

JIRA:
https://issues.jboss.org/browse/KIALI-3192

**Comment by jotak** [comment]
I'm thinking about a new config, that would look like this:

```yaml
- entityAnnotations:
  - name: "mydomain/git-sha"
    displayName: "GIT SHA"
  - name: "mydomain/ci-link"
    displayName: "Build URL"
```

Reading the initial request from @omerlh ( #1299 )  it seems obvious that we'll want links in some cases, so either we auto-detect URLs (starts with http) and always display them as link, or we add an extra config flag such as `showAsLink: true` within the annotation config. I would rather go first 1st option.

That would give something like this: 

![Capture d’écran de 2019-11-04 11-53-11](https://user-images.githubusercontent.com/2153442/68115975-f5766680-fef9-11e9-83f7-77192517ab1c.png)

**Comment by jmazzitelli** [comment]
> ```yaml
> - entityAnnotations:
> ```

I would call it something else - just saying "entityAnnotations" doesn't give any indication what this setting does.

A better name would be something like:

```yaml
annotations_to_display:
- name: "mydomain/git-sha"
  display_name: "GIT SHA"
```

What about labels? Is someone going to want to restrict the labels we display? If so, how about:

```yaml
for_display:
  annotations:
  - name: "mydomain/git-sha"
    display_name: "GIT SHA"
  labels:
  - name: app
    display_name: Application
```

I actually don't like the idea of restricting labels, but **if** we think people are going to want this, prepare for it now by creating that outer setting (`for_display` or something like it) so we can put both annotations and labels under it.
