### ISSUE TITLE
Could not fetch traces from Jaeger

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1647]
Kiali often shows "Could not fetch traces" from Jaeger (see attached screenshot). Jaeger all-in-one was correctly deployed and Kiali CR points to Jaeger query service.

```yaml
    tracing:
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        password: 1X/CET+lKOm0t6R5UfcYdrRMJ1gc6oCbU8DJg/i4IxCHWJ4YrZAW1kRsMvUXGCEh8fYFvjo3QLdzcarJmdqjFtr7IktKRvCnR2hcxgXncibsiKoWcDukilb9qQyw7IlXAc8PWAhy5tRvTN2/tLKAcXFSXxAkifMnEg8QOMFQ504b1Qhi3OaBNTmqBtjYRKQNhetcwTX0l+SKS7zsKISdLig79b4l3lD6zzp9BZeTdAELi7NtceR8nzbGJmRov8LTNwhzr3un20GiUMv4tII5oz9aVKYcqmDWJdY5uPJJf0zBQuZKYI7WhLa1VkVelJ6oU7KQoHxNSYYMFGyouzB9
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      namespace: istio-system
      service: jaeger-query
      url: https://jaeger-istio-system.apps.ploffay.crossproduct.rhmw.io
```

![Screenshot of Kiali  istio-system  (1)](https://user-images.githubusercontent.com/5618424/64531037-d222a700-d30e-11e9-85b7-ea7de948815d.png)

[kiali-cr.txt](https://github.com/kiali/kiali/files/3590473/kiali-cr.txt)
