### ISSUE TITLE
Jaeger URL configuration problems

### ISSUE THREAD

**Issue by Demonian** [kiali/kiali#1695]
**Describe the bug**
External Jaeger URL is used by Kiali for internal requests, which is causing problem if for example AWS ELB is used for Jaeger (Host DNS will not be resolved from pod). So basically there are two situations possible and both of them has problems.

_**Situation 1 (jaeger url config is set to Extrernal URL (AWS ELB)):**_

```
external_services:
      tracing:
        namespace: istio-system
        service: jaeger-tracing-query
        # No ability to set external URL here, because it also will be used for internal calls from Kiali pod, which could be not possible if  for example ELB is used.
        url: https://numbrs-jaeger-sandbox.cwc.io/jaeger
```
<img width="1279" alt="Screen Shot 2019-09-19 at 23 31 01" src="https://user-images.githubusercontent.com/9040058/65278841-9c16cb80-db35-11e9-8834-fd4fcc6fe994.png">

**_Situation 2 (Internal Jaeger URL is used):_**
```
external_services:
      tracing:
        namespace: istio-system
        service: jaeger-tracing-query
        # No ability to set external URL here, because it also will be used for internal calls from Kiali pod, which could be not possible if  for example ELB is used.
        url: http://jaeger-tracing-query.istio-system.svc.cluster.local:16686/jaeger
```
<img width="1274" alt="Screen Shot 2019-09-19 at 23 48 03" src="https://user-images.githubusercontent.com/9040058/65279919-f31da000-db37-11e9-8a83-ea90adbb8679.png">

So in Situation 2 redirection to Jaeger UI will not work, because Internal cluster URL is used.

**Additional information**

I have made some additional digging and I think that the fast fix could be pretty simple, this `if`
block should be deleted: [jaeger.go](https://github.com/kiali/kiali/blob/bfe9d12205121d501af93b4b97ac112ca005bd7b/handlers/jaeger.go#L49)
So internal Jaeger URL will be discovered automatically by `service`, `namespace`, `port` configuration from configs and `path` (if it configured) from External URL.

The other way to fix this is to use the same strategy as in Grafana integration configurations, where internal and external URL could be declared separately and transparent.
```
external_services:
  grafana:
        in_cluster_url: http://grafana.monitoring.svc.cluster.local:3000
        url: https://grafana-sandbox.cwc.io
```

**Versions used**
Kiali: v1.4.0 (also tested with v1.5.0-snapshot.1)
Istio: v1.2.2 (with custom ConfigMap for Kiali to support latest Kiali configurations)
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) raw k8s v1.11.7

**To Reproduce**
1. Set external Jaeger URL  that could be accessible from outside the cluster, in our case through AWS ELB (E.g. https://external-jaeger.test.com/jaeger)
2. Set `jaeger.namespace` and `jaeger.service` for Internal URL discovery.
3. Login to Kiali.
4. See error and tracing integration is disabled.
____
If in step one we will set internal URL (E.g http://jaeger-query.istio-system.svc.cluster.local:16686/jaeger) there will not be error in Kiali but redirection to Jaeger will not work (E.g. Click on `Distributed Tracing` button on UI), which is expected.

**Expected behavior**
Both redirection to Jaeger UI and internal Kiali's requests to Jaeger api works.

**Comment by lucasponce** [comment]
Thanks @Demonian.
cc @aljesusg

**Comment by aljesusg** [comment]
Hi @Demonian ,

Thanks for report the issue, kiali use the **service** parameter that you have in the configuration to fetch traces (Kiali triy autodiscover the service if is empty), we detected that this give problems in some environments like you ask us, we did a patch for the v1.0 to be aligned with grafana like you proposed.

To use the integration in Kiali you should set in the URL the endpoint to Jaeger to the UI not the internal one (http://jaeger-tracing-query.istio-system.svc.cluster.local:16686/jaeger). Please try it with the correct endpoint where you can see the Jaeger UI from your browser.

The problem here is the internal requests with jaeger.

We fixed this in the v1.0 https://github.com/kiali/kiali/pull/1628
Here is the PR to make the changes in master https://github.com/kiali/kiali/pull/1700

Thanks for this issue !!!

**Comment by Demonian** [comment]
@aljesusg Thanks for you answer. It is very cool that this issue has been already fixed=)

**Comment by aljesusg** [comment]
Anyway @Demonian  can you try to set the url in jaeger to the correct JAEGER UI endpoint to check it ?

**Comment by Demonian** [comment]
It is not working now, if i set it with `http://jaeger-tracing-query.istio-system.svc.cluster.local:16686/jaeger` redirection will not work, but all internal api calls to jaeger from kiali will work as I described in `Situation 2`, if I am setting it to `https://numbrs-jaeger-sandbox.cwc.io/jaeger`, all jaeger integration will stop working.

**Comment by aljesusg** [comment]
Hi @Demonian  I was in PTO. Can you show me your actual configmap and kiali version?

**Comment by lucasponce** [comment]
I guess that if this issue is not finally something to change in the code, but probably it requires a check/update in the kiali.io documentation how to follow these steps/troubleshooting.

**Comment by lucasponce** [comment]
Ping @Demonian

**Comment by Demonian** [comment]
@aljesusg @lucasponce Sorry missed this messages=)
Here is my current config, the problem with it is that redirection to Jaeger UI is not working (which is expected because in-cluster DNS is used):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: numbrs-istio
data:
  config.yaml: |
    istio_namespace: istio-system
    auth:
      strategy: anonymous
    server:
      port: 20001
    external_services:
      tracing:
        namespace: istio-system
        service: jaeger-tracing-query
        # if I will set external URL here there will be errors which I have described above
        url: http://jaeger-tracing-query.istio-system.svc.cluster.local:16686/jaeger
      grafana:
        in_cluster_url: http://grafana.monitoring.svc.cluster.local:3000
        url: https://grafana-integration.cwc.io
      prometheus:
        url: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        # See https://www.kiali.io/documentation/runtimes-monitoring/#_prometheus_configuration
        custom_metrics_url: http://prometheus-k8s.monitoring.svc.cluster.local:9090
```

**Comment by aljesusg** [comment]
mmm you have some services with https and others with http. 
What protocol are you using for kiali ? Is it under security?

**Comment by Demonian** [comment]
@aljesusg It is secured with `nginx-ingress`. SO to access it from external world `https` should be used, but inside the cluster it is plain http

**Comment by aljesusg** [comment]
The point @Demonian is that you can't use kiali https with jaeger in http. Browsers don't allow you to have http iframe in https sites or https iframes in htpp site.  

Documentation: http://kiali.io/documentation/distributed-tracing/

**Comment by Demonian** [comment]
@Demonian I understand this, but this is not the point, I will still be not able to access Jaeger UI with internal in-cluster URL even if it will be `https`, but my real external URL for Jaeger is `https` and jaeger could be accessible by it with `https://jaeger-integration.cwc.io`. SO this is not a problem that I cannot set url for redirections like it is for e.g. in Kiali-Grafana integration.

**Comment by aljesusg** [comment]
So the **url** should be https://jaeger-integration.cwc.io if you are able to access by browser instead http://jaeger-tracing-query.istio-system.svc.cluster.local:16686/jaeger , we fetch the error traces using the **service** name, this allow you to see the number of error traces in the error tab in the service details (If not you'll see a warning and you won't see this number but you'll have the integration  ). 

So with the url to the jaeger endpoint that you can access by browser should be work.

**Comment by Demonian** [comment]
@aljesusg This is the point)) If I set it to `external` URL there will be errors that I have described in mine first message.

**Comment by aljesusg** [comment]
@Demonian maybe we can do a videocall because it seems that we do not understand each other or I don't understand this.

The UI use the url that you set in the configuration to have the integration. (The integration is disabled in the UI if protocol is different).

Can you show me a screenshot of the about modal output of the UI? Can you see there the jaeger url endpoint?

**Comment by Demonian** [comment]
We can have a videocall. BTW screenshots for both scenarios are in the first message, or do you need some more info?

**Comment by aljesusg** [comment]
Yes I want to see a screenshot of the about modal

**Comment by Demonian** [comment]
There are no model if `external` URL is set because integration with Jaeger will be disabled

**Comment by Demonian** [comment]
Let's have a call and I will show and describe all the things.

**Comment by aljesusg** [comment]
please can you add the screenshot ? When can you have the call?

**Comment by aljesusg** [comment]
@Demonian Can you share the output of /api/jaeger too ? Maybe you are missing some configuration, try to set in_cluster_url and url. We did this change in kiali 1.6 please upgrade it.

Example:
```json
tracing:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        enabled: true
        in_cluster_url: 'https://jaeger-istio-system.apps.agutierr.devcluster.com'
        namespace: istio-system
        port: 16686
        service: 'jaeger'
        url: 'https://jaeger-istio-system.apps.agutierr.devcluster.com'
```

**Comment by Demonian** [comment]
@aljesusg Will check this today. Thanks

**Comment by Demonian** [comment]
@aljesusg My configs had this property `in_cluster_url` but it was ignored used in version `1.0.5` (my bad), but I have verified my configuration with version `1.6.1` and even `1.0.7` and everything start working, so I guess we can close this issue, and thanks for help!

**Comment by AceHack** [comment]
I'm having a very similar issue when installing istio 1.4.3, can't seem to get this working.

**Comment by jotak** [comment]
@AceHack this issue was resolved I think, following this comment: https://github.com/kiali/kiali/issues/1695#issuecomment-553867897 . What config did you do for tracing urls?

With a default install (istio demo profile) I guess this should be something like:
```
external_services:
  tracing:
    in_cluster_url: http://tracing.istio-system/jaeger
    url: # set to accessible Jaeger URL from browser, e.g. http://localhost:45919/
```
