### ISSUE TITLE
More than one gateway

### ISSUE THREAD

**Issue by alexanderbuhler** [kiali/kiali#1743]
**Describe the bug**
Might be related to https://github.com/kiali/kiali/issues/1272
Kiali shows the [more_than_one_gateway_for_the_same_host_port_combination](https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination) error at the line of the first host occurence (\*e\*)
This is the manifest:

```yaml
spec:
  servers:
    - hosts:
        - api.example.com (*e*)
      port:
        name: http-api
        number: 80
        protocol: HTTP
    - hosts:
        - api.example.com
      port:
        name: https-api
        number: 443
        protocol: HTTPS
      tls:
        credentialName: api-gateway-tls
        mode: SIMPLE
  selector:
    istio: ingressgateway
```

**Versions used**
Kiali: 1.4.2
Istio: 1.3-20190930
Kubernetes flavour and version: 1.15.3

**Expected behavior**
No error, since host are the same, but ports are different.

**Comment by lucasponce** [comment]
Thanks @alexanderbuhler for the issue
I guess that @burmanm reported a similar one.

Micke do you remember if this one was also filled in an issue ?

**Comment by burmanm** [comment]
@alexanderbuhler It shouldn't be this object alone that's creating the issue (otherwise the https-api would be marked as invalid also). And running this as a unit test seems to work fine:

```go
func TestIssue1743(t *testing.T) {
	conf := config.NewConfig()
	config.Set(conf)

	assert := assert.New(t)

	gwObject := data.AddServerToGateway(
		data.CreateServer([]string{"api.example.com"}, 80, "http-api", "HTTP"),
		data.AddServerToGateway(data.CreateServer([]string{"api.example.com"}, 443, "https-api", "HTTPS"),
			data.CreateEmptyGateway("validgateway", "test", map[string]string{
				"app": "real",
			})))

	gws := [][]kubernetes.IstioObject{[]kubernetes.IstioObject{gwObject}}
	validations := MultiMatchChecker{
		GatewaysPerNamespace: gws,
	}.Check()

	assert.Empty(validations)
}
```

Are you sure there are no other objects with similar host (in any namespace) ?

**Comment by alexanderbuhler** [comment]
Alright, I'm sensing something here. I have the default gateway enabled in the helm chart since I didn't want to mess with the default settings and just get istio to work.

```yaml
 gateways:
      enabled: true
      istio-ingressgateway:
 ...
```

Might this be the cause? The default gateway also has those ports inside its configuration:

```yaml
       - port: 80
          targetPort: 80
          name: http2
          nodePort: 31380
        - port: 443
          name: https
          nodePort: 31390
```

Might be unrelated, but I'm going to ask anyway:
Should I disable the default gateway and move all ports into my custom one? Or should I keep both gateways and just separate the ports?

What would be the better pattern here?

Thanks
