### ISSUE TITLE
[operator] add label to the kiali operator to assist automation

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1821]
had a request from someone who is setting up servicemesh and kiali via automation. If we add a label to the operator deployment resource it will help if we ever have to change the name of the deployment again (automation can rely on the label, not the name)

**Comment by jmazzitelli** [comment]
I just attempted to test this by adding a label to the CSV:

```
  install:
    strategy: deployment
    spec:
      deployments:
      - name: kiali-operator
        labels:
          app: kiali-operatorMAZZ
        spec:
        ...

```

But after installing via OLM, I do not see that label on the operator Deployment. In fact, I don't see any custom labels on ServiceMesh or Jaeger operator deployments either.. all I see are these OLM labels, so I suspect its not possible today to add labels to the deployment:

```
 labels:
    olm.owner: kiali-operator.v1.7.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-operators
```

**Comment by jmazzitelli** [comment]
I tried adding a label to the CSV's own metadata labels (thinking perhaps they get projected down to the op deployment) and I tried other permutations under deployments. Nothing is working.

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kiali-operator.v1.7.0
  namespace: placeholder
  labels:
    app: kiali-operator-mazz-csv
...
  install:
    strategy: deployment
    spec:
      deployments:
      - name: kiali-operator-foo
        metadata:
          labels:
            app: kiali-operator-metadata
        labels:
          app: kiali-operator-labels
        app: kiali-operator-standalone
...
```

The only labels I see are the `olm` labels:

```
$ oc get deployment kiali-operator -n openshift-operators --show-labels
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
kiali-operator-foo   0/1     1            0           2m17s   olm.owner.kind=ClusterServiceVersion,olm.owner.namespace=openshift-operators,olm.owner=kiali-operator.v1.7.0
```
