### ISSUE TITLE
Mysql protocol gives warnings in Kiali

### ISSUE THREAD

**Issue by lentzi90** [kiali/kiali#1885]
**Describe the bug**
According to [istio documentation](https://istio.io/docs/setup/additional-setup/requirements/), you can use `mysql` as protocol when naming Service ports. Kiali complains that `mysql` is not a valid protocol prefix.

**Versions used**
Kiali: v1.4.2
Istio: 1.3.4
Kubernetes flavour and version: GKE 1.14.7

**To Reproduce**
1. Create a Service like this:
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: mariadb
     namespace: test
   spec:
     selector:
       app: mariadb
     ports:
     - name: mysql
       protocol: TCP
       port: 3306
       targetPort: 3306
   ```
2. Go into Kiali > Services and find the Service
3. Note that Kiali complains that it has invalid configuration.

**Expected behavior**
Kiali should show Services with port name prefix `mysql` as valid.

**Additional notes**

To save someone a bit of time, [this is where the protocols are defined](https://github.com/kiali/kiali/blob/master/kubernetes/istio_details_service.go#L21).
