### ISSUE TITLE
QUESTION: Why using anonymous mode can delete the istio config?

### ISSUE THREAD

**Issue by bangau1** [kiali/kiali#1887]
Hi,

I installed kiali using istio 1.3.3 chart version. The kiali chart is configured to use `anonymous` strategy. 

```yaml
kiali:
  enabled: true
  dashboard:
    auth:
      strategy: anonymous
```

Everything works fine, except that I don't expect the user (anonymous) can delete the istio configuration. I can confirm that the `delete` action really deletes the object.
 Is this expected? Is there anyway I can disable the delete action in kiali ui dashboard?
![Screen Shot 2019-11-06 at 17 40 31](https://user-images.githubusercontent.com/352737/68291717-07eccd80-00bd-11ea-9bb4-1cf1801b6ac4.png)

Best,
Agung
