### ISSUE TITLE
Validations shown in empty namespaces

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1930]
MultiMatchGateway checker returns warnings even when there aren't any Gateways in the selected namespace. See the following:
![Screenshot from 2019-11-13 17-51-09](https://user-images.githubusercontent.com/613814/68785342-53aff180-063e-11ea-9f43-12b20f6fccfa.png)

The shown validations come from the gateways in the bookinfo namespace:
![Screenshot from 2019-11-13 17-53-49](https://user-images.githubusercontent.com/613814/68785519-940f6f80-063e-11ea-871b-f0a35e52505d.png)

Expected output:
Return an empty set of validations when there are no Istio Objects for a given namespace.

**Comment by xeviknal** [comment]
Steps to reproduce:

```
cat <<EOF | oc apply -n bookinfo -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway-copy
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

Since Gateway are shared between namespaces and the gateways are pointing to '*', all namespace in the cluster has the warning that they have a more than one gateway pointing to the same host. Actually, it is useful because if the user adds a new gateway it might be clashing with other gateways defined in the cluster.

So I guess that this is not a but. It is a legit scenario.
@lucasponce @burmanm wdyt?

Same case happened to @jshaughn in https://github.com/kiali/kiali/pull/1932#issuecomment-555629143
