### ISSUE TITLE
Support 1.4 mirror_percent in graph

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2015]
**Is your feature request related to a problem? Please describe.**
New with Release 1.4 is the ability to change the **mirror_percent**, so now instead of mirroring 100% we can now specify the mirror_percent to say 20% or whatever.

**Describe the solution you'd like**
I would like to see the **mirror_percent** show up on the mirrored traffic edge.
![mirror_percent](https://user-images.githubusercontent.com/1312165/70477515-dc7b4b00-1a8d-11ea-936d-5a61f9963a5d.png)

**Additional context**
https://istio.io/news/releases/1.4.x/announcing-1.4/change-notes/
https://istio.io/docs/tasks/traffic-management/mirroring/
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 100
    mirror:
      host: httpbin
      subset: v2
    mirror_percent: 100
```
