### ISSUE TITLE
Changes in kiali CR are not propagated (external_services url)

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#2033]
When I update kiali CR external_services section from:
``` 
 external_services:
    grafana:
      url: ''
    tracing:
      url: ''
```
to:
```
  external_services:
    grafana:
      url: 'http://test.grafana.com'
    tracing:
      url: 'http://test.jaeger.com'
```
and restart kiali pod the changes are not propagated to kiali configmap and are not visible in kiali UI in about dialog.

**Versions used**
Kiali-ui
    1.11.0 (cec5023977c1f247ab860092abb0a3a8f160a31b)
Kiali
    v1.11.0-SNAPSHOT (e5afc4d607f02697a25187626e52001c8e0eaaf6)

Components

Istio
    1.4.2 
Prometheus
    2.12.0 
Kubernetes
    v1.16.2 

**To Reproduce**
1. Install Istio 1.4 via install-istio-via-istioctl.sh -iee true -de true
2. Install the latest kiali operator and kiali via deploy-kiali-operator.sh with following env vars:
OPERATOR_IMAGE_NAME=quay.io/kiali-qe/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=Always
OPERATOR_IMAGE_VERSION=latest
OPERATOR_INSTALL_KIALI=true
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=master
OPERATOR_WATCH_NAMESPACE=kiali-operator
ACCESSIBLE_NAMESPACES=default
AUTH_STRATEGY=openshift
CREDENTIALS_CREATE_SECRET=false
GRAFANA_URL=
KIALI_CR=
KIALI_IMAGE_NAME=quay.io/kiali-qe/kiali
KIALI_IMAGE_PULL_POLICY=Always
KIALI_IMAGE_VERSION=latest
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
3. check that kiali CR contains:
```
  external_services:
    grafana:
      url: ''
    tracing:
      url: ''
```
4. Change it to:
```  
  external_services:
    grafana:
      url: 'http://test.grafana.com'
    tracing:
      url: 'http://test.jaeger.com'
```

5. Save and restart kiali pod

**Expected behavior**
URLs from step 4 are propagated to kiali UI about dialog.
