### ISSUE TITLE
Innaccurate validation References for DR multimatch validation

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2052]
References aren't accurate when you have the following DRs:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviewsa
spec:
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviewsb
spec:
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviewsc
spec:
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
```

References for reviewsa, should be reviewsb and reviewsc. For reviewsb, should be reviewsa, reviewsc. For reviewsc, should be reviewsa, reviewsc.
That is not happening now.
