### ISSUE TITLE
[operator] Kubernetes Ingress always assumes HTTPS when it should not

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2066]
In the Kiali CR there is a "spec.deployment.ingress_enabled" setting that when true (the default) tells the operator to create a Kubernetes Ingress when installing on Kubernetes (non-OpenShift) environment.

When testing on minikube for example, you will see an Ingress created with the nginx annotations set to indicate HTTPS. But if you do not have Kiali configured for HTTPS (that is, the `identity` settings set to empty strings which disables HTTPS) these Ingress nginx annotations need to be set accordingly to turn off the expectation of HTTPS on the backend.

The problem is here:

https://github.com/kiali/kiali/blob/v1.11/operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml#L9-L14

```
  annotations:
    # For ingress-nginx versions older than 0.20.0
    # (see: https://github.com/kubernetes/ingress-nginx/issues/3416#issuecomment-438247948)
    nginx.ingress.kubernetes.io/secure-backends: "true"
    # For ingress-nginx versions 0.20.0 and later
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

We need to do some similar templating as we do in the [service template](https://github.com/kiali/kiali/blob/v1.11/operator/roles/kiali-deploy/templates/kubernetes/service.yaml#L14).
