### ISSUE TITLE
Remove "external_services -> tracing -> url" and Tracing is gone

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2166]
Happens on master.
In Kiali CR, remove "external_services -> tracing -> url" and leave only the "in_cluster_url".

Tracing tab is not shown, Jaeger URL is NA in info, no any notification:
![Screenshot from 2020-01-28 11-10-32](https://user-images.githubusercontent.com/604313/73254511-d583d580-41be-11ea-8032-e08fef2905e4.png)
![Screenshot from 2020-01-28 11-11-47](https://user-images.githubusercontent.com/604313/73254585-fd733900-41be-11ea-9969-8a9122ea4b29.png)

**Comment by aljesusg** [comment]
Yep I fixed this in the other PR hayk let me merge it and we can check this again

**Comment by aljesusg** [comment]
We can close this one, Can you verify @hhovsepy ?

**Comment by lucasponce** [comment]
Please, link the PR that closes this one as a reference.

**Comment by aljesusg** [comment]
This PR set the URL to empty string https://github.com/kiali/kiali/pull/2177 . Anyway the operator set by default a empty string to this value in https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/defaults/main.yml#L123 like mazz told us.

I tested it, I removed the url with a configmap
```yml
tracing:
    enabled: true
    in_cluster_url: http://localhost:16686
    namespace_selector: true
    port: 443
    auth:
      insecure_skip_verify: true
      password: iYWVMHFGzy0tatBS7gHWeRLA+rXd7tTmtWCVjxTa52LpMNB9TITjulloPyT7Bi1+NuJxhpTn7V69Amvakd5bgMIUvcsZTWfjYAvg9NOs3NJjrfjY03gQpekYJPGloxw5IxCGOfNHfMFOq0Ohf8c9bsLTRJHy3/M8+nrfZDQb2cEHGtHJrkUHs/18SW9jNYAgwKiojx8d+OHT2ITq0fpQmZAvikeB17ik1DQSVi3B5EQ4tLGZB54dOs7G/xKyTBklPFoP40C7ugbmsBEH61Zqj/GH1QQubby8SnH0ur8TgWlC71VUy8opo9hqqICJ5IHPQMcRYGRjnTWXYQJJfJFU
      type: basic
      use_kiali_token: false
      username: internal
```
and the result is 

```json
{"url":"","namespaceSelector":true,"integration":true,"integrationMessage":""}
```
