### ISSUE TITLE
Tracing and metrics fail to resolve

### ISSUE THREAD

**Issue by dcberg** [kiali/kiali#222]
I have istio 0.7.1 installed with all of the add-ons (includes jaeger). However when I follow the instructions to install kiali I see errors to resolve grafana and jaeger services in the kiali UI. I don't see a configuration map that allows me to set the service URL. Are there built-in assumptions about the istio installation that kiali has baked in that I must use the istio install from the kiali project (I wouldn't think this would be the case). 

Note, everything is installed in the istio-system namespace. I am using a 1.10.1 kubernetes install in IKS. Istio with grafana and jaeger are working fine.

**Comment by jotak** [comment]
@dcberg thank you for reporting an issue.
I'm assuming the issue you have is incorrect links to Grafana and Jaeger. Can you tell us what are the URL displayed in your UI? Or don't you have any link at all?

While in an OpenShift setup, routes are created to provide access to Jaeger and Grafana services, in a plain Kubernetes setup these routes are not available, so Kiali tries to find the Grafana & Jaeger services external IPs, if configured, and build the URLs from that. As an alternative you can override the URLs in config, either via config map (named `kiali` / `config.yaml`)
```
products:
  grafana:
    url: VALUE
  jaeger:
    url: VALUE
```
or via environment variables :
`GRAFANA_URL`  and `JAEGER_URL`

All options are described there: https://github.com/kiali/kiali#environment-variables

Hope it will help. Please let me know also if the documentation is inaccurate.

**Comment by pilhuhn** [comment]
@dcberg Thanks for the report. On top of what @jotak said: if you have a good idea on how to detect / set up the equivalent of the OpenShift routes for plain Kube, could you help us here and potentially even submit a PR ?

**Comment by abonas** [comment]
@pilhuhn AFAIK the [k8s ingress](https://kubernetes.io/docs/concepts/services-networking/ingress) is the closest equivalent to openshift route. It requires also creating an Ingress controller (without which the created ingresses won't work, but it does exist by default on GCE), while (iirc) in openshift there is a Router out of the box.

**Comment by pilhuhn** [comment]
On 29 May 2018, at 13:31, abonas wrote:

> @pilhuhn AFAIK the [k8s 
> ingress](https://kubernetes.io/docs/concepts/services-networking/ingress) 
> is the closest equivalent to openshift route. It requires

If that Ingress controller is created for Jaeger and Prometheus (which I
assume, as Istio users want to access them from outside the cluster),
we could try to find it and then populate the config map from it.

We = Kiali :-)
Patches are welcome 😎

**Comment by abonas** [comment]
@pilhuhn I cannot find any mention of ingress in p8s/grafana/jaeger "installation" files (at least for  ymls that go with istio 0.7.1)

**Comment by dcberg** [comment]
Correct...ingress is the proper way to do this in k8s. I am using IKS which comes with a pre-installed ingress controller based on nginx. I have been able to make some progress.

I created an ingress resource in k8s that looks like the following....

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali-ingress
  namespace: istio-system
  annotations:
    ingress.bluemix.net/rewrite-path: "serviceName=grafana rewrite=/;serviceName=jaeger-query rewrite=/"
spec:
  tls:
   - hosts:
     - <my-subdomain>
     secretName: <subdomain-secret>
  rules:
  - host: <my-subdomain>
    http:
      paths:
      - path: /
        backend:
          serviceName: kiali
          servicePort: 20001
      - path: /api/jaeger
        backend:
          serviceName: jaeger-query
          servicePort: 80
      - path: /api/grafana
        backend:
          serviceName: grafana
          servicePort: 3000
```

First I had to create a path to grafana and jaeger which kiali is expecting which are on the `/api/grafana` and `/api/jaeger` paths. Obviously grafana and jaeger know nothing of these paths which is why I have the rewrites in the annotation. I also had to use TLS because kiali complains if the routes are not secure (fair enough).

With the above ingress I am now seeing metrics on the service metrics tab. YAY!
But traces are still failing. In the Distributed Tracing tab I see the correct URL is used for jaeger but the page is blank (no obvious errors being thrown). When I go to the service > traces tab I get redirected to an `undefined` URL.

`https://<my-subdomain>/console/namespaces/default/services/undefined/search?service=productpage`

So close to making it work.  :)
Any ideas?

**Comment by abonas** [comment]
actually, I just saw that for Istio there is another recommended way that is not Ingress (but it works on k8s too). it is called Istio Gateway https://istio.io/docs/tasks/traffic-management/ingress/

**Comment by morvencao** [comment]
@jotak Seems that simply adding `external_services.jaeger.service` and `external_services.jaeger.service_namespace` to `kiali/config.yaml` doesn't work. 

Here is my `config` for `kiali`:
```
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
      credentials:
        username: admin
        password: admin
    external_services:
      jaeger:
        service_namespace: istio-system
        service: jaeger-query
kind: ConfigMap
metadata:
  labels:
    app: kiali
  name: kiali
  namespace: istio-system
```

Still get error from `kiali` logs:
```
...
W0612 09:58:02.514872       1 unused_service.go:62] Deployment prometheus has not a proper version label [version]
W0612 09:58:02.514985       1 unused_service.go:62] Deployment servicegraph has not a proper version label [version]
I0612 09:58:02.522922       1 graph.go:326] DEBUG: Generating config for [cytoscape] service graph...
I0612 09:58:02.522941       1 graph.go:336] DEBUG: Done generating config for [cytoscape] service graph.
E0612 09:58:04.816654       1 jaeger.go:18] Unable to find Jaeger URL: no route defined. ExternalIPs not defined on service 'jaeger'
```

Have gone through the code that generates the err:
https://github.com/kiali/kiali/blob/master/handlers/jaeger.go#L26-L65
We can see that for plain Kubernetes cluster(not OpenShift), Kiali tries to find the Jaeger services external IPs, no matter whether the `service_namespace` and `service` are defined or not.
And have tried with setting `service_url` and **environment variable**, still no good. 

/cc @gyliu513

**Comment by jotak** [comment]
@morvencao , I suspect you've read about `external_services.jaeger...` from the docs in `master`, but you're using an older version, no? Can you try to replace `external_services` with `products` ? It has been renamed [lately](https://github.com/kiali/kiali/commit/192589d1b8948d447c6715f48fea0fbe2ee83578#diff-7bd4a925c695c2eb0eced3872b9b965f).

As of why we're not using the service's DNS + port, it's because the config is only used to generate links in the front-end, so it has to be valid from your client browser standpoint, not for Kiali backend itself.

**Comment by morvencao** [comment]
@jotak Thanks for your reminder. Have updated `external_services` to `products`, still no good.
`jaeger-query` service in my env:
```
root@master:~# kubectl -n istio-system get svc jaeger-query -o yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracing
    chart: tracing
    heritage: Tiller
    jaeger-infra: jaeger-service
    release: istio
  name: jaeger-query
  namespace: istio-system
spec:
  clusterIP: 10.0.0.242
  externalTrafficPolicy: Cluster
  ports:
  - name: query-http
    nodePort: 30051
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app: tracing
    chart: tracing
    heritage: Tiller
    release: istio
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```
As you can see, I'm running `istio` and `jaeger` in a kubenetes cluster without `loadbalancer`, so the `external IP` for `jaeger-query` is empty.
