### ISSUE TITLE
LDAP Authentication with multiple OUs

### ISSUE THREAD

**Issue by enthurohini** [kiali/kiali#2464]
**LDAP integration issue with multiple OUs**

Being a big organization, we have multiple OUs in Active Directory. An example is as follow:
"CN={USERID},OU=SRE,OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"
"CN={USERID},OU=Security,OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"
"CN={USERID},OU=Team1,OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"
"CN={USERID},OU=Team2,OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"
...
"CN={USERID},OU=TeamN,OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"

Now, we want to give access to all the users that are in "Technology" OU. I am not able to do it. Below is the config for ldap:

```
auth:
      strategy: ldap
      ldap:
        ldap_base: "DC=xyz,DC=com"
        ldap_bind_dn: "CN={USERID},OU=Technology,OU=xyzIN,OU=User,DC=xyz,DC=com"
        ldap_group_filter: "(cn=%s)"
        ldap_host: "ad.xyz.com"
        ldap_insecure_skip_verify: true
        ldap_mail_id_key: "mail"
        ldap_member_of_key: "memberOf"
        ldap_port: 389
        ldap_role_filter: ""
        ldap_use_ssl: false
        ldap_search_filter: "(&(name={USERID}))"
        ldap_user_filter: "(cn=%s)"
        ldap_user_id_key: "cn"
```

Please help.

**Versions used**
Kiali:  v1.4.2
Istio:  1.3.3
Kubernetes flavour and version: On premise kubernestes v1.15.5

**Expected behavior**
It should work with the above config and should be able to consider all the users falls in the *Technology* OU like SRE, Security etc.
