### ISSUE TITLE
signing key for login tokens is invalid

### ISSUE THREAD

**Issue by benpettman** [kiali/kiali#2624]
I am using version 1.12 and I have a secret named k-login-creds, it has the values in it, its in the same namespace as kiali in my k8 cluster, but I am getting `signing key for login tokens is invalid`, which from looking at the code seems to suggest the name of the secret cannot be `kiali` or `0` in length, but for some reason it will not deploy the pod.

I have tried this with version 1.16 and get the same error. This was all working when I set it up and have not changed anything about it.

Any help to resolve would be appreciated

**Comment by benpettman** [comment]
v1.14 that hasn't been updated to have all the latest security checks in it works, so ill assume something in the latest release isn't quite working, or some extra config is needed.

**Comment by jmazzitelli** [comment]
I need more details. Because I don't think you are using v1.12 - we only introduced the restriction from not allowing the signing key to be "kial" in Kiali v1.15.1 and after.

1) how are you installing kiali?
2) are you defining the custom signing key for kiali to use?

If you are installing with Kiali Operator and you want your own signing key in a secret, in the Kiali CR's "spec.login_token.signing_key" it should be something like `secret:<your-secret-name>:<the-secret-key-whose-value-is-base64-encoded-key>`

**Comment by benpettman** [comment]
I have installed it using istio manifest file, the tagged version from  here https://quay.io/repository/kiali/kiali?tab=tags seems to suggest that v1.12 was updated 6 days ago, the same time v1.16 was....

```
kiali:
      enabled: true
      replicaCount: 1
      hub: quay.io/kiali
      tag: v1.14
      contextPath: /kiali
      nodeSelector: {}
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      ingress:
        enabled: false
        hosts:
          - kiali.local
        annotations:
        tls:
      dashboard:
        secretName: k-login-creds
        usernameKey: username
        passphraseKey: passphrase
        viewOnlyMode: false
        grafanaURL: "https://xxx.com/"
        jaegerURL: "https://xxx.com/"
      prometheusNamespace:
      createDemoSecret: false
      security:
        enabled: false
        cert_file: /kiali-cert/cert-chain.pem
        private_key_file: /kiali-cert/key.pem
```
Version 1.14 works fine, v1.12 and v1.16 do not
