### ISSUE TITLE
[operator] set proper relatedImages in metadata

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2627]
To support disconnected use-cases, our metadata sets some environment variables telling the operator what images to use. We also need to set relatedImages to the images we need.

We should use fieldRefs to refer back to the relatedImages fields so there is less changes needed to be made in the CSV yaml.

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md

So we will need to do something like this in our CSVs:

```
spec:
  relatedImages:
  - name: kiali-v1.0
    annotation: kiali-v1.0
    required: true
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel7:1.0.12
  - name: kiali-v1.12
    annotation: kiali-v1.12
    required: true
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel7:1.12.7
...
                - name: KIALI_IMAGE_default
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.0']
                - name: KIALI_IMAGE_v1_0
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.0']
                - name: KIALI_IMAGE_v1_12
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.12']
```
