### ISSUE TITLE
[operator] use fieldRefs in deployment env vars to pull in proper relatedImage names

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2641]
In the future, OLM will create annotations on operator deployments that point to the relatedImages that are defined in the CSV. Once that is implemented, we should set our KIALI_IMAGE_xyz environment variables using fieldRefs to refer to those annotations.

So the operator deployment env vars found in the CSV should look like:

```
   - name: KIALI_IMAGE_default
     valueFrom:
       fieldRef:
         fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.0']
   - name: KIALI_IMAGE_v1_0
     valueFrom:
       fieldRef:
         fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.0']
   - name: KIALI_IMAGE_v1_12
     valueFrom:
       fieldRef:
         fieldPath: metadata.annotations['olm.relatedImage.kiali-v1.12']
```

See: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md

This is related to: https://github.com/kiali/kiali/issues/2627 and https://github.com/kiali/kiali/issues/2031
