### ISSUE TITLE
Issue updating ConfigMap from Kiali Operator

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2711]
Please @jmazzitelli, take a look to this problem.

I have a dev environment on minikube.
After update the operator in this way:

```
  namespace: kiali-operator
  resourceVersion: "250912"
  selfLink: /apis/kiali.io/v1alpha1/namespaces/kiali-operator/kialis/kiali
  uid: 136500c1-8898-11ea-98b0-e0f4c42844e7
spec:
  auth:
    strategy: login
  deployment:
    accessible_namespaces:
    - '**'
    image_name: localhost:5000/kiali/kiali
    image_pull_policy: Always
    image_version: dev
    namespace: istio-system
    service_type: ClusterIP
    verbose_mode: 3
  extensions:
    iter8:
      enabled: true
    threescale:
      adapter_name: threescale
      adapter_port: 3333
      adapter_service: threescale-istio-adapter
      enabled: true
  version: default
```

I can see that reconciled ConfigMap has:

```
[lponce@newrecopolis k-charted]$ kubectl get configmaps/kiali -n istio-system -o yaml
apiVersion: v1
data:
  config.yaml: |
    additional_display_details:
    - annotation: kiali.io/api-spec
      icon_annotation: kiali.io/api-type
      title: API Documentation
    api:
      namespaces:
        exclude:
        - istio-operator
        - kube.*
        - openshift.*
        - ibm.*
        - kiali-operator
    auth:
      ldap:
        ldap_base: ''
        ldap_bind_dn: ''
        ldap_group_filter: (cn=%s)
        ldap_host: ''
        ldap_insecure_skip_verify: false
        ldap_mail_id_key: mail
        ldap_member_of_key: memberOf
        ldap_port: 0
        ldap_role_filter: ''
        ldap_search_filter: (&(name={USERID}))
        ldap_use_ssl: false
        ldap_user_filter: (cn=%s)
        ldap_user_id_key: cn
      strategy: login
    deployment:
      accessible_namespaces:
      - '**'
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      image_name: localhost:5000/kiali/kiali
      image_pull_policy: Always
      image_pull_secrets: []
      image_version: dev
      ingress_enabled: true
      namespace: istio-system
      node_selector: {}
      pod_annotations: {}
      priority_class_name: ''
      replicas: 1
      resources: {}
      secret_name: kiali
      service_annotations: {}
      service_type: ClusterIP
      tolerations: []
      verbose_mode: 3
      version_label: dev
      view_only_mode: false
    extensions:
      iter8:
        enabled: false
      iter_8:
        enabled: true
      threescale:
        adapter_name: threescale
        adapter_port: 3333
        adapter_service: threescale-istio-adapter
        enabled: true
```

Note the "iter_8" format which I don't know where it comes from.

In the operator all config looks correct, perhaps is something from ansible script ?

@hhovsepy did you see that in your tests, too ?

**Comment by jmazzitelli** [comment]
I suspect your Kiali CR is incorrectly configured to use "iter_8" - the Kiali CR spec fields will go into the ConfigMap, so if you used "iter_8" by mistake, you will see that in the ConfigMap. Then the operator will put the default value of the correct setting "iter8" in the ConfigMap as well. We do not have [CRD Schemas](https://github.com/kiali/kiali/pull/1920) in place to detect this yet.

**Comment by jmazzitelli** [comment]
Note that the string "iter_8" is no where to be found in the Kiali Operator source repo - so we know it isn't anywhere in the ansible scripts: https://github.com/kiali/kiali-operator/search?q=iter_8&unscoped_q=iter_8

**Comment by lucasponce** [comment]
@jmazzitelli that's why I opened the issue :-).
I modifed the operator using kubectl edit and it appeared in the configmap :-).

In the operator was typed correctly, so, no sure how it could be changed.

**Comment by jmazzitelli** [comment]
> I modifed the operator using kubectl edit and it appeared in the configmap :-).

You modified the operator? How did you modify the operator via kubectl?

**Comment by jmazzitelli** [comment]
Looking at master branch of operator, I see no `iter_8` anywhere in templates, or defaults, or tasks or anywhere:

```
$ grep -R iter_8 *
```

Returns nothing. But `iter8` returns:

```
$ grep -R iter8 *
deploy/kiali/kiali_cr.yaml:# Additional documentation https://iter8.tools/
deploy/kiali/kiali_cr.yaml:#    iter8:
deploy/kiali/kiali_cr.yaml:# Flag to indicate if iter8 extension is enabled in Kiali
deploy/role.yaml:- apiGroups: ["iter8.tools"]
manifests/kiali-community/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml:        - apiGroups: ["iter8.tools"]
manifests/kiali-upstream/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml:        - apiGroups: ["iter8.tools"]
roles/default/kiali-deploy/defaults/main.yml:    iter8:
roles/default/kiali-deploy/templates/openshift/role.yaml:- apiGroups: ["iter8.tools"]
roles/default/kiali-deploy/templates/openshift/role-viewer.yaml:- apiGroups: ["iter8.tools"]
roles/default/kiali-deploy/templates/kubernetes/role.yaml:- apiGroups: ["iter8.tools"]
roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml:- apiGroups: ["iter8.tools"]
```

**Comment by jmazzitelli** [comment]
I think the issue is related to https://github.com/operator-framework/operator-sdk/issues/1770#issuecomment-621235683

The fix is to rename this setting to "iter_8" since all settings in Kiali CR are to be snake_case (see that issue above for the reason why) and if iter8 is considered camelCase now, that will causes breakages like we see here.

**Comment by lucasponce** [comment]
Before.
Kiali CR:
```
spec:
  auth:
    strategy: login
  deployment:
    accessible_namespaces:
   - '**'
    image_name: localhost:5000/kiali/kiali
    image_pull_policy: Always
    image_version: dev
    namespace: istio-system
    service_type: ClusterIP
    verbose_mode: 3
  version: default
```
Kiali ConfigMap:
```
    extensions:
      iter8:
        enabled: false
      threescale:
        adapter_name: threescale
        adapter_port: '3333'
        adapter_service: threescale-istio-adapter
        enabled: false
```

After.
Kiali CR:
```
spec:
  auth:
    strategy: login
  deployment:
    accessible_namespaces:
   - '**'
    image_name: localhost:5000/kiali/kiali
    image_pull_policy: Always
    image_version: dev
    namespace: istio-system
    service_type: ClusterIP
    verbose_mode: 3
  extensions:
    iter8:
      enabled: true
  version: default
```

Kiali ConfigMap:
```
    extensions:
      iter8:
        enabled: false
      iter_8:
        enabled: true
      threescale:
        adapter_name: threescale
        adapter_port: '3333'
        adapter_service: threescale-istio-adapter
        enabled: false
```
