### ISSUE TITLE
Do not share same auth config for second prometheus configured

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2740]
Today, configurations for prometheus `url` and `custom_metrics_url` share the same `auth` options, which prevents to have specific authentication for custom dashboards.

We currently have this:

```yaml
    prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      custom_metrics_url: ""
      url: ""
```

We should rather have something like this:

```yaml
    prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      url: ""
    custom_prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      url: ""
```

The bad part is that it's going to be a breaking change in config for custom prom url.
