### ISSUE TITLE
RBAC error "deployments.apps is forbidden" when kiali not installed in istio-system

### ISSUE THREAD

**Issue by yogeek** [kiali/kiali#2756]
**Describe the bug**

I deployed kiali-operator in `kiali-operator` namespace and a kiali instance with the following CR : 
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "3"
spec:
  # Leave the following line ! otherwise, the operator installs an old version by default...
  version: "default"
  auth:
    strategy: "anonymous"
  identity:
    cert_file: ""
    private_key_file: ""
  deployment:
    namespace: kiali-operator
    view_only_mode: true
    ingress_enabled: false
    accessible_namespaces:
    - kiali-operator
    - microdemo
  external_services:
    grafana:
      auth:
        password: "admin"
        type: basic
        use_kiali_token: false
        username: "admin"
      enabled: true
      in_cluster_url: http://grafana-service.monitoring.svc:3000
      url: http://grafana.${K8S_DOMAIN}
    prometheus:
      custom_metrics_url: http://prometheus-k8s.monitoring.svc:9090
      url: http://prometheus-k8s.monitoring.svc:9090
    tracing:
      auth:
        password: "kiali"
        type: basic
        username: "kiali"
      enabled: true
      in_cluster_url: http://jaeger-query.observability.svc:16686
      url: http://jaeger.${K8S_DOMAIN}
  installation_tag: "Kiali operated"
  istio_namespace: istio-system
```

where microdemo is a namespace in which I previously deployed this [demo application](https://github.com/GoogleCloudPlatform/microservices-demo)

As a result, I have this error displayed the UI notification :
```
Error fetching Istio deployment status.
deployments.apps is forbidden: User "system:serviceaccount:kiali-operator:kiali-service-account" cannot list resource "deployments" in API group "apps" in the namespace "istio-system"
```

If I add `istio-system` in the `accessible_namespaces` list, I do not have this error anymore.
But if I do that, I see `istio-system` displayed in the UI as an app and I'd rather not to as I prefer to only see my applications.

In the documentation, it is always implied that kiali is deployed in the default istio namespace (istio-system) and this case is not clear to me.

- Do we have to explicitely add `istio-system` in the `accessible_namespaces` list even if it is already specified in the `istio_namespace: istio-system` field ? 

**Versions used**
Kiali: v1.18.0
Istio: 1.5.2
Kubernetes flavour and version: kubeadm on AWS EC2, version 1.16.6

**Kiali startup logs**
```
E0509 23:49:20.647080       1 errors.go:21] deployments.apps is forbidden: User "system:serviceaccount:kiali-operator:kiali-service-account" cannot list resource "deployments" in API group "apps" in the namespace "istio-system"
W0509 23:49:20.662732       1 istio_validations.go:585] GetMeshPolicies validation failed due to insufficient permissions (probably Kiali doesn't have cluster permissions). Error: meshpolicies.authentication.istio.io is forbidden: User "system:serviceaccount:kiali-operator:kiali-service-account" cannot list resource "meshpolicies" in API group "authentication.istio.io" at the cluster scope
I0509 23:49:20.662898       1 cache.go:161] Waiting for Kiali cache for [namespace: microdemo] to sync
I0509 23:49:20.674013       1 versions.go:363] IstioSupportsCanonical: true
W0509 23:49:20.676296       1 kubernetes_service.go:377] IsMixerDisabled: Cannot retrieve Istio ConfigMap.
I0509 23:49:20.763035       1 cache.go:174] Kiali cache for [namespace: microdemo] started
E0509 23:49:35.655981       1 errors.go:21] deployments.apps is forbidden: User "system:serviceaccount:kiali-operator:kiali-service-account" cannot list resource "deployments" in API group "apps" in the namespace "istio-system"
E0509 23:49:50.651600       1 errors.go:21] deployments.apps is forbidden: User "system:serviceaccount:kiali-operator:kiali-service-account" cannot list resource "deployments" in API group "apps" in the namespace "istio-system"

```

**Comment by jmazzitelli** [comment]
Kiali needs to have the control plane in accessible_namespaces - it needs access to it. In fact, I'm surprised the Kiali ConfigMap doesn't have it in there - its supposed to be (the operator should add it if its missing in the Kiali CR - look in your Kiali ConfigMap - what is the accessible_namespaces value?)

Note also, you shouldn't have kiali-operator in accessible_namespaces - kiali has no need to access the namespace where its operator is.

If you want to hide istio-system from the drop down namespace list, add it to the excluded_namespaces setting:

https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/kiali/kiali_cr.yaml#L95-L121

I flipped the label to this issue as "question" as it isn't clear that this is a bug. It seems like its working as expected.

**Comment by jmazzitelli** [comment]
I'm investigating further - I'm wondering why that error happened because whether you explicitly specify "istio-system" in accessible_namespaces or not, the operator is supposed to inject it in there for you automatically (because it is required).

**Comment by jmazzitelli** [comment]
@yogeek Because you have "view_only_mode: true" in your Kiali CR, that should be creating roles called "kiali-viewer" in all the accessible_namespaces (including istio-system, even if you didn't specify it explicitly). Can you tell me if you see that? See:

```
$ kubectl get roles kiali-viewer -n istio-system
NAME           AGE
kiali-viewer   115s
```

**Comment by jmazzitelli** [comment]
Oh, I think I see the problem:

```
deployment:
    namespace: kiali-operator
```

That is incorrect. You don't want to install Kiali in the Kiali Operator's namespace. If you want Kiali in a different namespace than the control plane itself (istio-system) then you most likely will need to perform some additional things in order for Kiali to see the control plane services. It is highly recommended Kiali is deployed with the rest of the control plane components inside istio-system. 

Is there a reason you want Kiali installed in the Kiali Operator namespace and not istio-system? If this was simply a mistake, I would remove this "deployment.namespace" setting, let it fallback to the default, which is the control plane namespace.

**Comment by jmazzitelli** [comment]
OK, I'm flipping this back to "bug" because I do see a problem.

The way it is supposed to work is Kiali is supposed to have access to the control plane namespace. But if you deploy Kiali in some OTHER namespace, the operator is putting that namespace in accessible_namespaces when it should be putting in the control plane namespace.

So if you install Kiali in namespace "foo" (and Istio's control namespace is "istio-system") then the accessible_namespace should get "istio-system" injected in it for you - but instead the operator is putting "foo" there (it is assuming erroneously that where Kiali is installed is always the control plane namespace, but that is not always the case).

I'm still not sure what other problems might arise if you do this, but that is the thinking of how it should work.

I'm going to fix that.

Note that this doesn't answer your original question - but I answered that earlier - use the excluded_namespaces setting to do what you want.

**Comment by jmazzitelli** [comment]
This should fix the issue: https://github.com/kiali/kiali-operator/pull/34

With this fix, if you install Kiali in a namespace other than the control plane namespace (in other words, if Kiali CR's `spec.deployment.namespace` is different than `istio_namespace`) then the operator will ensure it puts the control plane namespace in the accessible_namespaces list so you do not have to. This is required because Kiali needs access to things in the control plane itself.

**Comment by jmazzitelli** [comment]
@yogeek To explicitly answer your questions:

> But if I do that, I see istio-system displayed in the UI as an app and I'd rather not to as I prefer to only see my applications.

Use the api.excluded_namespaces in the Kiali CR - add whatever namespaces you do not want to see. Note - if you set your own value here, be aware that the defaults are overwritten - you may want to add the default regexs as well because I assume you also do not want to see all the kube* namespaces as well. See: https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/kiali/kiali_cr.yaml#L95-L121

So you can have something like this in your Kiali CR:

```
api:
  namespaces:
    exclude:
    - "istio-system"
    - "istio-operator"
    - "kube.*"
    - "openshift.*"
    - "ibm.*"
    - "kiali-operator"
```

> In the documentation, it is always implied that kiali is deployed in the default istio namespace (istio-system) 

That is the default behavior. But you can override this behavior by setting "spec.deployment.namespace" and "spec.istio_namespace" in your Kiali CR (the former is where you want Kiali installed; the latter is where your control plane namespace is - typically that is "istio-system").

> Do we have to explicitely add istio-system in the accessible_namespaces list even if it is already specified in the istio_namespace: istio-system field ?

No, you should not have to, but there is a bug ([that I just fixed](https://github.com/kiali/kiali-operator/pull/34)) that did not do this if Kiali was installed in a namespace that was different than the control plane namespace (istio-system). So, in your case, if you really want to install Kiali in another namespace, then today you have to explicitly put "istio-system" in accessible_namespaces. This bug fix should be merged this week and should make it in the 1.18.1 release scheduled for this Friday.

That said, I don't think you really want to install Kiali in a different namespace. I think if you use the api.excluded_namespace setting, then it will do what you want and you can go back to installing Kiali in the control plane namespace of istio-system with the rest of the istio components.
