### ISSUE TITLE
Deleted k8s services are persisted within the Graph UI

### ISSUE THREAD

**Issue by robert-blackman** [kiali/kiali#2783]
**Describe the bug**
When a service is deleted from kubernetes, it still remains within the Graph UI. We are running  kiali across multiple environments and are seeing this behaviour in each of them. This behaviour was observed only once traffic was generated for the service.

Service doesn't exist
![kiali_no-svc](https://user-images.githubusercontent.com/57333677/81878202-b0c73880-95ca-11ea-9b5c-4992d0d40b6f.png)

![kiali_service_list](https://user-images.githubusercontent.com/57333677/81877194-cbe47900-95c7-11ea-97a9-34fd4496a6c3.png)

Service still appears in UI (_**Indefinitely**_)
![kiali_phantom_service](https://user-images.githubusercontent.com/57333677/81876987-511b5e00-95c7-11ea-947f-59423983b815.png)

**Versions used**
Kiali: 1.18.0-edge
Istio: 1.5.1
Kubernetes flavour and version: AWS EKS 1.15

**Additional Info**
Mutual TLS Enabled
Automatic Sidecar Injection Enabled
<details open>
<summary>DEBUG</summary>

```
{
  "backendConfigs": {
    "authenticationConfig": {
      "strategy": "login"
    },
    "computedServerConfig": {
      "extensions": {
        "threescale": {
          "enabled": false
        },
        "iter8": {
          "enabled": false
        }
      },
      "istioStatusEnabled": true,
      "istioIdentityDomain": "svc.cluster.local",
      "istioNamespace": "istio-system",
      "istioComponentNamespaces": {
        "grafana": "istio-system",
        "pilot": "istio-system",
        "prometheus": "istio-system",
        "tracing": "istio-system"
      },
      "istioLabels": {
        "appLabelName": "app",
        "versionLabelName": "version"
      },
      "prometheus": {
        "globalScrapeInterval": 15,
        "storageTsdbRetention": 21600
      },
      "durations": {
        "60": "1m",
        "300": "5m",
        "600": "10m",
        "1800": "30m",
        "3600": "1h",
        "10800": "3h",
        "21600": "6h"
      }
    }
  },
  "currentURL": "https://<REMOVED>/kiali/console/graph/namespaces/?edges=noEdgeLabels&graphType=versionedApp&namespaces=kiali-test&unusedNodes=false&injectServiceNodes=true&duration=60&refresh=15000&layout=dagre",
  "reduxState": {
    "authentication": {
      "status": 1,
      "session": {
        "username": null,
        "token": null,
        "expiresOn": "Thu, 14 May 2020 23:16:42 +0000"
      },
      "message": ""
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true,
      "lastRefreshAt": 1589415253920
    },
    "graph": {
      "layout": {
        "name": "dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "summaryData": {
        "summaryType": "graph",
        "summaryTarget": null
      },
      "toolbarState": {
        "compressOnHide": true,
        "edgeLabelMode": "noEdgeLabels",
        "findValue": "",
        "graphType": "versionedApp",
        "hideValue": "",
        "showCircuitBreakers": true,
        "showFindHelp": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showNodeLabels": true,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": true,
        "showUnusedNodes": false,
        "showVirtualServices": true
      },
      "updateTime": 1589415258651
    },
    "messageCenter": {
      "nextId": 0,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": true,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "kiali-test"
        }
      ],
      "isFetching": false,
      "items": [
        {
          "name": "default",
          "labels": null
        },
        {
          "name": "istio-system",
          "labels": {
            "istio-injection": "disabled",
            "istio-operator-managed": "Reconcile",
            "operator.istio.io/component": "Base",
            "operator.istio.io/managed": "Reconcile",
            "operator.istio.io/version": "1.5.1"
          }
        },
        {
          "name": "kiali-test",
          "labels": {
            "istio-injection": "enabled"
          }
        }
      ],
      "lastUpdated": "2020-05-13T23:37:13.954Z",
      "filter": ""
    },
    "statusState": {
      "status": {
        "Kiali console version": "1.18.0-edge",
        "Kiali container version": "latest",
        "Kiali core commit hash": "263acf0bf4e953424bddf72676a26c2805797c8a",
        "Kiali core version": "latest",
        "Kiali state": "running"
      },
      "components": [
        {
          "name": "Istio",
          "version": "1.5.1"
        },
        {
          "name": "Prometheus",
          "version": "2.15.1"
        },
        {
          "name": "Kubernetes",
          "version": "v1.15.11-eks-af3caf"
        },
        {
          "name": "Grafana"
        },
        {
          "name": "Jaeger"
        }
      ],
      "warningMessages": []
    },
    "userSettings": {
      "duration": 60,
      "interface": {
        "navCollapse": false
      },
      "refreshInterval": 15000,
      "replayActive": false,
      "replayQueryTime": 0,
      "replayWindow": {
        "interval": 0,
        "startTime": 0
      }
    },
    "jaegerState": {
      "enabled": true,
      "integration": true,
      "url": "",
      "namespaceSelector": true,
      "whiteListIstioSystem": [
        "jaeger-query",
        "istio-ingressgateway"
      ]
    },
    "meshTLSStatus": {
      "status": "MTLS_ENABLED"
    },
    "istioStatus": [
      {
        "name": "istio-egressgateway",
        "status": "NotFound",
        "is_core": false
      },
      {
        "name": "grafana",
        "status": "NotFound",
        "is_core": false
      },
      {
        "name": "istio-tracing",
        "status": "NotFound",
        "is_core": false
      }
    ],
    "tourState": {},
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}
```
</details>

**To Reproduce**

1. Create a K8s Service, Deployment and Istio VirtualService and DestinationRule

<details open>
<summary>Sample Manifests</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-test
  labels:
    app: kiali-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-test
  template:
    metadata:
      namespace: kiali-test
      labels:
        app: kiali-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kiali-test
spec:
  selector:
    app: kiali-test
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-test
spec:
  hosts:
  - kiali-test.<REMOVED>
  gateways:
  - default/<REMOVED>
  http:
  - name: kiali-test-route
    route:
    - destination:
        host: kiali-test
      subset: stable
        
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kiali-test
spec:
  host: kiali-test
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        app: kiali-test
      name: stable
```
</details>

2. Generate some traffic
3. Destroy created resources 
4. Click on `Graph`
5. See error

**Expected behavior**
The service should not be visible in the UI after it has been deleted.
