### ISSUE TITLE
Provided prometheus url being ignored

### ISSUE THREAD

**Issue by bjoernw** [kiali/kiali#2791]
**Describe the bug**
It appears that Kiali is still trying to reach the istio-managed prometheus instance even though i have set external_services.prometheus.url to my the instance in my monitoring namespace.

**Versions used**
Kiali UI
1.15.1 (1440a7722f9b4699caaee7b64d32db0f1beb5386)
Kiali Server
v1.15.2 (718aedca76e612e2f95498d022fab1e116613792)
Kiali Container
v1.15.2
Components
Istio
1.5.2
Kubernetes
v1.14.9-eks-502bfb

Configmap:
```
Name:         kiali
Namespace:    istio-system
Labels:       app=kiali
              operator.istio.io/component=AddonComponents
              operator.istio.io/managed=Reconcile
              operator.istio.io/version=1.5.2
              release=istio
Annotations:  
Data
====
config.yaml:
----
istio_component_namespaces:
  grafana: istio-system
  tracing: istio-system
  pilot: istio-system
  prometheus: istio-system
istio_namespace: istio-system
auth:
  strategy: anonymous
deployment:
  accessible_namespaces: ['**']
login_token:
  signing_key: "redacted"
server:
  port: 20001
  web_root: /kiali
external_services:
  istio:
    url_service_version: http://istio-pilot.istio-system:8080/version
  tracing:
    url:
    in_cluster_url: http://tracing/jaeger
  grafana:
    url:
    in_cluster_url: http://grafana:3000
  prometheus:
    url: http://prometheus-prometheus-oper-prometheus.monitoring.svc.cluster.local:9090

Events:  <none>
```

When navigating around kiali to view inbound/outbound metrics I see the following in kiali logs.
kiali logs:
```
E0514 19:58:26.142446       1 dashboards.go:286] runtimes discovery failed, cannot load metrics for labels: {namespace="cert-manager",app="cert-manager"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-05-14T19%3A58%3A26.035633363Z&match%5B%5D=%7Bnamespace%3D%22cert-manager%22%2Capp%3D%22cert-manager%22%7D&start=2020-05-
 14T18%3A58%3A26.035633363Z": dial tcp: lookup prometheus.istio-system on 172.20.0.10:53: no such host
```

**Expected behavior**
Kiali should be using the prometheus url I provided in the config.
