### ISSUE TITLE
Namespace TLS status: enabled/disabled status shouldn't be used with Permissive PeerAuth

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2819]
When I have a PeerAuthentication in permissive mode, the TLS status of the namespace shouldn't be either enabled or disabled.

Enabled => all the traffic in the mesh/ns uses mTLS.
Disabled => all the traffic in the mesh/ns doesn't use mTLS.

Using permissive mode, means that there is the possibility of both mtls/plain traffic flow.

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "details-disable-mtls"
  namespace: "bookinfo"
spec:
  host: details
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "bookinfo"
spec:
  mtls:
    mode: PERMISSIVE
```

Wrong behavior:
![Screenshot of Kiali Console (86)](https://user-images.githubusercontent.com/613814/82655422-7260f780-9c22-11ea-952c-cb9b62e343f6.png)

Good behavior:
The overview page, should show a hollow lock instead (both in mesh-wide tls and without).
