### ISSUE TITLE
Ability to reuse a handler when linking 3scale to workload

### ISSUE THREAD

**Issue by PhilipGough** [kiali/kiali#2860]
**Describe the solution you'd like**
cc @lucasponce: 
Currently it seems to be that when selecting a workload to be integrated with 3scale through the wizard, each integration creates a separate handler, instance and rule.

Ideally however, we would create only a single handler per account and provide the service ID directly by editing the deployment, assuming there are no issues in doing so on the Kiali side

Detailed description can be read here https://github.com/3scale/3scale-istio-adapter#routing-service-traffic-through-the-adapter

**Comment by lucasponce** [comment]
Hi @PhilipGough,

I think in Kiali (master branch) we have refactored this to address some of the behaviour you comment.

Now, when 3scale extension is present, there is a new top level menu in Kiali:

![image](https://user-images.githubusercontent.com/1662329/83727816-f74a0900-a645-11ea-833b-653750a284f6.png)

On the 3scale main page, there is a list of existing 3scale handlers:

![image](https://user-images.githubusercontent.com/1662329/83727913-15176e00-a646-11ea-879e-e62f58ae67c8.png)

As "3scale handler" is more a logical entity (in implementation is a rule/instance of mixer that can be changed in the future), Kiali manages it from "logical" perspective, so, that's reason those handlers are not namespaced on this page as they should live in the control-plane namespace.

The form to create a handler is placed here:

![image](https://user-images.githubusercontent.com/1662329/83728051-4859fd00-a646-11ea-816f-826d2c6e2dd5.png)

In this way, handlers are in practice shared between all services, we have eliminated the option to create a handler from the wizard but selecting an existing one (creation of handlers will happen from the 3scale extension section).

![image](https://user-images.githubusercontent.com/1662329/83728172-74757e00-a646-11ea-8e79-741323391182.png)

All of this is consolidated in master.

This refactoring was motivated to: a) address this re-use usecase, b) also to shape extensions in a more generic way, allowing other features to extend Kiali in a more organized way.

Please, if you have possibility to test this, we can try to see if the current work is valid or if we would need to change some aspect.

**Comment by lucasponce** [comment]
Probably, we can use this issue to study how to change the rule I think.
Today, every handler is linked with a single Rule with a explicit service condition.

**Comment by PhilipGough** [comment]
@lucasponce - thanks for the explanation

This all looks like valid changes, it still does tie the service ID directly to the handler though as opposed to coming from the target services deployment via a label as I linked above.

Saying that this way will still work, we haven't removed the option for a direct one-to-one linking but it does stop us using the handler to essentially hold credentials for many services.

You are probably aware also about the upcoming changes and deprecation out out of process adapters in favour of WASM, so things will be different going forward regardless and we don't yet fully know how config will be provided.

**Comment by lucasponce** [comment]
> Saying that this way will still work, we haven't removed the option for a direct one-to-one linking but it does stop us using the handler to essentially hold credentials for many services.

We can work to adapt this on master.
If you point me to a couple of examples of how Rules/Handlers/Instances should be created I can apply the changes.

I'd need some help for testing this as I don't have a 3scale instance (I had one but it was managed by Vanessa some time ago).

**Comment by PhilipGough** [comment]
Thanks Lucas, the link in the original post should answer a lot of those questions I believe https://github.com/3scale/3scale-istio-adapter#routing-service-traffic-through-the-adapter

The only issue I might see is that to do this Kiali would need to edit a deployment in another namespace which could prove problematic. If this is the case then this is a non-runner obviously and we can stick with the 1-1 mapping.

I'd certainly be happy to help test this out and answer any questions you have. If you have any questions regarding the config or if the doc above isn't clear then feel free to shout.

**Comment by lucasponce** [comment]
> The only issue I might see is that to do this Kiali would need to edit a deployment in another namespace which could prove problematic.

In a separate discussion we were also planning to enable actions per workload level, so, perhaps then we can move the service action at workload level an allow to modify this.

I need to review the details of the links you posted but probably it can be doable.

I'll be thinking on this.

**Comment by PhilipGough** [comment]
Great thanks Lucas, and like I said feel free to ping me if you need any help in testing or have any questions.

**Comment by lucasponce** [comment]
Hi @PhilipGough,

Perhaps you can help me to validate how I'm reading the threscale-adapter-config.yaml:

https://github.com/3scale/3scale-istio-adapter/blob/master/istio/threescale-adapter-config.yaml

So, in this proposal, we would define a single handler and a single rule linked with that handler.

The handler is linked with a single 3scale service id.

So, we may want to link several Kubernetes Services with a single handler, then the proposal is to add the label `destination.labels["service-mesh.3scale.net"] == "true"` to the Pod.

Or do you want that Handler can have no 3scale service id and that is read from the labels too ?

I know that user may edit those files but from high level Kiali use case I'd like to choose a single scenario and try to implement it.

**Comment by PhilipGough** [comment]
Hey @lucasponce - so in an ideal scenario, the service ID will come from the Pod also. In that way, one single 3scale account, represented in Istio as the `Handler`, just holds the accounts credentials and can be used to manage multiple Kubernetes Services.

That configuration you linked to is actually outdated. I need to fix that and will do so right away. Better to look at the samples for the integration tests: https://github.com/3scale/3scale-istio-adapter/tree/master/testdata

There you will see the `Rule` now has a [new label](https://github.com/3scale/3scale-istio-adapter/blob/master/testdata/threescale-adapter-config.yaml#L35) - `destination.labels["service-mesh.3scale.net/credentials"] == "threescale"`. This allow us to associate a Kubernetes Service with a Handler, via a matching label.

The second thing you might notice is [a new label](https://github.com/3scale/3scale-istio-adapter/blob/master/testdata/threescale-adapter-config.yaml#L13) on the `Instance`, `destination.labels["service-mesh.3scale.net/service-id"]`. This allow us to deliver the service ID to the adapter via a label.

This is the way we currently generate config via our own tool and also recommend setup to end users since they are likely to be managing many, many services via a single account and can reuse the same configuration for all by just adding two labels to the Pod they want to manage.

I hope this makes sense, and apologies if the outdated samples caused confusion, the documentation is up to date so I need to align these.

Any questions just shoot. Thanks


So as you suggested `destination.labels["service-mesh.3scale.net"] == "true"` table is used to match against a handler

**Comment by lucasponce** [comment]
Hi @PhilipGough,

Thanks, now I'm thinking in the Kiali wording and how we can provide this experience to the user.
Let me see what do you think:

- Instead to refer 3scale Handler in Kiali, we can rename that concept to 3scale Account.
- From user perspective, an account is defined with two parameters: access_token and system_url.
- From implementation perspective, a 3scale account is mapped to a pair of mixer handler + rule (I wonder if we need a single instance for all handlers or it needs an instance per handler+instance+rule).
- I don't know if user wants to mark specific workloads or it make sense to keep the link to 3scale from the Service instead Workload. I wonder if it makes sense to link the reviews-v1 and reviews-v2 but not reviews-v3 workload, instead to link/unlink the whole review Services (and let Kiali to identity the workloads and label them).

What do you think ?

**Comment by lucasponce** [comment]
@PhilipGough 

Or I'm also thinking to allow user to deal directly with Handler/Rules and just allow to create them in a simplified way from Kiali.
In other words, we would remove the special "3scale config" section and all handlers would be seen from regular Istio Config section.

Kiali may provide a simplified "3scale form" to create a new handler/rule pair, but once created they would modify them directly from the yaml editor.

Also, when 3scale detected, we can enable an action at workload level to "link" with 3scale providing the labels.

This needs to be detailed better, but perhaps on this way we can simplify this config without missing any feature.

**Comment by PhilipGough** [comment]
Hey @lucasponce 

I think we can totally agree on your first two points. The handler handler can be treated like an account and should remain static. It can standalone and has no reference itself to any instance or rule.

Regarding the third point, I think that should be left to the user to decide what fits. They may want multiple instance to support different authentication methods, OIDC and App key for example would each require a separate instance but could share the same handler.

With regards to the last point, I think that we should continue to use the workload since with API management, this could in fact be a requirement to manage different versions of the application differently.

Myself and @unleashed spoke about it this morning and this is how we would imagine the flow, ideally:

1. Create or select an account -> handler
2. Create or select an instance -> auth parameters config
3. Create or select a rule linking both (and maybe associate that rule as default for the handler)
4. Whenever a new workload is to be configured with the handler, if you have the concept of default rule, load it and load the referred instance and offer those as default but always let the user choose to create new rules and new instances

**Comment by lucasponce** [comment]
@PhilipGough could you point me to some examples of different instances on same/different rules ?
And also what typically would be the flow from the user to adjust the workload ?

What is not yet fully clear to me are the potential options of labelling the workload to connect/link with the 3scale rule.

I mean, I'm trying to abstract that to the user in a consistent way (just to not create a generic operation of labelling) perhaps a couple of examples could help me to figure out this and start applying these changes.

**Comment by PhilipGough** [comment]
@lucasponce sure, let's walk through some examples.

Say we have a single handler defined like this which represents a 3scale account:

```yaml
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  creationTimestamp: null
  name: threescale
  namespace: istio-system
spec:
  adapter: threescale
  connection:
    address: '[::]:3333'
  params:
    access_token: secret-token
    system_url: https://3scale.net
```

Now say we want to manage two applications in the mesh and tag them for API management, we will use `httpbin` and `bookinfo`  to keep it simple.

We might create a `Rule` and an `Instance` as such

```yaml
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  creationTimestamp: null
  name: threescale
  namespace: istio-system
spec:
  params:
    action:
      method: request.method | "get"
      path: request.url_path
      service: destination.labels["service-mesh.3scale.net/service-id"] | ""
    subject:
      properties:
        app_id: request.query_params["app_id"] | request.headers["app_id"] | ""
        app_key: request.query_params["app_key"] | request.headers["app_key"] | ""
        client_id: request.auth.claims["azp"] | ""
      user: request.query_params["user_key"] | request.headers["user_key"] | ""
  template: threescale-authorization
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  creationTimestamp: null
  name: threescale
  namespace: istio-system
spec:
  actions:
  - handler: threescale.handler.istio-system
    instances:
    - threescale.instance.istio-system
  match: |-
    context.reporter.kind == "inbound" &&
    destination.labels["service-mesh.3scale.net/credentials"] == "threescale"
```

Now of course these two applications running in the cluster have a mapping in 3scale, main them unique. However if both of them require the same configuration, then the only thing that makes them unique in 3scale is the service ID, which as we spoke about, can be delivered via a label so we might update the workload labels as follows:

`httpbin`: 

```yaml
# match on the rule
"service-mesh.3scale.net/credentials" : "threescale" 
# provide a service ID to the adapter
service-mesh.3scale.net/service-id": "123"
```

`bookinfo`: 

```yaml
# match on the rule
"service-mesh.3scale.net/credentials" : "threescale" 
# provide a service ID to the adapter
service-mesh.3scale.net/service-id": "abc"
```

In this case the Virtual Service will determine the destination.

**Comment by lucasponce** [comment]
Thanks @PhilipGough.

Ok, so Kiali would provide following changes:

- From Istio Config: "Create 3scale Handler" form, that would create an Istio Handler asking for access_token and url as a similar as it has today.
- From Istio Config: "Create 3scale Instance/Rule" form, what would create an Istio Instance and Rule, allowing to select an existing handler (for simplicity).
- From Workload Details: "Link with 3scale" action that would ask for list of instance/rule created (less assume that there are pair of these two objects but sharing name for simplicity).

What is not clear to me is if the user should provide `service-mesh.3scale.net/service-id` in a form, or it can assume the backed service of the workload (i.e. if we are in reviews-v3 workload, let's assume reviews, or the same workload name). Or if this service-id is something that needs to be in sync with the 3scale register.

**Comment by PhilipGough** [comment]
That sounds good to me @lucasponce 

I think attaching the service ID via a form makes sense when a user wants to add API management to a workload. We would expect that they would already have created the resources in 3scale (service,API, mapping rules etc) so they will indeed need to know the service ID up front for sure.

**Comment by lucasponce** [comment]
> I think attaching the service ID via a form makes sense when a user wants to add API management to a workload. We would expect that they would already have created the resources in 3scale (service,API, mapping rules etc) so they will indeed need to know the service ID up front for sure.

Makes sense.

Thanks for the feedback @PhilipGough. 

I think I have all needed infor the changes, I'll put you as a reviewer as well for these changes in Kiali.
From Kiali we can test that configuration is created but probably we can't test the complete end-to-end flow with the 3scale system.

**Comment by PhilipGough** [comment]
Great, thanks @lucasponce - sure, add me and ill be happy to test out the integration also

**Comment by lucasponce** [comment]
@PhilipGough 

Working in the implementation I was wondering is as from user experience, if it's better to allow him/her to perform the creation of handler/instance/rule in a single step instead of two.

After those assets are created, user can go to the Istio Config to edit them, but allow them to create in a single step:

```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  creationTimestamp: null
  name: my-name
  namespace: istio-system
spec:
  adapter: threescale
  connection:
    address: dns:///threescale-istio-adapter:3333
  params:
    access_token: my-token
    system_url: https://replaceme-admin.3scale.net:443
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  creationTimestamp: null
  name: my-name
  namespace: istio-system
spec:
  params:
    action:
      method: request.method | "get"
      path: request.url_path
      service: destination.labels["service-mesh.3scale.net/service-id"] | ""
    subject:
      properties:
        app_id: request.query_params["app_id"] | request.headers["app-id"] | ""
        app_key: request.query_params["app_key"] | request.headers["app-key"] | ""
        client_id: request.auth.claims["azp"] | ""
      user: request.query_params["user_key"] | request.headers["x-user-key"] | ""
  template: threescale-authorization
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  creationTimestamp: null
  name: my-name
  namespace: istio-system
spec:
  actions:
  - handler: my-name.handler.istio-system
    instances:
    - my-name.instance.istio-system
  match: |-
    context.reporter.kind == "inbound" &&
    destination.labels["service-mesh.3scale.net/credentials"] == "my-name" &&
    destination.labels["service-mesh.3scale.net/authentication-method"] == ""
---
```

as similar as the cmd tool:

```
export NS="istio-system" URL="https://replaceme-admin.3scale.net:443" NAME="my-name" TOKEN="my-token"
kubectl exec -n ${NS} $(kubectl get po -n ${NS} -o jsonpath='{.items[?(@.metadata.labels.app=="3scale-istio-adapter")].metadata.name}') \
-it -- ./3scale-config-gen \
```

Perhaps it can improve the experience from the user and let them to edit the particular instances in case they want to perform more complicated scenarios.

What do you think ?

I've also seen that examples used take that scenario as the more common one.

**Comment by PhilipGough** [comment]
@lucasponce would they then loose the ability to create a new rule/instance pair and link it to an existing handler?

**Comment by lucasponce** [comment]
> @lucasponce would they then loose the ability to create a new rule/instance pair and link it to an existing handler?

Perhaps, I'm missing something, could you provide me an example of a single handler and two different instance1/rule1 and instance2/rule2 pairs ?

I understand that the concept of "3scale credentials" is used in the instance/rule pair, and probably user may want to change the instance to provide different parameters to apply different strategies in the same scenario, isn't it ?

But if the user applies the default one:

```
  params:
    action:
      method: request.method | "get"
      path: request.url_path
      service: destination.labels["service-mesh.3scale.net/service-id"] | ""
    subject:
      properties:
        app_id: request.query_params["app_id"] | request.headers["app-id"] | ""
        app_key: request.query_params["app_key"] | request.headers["app-key"] | ""
        client_id: request.auth.claims["azp"] | ""
      user: request.query_params["user_key"] | request.headers["x-user-key"] | ""
```

Isn't that covering the most of the cases ? When would he/she create a different one ?

**Comment by PhilipGough** [comment]
@lucasponce so they would create a different instance if they wanted to manage the configuration differently. Say for example they wanted to enforce using OIDC, then they would create that instance. Or they may have an API that reads the application from a different query parameter for example, in that case they would need a different instance and a rule to link it. 

I know it is convoluted, but this is the only way we can remain compatible with the configuration that is available to 3scale users in other formats (non service mesh users). The "hybrid pattern" is something we built in the adapter to allow users to get off the grand quickly, and like you pointed to, it covers all of the use cases.

However the concept of a hybrid pattern isn't something that is available on 3scale itself. For each API, a user is locked in to one authentication method or another and must configure those individually. They would need to physically go and change the authentication pattern via the UI to adjust it. Hopefully that gives insight into the problems we faced and why we are trying to support anything outside of the example you pasted above.

**Comment by lucasponce** [comment]
Ok @PhilipGough 

Let me put some screenshots.

When the 3scale config is enabled in Kiali, now user would see a new "Create New 3scale config" from the Istio Config:

![image](https://user-images.githubusercontent.com/1662329/85557689-4b825080-b628-11ea-88f2-be293674b281.png)

The first use case is clear: a 3scale account is mapped into a Istio Handler:

![image](https://user-images.githubusercontent.com/1662329/85557821-6f459680-b628-11ea-8f15-50a3bbd608f2.png)

Now user can also create a 3scale authorization (pair of instance+rule):

![image](https://user-images.githubusercontent.com/1662329/85557908-87b5b100-b628-11ea-8d77-f6d654aa6792.png)

And from this form (it's a WIP mock, not yet implemented):

![image](https://user-images.githubusercontent.com/1662329/85557949-92704600-b628-11ea-8d33-d9ca53ca9e92.png)

User should just choose a handler as an input for this pair of instance+rule, the rest of fileds can be provided automatically from Kiali.

Here is where I probably miss if user should provide at this step any other input, or in case they want to enable OIDC he/she would perform that from the yaml editor.

Once those resources are created, user will see them as proper handlers, instances and rules from the Istio Config:

![image](https://user-images.githubusercontent.com/1662329/85558289-e549fd80-b628-11ea-93e6-5365d22c20ae.png)

And user would be able to perform any personalization but from yaml, the 3scale form would be used just for creation operation.

Then, at workload level, user will have a "Link with 3scale action" where they will select one item from the list of instance+rules pairs and also a text input to provide the service-id.

**Comment by PhilipGough** [comment]
@lucasponce that nails it IMO, great thanks. Any input @unleashed?

@lucasponce I think allowing them to configure via yaml editor is fine. Having the form be the driver for all the inputs is likely confusing rather than an improvement.

**Comment by unleashed** [comment]
I think further down the line we would likely want to introduce a few more options in these forms to minimise the need to edit YAMLs, but this looks about right for a first iteration. Thanks @lucasponce!

**Comment by lucasponce** [comment]
> I think further down the line we would likely want to introduce a few more options in these forms to minimise the need to edit YAMLs, but this looks about right for a first iteration. Thanks @lucasponce!

Feel free to add suggestions/comments, I mean this is intented to be included in the Kiali version that will be included in the next version, so, anything that can reach the feature freeze the better, otherwise perhaps future 3scale integrations would need to address the new architecture.

Also, Kiali only would take care of the configuration side, the whole configuration with the 3scale integration adapter should be dirven by Maistra.

**Comment by unleashed** [comment]
@lucasponce sure!

The main idea I have is adding an option to select the authentication type that 3scale uses (much like the CLI tool option) so they don't need to edit or even see the YAML since there is only a handful to select from and most of the time users will just accept the generated instance CR, and later on perhaps allowing the customisation of the field names to extract the credentials (ie. whether to take them from a specific header, or from a query string parameters, from one of them and the other as fallback, etc).

From a user POV one of the things we don't really place restrictions in to gain flexibility at the cost of complexity is defining the combination of rules and instances. One of the things we do when we generate the default CRs with the CLI tool is adding a condition to the rule on having a check on an empty label named authentication method. This is so users could have specific rules matching the content of that label and linking to instances that extract parameters related to that authentication type.

For example, you could have a rule matching on any authentication type:

```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  creationTimestamp: null
  name: my-account-hybrid
  namespace: istio-system
spec:
  actions:
  - handler: my-account.handler.istio-system
    instances:
    - hybrid-authn.instance.istio-system
  match: |-
    context.reporter.kind == "inbound" &&
    destination.labels["service-mesh.3scale.net/credentials"] == "my-account" &&
    destination.labels["service-mesh.3scale.net/authentication-method"] == ""
```

vs one just for OIDC:

```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  creationTimestamp: null
  name: my-account-oidc
  namespace: istio-system
spec:
  actions:
  - handler: my-account.handler.istio-system
    instances:
    - oidc-authn.instance.istio-system
  match: |-
    context.reporter.kind == "inbound" &&
    destination.labels["service-mesh.3scale.net/credentials"] == "my-account" &&
    destination.labels["service-mesh.3scale.net/authentication-method"] == "oidc"
```

With the benefit being that you can restrict the extracted parameters to just the ones you know you will be using (when compared to a hybrid instance, this might be used when strict security policy requirements are in place, and additionally to gain a tiny bit of performance) plus you could refer to one of a few default instances that remain the same for all accounts in the installation.

I am not sure Kiali would want to go that far (at least at the moment) given the hybrid instance works for all authentication types, but the above might work for a majority of users with no need to ever edit YAMLs.
