### ISSUE TITLE
Istio health masthead: support addon custom installation

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2916]
Found in: https://discuss.istio.io/t/kiali-istio-component-status-masthead/7032

When addons (tracing, grafana and prometheus) are installed in different namespaces than the control plane, the masthead warns that they are no present.

A way to install that is using the following helm chart:
```
addonComponents:
  prometheus:
    enabled: false
  kiali:
    enabled: true
  grafana:
    enabled: false
  tracing:
    enabled: false
```

Secondly, installing both tree components apart.
And then, enabling both Prometheus, Grafana and Tracing in Kiali CR, plus changing the URLs for each component.

This health needs to support this custom installation.

**Versions used**
Kiali: 1.18.2
Istio: 1.6.1
