### ISSUE TITLE
Kiali is not showing traffic for any of the services

### ISSUE THREAD

**Issue by Shashankft9** [kiali/kiali#2950]
**Describe the bug**
I am unable to see any traffic in the Kiali UI, hence no graphs etc. Also, I have had to apply a configmap yaml for kiali after the first deployment through the install config in Istio. Following files will explain better:

My install config: (here `prometheus-k8s` is our instance that we want to use, not the `prometheus.istio-system`.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: false
    telemetry:
      enabled: true
  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
  values:
    kiali:
      prometheusAddr: http://prometheus-k8s.monitoring.svc.cluster.local:9090
  values:
    global:
      tracer:
        zipkin:
          address: istio-jaeger-collector.istio-system:9411
```

Oddly for me applying this doesnt reflect the prometheus url in configmap created, it still points to the `prometheus.istio-system`, so then I go on to manually apply the updated configmap and I restart the kiali pod:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: istio
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: monitoring
      tracing: istio-system
      istiod: istio-system
      prometheus: monitoring
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "gEwUmcJZ1J"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istiod.istio-system:15014/version
      tracing:
        url:
        in_cluster_url: 'http://istio-jaeger-query.istio-system.svc.cluster.local:16686'
      grafana:
        url: http://grafana.monitoring.svc.cluster.local:3000
        in_cluster_url:
      prometheus:
        url: http://prometheus-k8s.monitoring.svc.cluster.local:9090
```

I created a service account that would put the metrics into my prometheus instance as:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: mixer
  name: telemetry
  namespace: istio-system
spec:
  endpoints:
  - port: http-monitoring
  selector:
    # the below should be the labels from kind: Service for the app
    matchLabels:
      app: mixer

```

To observe the traffic, I have deployed both bookinfo app and this: https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#set-up-the-cluster (in foo and bar namespaces only)

and then I curl from inside the `sleep` pod of ns `bar` to `httpbin` pod of ns `foo` as:
`for i in `seq 1 100`; do curl httpbin.foo.svc.cluster.local:8000; done`

I get no traffic at all. 
I am able to trace the traffic in jaeger successfully but nothing turns up in the kiali UI. 

**Expected behavior**
there should be some traffic and graphs on the Kiali UI as mentioned in the documentation.

Istio version: v1.6.3

Please let me know if you would want more config files.

**Comment by Shashankft9** [comment]
attaching some snaps:
![error1](https://user-images.githubusercontent.com/48708039/86138637-58151600-bb0c-11ea-8312-7283abd3ccdd.PNG)
![error2](https://user-images.githubusercontent.com/48708039/86138642-59464300-bb0c-11ea-9598-64c4bcec74a7.PNG)

**Comment by jotak** [comment]
@Shashankft9 if you open up the Prometheus console, or Grafana, do you see some istio metrics or not? (to make sure the problem is with Kiali and not with Prometheus getting the metrics). Note that Jaeger doesn't use Prometheus so you could be able to see traces even when you don't have metrics.

Is there anything suspicious in Kiali logs? (you can copy/paste the logs here)

**Comment by Shashankft9** [comment]
mhm I noticed this in the logs just now: 

```
E0630 14:27:06.686494       1 dashboards.go:307] runtimes discovery failed, cannot load dashboards in namespace bar. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
E0630 14:27:06.699744       1 dashboards.go:288] runtimes discovery failed, cannot load metrics for labels: {namespace="bar",app="httpbin",version="v1"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-06-30T14%3A27%3A06.684980828Z&match%5B%5D=%7Bnamespace%3D%22bar%22%2Capp%3D%22httpbin%22%2Cversion%3D%22v1%22%7D&start=2020-06-30T13%3A27%3A06.684980828Z": dial tcp: lookup prometheus.istio-system on 10.233.0.3:53: no such host
```

odd that it is still trying to contact `prometheus.istio-system`

I'll check metrics on prometheus meanwhile.

**Comment by Shashankft9** [comment]
dump for `kubectl get cm -n istio-system kiali`:

```
apiVersion: v1
data:
  config.yaml: "istio_component_namespaces:\n  grafana: monitoring\n  tracing: istio-system\n
    \ istiod: istio-system\n  prometheus: monitoring\nistio_namespace: istio-system\nauth:\n
    \ strategy: login\ndeployment:\n  accessible_namespaces: ['**']\nlogin_token:\n
    \ signing_key: \"gEwUmcJZ1J\"\nserver:\n  port: 20001\n  web_root: /kiali\nexternal_services:\n
    \ istio:\n    url_service_version: http://istiod.istio-system:15014/version\n
    \ tracing:\n    url: \n    in_cluster_url: 'http://istio-jaeger-query.istio-system.svc.cluster.local:16686'\n
    \ grafana:\n    url: http://grafana.monitoring.svc.cluster.local:3000\n    in_cluster_url:
    \n  prometheus:\n    url: http://prometheus-k8s.monitoring.svc.cluster.local:9090\n"
kind: ConfigMap

```

**Comment by jotak** [comment]
> mhm I noticed this in the logs just now:
> 
> ```
> E0630 14:27:06.686494       1 dashboards.go:307] runtimes discovery failed, cannot load dashboards in namespace bar. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
> E0630 14:27:06.699744       1 dashboards.go:288] runtimes discovery failed, cannot load metrics for labels: {namespace="bar",app="httpbin",version="v1"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-06-30T14%3A27%3A06.684980828Z&match%5B%5D=%7Bnamespace%3D%22bar%22%2Capp%3D%22httpbin%22%2Cversion%3D%22v1%22%7D&start=2020-06-30T13%3A27%3A06.684980828Z": dial tcp: lookup prometheus.istio-system on 10.233.0.3:53: no such host
> ```
> 
> odd that it is still trying to contact `prometheus.istio-system`
> 

You can ignore this one for the time being: it's an alternate config of prometheus URL, in the case you would want to show custom dashboards in Kiali: see https://kiali.io/documentation/latest/runtimes-monitoring/ ; but the main config URL is the one you set up in config map

**Comment by Shashankft9** [comment]
so, I am not seeing the metrics on prometheus dashboard as well, let me fix that and get back to you with the status

**Comment by Shashankft9** [comment]
@jotak can you also please check with the secondary issue here - why the prometheusAddr is not working in the istio config installation? which is why I have to apply the configmap exculsively afterwards.

**Comment by Shashankft9** [comment]
Hey, I see the metrics coming up on the prometheus dashboard now both for jobs: `istio-telemetry` and `istiod`
but the kiali dashboard still shows no traffic. Is there some specific metric that you want me to look out for?

**Comment by Shashankft9** [comment]
I am not able to see these metrics in the `istio-telemetry` job: https://istio.io/latest/docs/concepts/observability/#service-level-metrics and I am guessing kiali would make use of this?

**Comment by jotak** [comment]
Yes, `istio_requests_total` is the main one that is used for graph generation with http traffic. So, you have traffic but those metrics aren't populated? You could check the istio sidecar logs of your pods, also commands like described here to check the mesh status: https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/

**Comment by jotak** [comment]
@jmazzitelli @gbaufake do you know anything about the `prometheusAddr` not being set to Kiali configmap? (as stated in the initial comment above) - is there a known issue in istio operator?

**Comment by Shashankft9** [comment]
@jotak I do have the traffic, I can see it the jaeger UI, but unfortunately the metrics aren't being populated. And this also looks good:
```
istioctl proxy-status
NAME                                                CDS        LDS        EDS        RDS        PILOT                       VERSION
details-v1-7f6df6f54-72xt7.default                  SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
httpbin-654c6cbbb9-25ct5.bar                        SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
httpbin-654c6cbbb9-ls5sq.foo                        SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
istio-ingressgateway-fw5d7.istio-system             SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
istio-ingressgateway-jz4zh.istio-system             SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
istio-ingressgateway-ndkgb.istio-system             SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
productpage-v1-69886c8bcb-p7qj9.default             SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
ratings-v1-6665bbd4db-g7ddx.default                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
redis-cluster-operator-76c5776889-ssn6g.default     SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
reviews-v1-7fd87d96bd-ptwqv.default                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
reviews-v2-55d9bfb6d8-dznp8.default                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
reviews-v3-5776c54c64-rmpzc.default                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
sleep-6bdb595bcb-fgvb2.bar                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
sleep-6bdb595bcb-vh4tj.foo                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-6668c47f97-fmwx8     1.6.3
```

**Comment by Shashankft9** [comment]
Some additional context: I am running ingressgateway as a dameonset instead and I don't have its service running. I don't think this should affect but yes.

**Comment by Shashankft9** [comment]
@jotak everything looks good from the document.  Can you confirm if the installation only requires me to turn on Telemetry component of Istio? are there any addtional steps? Because I am getting confused from here: https://istio.io/latest/docs/setup/getting-started/ this installs the demo profile which has telemetry as disabled but still they go on to show something working on the Kiali UI.

**Comment by jotak** [comment]
Why do you say demo has telemetry disabled? It should be enabled - it's the profile I'm also using everyday for development, and I don't have any additional step to do. I'm going to try 1.6.3 to make sure nothing is broken in that particular version. Can you give me the full install command that you run?

**Comment by Shashankft9** [comment]
I run `istioctl profile dump demo` and this comes up in the `components` section:
```
 telemetry:
      enabled: false
```
I am using to install the istio components: https://istio.io/latest/docs/setup/install/standalone-operator/ and my install file looks like this:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: false
    telemetry:
      enabled: true
  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
  values:
    kiali:
      prometheusAddr: http://prometheus-k8s.monitoring.svc.cluster.local:9090
```

you'd wanna enable ingressgateway. I install it separately as a daemonset.

**Comment by jotak** [comment]
Hmm indeed in `spec.components.telemetry` it says disabled for me too, but in `spec.telemetry` I can see it enabled with v1 disabled and v2 enabled. Perhaps this section is more relevant to look at. I have:

```yaml
# ...
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        metadataExchange: {}
        prometheus:
          enabled: true
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```

**Comment by jmazzitelli** [comment]
Sounds like you should be reporting this up to the core Istio folks - seems like perhaps the istioctl installer has a problem.

**Comment by Shashankft9** [comment]
right, and how do I do the same thing through my install config file?

**Comment by Shashankft9** [comment]
so, I am installing default profile which too has:

```
telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        metadataExchange: {}
        prometheus:
          enabled: true
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```
does this mean I don't have to explicitly enable it? using:
```
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: false
    telemetry:
      enabled: true
```
