### ISSUE TITLE
OpenID login fails with "Error fetching OpenID provider metadata"

### ISSUE THREAD

**Issue by joba-hy** [kiali/kiali#2978]
**Describe the bug**
I am trying to configure Kiali to use the openid authentication.
When I press the "Log In With OpenID" button, I am redirected to `/kiali/api/auth/openid_redirect` with the error message: 
```
{"error":"Error fetching OpenID provider metadata.","detail":"Get \"/.well-known/openid-configuration\": unsupported protocol scheme \"\""}
```

There is no error in the Kiali log.

Kiali configuration in istio profile.yaml:

```
    kiali:
      contextPath: /kiali
      createDemoSecret: true
      prometheusAddr: http://prometheus-operator.monitoring.svc.cluster.local:9090
      dashboard:
        auth:
          strategy: openid
          openid:
            client_id: <id>.apps.googleusercontent.com
            issuer_uri: https://accounts.google.com
            username_claim: email
        grafanaInClusterURL: http://grafana:3000
        jaegerInClusterURL: http://tracing/jaeger
        viewOnlyMode: false
      hub: quay.io/kiali
      nodeSelector: {}
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      security:
        cert_file: /kiali-cert/cert-chain.pem
        enabled: false
        private_key_file: /kiali-cert/key.pem
      service:
        annotations: {}
      tag: v1.20
```

The values for `client_id`, `issuer_uri` and `username_claim` are set as defined in the [documentation](https://kiali.io/documentation/latest/getting-started/#_openid_connect)

**Versions used**
Kiali: v1.20
Istio: 1.6.5
Kubernetes: 1.18.5
