### ISSUE TITLE
KIA0104 error severity

### ISSUE THREAD

**Issue by MarkDeckert** [kiali/kiali#3001]
**General Remarks**

When applying an AuthorizationPolicy on an istio-ingressgateway it's quite possible that there is legitimately and deliberately no service or ServiceEntry directly matching the host in the AuthorizationPolicy.

**Bug description**
Let's say you have a Gateway object and a VirtualService object for foo.example.com.  There are two routes configured in the VirtualService - /bar goes to an actual service in the cluster called "bar".  /foo goes to a ServiceEntry called "bar.vms.svc.cluster.local" that refers to an external service.

If I want to set AuthorizationPolicy that applies to both services (or maybe just the external service).  The only way to have it apply to the external service as well is to apply the policy to the istio-ingressgateway itself.

In this example there is no service or ServiceEntry that refers to a "foo.example.com" host.  Only the Gateway object and VirtualService object know about the hostname.

Additionally these objects may not even be in the same namespace as the istio-ingressgateway deployment itself.

Apply an authorization policy on the istio-ingressgateway using 
```
  - to:
    - operation:
        hosts:
          - "foo.example.com"
```

Under the hood the envoy http rbac filter rule results in:
```
{
    "header": {
        "name": ":authority",
        "exactMatch": "foo.example.com"
    }
}
```
Authorization policy works correctly and matches requests that have -- depending on protocol -- the http1.1  host header "foo.example.com" or http2 authority header "foo.example.com" as it should according to the AuthorizationPolicy reference documentation. However in Kiali it reports a KIA0104 error. https://kiali.io/documentation/v1.15/validations/#_kia0104_this_host_has_no_matching_entry_in_the_service_registry

**Expected behavior**
This should not be an error because its a legitimate -- though perhaps obscure -- AuthorizationPolicy configuration. Again, only the Gateway and VirtualService need to know about the hostname.

I propose modifying the KIA0104 error so that it takes into account VirtualService and Gateway entries.

**Versions used**
Kiali: 1.18.2
Istio: 1.6.5

**Comment by lucasponce** [comment]
cc @xeviknal

**Comment by xeviknal** [comment]
hi @MarkDeckert, thanks for taking the time and issue this scenario.
I see a couple of things that might be happening here. Do you have the chance to share the four pieces of config you are saying in the description (obscured if it has to)? Virtual Service, Gateway, ServiceEntry and the AuthzPolicy itself (including the namespaces where they are living). It would really help me to better identify the underlying problem.

One of the problems we have to deal with in kiali is the cross-namespace reference. There are scenarios where multiple namespaces are involved and thus, the validations can't access to all of its components.

Thank you

**Comment by MarkDeckert** [comment]
Hi @xeviknal I apologize as it is a somewhat convoluted issue. I've attached a full config below.  This is a slightly contrived example in the simplest form I could think of that still generates the KIA0104 error.  The only scrubbed value is the hostname "example" in foo.example.com.

However there are other complexities that could come into play if the example was more complex:

- istio rootNamespace _could_ be, and often is, a namespace other than istio-system. Any istio objects in rootNamespace apply to all namespaces. Otherwise objects in istio-system also apply to all namespaces by default.
- ServiceEntries by default apply to all namespaces unless exportTo is set to "." current namespace. The default can be changed in the istio deployment itself, but even then a ServiceEntry can still be set to exportTo "*" to apply to all.

Given these conditions its possible to have a situation where (Gateway/VirtualService), (ServiceEntry), and (AuthorizationPolicy) all exist in different namespaces.  It may seem unlikely but I could see different teams being responsible for each of these separate components in certain scenarios which could result in a config thats spread out across namespaces like that.

For simplicity though the below example all lives in istio-system including the actual istio-ingressgateway deployment.


ServiceEntry
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: foo-dev
  namespace: istio-system
spec:
  endpoints:
  # ip is a vm/service outside the cluster
  - address: 10.15.1.121
  exportTo:
  - "."
  hosts:
  - foo-dev.istio-config.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 49000
    protocol: HTTP
  resolution: STATIC
```
VirtualService:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-dev
  namespace: istio-system
spec:
  hosts:
  - foo-dev.example.com
  gateways:
  - foo-dev
  http:
  - name: foo-svc
    match:
    - uri:
        prefix: /foo
    rewrite:
      uri: "/foo"
    route:
    - destination:
        host: foo-dev.istio-config.svc.cluster.local
        port:
          number: 49000
```
Gateway:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo-dev
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "foo-dev.example.com"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - hosts:
    - "foo-dev.example.com"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
And finally AuthorizationPolicy
```
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-foo
  namespace: istio-system
spec:
  action: DENY
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
  - to:
    - operation:
        hosts:
          - "foo-dev.example.com"
        paths:
          - "/foo"
    when:
    - key: request.headers[x-token]
      notValues:
      - "fooreader"
```
