### ISSUE TITLE
Using grafana with token occur authorization error

### ISSUE THREAD

**Issue by winty56** [kiali/kiali#3021]
**Describe the bug**

When using grafana with auth, it look like carriage return character(\n) append to token end .
below is pod's error log when UI try to access grafana 
```
E0722 21:01:51.337404       1 grafana.go:35] Get "http://myhost:3000/api/search?query=Istio%20Service%20Dashboard&orgId=3": net/http: invalid header  ││ field value "Bearer eyJrIj~~{omitted}~~I6M30=\n" for key Authorization    
```

**Versions used**
Kiali: v1.21.0
Istio: 1.6.5
Kubernetes flavour and version:  Kubernetes 1.7

**To Reproduce**
1. config Kiali
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
spec:
  external_services:
    grafana:
      auth:
        token: secret:kiali-external-services:grafana-token-kiali
        type: bearer
```
2. config Secret
```
apiVersion: v1
kind: Secret
type: Opaque
data:
  grafana-token-kiali: {token encoded base64}
```

3. Click on Kiali UI [Services]->resource->[Inbound Metrics]
4. see Kiali pod's error logs

**Expected behavior**
No Authorization and metric should be show.
