### ISSUE TITLE
Error kiali integration jaeger - Could not fetch spans.

### ISSUE THREAD

**Issue by thiagoleitetr** [kiali/kiali#3041]
**Description:**
Error in UI "Could not fetch spans." after upgrade Istio from 1.14.3 to 1.16.5.

**URL:**
https://kiali.mydomain/kiali/console/namespaces/<NAMESPACE>/applications/<APP>?tab=in_metrics

**Debugging:**
1) 503 in https://kiali.mydomain/kiali/api/namespaces/<NAMESPACE>/services/<APP>/spans?startMicros=1595881861110000
returns:
`{"error":"invalid character '\u003c' looking for beginning of value"}`

2) I got the output above from tcpdump from kiali pod to jaeger-query service, I was expecting a json output but it returns a html data:
URL:
http://jaeger-query.istio-system:16686/api/traces?end=&limit=100&service=<APP>.<NAMESPACE>&start=1595879883877000

Running it manually:
```
[kiali@kiali-787fbdd6c7-lz92f kiali]$ curl "http://jaeger-query.istio-system:16686/api/traces?end=&limit=100&service=<APP>.<NAMESPACE>&start=1595879883877000"

<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="cache-control" content="max-age=0"/><meta http-equiv="cache-control" content="no-cache"/><meta http-equiv="expires" content="0"/><meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT"/><meta http-equiv="pragma" content="no-cache"/><base href="/jaeger/" data-inject-target="BASE_URL"/><link rel="shortcut icon" href="./favicon.ico"><title>Jaeger UI</title><script>// Jaeger UI config data is embedded by the query-service. This is
      // later merged with defaults into the redux `state.config` via
      // src/utils/config/get-config.js. The default provided by the query
      // service should be an empty object or it can leave `DEFAULT_CONFIG`
      // unchanged.
      function getJaegerUiConfig() {
        const DEFAULT_CONFIG = null;
        const JAEGER_CONFIG = DEFAULT_CONFIG;
        return JAEGER_CONFIG;
      }</script><link href="./static/css/1.83b7ce44.chunk.css" rel="stylesheet"><link href="./static/css/main.363d31b1.chunk.css" rel="stylesheet"></head><body><div id="jaeger-ui-root"></div><script>!function(l){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],f=0,i=[];f<n.length;f++)t=n[f],p[t]&&i.push(p[t][0]),p[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(l[r]=o[r]);for(s&&s(e);i.length;)i.shift()();return c.push.apply(c,u||[]),a()}function a(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==p[u]&&(n=!1)}n&&(c.splice(r--,1),e=f(f.s=t[0]))}return e}var t={},p={2:0},c=[];function f(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return l[e].call(r.exports,r,r.exports,f),r.l=!0,r.exports}f.m=l,f.c=t,f.d=function(e,r,t){f.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(r,e){if(1&e&&(r=f(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)f.d(t,n,function(e){return r[e]}.bind(null,n));return t},f.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="./";var r=window.webpackJsonp=window.webpackJsonp||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;a()}([])</script><script src="./static/js/1.d7e3159f.chunk.js"></script><script src="./static/js/main.d8e504a9.chunk.js"></script></body></html>[kiali@kiali-787fbdd6c7-lz92f kiali]$ 

```

**My kiali configmap:**
```
istio_namespace: istio-system
istio_component_namespaces:
  grafana: istio-system
  tracing: istio-system
  istiod: istio-system
  prometheus: istio-system
deployment:
  accessible_namespaces: ['**']
auth:
  strategy: anonymous
server:
  port: 20001
  web_root: /kiali
external_services:
  grafana:
    auth:
      insecure_skip_verify: true
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
      type: bearer
    dashboards: []
    enabled: true
    in_cluster_url: "http://prometheus-grafana.prometheus"
    url: https://grafana.mydomain
  prometheus:
    auth:
      insecure_skip_verify: true
    custom_metrics_url: http://prometheus-server.prometheus
    url: http://prometheus-server.prometheus
  tracing:
    auth:
      insecure_skip_verify: true
    enabled: true
    in_cluster_url: "http://jaeger-query.istio-system:16686"
    namespace: istio-system
    port: 16686
    service: "jaeger-query"
    url: "https://jaeger.mydomain/jaeger"

```

**Versions:**
- docker.io/jaegertracing/all-in-one:1.18.1
- quay.io/kiali/kiali:v1.18.3
- istio 1.6.5
- kubernetes: 1.18.6
