### ISSUE TITLE
Validations: Support `exportTo` field

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3061]
As of today, kiali validations doesn't consider the `exportTo` field. This field allows users to specify the scope of each config.

> This feature provides a mechanism for service owners and mesh administrators to control the visibility of services across namespace boundaries.

One example:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
  namespace: bookinfo
spec:
  hosts:
  - api.dropboxapi.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  exportTo:
  - '.'
  - foo
  - bar
```

This service entry is only available for `bookinfo, foo, bar` namespaces only.

Validations has to be adapted to filter those config by the exportTo field. This might trigger thoughts of cross-namespace validations.

- [x] #4314
- [x] #4315
- [x] #4316
- [x] #4317
