### ISSUE TITLE
Add configuration option to specify Kiali's public port (OIDC support)

### ISSUE THREAD

**Issue by funkypenguin** [kiali/kiali#3111]
**Describe the bug**

When using Kiali behind an Istio VirtualService (or likely a Kubernetes Ingress too), the openid login button redirects me to `<schema>://<web_fqdn>:20001`. Since I'm terminating all ingress on port 443, this behaviour breaks my ability to use openid.

**Versions used**
Kiali: 1.22
Istio: 1.6
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) Kubernetes 1.18.6 bare-meal

**To Reproduce**
1. Configure Kiali behind an Ingress with a public FQDN (in my case, `kiali.elpenguino.net`)
2. Configure openid auth
3. At the initial screen, click "Log in with OpenID"
4. You are redirected to `https://kiali.elpenguino.net:20001/kiali/api/auth/openid_redirect`

**Expected behavior**

I should be able to override the URL to remove the `:20001` component. This should also apply to the redirect_url passed during the OIDC login process.

**Comment by israel-hdez** [comment]
@funkypenguin Can you provide an example of the VS?

**Comment by israel-hdez** [comment]
@funkypenguin As a workaround, if you are using VirtualServices, you could add a `X-Forwarded-Port` header with the right port you need. See: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers

If you are using an Ingress, it *may* also offer header injection.

**Comment by funkypenguin** [comment]
Thanks @israel-hdez, here's the VirtualService:

```
spec:
  gateways:
  - istio-ingressgateway.istio-system.svc.cluster.local
  hosts:
  - kiali.elpenguino.net
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001
    timeout: 30s
```

Re the workaround with the header, I'll give it a try ;)

D

**Comment by funkypenguin** [comment]
OK, looks like this fixed the hard-coded port issue:

```
spec:
  gateways:
  - istio-ingressgateway.istio-system.svc.cluster.local
  hosts:
  - kiali.elpenguino.net
  http:
  - headers:
      request:
        set:
          X-Forwarded-Port: "443"
    route:
    - destination:
        host: kiali
        port:
          number: 20001
    timeout: 30s
```

I can now log into KeyCloak, and I get successfully redirected back to Kiali's login page.

Next step to work out how to correlate the returning user details with what kube-api expects (kube-api is using `"oidc-username-prefix": "oidc:"`). Another day, another issue. Thanks! :)

**Comment by jmazzitelli** [comment]
@israel-hdez this sounds like something we should put in the FAQ: https://kiali.io/documentation/latest/faq/#token-strategy
I'll add that, unless you think we should solve this in the code and not require `X-Forwarded-Port`

**Comment by funkypenguin** [comment]
I think the `X-Forwarded-Port` trick is a neat workaround, but I'd appreciate being able to set this value, just like a can set `web_fqdn`, via the config :)

(re-opening this issue since it's still under discussion)

**Comment by jmazzitelli** [comment]
FAQ PR: https://github.com/kiali/kiali.io/pull/291
See: https://deploy-preview-291--kiali.netlify.app/documentation/staging/faq/#x-forwarded-port

**Comment by israel-hdez** [comment]
IMO, it's a little odd to see that you can configure the hostname via the `web_fqdn` configuration and also configure the protocol via the `web_schema`, but not the port. So, I think we can leave this open with the aim for a more complete config.

I'll relabel as `enhancement`. For now, I think the workaround and the new FAQ entry would be quite fine.

Don't expect this to be implemented soon, though, as there are other priorities ;)

**Comment by jshaughn** [comment]
@israel-hdez I'll add to the backlog, let me know if and when we should prioritize.

**Comment by israel-hdez** [comment]
@cfcosta wanna help with this?

**Comment by cfcosta** [comment]
@israel-hdez sounds good, let me take a look.

**Comment by juliusoh** [comment]
I'm still running into issue 

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: gateway
spec:
  parentRefs:
    - name: 'istio-public'
      namespace: gateway
      sectionName: https
  hostnames:
    - ${hostname}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kiali
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Port
                value: '443'
              - name: X-Forwarded-Proto
                value: 'https'
              - name: X-Forwarded-Host
                value: '${hostname}'
      backendRefs:
        - name: kiali
          namespace: istio-system
          port: 20001
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /kiali/console
            statusCode: 302

```
