### ISSUE TITLE
Correct version in operator when OPERATOR_CONTAINER_VERSION is set

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#3132]
When I upload a operator version from local I saw that in minikube show the version **v1.23.0-SNAPSHOT** when _OPERATOR_CONTAINER_VERSION=dev_ and the image loaded is localhost:5000/kiali/kiali-operator:dev .

I think that we should tag this with dev instead the latest one. What do you think ?

![Screenshot from 2020-08-18 10-28-23](https://user-images.githubusercontent.com/3019213/90489485-a4102e80-e13d-11ea-964f-6023c6150c67.png)

```yaml
# Source: kiali-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
  namespace: kiali-operator
  labels:
    helm.sh/chart: kiali-operator-1.23.0-SNAPSHOT
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.23.0-SNAPSHOT"
    app.kubernetes.io/version: "v1.23.0-SNAPSHOT"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali-operator
      app.kubernetes.io/instance: kiali-operator
  template:
    metadata:
      name: kiali-operator
      namespace: kiali-operator
      labels:
        # required for the operator SDK metric service selector
        name: kiali-operator
        helm.sh/chart: kiali-operator-1.23.0-SNAPSHOT
        app: kiali-operator
        app.kubernetes.io/name: kiali-operator
        app.kubernetes.io/instance: kiali-operator
        version: "v1.23.0-SNAPSHOT"
        app.kubernetes.io/version: "v1.23.0-SNAPSHOT"
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: kiali-operator
      containers:
      - name: operator
        image: "localhost:5000/kiali/kiali-operator:dev"
        imagePullPolicy: Always
        args:
        - "--zap-level=info"
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: kiali-operator
        - name: ANSIBLE_DEBUG_LOGS
          value: "true"
        - name: ANSIBLE_VERBOSITY_KIALI_KIALI_IO
          value: "1"
        ports:
        - name: http-metrics
          containerPort: 8383
        - name: cr-metrics
          containerPort: 8686
      volumes:
      - name: runner
        emptyDir: {}
      affinity:
        {}

```
