### ISSUE TITLE
Kiali should not overtake a port

### ISSUE THREAD

**Issue by PatrickDuncan** [kiali/kiali#3134]
#### Is your feature request related to a problem? Please describe.
Hello! I have 2 Kiali deployments running in 2 separate namespaces (#3002) in a single cluster. I'm using SNI with my cluster's ingress subdomain and I can only ever route to 1 Kiali instance.
Let's say:
```
Kiali-1: https://kiali-sni-1.my-super-long-subdomain.com
Kiali-2: https://kiali-sni-2.my-super-long-subdomain.com
```

After I go to Kiali-1 in my browser it completely overtakes port 443. So Kiali-2 would resolve to Kiali-1. `https://my-super-long-subdomain.com` would resolve to Kiali-1. `https://gibberish123.my-super-long-subdomain.com` will resolve to Kiali-1.

If I open incognito and go to Kiali-2, it resolves to Kiali-2.

If I use SNI with a basic nginx server then this wildcard problem doesn't exist. ~So I'm inclined to think that this is a problem with the kiali-ui and React Router.~

Let's say I have Kiali-3 which is actually SNI pointing to nginx. If I open a new browser and open Kiali-3 first it will go to nginx. If I enter a wildcard it fails. If I then open Kiali-1 then `*.my-super-long-subdomain.com` will resolve to Kiali-1. Except for Kiali-3, that will continue going to Kiali-3. I believe this proves that this is a Kiali problem and not a SNI problem.

Here's an example of a Gateway and VirtualService:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-1
  namespace: r1
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        protocol: https
        name: HTTPS-kiali-1
      tls:
        mode: PASSTHROUGH
      hosts:
        - "kiali-sni-1.my-super-long-subdomain.com"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-1
  namespace: r1
spec:
  hosts:
    - kiali-sni-1.my-super-long-subdomain.com
  gateways:
    - kiali-1
  tls:
    - match:
        - port: 443
          sniHosts:
            - kiali-sni-1.my-super-long-subdomain.com
      route:
        - destination:
            host: kiali
            port:
              number: 20001
```

I've also tried TLS with port 15443.

#### Describe the solution you'd like
Kiali shouldn't overtake a port with a wildcard. It should only live on the exact host. **Multiple services should be able to live alongside Kiali on a single port with SNI.**

#### Describe alternatives you've considered
An alternative would be to have a different port for each Kiali instance which doesn't fit our use case. I don't believe subdomains fit our use case either.
