### ISSUE TITLE
Grafana 401 unauthorized error on Kiali 1.22.1 and Istio 1.7.0 

### ISSUE THREAD

**Issue by vivekpd15** [kiali/kiali#3151]
Describe the bug

When using grafana with login authorization strategy, kiali is giving 401 unauthorized error . I am able to access the grafana dashboard directly using the same username and password.

Versions used
Kiali: v1.22.1
Istio: 1.7.0
Kubernetes flavour and version: KOPS Kubernetes 1.18.8

To Reproduce
Deploy Grafana
`kubectl create secret generic grafana -n istio-system --from-literal=username=grafanaadmin --from-literal=passphrase=12345`
`helm repo add bitnami https://charts.bitnami.com/bitnami`
`helm repo update`
`helm upgrade --install grafana bitnami/grafana -f ./grafana-values.yaml -n istio-system`

Deploy Kiali Operator
`kubectl create ns kiali-operator`
`helm install \
    --set cr.create=false \
    --namespace kiali-operator \
    --repo https://kiali.org/helm-charts \
    kiali-operator \
    kiali-operator`

Deploy Kiali using the following CR in istio-system namespace:
`kubectl create secret generic kiali -n istio-system --from-literal=username=kialiadmin --from-literal=passphrase=12345`
`kubectl apply -f ./kiali-cr.yaml -n istio-system`

kiali-cr.yaml --> [kiali-cr.txt](https://github.com/kiali/kiali/files/5124982/kiali-cr.txt)

Click on Kiali UI [Services]-> Resource->[Inbound Metrics]
Check Kiali pod's error logs

Expected behavior
Kiali should be able to access Grafana

**Comment by lucasponce** [comment]
is this URL "http://grafana.istio-system.svc.cluster.local:3000" available from the browser ?

**Comment by vivekpd15** [comment]
@lucasponce No it is not. We are not planning to expose grafana using ingress. AFAIK, it is not mandatory for grafana to be exposed, and it is only for making a few links work when used in the browser. Is this not correct?

**Comment by jmazzitelli** [comment]
> We are not planning to expose grafana using ingress. AFAIK, it is not mandatory for grafana to be exposed, and it is only for making a few links work when used in the browser.

How are your users going to be able to see Grafana in their browser if you don't expose those links externally?

**Comment by jmazzitelli** [comment]
> it is not mandatory for grafana to be exposed, and it is only for making a few links work when used in the browser. Is this not correct?

Kiali's native Jaeger integration does that (you don't need to expose Jaeger UI - Kiali has some views that read Jaeger data and populates its own pages using that data). If you do not expose Jaeger UI externally, you do lose some capability, but not all. 

But Kiali doesn't do anything like that for Grafana - Grafana is its own graphs/charts. Kiali just links to them - pointing your user's browser to it. So those links need to be exposed.

**Comment by vivekpd15** [comment]
@jmazzitelli I just exposed it over istio's ingress gateway. Still 401 unauthorized for me.

**Comment by jmazzitelli** [comment]
In your Kiali CR you have:

```
      in_cluster_url: "http://grafana.istio-system.svc.cluster.local:3000"
      url: "http://grafana.istio-system.svc.cluster.local:3000"
 ```

I'm pretty sure that is not right. `url` is the external root URL that your users' browsers will need to access to get to Grafana (e.g. if you are exposing it over an Istio Ingress, you'll want to provide the ingress URL here). `url` is typically NOT the same as `in_cluster_url`.

See: https://github.com/kiali/kiali-operator/blob/v1.21/deploy/kiali/kiali_cr.yaml#L464-L466

**Comment by vivekpd15** [comment]
@jmazzitelli That is the old version. I had changed URL to "https://grafana.example.com" and it is accessible separately using the same link, username and password but kiali says 401 unauthorized to me.

**Comment by lucasponce** [comment]
@vivekpd15 ok, let me check if I can reproduce your scenario, I'm not sure if the grafana version can be involved in this.
I'll post a follow up comment with my findings.

**Comment by vivekpd15** [comment]
Thank you @lucasponce. Look forward to it.

**Comment by lucasponce** [comment]
I've performed some tests Minikube + Istio 1.7.0 to help to spot the issue.

By default, Grafana integration is disabled because, addons are not exposed..

I've exposed them with the recommendation Istio recommendation [1]

And I've update Kiali configmap:

```
[...]
    external_services:
      grafana:
        auth:
          ca_file: ""
          insecure_skip_verify: true
          password: ""
          token: ""
          type: none
          use_kiali_token: false
          username: ""
        dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        enabled: true
        in_cluster_url: http://grafana:3000
        url: "https://grafana.10.107.168.123.nip.io"
[...]
```

I don't have Grafana protected, but I wanted to test the basic integration first.

As you can see in the config [2], Kiali uses `in_cluster_url` to access to the internal grafana service to fetch information about the dashboards to build the query parameters used in the link generated from the `url` parameter that is the public URL how the browser should access to grafana.

With those in place I can see Grafana (note the url):

![image](https://user-images.githubusercontent.com/1662329/91281310-32149680-e788-11ea-9f51-bd46c6d50a64.png)

And Kiali with Grafana integrated:

![image](https://user-images.githubusercontent.com/1662329/91281361-43f63980-e788-11ea-96fb-f52cf26e1a78.png)

![image](https://user-images.githubusercontent.com/1662329/91281572-8d468900-e788-11ea-9e97-b7375d4b1f9b.png)

So, I guess this scenario works for you @vivekpd15. And the problem is the authentication with the grafana username/password/credentials, isn't it ?

I'd like to confirm to reach a stable point to scope if there is a problem we can reproduce in any env.

[1] https://istio.io/latest/docs/tasks/observability/gateways/
[2] https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L446
