### ISSUE TITLE
review operator playbooks to confirm `until` loops do not expect template re-evaluation

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3167]
I have been assuming Ansible evaluates templates (e.g. the `{{ lookup(...) }}`) for each retry of an `until` loop, but that is a bad assumption. Ansible apparently only evaluates them a single time regardless of the number of retries within an `until` loop.

We need to go through the operator playbooks and confirm this bad assumption is not made in there. I went over all the molecule tests (where I originally encountered this problem) and [fixed this where it exists in the tests](https://github.com/kiali/kiali-operator/pull/125). But the operator playbooks themselves need to be checked and scrubbed of this problem if it exists.

Here's the original description of the bug I hit in the molecule test that illustrates this problem. I fixed this within https://github.com/kiali/kiali-operator/pull/125

===

An ansible task in a molecule test wants to update a value within the Kiali CR yaml. The task waits until the CR status indicates the current reconciliation finishes by looking for `ansibleResult` in the CR status field. Here's the task:

```
- vars:
    current_kiali_cr: "{{ lookup('k8s', api_version='kiali.io/v1alpha1', kind='Kiali', namespace='kiali-operator', resource_name='kiali') }}"
  set_fact:
    new_kiali_cr: "{{ current_kiali_cr | combine({'spec': {'deployment': {'accessible_namespaces': namespace_list }}}, recursive=True) }}"
  until:
  - new_kiali_cr is defined
  - new_kiali_cr.status is defined
  - new_kiali_cr.status.conditions | length > 0
  - new_kiali_cr.status.conditions[0].ansibleResult is defined
  retries: 360
  delay: 5
```

Notice the `until` clause will keep looping until the CR has a `status.conditions[0].ansibleResult` which means there is no reconciliation running at that time. Notice also that the task has a `var current_kiali_cr` that looks up the current CR.
For each retry loop, the ansible debug logs tell me the `status` field is:

```
     "status": {
                    "conditions": [
                        {
                            "lastTransitionTime": "2020-09-01T20:49:38Z",
                            "message": "Running reconciliation",
                            "reason": "Running",
                            "status": "True",
                            "type": "Running"
                        }
                    ]
                }
```

But yet, as it is telling me this, in another console, I do an `oc get` to obtain the CR and I see:

```
$ oc get kiali kiali -n kiali-operator -o yaml
status:
  accessibleNamespaces:
  - '**'
  conditions:
  - ansibleResult:
      changed: 10
      completion: 2020-09-01T20:52:29.51319
      failures: 0
      ok: 88
      skipped: 71
    lastTransitionTime: "2020-09-01T20:49:38Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
```

See the `Awaiting next reconciliation` and the `ansibleResult` in `status`? There is no reconciliation going on. So why doesn't my ansible task see this CR with that `status` field? It is as if the `var: current_kiali_cr: "{{ lookup(...."`  isn't being called for each retry. The CR has a `status` field with `"Awaiting  next reconciliation"` but the ansible task can't see it.
