### ISSUE TITLE
Configurable Tresholds - 0% is shown in Failure objects

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3202]
When App/Workload/Service status is Failure, because of set configurable treshold on error rates, the status icon tooltip shows 0% on Failure cases.
In Degraded and Success cases it shown both rates in giver correct %.

![Screenshot from 2020-09-11 10-24-45](https://user-images.githubusercontent.com/604313/92893214-c84bec00-f419-11ea-96c7-8c2b56e9380d.png)
![Screenshot from 2020-09-11 10-22-29](https://user-images.githubusercontent.com/604313/92893217-c8e48280-f419-11ea-955d-b64501fb3c93.png)
![Screenshot from 2020-09-11 10-24-35](https://user-images.githubusercontent.com/604313/92893222-c97d1900-f419-11ea-8663-8dcb25436a62.png)
![Screenshot from 2020-09-11 10-22-39](https://user-images.githubusercontent.com/604313/92893225-ca15af80-f419-11ea-9743-9639fccf8854.png)
![Screenshot from 2020-09-11 10-22-08](https://user-images.githubusercontent.com/604313/92893204-c6822880-f419-11ea-99d7-cd766cdeebc5.png)
![Screenshot from 2020-09-11 10-21-18](https://user-images.githubusercontent.com/604313/92893210-c7b35580-f419-11ea-8a80-845e04e07d7d.png)

**Comment by aljesusg** [comment]
Can you paste here the debug health info?

**Comment by hhovsepy** [comment]
`    health_config:
      rate:
        - namespace: "alpha"
          tolerance:
            - code: "404"
              failure: 10
              protocol: "http"
            - code: "[45]\\d[^\\D4]"
              protocol: "http"
        - namespace: "beta"
          tolerance:
            - code: "[4]\\d\\d"
              degraded: 5
              failure: 10
              protocol: "http"
            - code: "[5]\\d\\d"
              protocol: "http"`

**Comment by hhovsepy** [comment]
Health Config
`
{
  "healthConfig": {
    "rate": [
      {
        "namespace": "/alpha/",
        "kind": "/.*/",
        "name": "/.*/",
        "tolerance": [
          {
            "code": "/404/",
            "degraded": 0,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/[45]\\d[^\\D4]/",
            "degraded": 0,
            "failure": 0,
            "protocol": "/http/",
            "direction": "/.*/"
          }
        ]
      },
      {
        "namespace": "/beta/",
        "kind": "/.*/",
        "name": "/.*/",
        "tolerance": [
          {
            "code": "/[4]\\d\\d/",
            "degraded": 5,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/[5]\\d\\d/",
            "degraded": 0,
            "failure": 0,
            "protocol": "/http/",
            "direction": "/.*/"
          }
        ]
      },
      {
        "namespace": "/.*/",
        "kind": "/.*/",
        "name": "/.*/",
        "tolerance": [
          {
            "code": "/^5\\d\\d$/",
            "degraded": 0.1,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/^4\\d\\d$/",
            "degraded": 10,
            "failure": 20,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/^[1-9]$|^1[0-6]$/",
            "degraded": 0.1,
            "failure": 10,
            "protocol": "/grpc/",
            "direction": "/.*/"
          }
        ]
      }
    ]
  }
}
`

**Comment by aljesusg** [comment]
> When App/Workload/Service status is Failure, because of set configurable treshold on error rates, the status icon tooltip shows 0% on Failure cases.
> In Degraded and Success cases it shown both rates in giver correct %.
> 
> ![Screenshot from 2020-09-11 10-24-45](https://user-images.githubusercontent.com/604313/92893214-c84bec00-f419-11ea-96c7-8c2b56e9380d.png)

in this case we use this yaml and the responses are "200,9;404,1"

```yaml
{
        "namespace": "/beta/",
        "kind": "/.*/",
        "name": "/.*/",
        "tolerance": [
          {
            "code": "/[4]\\d\\d/",
            "degraded": 5,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/[5]\\d\\d/",
            "degraded": 0,
            "failure": 0,
            "protocol": "/http/",
            "direction": "/.*/"
          }
        ]
```

so the tolerance to apply would be 

```yaml
 {
            "code": "/[4]\\d\\d/",
            "degraded": 5,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          }
```
> ![Screenshot from 2020-09-11 10-22-29](https://user-images.githubusercontent.com/604313/92893217-c8e48280-f419-11ea-955d-b64501fb3c93.png)

In this one responses are "200,9;500,1" so the tolerance is

```yaml
{
            "code": "/[5]\\d\\d/",
            "degraded": 0,
            "failure": 0,
            "protocol": "/http/",
            "direction": "/.*/"
          }
```

this is why you see >0 >0 because degraded and failure is 0 so the errorRate is greather than 0 and the result is failure
> ![Screenshot from 2020-09-11 10-24-35](https://user-images.githubusercontent.com/604313/92893222-c97d1900-f419-11ea-8663-8dcb25436a62.png)
In this case this app get reposnes from 2 servers

x-server "200,9;404,1"
y-server "200,9;500,1"

From x-server would be degraded but the tolerance from y-server is failure so by priority the result would be failure then the tolerance applied is correct.

> ![Screenshot from 2020-09-11 10-22-39](https://user-images.githubusercontent.com/604313/92893225-ca15af80-f419-11ea-9743-9639fccf8854.png)

z-server "200,8;201,1;202,1"
healthy in both tolerances so we show the first one

```yaml
 {
            "code": "/[4]\\d\\d/",
            "degraded": 5,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          }
```
Yep maybe here we should remove the tolerance if all cases are healthy. are you agree @lucasponce ?


> ![Screenshot from 2020-09-11 10-22-08](https://user-images.githubusercontent.com/604313/92893204-c6822880-f419-11ea-99d7-cd766cdeebc5.png)
x-server "200,9;404,1" 

tolerance to apply
```yaml
{
            "code": "/[4]\\d\\d/",
            "degraded": 5,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"          
```
> ![Screenshot from 2020-09-11 10-21-18](https://user-images.githubusercontent.com/604313/92893210-c7b35580-f419-11ea-8a80-845e04e07d7d.png)

Same
