### ISSUE TITLE
Kiali stuck in endless reconciliation

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3212]
When running the kiali with maistra 2.0 the kiali operator is stuck in loop trying to re-deploy kiali.

**Versions used**
Kiali: https://github.com/kiali/kiali/pull/3206 with https://github.com/kiali/kiali-operator/pull/127
Istio: maistra 2.0 deployed from quay.io/maistra/servicemesh-olm-cs:latest-2.0-qe
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.5

**To Reproduce**
1. Install kiali operator from https://github.com/kiali/kiali-operator/pull/127 using kiali-operator/deploy/deploy-kiali-operator.sh
2. Install jaeger operator from rh-verified-operators using tech-preview channel
3. Install maistra operator using quay.io/maistra/servicemesh-olm-cs:latest-2.0-qe
4. apply following SMCP CR:
```
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: install-istio-system
spec:
  version: v2.0
  security:
    mutualTLS:
      enable: false
      auto: true
      controlPlane:
        enable: false
  addons:
    tracing:
      # change to None to disable tracing
      type: Jaeger
      jaeger:
        name: jaeger
        # we want maistra to create the jaeger resource
        # TODO: not working yet
        install:
          type: Memory
          elasticSearch:
            nodeCount: 1
    visualization:
      grafana:
        enabled: true
        install: {}
      kiali:
        name: kiali
        enabled: true
        # we want maistra to create the kiali resource
        install: {}
```
5. Patch kiali CR so it uses kiali build from PR 3206:
```
oc patch kiali kiali -n istio-system --type=merge '-p={"spec":{"deployment": {"image_version": "core3206" }}}'
oc patch kiali kiali -n istio-system --type=merge '-p={"spec":{"deployment": {"image_pull_policy": "Always" }}}'
oc patch kiali kiali -n istio-system --type=merge '-p={"spec":{"deployment": {"image_name": "quay.io/kiali-qe/kiali" }}}'
```
6. Edit kiali cr to add workaround for https://issues.redhat.com/browse/MAISTRA-1804 by setting spec.external_services.istio.config_map_name to istio-install-istio-system

**Actual behavior**
Kiali operator is stuck in loop trying to re-deploy kiali. Operator contains following error:
TASK [v1.12/kiali-deploy : fail]  but kiali pod is running fine and is not being restarted.

Full kiali, kiali-operator and kiali cr attached.
[kiali.log](https://github.com/kiali/kiali/files/5226134/kiali.log)
[kiali-operator.log](https://github.com/kiali/kiali/files/5226135/kiali-operator.log)
[kiali-kiali.log](https://github.com/kiali/kiali/files/5226152/kiali-kiali.log)
