### ISSUE TITLE
Setting non-default PrometheusURL breaks Istio Component Status indicator

### ISSUE THREAD

**Issue by dntosas** [kiali/kiali#3225]
**Describe the bug**
When we set in the configuration a non-default prometheusURL, Kiali shows a notification that Prometheus is missing even though it correctly fetches data.

Configuration block:
```bash
    external_services:
      istio:
        url_service_version: http://istiod:15014/version
      prometheus:
        url: http://istio-prometheus:9090
```
![Screenshot from 2020-09-18 08-49-41](https://user-images.githubusercontent.com/15010919/93560940-ea022180-f98b-11ea-86ee-8666c7e6e7a2.png)

**Versions used**
Kiali: `1.23.0`
Istio: `1.7.1`
Kubernetes flavour and version: `Kops - 1.18.6`

**To Reproduce**
1. Set a non-default PrometheusURL on conf (means no defaulting to `http://prometheus:9090`)
1. Go to 'Kiali Home Page'
2. See error on Notification Istio Component status which is `RED`

**Expected behavior**
Kiali to understand that Prometheus is present

**Comment by lucasponce** [comment]
I think there is a PR on the way about this, I'll cc @xeviknal on this as he has more details around it.

**Comment by xeviknal** [comment]
@dntosas hello! In kiali 1.23, in both the CR and the ConfigMap you have the following field where you can put the label value of your prometheus pods: https://github.com/kiali/kiali-operator/blob/v1.23/deploy/kiali/kiali_cr.yaml#L539

```
external_services:
  prometheus:
    component_status:
      app_label: prometheus-app-label
      is_core: true
```

Make sure that the prometheus pods have the "app" label set with the value you put in the setting (e.g. prometheus-app-label).

See my example:

```
$ k describe pods -n istio-system prometheus-9d5676d95-lrjpp
Name:         prometheus-9d5676d95-lrjpp
Namespace:    istio-system
Labels:       app=prometheus
              chart=prometheus-11.7.0
              component=server
              heritage=Helm
              pod-template-hash=9d5676d95
              release=prometheus
```

In case you had prometheus in another namespace, you'd need to add an [extra setting](https://github.com/kiali/kiali-operator/blob/v1.23/deploy/kiali/kiali_cr.yaml#L48):

```
istio_component_namespaces:
  prometheus: prom-ns
```

This last bit will change in v1.24 where you'll be able to specify the namespace like this:
```
external_services:
  prometheus:
    component_status:
      app_label: prometheus-app-label
      is_core: true
      namespace: prom-ns
```

Does this make sense?
