### ISSUE TITLE
Operator unable to list server APIs

### ISSUE THREAD

**Issue by MarianZoll** [kiali/kiali#3239]
**Describe the bug**
The Kiali operator does not finish the Kiali CR installation and repeats its installation. Most probably, we are missing some required server APIs or authorization context. But as we did not define any specific rights nor have a strange Kubernetes setup we cannot narrow down the actual root cause.

Some sample errors of the errors presented in the attached log file ([kiali-operator.log](https://github.com/kiali/kiali/files/5267397/kiali-operator.log)).:
```
{"level":"error","ts":1600854468.34076,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"rbac.authorization.k8s.io/v1, Kind=ClusterRole","error":"unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:99\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/net/http/server.go:1890"}

{"level":"error","ts":1600854478.9411542,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"apps/v1, Kind=Deployment","error":"unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:99\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/net/http/server.go:1890"}
```

The operator is installed via Terraform and Helm:
```
NAME          	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
kiali-operator	kiali-operator	1       	2020-09-23 09:45:54.527002774 +0000 UTC	deployed	kiali-operator-1.24.0	v1.24.0  
```

The Kiali CR is defined as:
```
# Configurations are taken from: https://raw.githubusercontent.com/kiali/kiali-operator/master/deploy/kiali/kiali_cr.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  additional_display_details:
  - annotation: kiali.io/api-spec
    icon_annotation: kiali.io/api-type
    title: API Documentation
  api: 
    namespaces:
      exclude:
      - istio-operator
      - kube.*
      - openshift.*
      - ibm.*
      - kiali-operator
  auth:
    strategy: token
  deployment:
    accessible_namespaces:
    - '**'
    additional_service_yaml: {}
    affinity:
      node: {}
      pod: {}
      pod_anti: {}
    custom_dashboards:
      excludes: ['*']
      includes: ['kiali','envoy','quarkus']
    secret_name: kiali
  extensions:
    iter_8:
      enabled: false
    threescale:
      adapter_name: threescale
      adapter_port: "3333"
      adapter_service: threescale-istio-adapter
      enabled: false
      template_name: threescale-authorization
  external_services:
    istio:
      istio_identity_domain: svc.cluster.local
      istio_sidecar_annotation: sidecar.istio.io/status
      istio_status_enabled: true
      url_service_version: http://istiod:15014/version
    prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: none
        use_kiali_token: false
        username: ""
      custom_metrics_url: http://prometheus:9090
      url: http://prometheus:9090
    tracing:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: none
        use_kiali_token: false
        username: ""
      enabled: true
      in_cluster_url: http://tracing/jaeger
      namespace_selector: true
      url: ""
      whitelist_istio_system:
      - jaeger-query
      - istio-ingressgateway
  istio_labels:
    app_label_name: app
    version_label_name: version
  istio_namespace: istio-system
  kubernetes_config:
    burst: 200
    cache_duration: 300
    cache_enabled: true
    cache_istio_types:
    - DestinationRule
    - Gateway
    - ServiceEntry
    - VirtualService
    cache_namespaces:
    - .*
    cache_token_namespace_duration: 10
    excluded_workloads:
    - CronJob
    - DeploymentConfig
    - Job
    - ReplicationController
    qps: 175
  login_token:
    expiration_seconds: 86400
    signing_key: CHANGEME
  server:
    address: ""
    audit_log: true
    cors_allow_all: false
    gzip_enabled: true
    metrics_enabled: true
    metrics_port: 9090
    port: 20001
    web_fqdn: ""
    web_root: /kiali
    web_schema: ""
```

**Versions used**
Kiali: 1.24
Istio: 1.17
Kubernetes flavour and version: Azure Kubernetes Service (AKS) 1.17.9

**To Reproduce**
1. Install Kiali Operator via Helm
2. Install Istio 1.17 with Jaeger and Prometheus
3. Apply the Kiali CR

**Expected behavior**
The operator should create all necessary permissions for its service accounts or a more precise error message might be nice.
