### ISSUE TITLE
Prometheus health endpoint EOF

### ISSUE THREAD

**Issue by eperdeme** [kiali/kiali#3242]
**Describe the bug**
Kiali fails to get prometheus health. If I bash on to the Kiali container and use curl to POST to the api endpoint it functions fine. The Kiali UI appears to be rending maps/etc so prometheus must be accessible?

Error message:
"Could not fetch health: Error while fetching app health: Post "http://prometheus-operator-prometheus.prometheus.svc:9090/api/v1/query": EOF"

![Screenshot 2020-09-23 at 13 59 13](https://user-images.githubusercontent.com/158550/94015583-fb409900-fda4-11ea-83d7-500975ca62b1.png)

Curl example:
```
kubectl exec -it -n kiali kiali-5fc7bf8969-dxbgt /bin/bash 

Defaulting container name to kiali.

[kiali@kiali-5fc7bf8969-dxbgt kiali]$ curl -X POST http://prometheus-operator-prometheus.prometheus.svc:9090/api/v1/query
{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:1: parse error: no expression found in input"}[kiali@kiali-5fc7bf8969-dxbgt kiali]$ 
```

Operator config;
```
cr:
    create: true
    namespace: kiali
    spec:
        namespaces:
          exclude:
        auth:
          strategy: anonymous
        image_name: docker-registry.prod.williamhill.plc/mirrors/quay.io/kiali
        istio_namespace: istio-system
        external_services:
          prometheus:
            url: http://prometheus-operator-prometheus.prometheus.svc:9090
            component_status:
              app_label: prometheus
              is_core: false 
              namespace: prometheus
        deployment:
          image_version: v1.24.0
          accessible_namespaces:
          - '**'
          view_only_mode: true
          resources:
            requests:
                cpu: 2
                memory: 768Mi
            limits:
                memory: 768Mi
```

**Versions used**
Kiali: 1.24.0
Istio: 1.6.5
Kubernetes flavour and version: EKS 1.17

**Expected behavior**
I would not expect the UI to fail with an error and present it.
