### ISSUE TITLE
kiali pod keeps restarting every 60 seconds

### ISSUE THREAD

**Issue by samene** [kiali/kiali#3251]
I have installed kiali operator v1.23

This is my CR

``` 
deployment:
    image_version: v1.23.0
    namespace: istio-system
    verbose_mode: "1"
    view_only_mode: false
external_services:
    grafana:
      url: ""
    prometheus:
      url: http://prometheus-service.cattle-prometheus.svc:8080
    tracing:
      in_cluster_url: http://simple-prod-query.jaeger-operator.svc:16686
      url: ""
installation_tag: Klerity Kiali
istio_namespace: istio-system
```

After applying the CR, the kiali pods comes up, runs for around a minute and then keeps restarting. They keep restarting forever after that.
I'm attaching the kiali operator logs
