### ISSUE TITLE
Kiali keeps reaching wrong prometheus host

### ISSUE THREAD

**Issue by neolunar7** [kiali/kiali#3255]
**Describe the bug**
I set the Kiali CR using the config below.
```
external_services:
  prometheus:
    url: "http://prometheus.prometheus.svc.cluster.local:9090"
    custom_metrics_url: "http://prometheus.prometheus.svc.cluster.local:9090"
```
However, I get error of 
`Cannot load the graph: Post "http://prometheus.istio-system:9090/api/v1/query": dial tcp: lookup prometheus.istio-system on 172.20.0.10:53: no such host`

**Versions used**
Kiali: v1.24.0
Istio: v1.5.1
Kubernetes flavour and version: 1.15

**To Reproduce**

**Expected behavior**
Expected Kiali to show no error, but keeps showing query error due to wrong prometheus host, though I think I configured it right.
