### ISSUE TITLE
Need of a warning[KIA0302 No matching workload found for gateway selector in this namespace]? 

### ISSUE THREAD

**Issue by abhioncbr** [kiali/kiali#3265]
**General remarks**

I am getting the following warning in Kiali UI, `KIA0302 No matching workload found for gateway selector in this namespace.`
following below are my Ingress & istio Gateway manifests
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: frontend-nodejs-app 
  namespace: istio-system
  name: istio-securegw-nginx-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - istio-securegw-nginx-exmple.aks.com
  rules:
  - host: istio-securegw-nginx-exmple.aks.com
    http:
      paths:
      - backend:
          serviceName: internal-ingressgateway
          servicePort: 443
        path: /  
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-securegw-sample
  name: istio-securegw-sample-gateway
spec:
  selector:
    istio: internal-ingressgateway # use istio default controller
  servers:
  - port:
      number: 8443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: aks-ingress-tls
    hosts:
      - istio-securegw-nginx-exmple.aks.com
```

The warning makes sense since `internal-ingressgateway` is in the `istio-system` namespace, however in my opinion this is always going to be the same in most cases, so does this warning is needed or not? 

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: 1.17.9
Istio: 1.6.5
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) AKS, 1.17.9

**To Reproduce**

**Expected behavior**
