### ISSUE TITLE
Prometheus Not Found and missing expected TS labels

### ISSUE THREAD

**Issue by crhuber** [kiali/kiali#3289]
**Describe the bug**

We have Kiali 1.18.2 and Istio 1.6.8 with Telemetry-v2. I installed Kiali using the 1.24 operator.  When I go to the **Graph** with **workload** selected for a service which currently gets traffic I get the error "Empty Graph"
 
Then in the logs I see:

> kiali-699b659fc8-jv5ss kiali E1005 12:51:56.732727       1 dashboards.go:288] runtimes discovery failed, cannot load metrics for labels: {namespace="istio-demo",app="sampleapp",version="v1"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-10-05T12%3A51%3A54.695225841Z&match%5B%5D=%7Bnamespace%3D%22istio-demo%22%2Capp%3D%22sampleapp%22%2Cversion%3D%22v1%22%7D&start=2020-10-05T11%3A51%3A54.695225841Z": dial tcp: lookup prometheus.istio-system on 169.254.20.10:53: no such host

However I have the prometheus url configured for a different namespace and hostname (see config below). So I don't know why its trying to point to `prometheus.istio-system`

> kiali-699b659fc8-jv5ss kiali W1005 12:51:54.732149       1 istio.go:217] Skipping {destination_app="sampleapp", destination_service="sampleapp.istio-demo.svc.cluster.local", destination_service_name="sampleapp", destination_service_namespace="istio-demo", destination_workload="sampleapp", destination_workload_namespace="istio-demo", response_code="200", response_flags="-", source_app="istio-ingressgateway", source_workload="istio-ingressgateway", source_workload_namespace="istio-system"}, missing expected TS labels.

The same query works on prometheus (see screenshot)
What are the expected TS labels? We have a large Istio deployment and some labels are high cardinality so we cannot include them. Which ones are needed?

Config

```
kind: Kiali
metadata:
  finalizers:
  - finalizer.kiali
  generation: 5
  labels:
    app: kiali-operator
    version: v1.24.0
  name: kiali
  namespace: utility
spec:
  api:
    namespaces:
      label_selector: kiali-enabled=true
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
    - '**'
    image_version: v1.18.2
    replicas: 2
    view_only_mode: true
  external_services:
    grafana:
      enabled: false
    istio:
      component_status:
        enabled: false
    prometheus:
      url: http://istio-prometheus-prometheus.monitoring.svc.cluster.local:9090
    tracing:
      enabled: false
```

For UI issues please also add a screenshot that shows the issue.

![image](https://user-images.githubusercontent.com/5857391/95085855-0dfd8b00-0720-11eb-8cf7-69781bf5fb28.png)

working prom query

![image](https://user-images.githubusercontent.com/5857391/95086634-04285780-0721-11eb-8cc9-a6b5022571ff.png)

**Versions used**
Kiali: v.1.18.2
Istio: 1.6.8
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) : EKS 1.17

**To Reproduce**
1. Install Istio 1.6.8
2. Turn on telemetry-v2
3. Install Kiali 1.18.2

**Expected behavior**

Prometheus is found and service graph is drawn

**Comment by jotak** [comment]
Hi @crhuber ,
First thing, the error you see in the logs is not the cause of not seeing any graph. It's because Kiali has actually 2 urls that can point to distinct prometheus servers, and it seems you didn't change the second one, but it's only for seeing some custom dashboard it will not affect graph display. This second URL can be set up in config map at `external_services.prometheus.custom_metrics_url` , see https://kiali.io/documentation/v1.18/runtimes-monitoring/#_prometheus_configuration)

The second thing is about the prometheus labels that you excluded. I believe what you have excluded are the pod name, pod template hash and instance, right? As they're the ones that greatly increase cardinality. Kiali shouldn't suffer about that, it doesn't require any pod-related label. So, I'm not sure about what could be the cause. Do you mind sharing your rewriting rules?

(Also you might be interested in reading this: https://medium.com/kialiproject/kiali-with-production-scale-prometheus-c53ddfa20570)

**Comment by crhuber** [comment]
@jotak yes thats exactly right about labels excluded. To exclude certain labels I have configured

**Envoy Filter** 
Omits the following labels:

```
destination_canonical_service
source_canonical_service
destination_principal
source_principal
connection_security_policy
grpc_response_status
source_version
destination_version
request_protocol
source_canonical_revision
destination_canonical_revision
```

**Prometheus Scrape**
Drops or renames as such
```

destination_principal (drop)
source_principal (drop)
connection_security_policy (drop)
grpc_response_status (drop)
source_version (drop)
destination_version (drop)
request_protocol (drop)
source_canonical_revision (drop)
destination_canonical_revision (drop)
permissive_response_code (drop)
permissive_response_policyid (drop)
service_istio_io_.* (drop)
security_istio_io_tlsMode (drop)
version (drop)
chart (drop)
group (drop)
heritage (drop)
instance (drop)
pod_template_hash (drop)
pod_name > pod (replace)
__meta_kubernetes_pod_label_ (drop)
__meta_kubernetes_namespace > namespace (replace)
envoy_* (drop)
```



Recording rules look like this:

```
  - name: "istio.requests-total"
    interval: 30s
    rules:
    - record: "workload:istio_requests_total"
      expr: sum(istio_requests_total) without(instance, namespace, pod, pod_template_hash, pod_name)
```
