### ISSUE TITLE
"View in Grafana" link can be wrong

### ISSUE THREAD

**Issue by kjetillilleby** [kiali/kiali#3305]
**Describe the bug**
I use the kiali-operator for installation, and have specified (among other thing)
```yaml
spec:
  external_services:
    grafana:
      url: "/system/grafana"
```
 

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/9693382/95454265-822c6e80-096c-11eb-9c7c-6260f2e67cc7.png)

**Versions used**
Kiali: 1.24
Istio: 1.7
Kubernetes flavour and version: v1.18.6-gke.4801

**To Reproduce**
1. Go to 'Workloads -> Inbound Metrics'
2. Inspect the url on the "View in Grafana" link
3. See error: url starts with `/system/grafana/system/grafana`

**Expected behavior**
url to start with `/system/grafana`
