### ISSUE TITLE
Proxy-status reporting out of sync for all pods

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3318]
I'm not sure what the issue is but it seems that the proxy-status reporting is not working for me.
openshift 4.5
bookinfo
istio 1.7.3
kiali master (1.25+)

![image](https://user-images.githubusercontent.com/2104052/95886450-985f7380-0d4c-11eb-92dd-74f29d62eb55.png)

Every workload/app node reports "0 synced proxy", yet from the CLI:

```
$ _output/istio-1.7.3/bin/istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          ISTIOD                      VERSION
details-v1-558b8b4b76-x9242.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
istio-egressgateway-669785ffb4-sm4kj.istio-system      SYNCED     SYNCED     SYNCED     NOT SENT     istiod-75c5776d98-lcmlm     1.7.3
istio-ingressgateway-76447f8f85-9gg65.istio-system     SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
kiali-traffic-generator-n8pjf.bookinfo                 SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
mongodb-v1-78d87ffc48-88rk9.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
productpage-v1-6987489c74-7g99w.bookinfo               SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
ratings-v1-7dc98c7588-w8cml.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
ratings-v2-86f6d54875-25btb.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
reviews-v1-7f99cc4496-8txf7.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
reviews-v2-7d79d5bd5d-r2wl6.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
reviews-v3-7dbcdcbc56-6686b.bookinfo                   SYNCED     SYNCED     SYNCED     SYNCED       istiod-75c5776d98-lcmlm     1.7.3
```

**Comment by lucasponce** [comment]
Thanks @jshaughn.
I'll take a look as @xeviknal is out this week.

**Comment by lucasponce** [comment]
I'm testing with 1.7.2 and I can't get same result you got.
If you have available this error scenario, would you attach what info is showing the unhealthy pod, like this ?

![image](https://user-images.githubusercontent.com/1662329/95978137-0c1b8200-0e1a-11eb-9c5f-a6140fe64836.png)

Note, I'm going to re-provision my cluster with Istio 1.7.2 in the very edge case that the difference version may be involved on this.

**Comment by jshaughn** [comment]
@lucasponce It is only showing unhealthy in the graph, which is odd.  Look at the minigraph in the detail:

![image](https://user-images.githubusercontent.com/2104052/95987602-a4ebd680-0df5-11eb-95a5-77db19e0ee70.png)

**Comment by lucasponce** [comment]
> @lucasponce It is only showing unhealthy in the graph, which is odd. Look at the minigraph in the detail:

Ah, ok, that's a clue, perhaps if I can access to your environment I can get more info to reproduce this locally.

But I think I have a suspect.

**Comment by JuanSeBestia** [comment]
I have the same issue for me, also I'm using anonym user in gke, maybe I should try with token auth to see if change

Kiali UI 1.26.0 (35e2d8b075bd5c4bcc3f315aef9e6144aad0b608)
Kiali Server v1.26.1 (0cf243d730d45cd16e254e2c8d4d2a0ac0cf5222)
Kiali Container v1.26.1
Components
Istio 1.7.4
Prometheus 2.18.2
Kubernetes v1.17.12-gke.1504

**Comment by xeviknal** [comment]
Hello @JuanSeBestia!
Adding you a couple of questions for me better understand which point are you at.

- Could you tell me how did you install kiali? In case you recently updated it, which method did you follow?
- Do you mind pasting your kiali clusterrole? `kubectl get clusterrole -n istio-system kiali -o yaml`
- Could you please share with us the logs of kiali?

Let's try with this intuition: there has been a change in the kiali permissions at pod level. Therefore, in the case of updating the kiali version just changing the image version number, it won't work. You'd need to re-install kiali to give those permissions.

Let me know, thx

**Comment by JuanSeBestia** [comment]
@xeviknal thanks for your suggestion :)
Let me work on another task to move into this (maybe tomorrow).

**Comment by JuanSeBestia** [comment]
@xeviknal 

1. Installation
```yaml
# kiali-operator
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-operator
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: kiali-operator
  forceUpgrade: false
  chart:
    repository: https://kiali.org/helm-charts
    name: kiali-operator
    version: "1.24.0" 
  values:
    metrics:
      enabled: true
    debug:
      enabled: true
      verbosity: "1"

    watchNamespace: ""
    clusterRoleCreator: true
    onlyViewOnlyMode: false
    cr:
      create: false
```

``` yaml
#kiali-cr
## Extracted from https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  deployment:
    accessible_namespaces:
      - '**'
  auth:
    strategy: "anonymous"
  istio_component_namespaces:
    prometheus: observability
    tracing: observability
    grafana: observability
  istio_namespace: istio-system
  external_services:
    # jeager
    tracing:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      component_status:
        app_label: "jaeger"
        is_core: true
        namespace: "observability"
      enabled: true
      in_cluster_url: "http://jaeger-query.observability:16686"
      namespace_selector: true
      # FIXME: put correct url
      url: "http://my-jaeger-portforward-UI"
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway"]
    prometheus:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      component_status:
        app_label: prometheus
        is_core: true
        namespace: 'observability'
      url: http://kps-prometheus.observability:9090
      custom_metrics_url: http://kps-prometheus.observability:9090
    grafana:
      auth:
        ca_file: ''
        component_status:
          app_label: grafana
          is_core: true
          namespace: ''
        insecure_skip_verify: false
        username: 'juanse@juanse.dev'
        password: 'secret:grafana-auth-secret:admin-password'
        token: ''
        type: basic
        use_kiali_token: false
      dashboards:
      - name: Istio Service Dashboard
        variables:
          namespace: var-namespace
          service: var-service
      - name: Istio Workload Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
      - name: Kubernetes / API server
        variables:
          var-datasource: default
          var-cluster : "" 
          var-instance : "All"
      enabled: true
      in_cluster_url: http://prometheus-grafana.observability:80
      # FIXME: put correct url
      url: 'http://my-grafa-porforward:3000'
```

2. Role

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    operator-sdk/primary-resource: observability/kiali
    operator-sdk/primary-resource-type: Kiali.kiali.io
  creationTimestamp: "2020-11-12T15:12:32Z"
  labels:
    app: kiali
    version: v1.26.1
  name: kiali
  resourceVersion: "9339"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kiali
  uid: bbe8911c-b4ae-4064-b94a-eeaa9d81e691
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - namespaces
  - nodes
  - pods
  - pods/log
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - config.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - monitoring.kiali.io
  resources:
  - monitoringdashboards
  verbs:
  - get
  - list
- apiGroups:
  - iter8.tools
  resources:
  - experiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
```
3. relevant log

``` log
W1112 16:44:53.508720       1 workloads.go:1257] GetPodProxyStatus is failing for [namespace: bio4n-dev] [pod: redis-master-0]: unknown (get pods istiod-5d4798c786-bwshj) 
W1112 16:44:53.799185       1 workloads.go:1257] GetPodProxyStatus is failing for [namespace: bio4n-dev] [pod: redis-master-0]: unknown (get pods istiod-5d4798c786-bwshj) 
```

**Comment by JuanSeBestia** [comment]
@xeviknal in this installation, I created a new cluster with these resources, so the issue with the update would not happen.

I will change to token auth and then updating the version of kiali

**Comment by JuanSeBestia** [comment]
I change to token accesss and not work

**Comment by JuanSeBestia** [comment]
I update the kiali-operator from 1.24.0 -> 1.26.1 with auth:anonymous 

Now it works  🎉

**Comment by xeviknal** [comment]
`I update the kiali-operator from 1.24.0 -> 1.26.1 with auth:anonymous`
Here's the point. Using a different operator version than the kiali version might lead to problems like this one.

Glad it is working for you! Don't hesitate to reach us whenever you have a problem!

**Comment by HazemElAgaty** [comment]
I started noticing the same behaviour when I updated kiali + operator to v1.27.0.

**Kiali Operator Helmfile**
I am using `kiali/kiali-operator` helm chart `v1.27.0`

```yaml
    name: kiali-operator
    namespace: kiali-operator
    chart: kiali/kiali-operator
    version: 1.27.0
    values:
      - cr:
          create: false
          namespace: istio-system
```
**Kiali CR**
The `auth.strategy` is set to `token` by default.

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  deployment:
    namespace: kiali-operator
  external_services:
    prometheus:
      url: http://prometheus-chart-server.monitoring.svc.cluster.local
    istio_namespace: istio-system
```

Any idea what might be causing this in my case?
