### ISSUE TITLE
Kiali reported missing sidecar but did not

### ISSUE THREAD

**Issue by wutz** [kiali/kiali#3320]
**General remarks**

The app works fine with istio, but kiali shows the missing sidecar.

**Describe the bug**

![image](https://user-images.githubusercontent.com/9458625/95978721-228f0100-0e4d-11eb-97d6-c9c306fc144c.png)

**Versions used**
Kiali: 1.25.0
Istio: 1.7.3
Kubernetes flavour and version: v1.16.9

**To Reproduce**
I don’t log in often to check kiali. Today, I found that kiali shows the missing sidecar, but I visit to check istio and application its work correct.

**Expected behavior**
Details display empty

**Comment by jshaughn** [comment]
It is possible for the app to work correctly but not have a sidecar, it would mean those workloads are not in the mesh.  Of course there could be an issue with sidecar detection.  Can you click on those workloads an in the workload detail, in the pods tab at the bottom, you should be able to see whether ot not the istio containers are listed.  If they are not there then perhaps you reqally are missing the sidecar proxy containers.

**Comment by wutz** [comment]
![image](https://user-images.githubusercontent.com/9458625/95989351-bcaa7580-0e5c-11eb-8ca8-e5b95220af18.png)
![image](https://user-images.githubusercontent.com/9458625/95989502-f11e3180-0e5c-11eb-9b05-b63c16807087.png)

**Comment by wutz** [comment]
![Uploading image.png…]()

**Comment by jshaughn** [comment]
@wutz Thanks, that's pretty strange.  cc @lucasponce

**Comment by lucasponce** [comment]
@wutz mmm how did you inject the sidecar ?

**Comment by wutz** [comment]
@lucasponce I set label `istio-injection=enabled` on the namespace

![image](https://user-images.githubusercontent.com/9458625/96060424-0a59c900-0ec3-11eb-8917-bd7952284c9e.png)

**Comment by wutz** [comment]
@lucasponce It's true when i edit pod with annotation `sidecar.istio.io/status`, kiali reported missing sidecar go away.

**Comment by wutz** [comment]
I manually add `sidecar.istio.io/status` to the pod, then kiali can detect sidecar.

![image](https://user-images.githubusercontent.com/9458625/96067803-1f3b5a00-0ecd-11eb-802f-e6679b051d8c.png)

**Comment by lucasponce** [comment]
Thanks for confirming @wutz.

I'll take the issue to review that check in Kiali as you point, there are scenarios where workloads have not that annotation and should be detected as well.

**Comment by lucasponce** [comment]
I'm investigating, not having a "sidecar.istio.io/status" annotation in the Pod might be a symptom of a problem.
Looking into the specification [1] and code [2][3] it seems that annotation sould be added as part of the process to patch the Pod.

@wut would you mind to paste the full Deployment (controller) and Pod (runtime) description ?
Do you reproduce this always ? Or does it happen only on some scenarios ?

If a missing status annotation is a un healthy scenario I'm thinking that perhaps Kiali can add a better description but keep the message to force user to investigate.

[1] https://istio.io/latest/docs/reference/config/annotations/
[2] https://github.com/istio/istio/blob/19581dd056db5a56ef7957e3bb3dcf3075ee18d5/pkg/kube/inject/webhook.go#L731
[3] https://github.com/istio/istio/blob/19581dd056db5a56ef7957e3bb3dcf3075ee18d5/pkg/kube/inject/webhook.go#L809

**Comment by wutz** [comment]
[pod.txt](https://github.com/kiali/kiali/files/5385251/pod.txt)
[deployment.txt](https://github.com/kiali/kiali/files/5385254/deployment.txt)

All deployment with istio injection have same issue in my cluster, and its always happen.

**Comment by lucasponce** [comment]
Ah @wutz is there some change in the standard admission webhook ? 

```
lxcfs-admission-webhook.aliyun.com/status: mutated
```

Is it possible that there is webhook in the chain that is overwriting the Istio annotations ?

**Comment by wutz** [comment]
I disable `lxcfs-admission-webhook.aliyun.com/status` label on the namespace, and restart deployment, then get pod details which have annotations `sidecar.istio.io/status`

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2020-10-15T21:55:27+08:00"
    kubernetes.io/psp: ack.privileged
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/status: '{"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istiod-ca-cert"],"imagePullSecrets":null}'
  creationTimestamp: "2020-10-15T13:56:04Z"
  generateName: appintegration-v1-744f7f5c4c-
```

Thanks for you support, i wiil report a bug to lxcfs-admission-webhook project.
