### ISSUE TITLE
[error Prometheus] Could not fetch Health.

### ISSUE THREAD

**Issue by JuanSeBestia** [kiali/kiali#3366]
**Describe the bug**

In all the workloads the same thing appears "Could not fetch Health."

![Screen Shot 2020-10-28 at 8 59 05 AM](https://user-images.githubusercontent.com/7362688/97446395-57df2880-18fc-11eb-8731-8cfd1b896b9d.png)

Recently migrated from istio 1.6 addons installation to istio 1.6 + KialiOperator + kube-prometheus-stack

I'm not sure if I have a configuration error or something bad is happening, can you help me diagnose the problem please.

I will add as much as I can about the problem

**Versions used**

Kiali Operator: v1.25.0
Kiali UI 1.25.0 (6646d8b248dad2f8aea0fcd915085065f25f2776)
Kiali Server v1.25.0 (275a5cba051ed25677a513706cd9eff36dc58d78)
Kiali Container v1.25.0
Components
Istio 1.6.8
Prometheus 2.18.2
Kubernetes v1.17.12-gke.1504

**To Reproduce**
1. Go to 'workloads'
2. Click on 'productpage-v1' (of bookinfo deployment)
3. See error

**Expected behavior**
See the graph and some metrics

NOTE: I will attach config bellow

**Comment by lucasponce** [comment]
Would you mind to see / attach the Kiali logs ?

**Comment by JuanSeBestia** [comment]
Kiali and Prometheus 
```
# kiali-operator-release.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-operator
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: kiali-operator
  forceUpgrade: false
  chart:
    repository: https://kiali.org/helm-charts
    name: kiali-operator
    version: "1.24.0" 
  values:
    metrics:
      enabled: true

    debug:
      enabled: true
      verbosity: "1"
    watchNamespace: ""
    clusterRoleCreator: true
    onlyViewOnlyMode: false
    cr:
      create: false
---
# kiali-cr.yaml
## Extracted from https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  deployment:
    accessible_namespaces:
      - '**'
  auth:
    strategy: "anonymous"
  istio_component_namespaces:
    prometheus: observability
    tracing: observability
    grafana: observability
  istio_namespace: istio-system
  external_services:
    # jeager
    tracing:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      component_status:
        app_label: "jaeger"
        is_core: true
        namespace: "observability"
      enabled: true
      in_cluster_url: "http://jaeger-query.observability:16686"
      namespace_selector: true
      # FIXME: put correct url
      url: "http://my-jaeger-portforward-UI"
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway"]
    prometheus:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      component_status:
        app_label: prometheus
        is_core: true
        namespace: 'observability'
      url: http://prometheus-kube-prometheus-prometheus.observability:9090
      custom_metrics_url: http://prometheus-kube-prometheus-prometheus.observability:9090
    grafana:
      auth:
        ca_file: ''
        component_status:
          app_label: grafana
          is_core: true
          namespace: ''
        insecure_skip_verify: false
        username: 'someuser@yopmail.com'
        password: 'secret:grafana-auth-secret:admin-password'
        token: ''
        type: basic
        use_kiali_token: false
      dashboards:
      - name: Istio Service Dashboard
        variables:
          namespace: var-namespace
          service: var-service
      - name: Istio Workload Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
      - name: Kubernetes / API server
        variables:
          var-datasource: default
          var-cluster : "" 
          var-instance : "All"
      enabled: true
      in_cluster_url: http://prometheus-grafana.observability:80
      # FIXME: put correct url
      url: 'http://my-grafa-porforward:3000'
---
## Prometheus-grafana Config
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  name: app-prometheus-ssd
parameters:
  fstype: ext4
  replication-type: none
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ConfigMap
# data: some data
metadata:
  labels:
    grafana_dashboard: "1"
  name: cm-controlplane-dashboard
---
apiVersion: v1
kind: ConfigMap
# data: some data
metadata:
  labels:
    grafana_dashboard: "1"
  name: cm-mesh-dashboard
---
apiVersion: v1
kind: ConfigMap
# data: some data
metadata:
  labels:
    grafana_dashboard: "1"
  name: cm-performance-dashboard
---
apiVersion: v1
kind: ConfigMap
# data: some data
metadata:
  labels:
    grafana_dashboard: "1"
  name: cm-service-dashboard
---
apiVersion: v1
# data: some data
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: cm-workload-dashboard
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: prometheus
spec:
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 9.4.4
  forceUpgrade: false
  releaseName: prometheus
  values:
    alertmanager:
      enabled: false
    grafana:
      admin:
        existingSecret: grafana-auth-secret
      defaultDashboardsEnabled: true
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    nodeExporter:
      enabled: false
    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 2
        resources:
          requests:
            memory: 400Mi
        retention: 4d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
              storageClassName: app-prometheus-ssd
    prometheusOperator:
      admissionWebhooks:
        enabled: false
        patch:
          enabled: false
      tlsProxy:
        enabled: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: prometheus-oper-istio-controlplane
spec:
  endpoints:
  - interval: 15s
    port: http-monitoring
  - interval: 15s
    port: http-policy-monitoring
  jobLabel: istio
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
    - key: istio
      operator: In
      values:
      - mixer
      - pilot
      - galley
      - citadel
      - sidecar-injector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: istio-dataplane
    release: prometheus
  name: prometheus-oper-istio-dataplane
spec:
  endpoints:
  - interval: 15s
    path: /stats/prometheus
    relabelings:
    - action: keep
      regex: .*-envoy-prom
      sourceLabels:
      - __meta_kubernetes_pod_container_port_name
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod_name
    targetPort: http-envoy-prom
  jobLabel: envoy-stats
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
    - key: istio-prometheus-ignore
      operator: DoesNotExist
```

**Comment by JuanSeBestia** [comment]
@lucasponce sure!

Attaching logs of pod kiali 
[kiali.log](https://github.com/kiali/kiali/files/5452455/kiali.log)

**Comment by JuanSeBestia** [comment]
Also attach debug info:
Health Config
``` JSON
{
  "healthConfig": {
    "rate": [
      {
        "namespace": "/.*/",
        "kind": "/.*/",
        "name": "/.*/",
        "tolerance": [
          {
            "code": "/^5\\d\\d$/",
            "degraded": 0,
            "failure": 10,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/^4\\d\\d$/",
            "degraded": 10,
            "failure": 20,
            "protocol": "/http/",
            "direction": "/.*/"
          },
          {
            "code": "/^[1-9]$|^1[0-6]$/",
            "degraded": 0,
            "failure": 10,
            "protocol": "/grpc/",
            "direction": "/.*/"
          },
          {
            "code": "/^-$/",
            "degraded": 0,
            "failure": 10,
            "protocol": "/http|grpc/",
            "direction": "/.*/"
          }
        ]
      }
    ]
  }
}
```
Please include this information when opening a bug.
``` JSON
{
  "backendConfigs": {
    "authenticationConfig": {
      "strategy": "anonymous"
    },
    "computedServerConfig": {
      "extensions": {
        "threescale": {
          "adapterName": "threescale",
          "adapterPort": "3333",
          "adapterService": "threescale-istio-adapter",
          "enabled": false,
          "templateName": "threescale-authorization"
        },
        "iter8": {
          "enabled": false,
          "namespace": "iter8"
        }
      },
      "healthConfig": {
        "rate": [
          {
            "namespace": "/.*/",
            "kind": "/.*/",
            "name": "/.*/",
            "tolerance": [
              {
                "code": "/^5\\d\\d$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/^4\\d\\d$/",
                "degraded": 10,
                "failure": 20,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/^[1-9]$|^1[0-6]$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/grpc/",
                "direction": "/.*/"
              },
              {
                "code": "/^-$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http|grpc/",
                "direction": "/.*/"
              }
            ]
          }
        ]
      },
      "istioAnnotations": {
        "istioInjectionAnnotation": "sidecar.istio.io/inject"
      },
      "istioStatusEnabled": true,
      "istioIdentityDomain": "svc.cluster.local",
      "istioNamespace": "istio-system",
      "istioComponentNamespaces": {
        "grafana": "observability",
        "istiod": "istio-system",
        "pilot": "istio-system",
        "prometheus": "observability",
        "tracing": "observability"
      },
      "istioLabels": {
        "appLabelName": "app",
        "injectionLabelName": "istio-injection",
        "versionLabelName": "version"
      },
      "istioTelemetryV2": true,
      "istioConfigMap": "istio",
      "kialiFeatureFlags": {
        "istioInjectionAction": true
      },
      "prometheus": {
        "globalScrapeInterval": 30
      },
      "durations": {
        "60": "1m",
        "300": "5m",
        "600": "10m",
        "1800": "30m",
        "3600": "1h",
        "10800": "3h",
        "21600": "6h",
        "43200": "12h",
        "86400": "1d",
        "604800": "7d",
        "2592000": "30d"
      }
    }
  },
  "currentURL": "http://localhost:20001/kiali/console/namespaces/bio4n-dev/workloads/productpage-v1?duration=600&refresh=60000",
  "reduxState": {
    "authentication": {
      "message": "",
      "session": {
        "username": null,
        "expiresOn": "2020-10-29T13:58:21.178Z"
      },
      "status": 1,
      "uiExpiresOn": "2020-10-29T13:58:21.178Z"
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true,
      "lastRefreshAt": 1603895121727
    },
    "graph": {
      "graphDefinition": null,
      "layout": {
        "name": "cola",
        "animate": false,
        "fit": false,
        "flow": {
          "axis": "x"
        },
        "nodeDimensionsIncludeLabels": true,
        "randomize": false
      },
      "summaryData": null,
      "toolbarState": {
        "compressOnHide": true,
        "edgeLabelMode": "noEdgeLabels",
        "findValue": "",
        "graphType": "versionedApp",
        "hideValue": "",
        "showCircuitBreakers": true,
        "showFindHelp": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showNodeLabels": true,
        "showOperationNodes": false,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": false,
        "showUnusedNodes": false,
        "showVirtualServices": true
      },
      "updateTime": 0
    },
    "messageCenter": {
      "nextId": 28,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [
            {
              "id": 27,
              "content": "Could not fetch Health.",
              "detail": "",
              "type": "error",
              "count": 28,
              "show_notification": false,
              "seen": false,
              "created": "2020-10-28T14:25:24.743Z",
              "showDetail": false,
              "firstTriggered": "2020-10-28T13:58:26.230Z"
            }
          ],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": false,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "bio4n-dev"
        }
      ],
      "isFetching": false,
      "items": [],
      "filter": ""
    },
    "statusState": {
      "status": {
        "Kiali console version": "1.25.0",
        "Kiali container version": "v1.25.0",
        "Kiali core commit hash": "275a5cba051ed25677a513706cd9eff36dc58d78",
        "Kiali core version": "v1.25.0",
        "Kiali state": "running"
      },
      "components": [
        {
          "name": "Istio",
          "version": "1.6.8"
        },
        {
          "name": "Prometheus",
          "version": "2.18.2"
        },
        {
          "name": "Kubernetes",
          "version": "v1.17.12-gke.1504"
        },
        {
          "name": "Grafana",
          "url": "http://my-grafa-porforward:3000"
        },
        {
          "name": "Jaeger",
          "url": "http://my-jaeger-portforward-UI"
        }
      ],
      "warningMessages": []
    },
    "userSettings": {
      "duration": 600,
      "interface": {
        "navCollapse": false
      },
      "refreshInterval": 60000,
      "replayActive": false,
      "replayQueryTime": 0,
      "replayWindow": {
        "interval": 0,
        "startTime": 0
      }
    },
    "jaegerState": {
      "enabled": true,
      "integration": true,
      "url": "",
      "namespaceSelector": true,
      "whiteListIstioSystem": [
        "jaeger-query",
        "istio-ingressgateway"
      ],
      "info": {
        "enabled": true,
        "integration": true,
        "url": "http://my-jaeger-portforward-UI",
        "namespaceSelector": true,
        "whiteListIstioSystem": [
          "jaeger-query",
          "istio-ingressgateway"
        ]
      }
    },
    "meshTLSStatus": {
      "status": "MTLS_NOT_ENABLED"
    },
    "istioStatus": [
      {
        "name": "istio-egressgateway",
        "status": "NotFound",
        "is_core": false
      },
      {
        "name": "grafana",
        "status": "NotFound",
        "is_core": false
      }
    ],
    "tourState": {},
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}
```

**Comment by lucasponce** [comment]
The kiali.log sounds familiar to this issue https://github.com/kiali/kiali/issues/3318
It seems you are using an old operator to install Kiali 1.25 and there are missing API in the roles.

**Comment by JuanSeBestia** [comment]
Okay, I will try change kiali-operator to 1.25

**Comment by lucasponce** [comment]
> Okay, I will try change kiali-operator to 1.25

Let me know if it works ! Gracias !

**Comment by JuanSeBestia** [comment]
@lucasponce I already made the modification, but it doesn't work :(, thanks for propose it

**Comment by lucasponce** [comment]
@JuanSeBestia ouch, thanks for testing, and sorry it didn't work.

Let me help to investigate if there is anything more, can you confirm that you are experimenting this problem:

https://github.com/kiali/kiali/issues/3318#issuecomment-708465857

I mean, to test from a pod that there is a missing api in the role.

**Comment by JuanSeBestia** [comment]
Okay, I will test without Anonymus auth

**Comment by JuanSeBestia** [comment]
Finally, I found my bug
In parallel, I update Istio to 1.7.4, but doesn't work, then installed the Prometheus with [addons/prometheus.yaml](https://github.com/istio/istio/blob/1.7.0/samples/addons/prometheus.yaml) and works!, so I realize that the error is in my Prometheus config in special te ServiceMonitor [addons/extras/prometheus-operator.yaml#L4](https://github.com/istio/istio/blob/1.7.0/samples/addons/extras/prometheus-operator.yaml#L4), I used the Prometheus UI/ Service discovery and see that the config of ServiceMonitor does not filter any target :(.

Finally I can't fix the ServiceMonitor, so I decided to put the config directly on Prometheus definition. Is not too elegant but work. maybe if the service and pods would have a particular label ServiceMonitor would be work.

I share my config if it is helpful for other people

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  forceUpgrade: false
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: "9.4.4"
  # info https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/ 
  values:
    nameOverride: "kps"
    fullnameOverride: "kps"
    prometheusOperator:
      admissionWebhooks:
        enabled: false
        patch:
          enabled: false
      tlsProxy:
        enabled: false
    nodeExporter:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      replicas: 1
      defaultDashboardsEnabled: true
      grafana.ini:
      ## grafana Authentication can be enabled with the following values on grafana.ini
      # server:
            # The full public facing url you use in browser, used for redirects and emails
      #    root_url:
      ## LDAP Authentication can be enabled with the following values on grafana.ini
      ## NOTE: Grafana will fail to start if the value for ldap.toml is invalid
        auth.ldap:
          enabled: true
          allow_sign_up: true
          config_file: /etc/grafana/ldap.toml
      admin:
        existingSecret: grafana-auth-secret
      sidecar:
        datasources:
          enabled: true
      ldap:
        enabled: true
        existingSecret: grafana-ldap 
      resources: 
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    prometheus:
      enabled: true
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retention: 4d
        replicas: 2
        resources: 
          requests:
            cpu: 200m
            memory: 400Mi
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: bio4n-prometheus-ssd
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        additionalScrapeConfigs:
          - job_name: prometheus
            static_configs:
            - targets:
              - localhost:9090
          - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            job_name: kubernetes-apiservers
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - action: keep
              regex: default;kubernetes;https
              source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            job_name: kubernetes-nodes
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics
              source_labels:
              - __meta_kubernetes_node_name
              target_label: __metrics_path__
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            job_name: kubernetes-nodes-cadvisor
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              source_labels:
              - __meta_kubernetes_node_name
              target_label: __metrics_path__
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          - job_name: kubernetes-service-endpoints
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape
            - action: replace
              regex: (https?)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_service_name
              target_label: kubernetes_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: kubernetes_node
          - job_name: kubernetes-service-endpoints-slow
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
            - action: replace
              regex: (https?)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_service_name
              target_label: kubernetes_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: kubernetes_node
            scrape_interval: 5m
            scrape_timeout: 30s
          - honor_labels: true
            job_name: prometheus-pushgateway
            kubernetes_sd_configs:
            - role: service
            relabel_configs:
            - action: keep
              regex: pushgateway
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_probe
          - job_name: kubernetes-services
            kubernetes_sd_configs:
            - role: service
            metrics_path: /probe
            params:
              module:
              - http_2xx
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_probe
            - source_labels:
              - __address__
              target_label: __param_target
            - replacement: blackbox
              target_label: __address__
            - source_labels:
              - __param_target
              target_label: instance
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: kubernetes_name
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: kubernetes_pod_name
          - job_name: kubernetes-pods-slow
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: kubernetes_pod_name
          
```
