### ISSUE TITLE
provide some UI defaults within the Kiali CR

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3371]
Consider adding a section to the Kiali CR to define UI-specific defaults. Something like this might be useful:

```
spec:
  ui:
    duration_default: "5m"
    refresh_period_default: "30s"
    ... and any other defaults we can think of...
```

Perhaps we can put this under "kiali_feature_flags" (just a thought):

```
spec:
  kiali_feature_flags:
    ui_defaults:
      duration: "5m"
      refresh_period: "30s"
      ...

```
The server can provide an API endpoint similar to the `/config` endpoint (if not part of the json that /config itself returns). The UI can call this at startup to obtain defaults that it will then use. We already do this kind of things for kiali_feature_flags and the health config.

This could be useful for folks that have very large meshes and want the UI to default to a duration of, for example, 5m, refresh every 1m (rather than the default which "last 1m" and "every 15s").
