### ISSUE TITLE
Issue integrating with existing jaeger

### ISSUE THREAD

**Issue by ediezh** [kiali/kiali#3426]
**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to 
>       [Kiali-users](https://groups.google.com/forum/#!forum/kiali-users) mailing list.
>
> For general Kiali-development questions refer to 
>       [Kiali-dev](https://groups.google.com/forum/#!forum/kiali-dev) mailing list.
>
> If you want to propose an enhancement or feature request, please use the feature request template.

**Describe the bug**
Kiali failed to fetch trace from external Jaeger.

<img width="484" alt="Screen Shot 2020-11-12 at 4 48 47 pm" src="https://user-images.githubusercontent.com/15918714/98901041-21fa9080-2507-11eb-81cf-31adb5649aa6.png">

**Versions used**
Kiali: 1.26
Istio: 1.70
Kubernetes flavour and version: EKS 1.16

**To Reproduce**
1. Configure jaeger service in the Kiali configmap like below
```
external_services:
  tracing:
    url: https://jaeger.example.com
    in_cluster_url: http://jaeger-operator-jaeger-query.observability
```
2. Go to the Kiali console
3. View Tracing for a selected service

**Expected behavior**
Expect Kiali to fetch tracing correctly.

**Comment by jshaughn** [comment]
@ediezh has this been resolved in any way?

**Comment by JuanSeBestia** [comment]
I have kiali-cr configured with the following values, it works as expected on Tracing, @ediezh test putting the exact port or using the configuration for namesapace
``` yaml
## Extracted from https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  deployment:
    image_version: 'operator_version'
    accessible_namespaces:
      - '**'
  auth:
    strategy: "anonymous"
  istio_component_namespaces:
    prometheus: observability
    tracing: observability
    grafana: observability
  istio_namespace: istio-system
  external_services:
    # jeager
    tracing:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      component_status:
        app_label: "jaeger"
        is_core: true
        namespace: "observability"
      enabled: true
      in_cluster_url: "http://jaeger-query.observability:16686"
      namespace_selector: true
      url: "http://my-jaeger-UI"
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway"]
 ...
```
