### ISSUE TITLE
Ability to set https_proxy on Kiali instances spawned by the operator

### ISSUE THREAD

**Issue by eperdeme** [kiali/kiali#3451]
**Describe the bug**
My Kiali instance has no direct internet access and so must send any request destined for the internet via proxy servers.
When enabling OIDC Kiali needs to fetch information from the OIDC provider such as .well-known/openid-configuration

I can not find a way to specify a proxy server to use for kiali. I can set ENVs for the operator pod via the helm chart, but I don't see a way in the CR to set ENV variables for the kiali pod. Also another user advises that even with https_proxy env vars Kiali for OIDC retrieval does not honour the env var.

**Versions used**
Kiali: v1.24.0
Istio: 1.7.3
Kubernetes flavour and version: EKS 1.17

**To Reproduce**

```
--- 
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: oidc-kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec: 
  auth:
    strategy: openid
    openid:
      client_id: "test-dev-kiali"
      disable_rbac: true
      issuer_uri: "https://sso.dev.mycorp.com"
  deployment: 
    accessible_namespaces: 
      - "**"
    image_version: v1.24.0
    resources: 
      limits: 
        memory: 768Mi
      requests: 
        cpu: 2
        memory: 768Mi
    view_only_mode: true
  external_services: 
    prometheus: 
      component_status: 
        app_label: prometheus-operator
        namespace: prometheus
      url: "http://kube-prometheus-prometheus.prometheus.svc:9090"
  image_name: docker-registry.prod.mycorp.plc/mirrors/quay.io/kiali
  istio_namespace: istio-system
  namespaces: 
    exclude:
```

Browser error;
```
{"error":"Error fetching OpenID provider metadata.","detail":"Get \"https://sso.dev.mycorp.com/.well-known/openid-configuration\": EOF"}
```

**Expected behavior**
Kiali uses a proxy to retrieve content. I guess this could either be done via specifying the ENV vars and Kiali consuming them (http_proxy, https_proxy, no_proxy), or explicitly having a kv in the spec to set one (similar to how prometheus works when setting proxys function.

```
spec: 
  auth:
    strategy: openid
    openid:
      client_id: "mycorp-dev-kiali"
      https_proxy: mycorp.proxy:3128
```
