### ISSUE TITLE
[operator] analyze performance of the operator and see if we can speed it up

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3469]
The Kiali Operator is implemented in Ansible. Ansible operators are, by their very nature, slower than Go-based operators. However, we should examine the Ansible playbooks and see if there are ways in which we can refactor them in order to speed up the operator so its reconciliation loops are faster.

**Comment by jmazzitelli** [comment]
Presentation on performance evaluation between Ansible vs. Go operators: https://developers.redhat.com/ansiblefest/2020/operators-by-the-numbers

**Comment by jmazzitelli** [comment]
Note that some folks are looking into using a 'turbo' module that caches the k8s connection between tasks that is already proving to be at least 50-70% faster if you do a lot of tasks interacting with the API. See ongoing testing here: https://github.com/ansible-collections/community.kubernetes/pull/270

**Comment by jmazzitelli** [comment]
Here's how you can turn on a profiler. In the Dockerfile, add this at the end:

```
RUN cp /etc/ansible/ansible.cfg ${HOME}/.ansible.cfg && echo "callback_whitelist = profile_tasks" >> ${HOME}/.ansible.cfg
```

Now just install a Kiali CR. Here's the first run I did (this is on minikube) - notice how horribly long it takes to create all the monitoring dashboards! We do already provide [a way to limit which ones are installed](https://github.com/kiali/kiali-operator/blob/v1.27.0/deploy/kiali/kiali_cr.yaml#L192-L203) or to [completely disable them](https://github.com/kiali/kiali-operator/blob/v1.27.0/deploy/kiali/kiali_cr.yaml#L387-L397). So that could be a workaround for people.

```
default/kiali-deploy : Create the Monitoring Dashboards ---------------- 25.31s
default/kiali-deploy : Get information about the operator --------------- 2.11s
Run the version-specific deploy role ------------------------------------ 1.78s
default/kiali-deploy : Create resource [serviceaccount] on [kubernetes] --- 1.70s
default/kiali-deploy : operator_sdk.util.k8s_status --------------------- 1.53s
default/kiali-deploy : Create resource [deployment] on [kubernetes] ----- 1.46s
default/kiali-deploy : Create resource [configmap] on [kubernetes] ------ 1.35s
default/kiali-deploy : Create resource [service] on [kubernetes] -------- 1.33s
default/kiali-deploy : Create resource [ingress] on [kubernetes] -------- 1.32s
default/kiali-deploy : Create resource [rolebinding] on [kubernetes] ---- 1.29s
default/kiali-deploy : Create resource [role] on [kubernetes] ----------- 1.20s
default/kiali-deploy : Get information about any existing signing key secret if we need to know if it exists or not --- 1.19s
default/kiali-deploy : Wait for Monitoring Dashboards CRD to be ready --- 1.18s
default/kiali-deploy : set_fact ----------------------------------------- 1.11s
default/kiali-deploy : Check for the existence of istiod version endpoint --- 1.04s
default/kiali-deploy : set_fact ----------------------------------------- 0.99s
default/kiali-deploy : Find all Monitoring Dashboards packaged with the operator --- 0.93s
default/kiali-deploy : Find current configmap, if it exists ------------- 0.60s
default/kiali-deploy : Find current deployment, if it exists ------------ 0.57s
default/kiali-deploy : Determine which Monitoring Dashboards are to be created --- 0.53s
```

**Comment by jmazzitelli** [comment]
This profiler could be very helpful. I think I'm going to add something to the operator such that an admin can tweek something to turn it on. We want this off by default I think, but it would be nice if we could relatively easily enable this.

**Comment by jmazzitelli** [comment]
I ran it a second time to see if I get the same results and I do. This second time, the entire playbook takes 65 seconds, with the "Create the Monitoring Dashboards" task itself taking 26s - that's 40% of the time solely to create monitoring dashboards that most people don't even use (they certainly don't use the vast majority of those dashboards).

I think as a quick fix, we should change the default to disable most if not all of these dashboards.

**Comment by FilipB** [comment]
I have following scenario:
1. 30 bookinfo applications all monitored by kiali (all listed in spec.deployment.accessible_namespaces)
2. remove one bookinfo app from spec.deployment.accessible_namespaces

It took ~14 minutes for the reconciliation to finish.
From operator logs it's visible that one cycle is not that bad (took 268 seconds) but this cycle is repeated 3 times for some reason.
So in total 3 cycles for removal of one namespace from accessible_namespaces: 273+268+268=809  which is ~ 14 minutes.

Here is debug info from last cycle (note that it did not print more lines but there are more namespaces in the accessible_namespaces):
```
Friday 27 November 2020  13:26:13 +0000 (0:00:00.022)       0:04:28.715 ******* 
=============================================================================== 
default/kiali-deploy : Determine all accessible namespaces, expanding regex expressions to matched namespaces -- 24.98s
default/kiali-deploy : Create the Monitoring Dashboards ---------------- 15.87s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-4] --- 2.79s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch2-4] --- 2.70s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-11] --- 2.65s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-18] --- 2.52s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-1] --- 2.52s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-20] --- 2.50s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch2-8] --- 2.49s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-12] --- 2.48s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch2-1] --- 2.47s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [istio-system] --- 2.46s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch2-7] --- 2.46s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-3] --- 2.45s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch2-3] --- 2.44s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-15] --- 2.44s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-16] --- 2.43s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [default] --- 2.42s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-13] --- 2.42s
default/kiali-deploy : Create additional Kiali roles in [openshift] namespace [bookinfo-batch1-10] --- 2.41s

```

Also note that all 3 cycles are actually doing something as the CPU consumption rise of the
 kiali operator pod exactly matches that 14 minutes window.

Operator log - [op-log.tar.gz](https://github.com/kiali/kiali/files/5608100/op-log.tar.gz)

**Comment by jmazzitelli** [comment]
OK, we will need to figure out if it's possible if we can get Ansible to perform some type of concurrent processing or bulk processing of adding the roles because as the number of namespaces increases, so will the reconciliation time (almost 2.5 seconds per namespace).

Also, "Determine all accessible namespaces, expanding regex expressions to matched namespaces" seems to increase with the size of the accessible_namespaces list. Some refactoring should also be considered here.

As for the number of reconciliations - the operator will perform a reconciliation for the initial change to the Kiali CR plus everytime the operator detects a change in resources it is watching. Because this is relying on the operator SDK's dependent resource watching feature and that simply listens to k8s events, this means the operator will run a second reconciliation loop immediately after creating any new objects. I believe this means we can never avoid a second trigger causing an immediately reconciliation loop to occur.

Why you are getting a third one is probably because you changed accessible_namespaces during your test and that triggered the third loop (I'm guessing here - but SOMETHING changed to cause that third loop).

**Comment by FilipB** [comment]
> Why you are getting a third one is probably because you changed accessible_namespaces during your test and that triggered the third loop (I'm guessing here - but SOMETHING changed to cause that third loop).

Only change done to the kiali CR as a part of the test was to remove one namespace from accessible_namespaces. Which means that one single change in the kiali CR invoked 3 rounds of reconciliation. No reconciliation was running when the test started so the third loop is not a result of some older "pending change" which is not part of the test.
If the third loop is not expected, does it mean that you are not able to see it in your env?

**Comment by jmazzitelli** [comment]
> Only change done to the kiali CR as a part of the test was to remove one namespace from accessible_namespaces. Which means that one single change in the kiali CR invoked 3 rounds of reconciliation.

I think this is all expected then:

Reconciliation loop 1: The initial creation of the Kial CR is detected and the operator installs Kiali - all Kiali resources are created now. The creation of the resources triggers k8s events.

Reconciliation loop 2: The k8s events that were triggered by the creation of the resources in reconciliation 1 causes reconciliation loop 2 to run (yes, it's weird. That's just how the ansible operator SDK works, AFAICS. I will ask the SDK team just to confirm this is supposed to happen - but ever since we enabled "dependent resource watching" in the operator, this has always happened - a 2nd reconciliation runs every time immediately after the initial Kiali CR creation).

Reconciliation loop 3: This loop runs when you "remove one namespace from accessible_namespaces." - the operator SDK will see the change to the Kiali CR and will tell the operator to update things.

**Comment by FilipB** [comment]
All 3 loops I'm talking about are result of removal of one namespace from accessible_namespaces. I'm not talking about reconciliation happening during installation of kiali.
So the timeline is following:
1. kiali CR is created and kiali is installed (I'm not interested in this reconciliation cycle)
2. kiali CR is updated to watch multiple namespaces (I'm not interested in this reconciliation cycle)
3. reconciliation for previous changes is finished
4. remove one namespace from accessible_namespaces
5. from this time point 3 reconciliation cycles run -> step 4. invokes 3 reconciliation cycles -> we need to understand why this simple change invoked 3 cycles

**Comment by jmazzitelli** [comment]
I really hate this feature of dependent resource watching. I think I should disable it. It is too "aggressive"

I too just saw the 3 loops by simply removing one namespace from the accessible_namespaces list. I might disable dependent resource watching AGAIN because it simply adds too much overhead.

**Comment by jmazzitelli** [comment]
OK, from the ansible operator SDK folks, this appears to be "expected":

```
If the change to the CR led to a change in a dependent resource, I think that's probably expected - first reconcile for CR change, second reconcile for resulting dependent resource change, third reconcile could be from status update when dependent resource is done doing whatever it was it was doing
```

I'm going to disable dependent resource watching because of this. We can't have the operator run a reconciliation 3 times everytime the Kiali CR is changed.

**Comment by jmazzitelli** [comment]
dependent resource watching disabled:
issue: https://github.com/kiali/kiali/issues/3482
master PR: https://github.com/kiali/kiali-operator/pull/207
backport 1.24 PR: https://github.com/kiali/kiali-operator/pull/208

**Comment by FilipB** [comment]
Verified that only one reconciliation cycle runs after removing one namespaces from accessible_namespaces.
It took 258s for 29 namespaces.

**Comment by jmazzitelli** [comment]
Some quick testing shows this speeds up the monitoring dashboard creation by alot - I'll create a PR for this:

```diff
 - name: Create the Monitoring Dashboards
   k8s:
     state: "present"
     namespace: "{{ kiali_vars.deployment.namespace }}"
-    definition: "{{ lookup('template', item) }}"
-  loop: "{{ monitoring_dashboard_yamls_to_deploy }}"
+    definition: |
+      {% for mdy in monitoring_dashboard_yamls_to_deploy %}
+      ---
+      {{ lookup("template", mdy) }}
+      ...
+      {% endfor %}
   when:
   - monitoringdashboards_crd_exists == True
   - monitoring_dashboard_yamls_to_deploy is defined
   - monitoring_dashboard_yamls_to_deploy | length > 0
   ignore_errors: yes
```

**Comment by jmazzitelli** [comment]
Documenting another task that needs to be refactored - this one is now at the top of the profiler report - it is slow and probably can be sped up by eliminating the ansible loop and using jinja instead:

```
- name: Determine all accessible namespaces, expanding regex expressions to matched namespaces
  set_fact:
    all_accessible_namespaces: "{{ ((all_accessible_namespaces | default([ kiali_vars.deployment.namespace, kiali_vars.istio_namespace ])) + [ item.1 | regex_search(item.0) ]) | unique }}"
  loop: "{{ kiali_vars.deployment.accessible_namespaces | product(all_namespaces) | list }}"
  when:
  - '"**" not in kiali_vars.deployment.accessible_namespaces'
  - item.1 | regex_search(item.0)
```

**Comment by jmazzitelli** [comment]
Next thing on the list is clearly a bottleneck - the task that creates the additional Kiali roles (one per namespace). Each run of the task takes about 1.5s - but if someone has 100 namespaces or 200, or 500.. well, you get the idea.

This task:

```
default/kiali-deploy : Create additional Kiali roles in [kubernetes] namespace [XYZ] --- 1.59s
```

There are other namespace-related tasks (like labeling the namespaces) where we might have to tackle as well:

```
default/kiali-deploy : Saving label to namespace [XYZ] ------------------- 1.35s
default/kiali-deploy : Get namespace [XYZ] that is to be labeled --------- 1.31s
```

**Comment by jmazzitelli** [comment]
Regarding the "Create additional Kiali roles" task - this is what we need to refactor to speed up:

[process-additional-roles.yml](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/process-additional-roles.yml):
```
# Create the roles needed to access a given namespace.
# If the namespace does not exist, this task will be skipped.
- name: "Create additional Kiali roles in [{{ process_resource_cluster }}] namespace [{{ role_namespace }}]"
  vars:
    role_namespace_obj: "{{ lookup('k8s', namespace=role_namespace, kind='Namespace', resource_name=role_namespace, api_version='v1') }}"
  include_tasks: process-resource.yml
  loop:
  - "{{ 'role-viewer' if kiali_vars.deployment.view_only_mode|bool == True else 'role' }}"
  - rolebinding
  loop_control:
    loop_var: process_resource_item
  when:
  - role_namespace_obj is defined
  - role_namespace_obj.metadata is defined
  - role_namespace_obj.metadata.name is defined
  - role_namespace_obj.metadata.name == role_namespace
```

Notice the three k8s api calls (one to set the role_namespace_obj, one to create the role, one to create the role binding).

The [process-resource.yml](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/process-resource.yml) mainly does this:

```
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'templates/' + process_resource_cluster + '/' + process_resource_item + '.yaml') }}"
  register: process_resource_result
```

This process-additional-roles.yml is included from both kubernetes [k8s-main.yml](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml) and openshift [os-main.yml](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/openshift/os-main.yml) tasks that look like this:


```
- name: Create additional Kiali roles on Kubernetes[OpenShift]
  include_tasks: process-additional-roles.yml
  vars:
    process_resource_cluster: "kubernetes[openshift]"
  loop: "{{ kiali_vars.deployment.accessible_namespaces }}"
  loop_control:
    loop_var: role_namespace
  when:
  - is_k8s[openshift] == True
  - '"**" not in kiali_vars.deployment.accessible_namespaces'
```

**Comment by jmazzitelli** [comment]
Just saw this at the top of the profiler report:
```
"default/kiali-deploy : Remove Monitoring Dashboards that should no longer be deployed -- 13.49s",
```

This should be easy to fix - just do the same thing we did for the creation of the monitoring dashboards.

See: https://github.com/kiali/kiali-operator/blob/v1.28.0/roles/default/kiali-deploy/tasks/main.yml#L801-L825

Make the removal task do the same kind of thing as the creation task:

```
- name: Remove Monitoring Dashboards that should no longer be deployed
  k8s:
    state: "absent"
    namespace: "{{ kiali_vars.deployment.namespace }}"
    definition: "{{ lookup('template', item) }}"
  loop: "{{ (monitoring_dashboard_yamls_all | default([])) | difference(monitoring_dashboard_yamls_to_deploy | default([])) }}"
  when:
  - monitoringdashboards_crd_exists == True
  ignore_errors: yes

- name: Create the Monitoring Dashboards
  k8s:
    state: "present"
    namespace: "{{ kiali_vars.deployment.namespace }}"
    definition: |
      {% for mdy in monitoring_dashboard_yamls_to_deploy %}
      ---
      {{ lookup("template", mdy) }}
      ...
      {% endfor %}
  when:
  - monitoringdashboards_crd_exists == True
  - monitoring_dashboard_yamls_to_deploy is defined
  - monitoring_dashboard_yamls_to_deploy | length > 0
  ignore_errors: yes
```
