### ISSUE TITLE
Prometheus unreachable in istio component status

### ISSUE THREAD

**Issue by tao-zhang** [kiali/kiali#3550]
**Describe the bug**
Although Kiali shows correct graph, istio component status still shows Prometheus unreachable.

<img width="2046" alt="Screenshot 2020-12-22 at 14 57 52" src="https://user-images.githubusercontent.com/2835004/102896082-1c795a00-4466-11eb-932c-e5017cfeb0e1.png">

**Versions used**
Kiali: 1.28.0
Istio: 1.8.1
Kubernetes flavour and version: AKS flavour, v1.18.10

**To Reproduce**
1. Install Istio 1.8.1
2. Install helm chart Kiali operator 1.28.0
3. Install helm chart kube-prometheus-stack 12.8.0
4. Configure Kiali to connect to prometheus installed in helm char kube-prometheus-stack

**Expected behavior**
Prometheus should not show 'unreachable'.

**Comment by jmazzitelli** [comment]
I suspect this is not a bug. You will have to tell us how you configured the Kiali CR.

Also, see these docs:

* https://kiali.io/documentation/latest/faq/#component-not-found
* https://kiali.io/documentation/latest/features/#_istio_component_status

**Comment by tao-zhang** [comment]
@jmazzitelli thank you for the information. As the screenshot shows, graph shows correctly based on Prometheus metrics. I also did a curl to prometheus service endpoint from Kiali pod, the connection is good.  Kiali CR is configured as:

```
  external_services:
    custom_dashboards:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      url: http://prometheus-stack-kube-prom-prometheus.monitor:9090
    tracing:
      enabled: false
  istio_component_namespaces:
    prometheus: monitor
```

**Comment by jmazzitelli** [comment]
[This commit](https://github.com/kiali/kiali/commit/aeffcbb5ab7705e2532462c2728b5b5b30f071d8) is the relevant code that was added to 1.28 wrt this component status checking. It looks like Prometheus will be reported as "Unreachable" when the external_services.prometheus.url returns >399 response code in response to an http request.

I don't know why it would do that if you can see a good graph.

@xeviknal will look at this.

**Comment by xeviknal** [comment]
hi @tao-zhang,

I have quite the same though as @jmazzitelli. However, I'd try to add one extra field in your config:

```yaml
  external_services:
    prometheus:
      url: http://prometheus-stack-kube-prom-prometheus.monitor:9090
      auth:
        use_kiali_token: true
```

On the other hand, could you tell us what is the result of accessing the kiali pod an executing the following:

```
KIALI_POD=kiali-6b5946854c-t5vng
k exec -n istio-system --stdin --tty $KIALI_POD -- curl http://prometheus-stack-kube-prom-prometheus.monitor:9090
```

Last but not least, would you mind to paste here the `external_services.prometheus` config from the Kiali ConfigMap?
```
k get cm -n kiali-operator kiali -o yaml
```

**Comment by tao-zhang** [comment]
@xeviknal @jmazzitelli 

```
k exec -n istio-system --stdin --tty kiali-fff775bc4-cvfj8 -- curl http://prometheus-stack-kube-prom-prometheus.monitor:9090
<a href="/prometheus/graph">Found</a>.
```
```
k exec -n istio-system --stdin --tty kiali-fff775bc4-cvfj8 -- curl -L http://prometheus-stack-kube-prom-prometheus.monitor:9090
404 page not found
```

ConfigMap 
```
      prometheus:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        cache_duration: 7
        cache_enabled: true
        cache_expiration: 300
        url: http://prometheus-stack-kube-prom-prometheus.monitor.svc:9090
```
Curl redirect to `/prometheus/graph`, then it gives 404 Not Found. I suspect that's related with ingress setting?
