### ISSUE TITLE
Kiali show service entries in another namespaces

### ISSUE THREAD

**Issue by alexandershelega** [kiali/kiali#3552]
Hi, we have create following service entry in dev namespace and use `exportTo "."` but when we open graph view for production namespace we also see that service entry.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: main-mongodb-se
  namespace: dev
spec:
  hosts:
    - main-db1-1.c.internal-ai.internal
    - main-db1-2.c.internal-ai.internal
    - main-db1-3.c.internal-ai.internal
  exportTo:
  - "."
  ports:
    - name: main-mongo-clients
      number: 27017
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
  ```

Please advice.

**Versions used**
Kiali: 1.28.1
Istio: 1.8.1
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
GKE : 1.17.13-gke.2600
