### ISSUE TITLE
Kiali Prometheus Configuration documentation issue

### ISSUE THREAD

**Issue by shake82** [kiali/kiali#3555]
Hi,

The problem is with the kiali documentation for [Prometheus Configuration](https://kiali.io/documentation/latest/runtimes-monitoring/#_prometheus_configuration)
The indentation for the configuration is wrong making it look like its under the custom_dashboards property. Instead of:
`
<pre>
external_services:
  custom_dashboards:
    prometheus:
      url: URL_TO_SERVER
    namespace_label: kubernetes_namespace
</pre>
`

It should be:
`
<pre>
external_services:
  custom_dashboards:
  prometheus:
    url: URL_TO_SERVER
  namespace_label: kubernetes_namespace
</pre>
`

**Comment by jmazzitelli** [comment]
The docs are correct. That `prometheus` section allows you to define a second Prometheus server that contains your custom dashboard metrics (separate from the istio telemetry).

Please read this: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L389-L411

**Comment by pangsq** [comment]
The doc [Using another Prometheus instance](https://kiali.io/documentation/latest/runtimes-monitoring/#_using_another_prometheus_instance) seems to be very misleading to me.
For most conditions, people want to change the prometheus config and do not care about the `second prometheus config for custom dashboard metrics`. And the config in doc is more proper to be like what @shake82 gived. 
According to [Prometheus-specific settings](https://github.com/kiali/kiali-operator/blob/76242369299c35db350119516c6db6fd87f47822/deploy/kiali/kiali_cr.yaml#L551), `external_services.prometheus` is supported.

Complete prometheus config would be like that:
```yaml
external_services:
  custom_dashboards:
    prometheus:
      url: URL_TO_SERVER_FOR_CUSTOM_DASHBOARDS
      namespace_label: kubernetes_namespace
    enabled: true
  prometheus:
    url: URL_TO_SERVER
    namespace_label: kubernetes_namespace
```
