### ISSUE TITLE
Kiali operator doesn't start

### ISSUE THREAD

**Issue by cebidhem** [kiali/kiali#3582]
**Describe the bug**
Kiali operator keeps `CrashLoopBackOff` when deploying using the Helm Chart.

I've followed this installation guide https://kiali.io/documentation/v1.28/installation-guide/#_helm_chart but the operator doesn't start.

When doing k get logs on the pods, I get:
```
flag provided but not defined: -zap-level
Usage of /opt/kiali/kiali:
  -config string
    	Path to the YAML configuration file. If not specified, environment variables will be used for configuration.
```

My values for the chart:
```
cr:
    create: true
    name: kiali
    namespace: istio-system
    spec:
        deployment:
          accessible_namespaces:
            - 'istio-system'
            - 'istio-poc-namespace'
image:
     repo: quay.io/kiali/kiali
     tag: v1.28.1
     pullPolicy: IfNotPresent
```

**Versions used**
Kiali: 1.28.1
Istio: 1.8.1
Kubernetes flavour and version: AWS EKS 1.18

**Expected behavior**
The operator is started and watched for kialis resources.
