### ISSUE TITLE
Incorrect workloadSelector spec key in ServiceEntry model prevents displaying workloadSelector in Kiali UI

### ISSUE THREAD

**Issue by axeal** [kiali/kiali#3587]
**Describe the bug**

The workloadSelector spec field was added to the kiali ServiceEntry model with the wrong key: `serviceEntry` instead of `workloadSelector` per https://github.com/kiali/kiali/blob/413d7fd35817957ff18726361ef7683154a55727/models/service_entry.go#L43 As a result, the workloadSelector is not displayed correctly within the kiali UI.

**Versions used**
Kiali: v1.28.1
Istio: v1.7.3
Kubernetes flavour and version: RKE2 v1.19.5

**To Reproduce**
1. Create a `ServiceEntry` resource with a `workloadSelector`, per the following example from the [Istio Service Entry docs](https://istio.io/v1.7/docs/reference/config/networking/service-entry/#ServiceEntry):
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details-svc
spec:
  hosts:
  - details.bookinfo.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
```
2. Navigate to `Istio Config` within the kiali UI and open the `details-svc` ServiceEntry.
3. Observe the workloadSelector is blank with `workloadSelector: ~` per the following screenshot:
![Screenshot from 2021-01-18 15-13-49](https://user-images.githubusercontent.com/9771530/104926330-4ad45180-59a0-11eb-879d-8c48622b750d.png)

**Expected behavior**

The UI should correctly show the workloadSelector, as follows:

```
  workloadSelector:
    labels:
      app: details
```
