### ISSUE TITLE
api-test molecule test failure

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3611]
Need to see if something is really broke or if the test needs to be fixed.

```yaml
    TASK [Results: /namespaces/graph: https://192.168.99.100/kiali/api/namespaces/graph?namespaces=simple-mesh&graphType=workload&injectServiceNodes=false] ***
    ok: [localhost] => {
        "msg": {
            "duration": 600,
            "elements": {
                "edges": [
                    {
                        "data": {
                            "destPrincipal": "spiffe://cluster.local/ns/simple-mesh/sa/default",
                            "id": "2f7ace8d53d82d6644764e714bb773cc",
                            "isMTLS": "100",
                            "responseTime": "5",
                            "source": "e26a73e7dde82950527dec642ff24f5a",
                            "sourcePrincipal": "spiffe://cluster.local/ns/simple-mesh/sa/default",
                            "target": "279175c6df0b586b508aa39563cf4c53",
                            "traffic": {
                                "protocol": "http",
                                "rates": {
                                    "http": "0.82",
                                    "httpPercentReq": "100.0"
                                },
                                "responses": {
                                    "200": {
                                        "flags": {
                                            "-": "100.0"
                                        },
                                        "hosts": {
                                            "simple-server-svc.simple-mesh.svc.cluster.local": "100.0"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ],
                "nodes": [
                    {
                        "data": {
                            "app": "simple-client",
                            "cluster": "cluster-default",
                            "id": "e26a73e7dde82950527dec642ff24f5a",
                            "isRoot": true,
                            "namespace": "simple-mesh",
                            "nodeType": "workload",
                            "traffic": [
                                {
                                    "protocol": "http",
                                    "rates": {
                                        "httpOut": "0.82"
                                    }
                                }
                            ],
                            "version": "v99",
                            "workload": "simple-client"
                        }
                    },
                    {
                        "data": {
                            "app": "simple-server",
                            "cluster": "cluster-default",
                            "destServices": [
                                {
                                    "cluster": "cluster-default",
                                    "name": "simple-server-svc",
                                    "namespace": "simple-mesh"
                                }
                            ],
                            "id": "279175c6df0b586b508aa39563cf4c53",
                            "namespace": "simple-mesh",
                            "nodeType": "workload",
                            "traffic": [
                                {
                                    "protocol": "http",
                                    "rates": {
                                        "httpIn": "0.82"
                                    }
                                }
                            ],
                            "version": "v99",
                            "workload": "simple-server"
                        }
                    },
                    {
                        "data": {
                            "app": "simple-client",
                            "cluster": "unknown",
                            "id": "3441ac506bb6b7b88ba0de131d9b3c72",
                            "isIdle": true,
                            "namespace": "simple-mesh",
                            "nodeType": "workload",
                            "version": "v99",
                            "workload": "simple-client"
                        }
                    },
                    {
                        "data": {
                            "app": "simple-server",
                            "cluster": "unknown",
                            "id": "b839f456761ee639d46c1ae31dfc3cf2",
                            "isIdle": true,
                            "namespace": "simple-mesh",
                            "nodeType": "workload",
                            "version": "v99",
                            "workload": "simple-server"
                        }
                    }
                ]
            },
            "graphType": "workload",
            "timestamp": 1611338918
        }
    }
    
    TASK [Assert that we were able to get the graph info for the small 2-node mesh] ***
fatal: [localhost]: FAILED! => {
    "assertion": "api_namespaces_graph_json.elements.nodes | length == 2",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```
