### ISSUE TITLE
Still getting KIA1102 errors with namespace/gateway-name

### ISSUE THREAD

**Issue by larsrnielsen** [kiali/kiali#3658]
The following VirtualService configuration generate a validation error in Kiali: KIA1102 VirtualService is pointing to a non-existing gateway. The virtual service works as intended. 

```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: content-routing-services
  namespace: cms-content
spec:
  hosts:
    - '*.something.com'
  gateways:
    - servicemesh/cms-apps-gateway
  http:
    - name: primary
      route:
        - destination:
            host: content-routing-services.cms-content.svc.cluster.local
```

```
❯ kubectl get gateway -n servicemesh
NAME                        AGE
cms-apps-gateway            48d
cms-apps-internal-gateway   48d
```

**Versions used**
Kiali: 
```
repoURL: 'https://kiali.org/helm-charts'
    chart: kiali-server
    targetRevision: "1.29"
```
Istio: 1.8.2
Kubernetes flavour and version: AWS EKS 1.18 (nodes v1.18.9-eks-d1db3c)
