### ISSUE TITLE
kiali-operator in one Namespace unable to talk to Istio in other Namespace

### ISSUE THREAD

**Issue by tskiens-quizlet** [kiali/kiali#3676]
The issue is that when I have Kiali configured to talk to istio in the proper namespace, the graph hangs and I see error messages in the bell notificaiton space in the app which show

```
 Error fetching Istio deployment status.
````

In the `Kiali-CR` I am supplying (shown in full below)

```
istio_namespace: istio-system
```

The graph loads and all `display` functions 
```
istio_namespace: monitoring
```
The one exception being that  "show idle nodes" fails to work. 

This seems like the most relevant error I've been able to find. This is from the kiali-operator pod.

```
 {"level":"error","ts":1612399271.6803517,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"apps/v1, Kind=Deployment","error":"unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request","stacktrace":"github.com/g
 o-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:99\nnet/http.serverHandler.ServeHTTP\n\t/home/t
 ravis/.gimme/versions/go1.13.12.linux.amd64/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.13.12.linux.amd64/src/net/http/server.go:1890"}
```

I see this WARN in the Kiali Pod - but I think it's not really important. 
```
2021-02-04T00:34:22Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-779c54bf49-brwv4]: the server is currently unable to handle the request (get pods istiod-8566b86db7-l2hl7)                                                                                                                  
```

---

Here's how I am installing it. I've used Helm to install. The intention for production is to have argo dehydrate the helm templates and send kubernetes yaml to the cluster.
```
helm install -n monitoring kiali-operator ./kiali-operator
```

**Chart.yaml**
```
apiVersion: v2
name: kiali-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: kiali-operator
    version: 1.29.0
    repository: https://kiali.org/helm-charts
```

**values.yaml**

```
###### these are for templates/Kiali-CR.yaml
Istio:
  Namespace: istio-system
Prometheus:
  Namespace: monitoring
Jaeger:
  Namespace: tracing
```

I've got a local Kiali-CR that I am using to define the deployment
Most of this is default. I use the demo to produce a CR and then pulled it down and stored it in my kiali-operator/templates/  path for helm to pick up during install. This does seem to work as expected.

I am using accessible_namespaces: '**' 

**Kiali-CR.yaml**
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  auth:
    openid:
      api_proxy: ''
      api_proxy_ca_data: ''
      authentication_timeout: 300
      authorization_endpoint: ''
      client_id: ''
      disable_rbac: false
      http_proxy: ''
      https_proxy: ''
      insecure_skip_verify_tls: false
      issuer_uri: ''
      scopes:
      - openid
      - profile
      - email
      username_claim: sub
    openshift:
      client_id_prefix: kiali
    strategy: anonymous
  deployment:
    accessible_namespaces:
    - '**'
    affinity:
      node: {}
      pod: {}
      pod_anti: {}
    custom_dashboards:
      excludes:
      - ''
      includes:
      - '*'
    hpa:
      api_version: autoscaling/v2beta2
      spec: {}
    image_name: quay.io/kiali/kiali
    image_pull_policy: IfNotPresent
    image_pull_secrets: []
    image_version: v1.29.0
    ingress_enabled: true
    logger:
      log_format: text
      log_level: warn
      sampler_rate: '1'
      time_field_format: 2006-01-02T15:04:05Z07:00
    namespace: ""
    node_selector: {}
    pod_annotations: {}
    pod_labels: {}
    priority_class_name: ''
    replicas: 1
    resources: {}
    secret_name: kiali
    service_annotations: {}
    tolerations: []
    version_label: v1.29.0
    view_only_mode: false
  extensions:
    iter_8:
      enabled: false
  external_services:
    custom_dashboards:
      enabled: true
      is_core_component: false
      namespace_label: ''
      prometheus:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        url: ''
    grafana:
      auth:
        ca_file: ''
        insecure_skip_verify: false
        password: ''
        token: ''
        type: none
        use_kiali_token: false
        username: ''
      dashboards:
      - name: Istio Service Dashboard
        variables:
          namespace: var-namespace
          service: var-service
      - name: Istio Workload Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
      enabled: true
      in_cluster_url: "http://{{ .Values.Grafana.Service }}.{{ .Values.Grafana.Namespace }}:3000"
      is_core_component: false
      url: ''
    istio:
      component_status:
        components:
        - app_label: istiod
          is_core: true
          namespace: {{ .Values.Istio.Namespace }}
        - app_label: istio-ingressgateway
          is_core: true
          namespace: {{ .Values.Istio.Namespace }}
        - app_label: istio-egressgateway
          is_core: false
          namespace: {{ .Values.Istio.Namespace }}
        enabled: true
      config_map_name: istio
      envoy_admin_local_port: 15000
      istio_identity_domain: svc.cluster.local
      istio_injection_annotation: sidecar.istio.io/inject
      istio_sidecar_annotation: sidecar.istio.io/status
      url_service_version: "http://istiod.{{ .Values.Istio.Namespace }}:15014/version"
    prometheus:
      auth:
        insecure_skip_verify: false
        type: none
        use_kiali_token: false
      cache_duration: 7
      cache_enabled: true
      cache_expiration: 300
      url: "http://{{ .Values.Prometheus.Service }}.{{ .Values.Prometheus.Namespace }}:9090"
    tracing:
      auth:
        insecure_skip_verify: false
        type: none
        use_kiali_token: false
      enabled: true
      in_cluster_url: "http://{{ .Values.Jaeger.Service }}.{{ .Values.Jaeger.Namespace }}"
      is_core_component: false
      namespace_selector: true
      whitelist_istio_system:
      - jaeger-query
      - istio-ingressgateway
  health_config:
    rate: []
  identity:
  istio_component_namespaces:
    grafana: "{{ .Values.Grafana.Namespace }}"
    istiod:  "{{ .Values.Istio.Namespace }}"
    prometheus: "{{ .Values.Prometheus.Namespace }}"
    tracing: "{{ .Values.Jaeger.Namespace }}"
  istio_labels:
    app_label_name: app
    injection_label_name: istio-injection
    version_label_name: version
  istio_namespace: "{{ .Values.Istio.Namespace }}"
  kiali_feature_flags:
    istio_injection_action: true
  kubernetes_config:
    burst: 200
    cache_duration: 300
    cache_enabled: true
    cache_istio_types:
    - DestinationRule
    - Gateway
    - ServiceEntry
    - VirtualService
    - Sidecar
    - PeerAuthentication
    - RequestAuthentication
    - AuthorizationPolicy
    cache_namespaces:
    - .*
    cache_token_namespace_duration: 10
    excluded_workloads: 
    qps: 999
  server:
    address: ''
    audit_log: true
    cors_allow_all: false
    gzip_enabled: true
    metrics_enabled: true
    metrics_port: 9090
    port: 20001
    web_fqdn: ''
    web_history_mode: ''
    web_port: ''
    web_root: /kiali
    web_schema: ''
```
