### ISSUE TITLE
Kiali behind proxy port issue

### ISSUE THREAD

**Issue by VanherpeDries** [kiali/kiali#3686]
### # Description 
I'm running a kiali server on a k8s 1.19, behind a ambassador proxy. I'm trying out the OpenID connection with Kiali. This Kiali instance is running on : https://kiali.k8s.local . But when i try to connect to the openid server it points to : https://kiali.k8s.local:20001 which can't be fount 

**Versions used**
Kiali: v1.29

**To Reproduce**

```
  auth:
    strategy: openid
    openshift: {}
    openid:
      client_id: "kiali"
      api_proxy: "https://kiali.k8s.local"
      issuer_uri: "https://openid.local/poam/oauth2"
      scopes: ["openid", "profile", "email", "groups"]
 ```

**Expected behavior**
Connecting to openid with https://kiali.k8s.local
