### ISSUE TITLE
No Traffic and Graph detected in Istio 1.9 and Kiali 1.29

### ISSUE THREAD

**Issue by widdix123** [kiali/kiali#3702]
**Describe the bug**
On EKS 1.17, Using Istio 1.9 and Kiali 1.29 i do not see any traffic on the UI

![image](https://user-images.githubusercontent.com/38529736/107883940-0218a580-6f18-11eb-9eb1-151a05581fe3.png)

**Versions used**
Kiali: 1.29
Istio: 1.90
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) EKS 1.17

**To Reproduce**
1. Go to Kiali Console
2. Click on Overview 
3. All Namespaces shows "No Traffic"

![image](https://user-images.githubusercontent.com/38529736/107883647-1bb8ed80-6f16-11eb-8523-76bcd53ad7c8.png)

4. Click on Any Applications, Go to Traffic  

![image](https://user-images.githubusercontent.com/38529736/107883664-355a3500-6f16-11eb-8a0d-21ad7012438a.png)

**Expected behavior**

It should show traffic for each Namespaces

**Comment by widdix123** [comment]
@israel-hdez  - Can you please check this ? 

The configmap for Kiali

```
data:
  config.yaml: |
    istio_labels:
      app_label_name: "app.kubernetes.io/name"
      version_label_name: "app.kubernetes.io/version"
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    dashboard:
      grafanaURL: http://prometheus-operator-grafana.logging.svc.cluster.local:80
    deployment:
      accessible_namespaces:
      - '**'
      additional_service_yaml: {}
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      hpa:
        api_version: autoscaling/v2beta2
        spec: {}
      image_name: quay.io/kiali/kiali
      image_pull_policy: Always
      image_pull_secrets: []
      image_version: v1.29
      ingress_enabled: false
      logger:
        log_format: text
        log_level: info
        sampler_rate: "1"
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: istio-system
      node_selector: {}
      override_ingress_yaml:
        metadata: {}
      pod_annotations:
        sidecar.istio.io/inject: "false"
      pod_labels: {}
      priority_class_name: ""
      replicas: 1
      resources: {}
      secret_name: kiali
      service_annotations: {}
      service_type: ""
      tolerations: []
      version_label: v1.29.0
      view_only_mode: false
    external_services:
      istio:
        url_service_version: http://istiod.istio-system:15014/version
        istio_status_enabled: false
      custom_dashboards:
        enabled: true
      prometheus:
        url: http://prometheus.istio-system.svc.cluster.local:9090
      grafana:
        url: http://prometheus-operator-grafana.logging.svc.cluster.local:80
    identity:
      cert_file: ""
      private_key_file: ""
    istio_namespace: istio-system
    login_token:
      signing_key: CHANGEME
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
```
