### ISSUE TITLE
Regex matching accessible namespaces is too broad

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3709]
**Describe the bug**
Regex matching accessible namespaces is too broad so when having e.g. bookinfo and bookinfo2 apps and following kiali CR:
```
spec:
  deployment:
    accessible_namespaces:
      - bookinfo
```
it will match both bookinfo and bookinfo2.

**Versions used**
Kiali: v1.31.0-SNAPSHOT (96cf9bf4db30d3fad550922435f03ab33cad98bb)
Istio:     1.9.0 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.6

**To Reproduce**
1. install istio with kiali
2. install bookinfo app to bookinfo namespace and add it to the kiali cr spec.deployment.accessible_namespaces
3. install bookinfo app to bookinfo2 namespace but do NOT add it to the kiali cr spec.deployment.accessible_namespaces
4. Kiali shows both bookinfo and bookinfo2. Kiali CR looks like this:
```
spec:  
  deployment:
    accessible_namespaces:
      - bookinfo
```
```
status:
  accessibleNamespaces: 'bookinfo,bookinfo2,istio-system'
```

**Expected behavior**
Only bookinfo,istio-system should be shown.
