### ISSUE TITLE
Workload page displays an error when accessing VirtualMachineInstance resource

### ISSUE THREAD

**Issue by rhrazdil** [kiali/kiali#3733]
**General remarks**
I'm working on integrating KubeVirt with Istio and Kiali, and I'm seeing an error when accessing the Workload entry in Kiali dashboard of a VirtualMachineInstance resource.

**Describe the bug**
Whe I try to navigate to the VirutalMachineInstance Workload, I get a page saying that there has been an error.

Kiali log reads:
```
2021-02-24T19:56:43Z WRN Workload vmi-cirros of type VirtualMachineInstance has not a ReplicaSet as a child controller, it may need a revisit
```

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v1.29.1
Istio: 1.9.0
Kubernetes flavour and version: k8s v1.20.2

**To Reproduce**
0. Have istio deployed and the current namespace labeled to auto-inject
1. Deploy KubeVirt
```
export RELEASE=v0.37.0
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml 
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
```
2. Create VMI
```
kubectl create -f https://raw.githubusercontent.com/rhrazdil/istio_samples/master/virtualmachines/vmi-cirros
```
3. Go to Kiali dashboard
4. Click Workloads, click vmi-cirros
5. You get an error

**Expected behavior**
I expect to have the actual content displayed

**Comment by lucasponce** [comment]
Thanks @rhrazdil, yes, you are right, KubeVirt are not yet tested on Kiali and as you pointed, the way to collect the top controller is missing a call for details and probably there is a gap on the existing logic.

Can you confirm the platform where you are testing kubevirt+kubernetes+istio ?

(Thinking in the best way to reproduce for those less familiar with kubevirt)

**Comment by rhrazdil** [comment]
Hello @lucasponce! Thanks for responding.

> Can you confirm the platform where you are testing kubevirt+kubernetes+istio ?
We use custom [k8s dockerized cluster](https://github.com/kubevirt/kubevirtci/blob/master/K8S.md), I can provide step by step to run the cluster and deploy kubevirt + istio. 
It could be reproduced with minikube, but one would need to disable selinux because there is a [bug](moby/moby#41370) in how docker works with selinux categories. 

Here I provide steps for deploying our platform with istio and kubevirt
**Note**:  these steps will work once this PR is merged https://github.com/kubevirt/kubevirtci/pull/541 (should happen today), 
which switches the docker ce with cri-o ce, without this PR, again, selinux must not be set to enforcing.

```
git clone https://github.com/kubevirt/kubevirtci.git                                  
cd kubevirtci

export KUBEVIRT_PROVIDER=k8s-1.20
export KUBEVIRT_NUM_NODES=2
export KUBEVIRT_NUM_SECONDARY_NICS=1
make cluster-up 

export KUBECONFIG=$(cluster-up/kubeconfig.sh)

# Here I assume you have istioctl 1.9.0 already installed
istioctl manifest generate --set profile=demo \
  --set components.cni.enabled=true \
  --set values.cni.chained=true \
  --set values.cni.cniBinDir=/opt/cni/bin \
  --set values.cni.cniConfDir=/etc/cni/net.d \
  --set values.global.jwtPolicy=first-party-jwt  > ./istio-deployment.yaml
  
  cluster-up/kubectl.sh create ns istio-system 
  cluster-up/kubectl.sh create -f ./istio-deployment.yaml
  
  export RELEASE=v0.37.0
  cluster-up/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml 
  cluster-up/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml

  cluster-up/kubectl.sh apply -f https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/kiali.yaml
  cluster-up/kubectl.sh apply -f https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/prometheus.yaml
  cluster-up/kubectl.sh apply -f https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/jaeger.yaml

  # create the VMI
  cluster-up/kubectl.sh -f https://raw.githubusercontent.com/rhrazdil/istio_samples/master/virtualmachines/vmi-cirros
```

**Comment by rhrazdil** [comment]
Hello again @lucasponce 
the code adding support for Istio got into a released KubeVirt version, which should make reproducing this way easier.

For Istio + KubeVirt deployment the easiest way seems to be minikube so just following
https://istio.io/latest/docs/setup/platform-setup/minikube/
and then 
```
export RELEASE=v0.43.0
cluster-up/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml 
cluster-up/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
```
Should be all that's needed.

As example VMs, the following manifests may be used:
```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    app: vmi-istio
  name: vmi-istio
spec:
  domain:
    devices:
      interfaces:
        - name: default
          masquerade: {}
      disks:
        - disk:
            bus: virtio
          name: containerdisk
    resources:
      requests:
        memory: 1024M
  networks:
    - name: default
      pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
    - name: containerdisk
      containerDisk:
        image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
---
# Istio requires for applications to have an associated kubernetes service
apiVersion: v1
kind: Service
metadata:
  name: vmi-istio-svc
spec:
  selector:
    app: vmi-istio
  ports:
    - port: 8080
      name: http
      protocol: TCP
```
