### ISSUE TITLE
Modify manifests to use readOnlyRootFilesystem

### ISSUE THREAD

**Issue by ludydoo** [kiali/kiali#3810]
**Is your feature request related to a problem? Please describe.**
It's a good security practice to use readOnlyRootFilesystems when deploying workloads. During kiali bootstrap, kiali tries to update the env.js and index.html (rootPath), which violate the readOnlyRootFilesystem condition.

**Describe the solution you'd like**
Update the documentation manifests to restrict readOnlyRootFilesystem.

**Describe alternatives you've considered**
I'm including a sample manifest that I'm using that uses an initContainer to copy the static files over to a memory volume.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: kiali
      labels:
        app: kiali
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        kiali.io/runtimes: go,kiali
    spec:
      serviceAccountName: kiali
      initContainers:
        - name: copy
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          image: "quay.io/kiali/kiali:v1.31.0"
          command:
            - sh
            - -c
            - cp -r /opt/kiali/console/* /tmp/static
          volumeMounts:
            - mountPath: /tmp/static
              name: static-content
      containers:
        - image: "quay.io/kiali/kiali:v1.31.0"
          imagePullPolicy: Always
          name: kiali
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          command:
            - "/opt/kiali/kiali"
            - "-config"
            - "/kiali-configuration/config.yaml"
          ports:
            - name: api-port
              containerPort: 20001
            - name: http-metrics
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          env:
            - name: ACTIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "text"
            - name: LOG_TIME_FIELD_FORMAT
              value: "2006-01-02T15:04:05Z07:00"
            - name: LOG_SAMPLER_RATE
              value: "1"
          volumeMounts:
            - name: kiali-configuration
              mountPath: "/kiali-configuration"
            - name: kiali-cert
              mountPath: "/kiali-cert"
            - name: kiali-secret
              mountPath: "/kiali-secret"
            - name: static-content
              mountPath: /opt/kiali/console
      volumes:
        - name: kiali-configuration
          configMap:
            name: kiali
        - name: kiali-cert
          secret:
            secretName: istio.kiali-service-account
            optional: true
        - name: kiali-secret
          secret:
            secretName: kiali
            optional: true
        - name: static-content
          emptyDir:
            medium: Memory
            sizeLimit: 50Mi
```
