### ISSUE TITLE
Need to specify namespace in error message "Graph not loading: configmaps "istio" not found'

### ISSUE THREAD

**Issue by friedemannf** [kiali/kiali#3821]
**Describe the bug**
Kiali is installed via the kiali-operator using the following CR:
```yaml
cr:
  create: true
  name: kiali
  namespace: "default"
  spec:
    auth:
      strategy: "anonymous"
    deployment:
      accessible_namespaces:
        - istio-system
        - default
      ingress_enabled: false
    external_services:
      prometheus:
        url: "http://monitoring-prod-prometheus-prometheus:9090"
```
Kiali starts just fine and seems completely functional except for the Graph display, which errors out with following message 
```
Cannot load the graph: configmaps "istio" not found
```
![image](https://user-images.githubusercontent.com/59653747/112675674-c0104700-8e67-11eb-9376-72d7b8ceaa2b.png)
The Kiali Server logs show the same error along with a stacktrace. All other functionality works as expected, e.g. Traffic Display, Metrics, etc.

I of course checked but the ConfigMap does in fact exist in the namespace `istio-system` that Istio is installed in:
```
❯ kubectl get configmaps --namespace istio-system
NAME                                   DATA   AGE
istio                                  2      20h
``` 

**Versions used**
Kiali: v1.31.0
Istio: 1.9.1
Kubernetes flavour and version: v1.18.16-gke.302

**To Reproduce**
1. Install the prometheus-operator
2. Install Istio using the default profile (ConfigMap is created as `istio` in the `istio-system` namespace)
3. Install kiali-operator with `cr.create: true` into a separate namespace but give access to `istio-system` using `accessible_namespaces`
4. Open the UI & click on Graph
5. See the error in the UI as well as the Kiali Server logs

**Expected behavior**
Kiali to be able to access the `istio` ConfigMap and show a graph in the UI.

**Comment by jmazzitelli** [comment]
_[@friedemannf  I'm not 100% sure of what I am going to say, but I'm 75% sure :)  Please try the fix I describe below and tell me if it works]_

This is probably not a bug, but Kiali could use a little better error message here. So I think we should leave this github bug report in place, but perhaps make the title more descriptive of what the problem actually is.

Notice the error message (`Cannot load the graph: configmaps "istio" not found`) doesn't say WHICH NAMESPACE it is looking in for the "istio" ConfigMap. It should say that - if it did, I suspect you would have found the problem.

Notice you put the Kiali CR in the namespace `default` - that is where it will install Kiali. It is also where it will look by default for the Istio components (including the ConfigMap).

If you want to install Kiali in a different namespace than where you installed your Istio control plane, then you need to tell the operator and Kiali where your Istio control plane is (otherwise, the default behavior is to assume Kiali is installed in the Istio control plane - so it is going to think Istio components are in the `default` namespace).

Thus, in your Kiali CR, you need to explicitly specify this: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L66

Example - your yaml should probably look like this:

```
cr:
  create: true
  name: kiali
  namespace: "default"
  spec:
    istio_namespace: istio-system
    ...and the rest...
```
