### ISSUE TITLE
Graph does not show mTLS when egress gateway with TLS origination is used

### ISSUE THREAD

**Issue by ludydoo** [kiali/kiali#3825]
**General remarks**

**Describe the bug**

Using istio egress gateways with tls-origination, the connection between a pod and the egress gateway is still using mTLS. I would expect that the graph would show this connection between the pod and the egress gateway as mTLS enabled.

![Screenshot from 2021-03-28 12-46-30](https://user-images.githubusercontent.com/38968/112749603-a5eb7b80-8fc3-11eb-9fa9-4d1b548e3be5.png)

**Versions used**
Kiali: 1.32.0
Istio: 1.9.1-distroless
Kubernetes flavour and version: AKS 1.20.2

**To Reproduce**

1. Configure an egress gateway with TLS origination using the istio manual. (SDS) https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/
2. Observe that the connection between the POD and the EGRESS-GATEWAY is not shown as using mTLS, even though the DestinationRule POD -> EGRESS is set to use MTLS.

**Expected behavior**
The connection between the mTLS pod and the egress gateway should be shown as mTLS enabled.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egress
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 443
        name: tls
        protocol: TLS
      hosts:
        - acme-v02.api.letsencrypt.org
        - acme-staging-v02.api.letsencrypt.org
      tls:
        mode: PASSTHROUGH
    - port:
        number: 80
        name: http-tls-origination
        protocol: HTTPS
      hosts:
        - REDACTED.westeurope.azure.elastic-cloud.com
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  exportTo:
    - "*"
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: elastic-cloud
      labels:
        istio: egressgateway
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 80
            tls:
              mode: ISTIO_MUTUAL
              sni: REDACTED.westeurope.azure.elastic-cloud.com
    - name: letsencrypt
      labels:
        istio: egressgateway
    - name: letsencrypt-staging
      labels:
        istio: egressgateway
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: elastic-cloud
  namespace: istio-system
spec:
  exportTo:
    - monitoring
    - istio-system
  hosts:
    - REDACTED.westeurope.azure.elastic-cloud.com
  ports:
    - number: 9243
      name: https-9243
      protocol: HTTPS
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elastic-cloud
  namespace: istio-system
spec:
  exportTo:
    - monitoring
    - istio-system
  host: REDACTED.westeurope.azure.elastic-cloud.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 9243
        tls:
          mode: SIMPLE
          credentialName: azure-elastic
          sni: REDACTED.westeurope.azure.elastic-cloud.com
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-elastic-cacert
  namespace: istio-system
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIZATCCF+mgAwIBAgIQBcrX1a+4ienlz6qbVWcyuDANBgkqhkiG9w0BAQsFADBPMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBEaWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMTAzMTAwMDAwMDBaFw0yMTExMTAyMzU5NTlaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRwwGgYDVQQKExNFbGFzdGljc2VhcmNoLCBJbmMuMSIwIAYDVQQDDBkqLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzWPiVVKBl3k54DmIQ6H/FW1FTNfpsbBgUOhq+GD2gDnpOzKhaDWJDwAZxGpzZbrMeceinVma8h4yqj+Ofr2BoXchk5nHw8yZ90lr2+nIsogSMyDhu1MEXtBkDKLY/RJfQ+BC6x68hAUJlVurVXGIDE52bElYUPGny4zXk8xL7jaJ4g4K70bm7y4ZpZdhtkSvpTGCt1LPFE5yG0hoDoqmVxobVwT6516p7dlXpONgrsVjdKfVajsquqNnaWw97GXcETqHXNmwhmBBkam6Avr95Rb5Knec8LfCqmxmyuHm0qfT5ERLRk87KlOxWMuR1gVbLRT2wmnfrDpnqxn3jvAm+QIDAQABo4IVqjCCFaYwHwYDVR0jBBgwFoAUt2ui6qiqhIx56rTaD5iyxZV2ufQwHQYDVR0OBBYEFAiYmWqKym5QSxRFOmwN3+ExOgecMIIS0gYDVR0RBIISyTCCEsWCGSouYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CEyouZWxhc3RpYy1jbG91ZC5jb22CISouZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIlKi5hcG0uZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIsKi5hcHAtc2VhcmNoLmVhc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLCouZW50LXNlYXJjaC5lYXN0dXMyLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiQqLndlc3RldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKCouYXBtLndlc3RldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLyouYXBwLXNlYXJjaC53ZXN0ZXVyb3BlLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgi8qLmVudC1zZWFyY2gud2VzdGV1cm9wZS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIhKi53ZXN0dXMyLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiUqLmFwbS53ZXN0dXMyLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiwqLmFwcC1zZWFyY2gud2VzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIsKi5lbnQtc2VhcmNoLndlc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJyouc291dGhlYXN0YXNpYS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIrKi5hcG0uc291dGhlYXN0YXNpYS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIyKi5hcHAtc2VhcmNoLnNvdXRoZWFzdGFzaWEuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMiouZW50LXNlYXJjaC5zb3V0aGVhc3Rhc2lhLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiMqLmphcGFuZWFzdC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYInKi5hcG0uamFwYW5lYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgi4qLmFwcC1zZWFyY2guamFwYW5lYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgi4qLmVudC1zZWFyY2guamFwYW5lYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiUqLm5vcnRoZXVyb3BlLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgikqLmFwbS5ub3J0aGV1cm9wZS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIwKi5hcHAtc2VhcmNoLm5vcnRoZXVyb3BlLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgjAqLmVudC1zZWFyY2gubm9ydGhldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CISoudWtzb3V0aC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIlKi5hcG0udWtzb3V0aC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIsKi5hcHAtc2VhcmNoLnVrc291dGguYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLCouZW50LXNlYXJjaC51a3NvdXRoLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgicqLmZyYW5jZWNlbnRyYWwuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKyouYXBtLmZyYW5jZWNlbnRyYWwuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMiouYXBwLXNlYXJjaC5mcmFuY2VjZW50cmFsLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgjIqLmVudC1zZWFyY2guZnJhbmNlY2VudHJhbC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYInKi5hdXN0cmFsaWFlYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgisqLmFwbS5hdXN0cmFsaWFlYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgjIqLmFwcC1zZWFyY2guYXVzdHJhbGlhZWFzdC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIyKi5lbnQtc2VhcmNoLmF1c3RyYWxpYWVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CIyouY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgicqLmFwbS5jZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLiouYXBwLXNlYXJjaC5jZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLiouZW50LXNlYXJjaC5jZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJCouZXMuZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbYInKi5lcy53ZXN0ZXVyb3BlLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiQqLmVzLndlc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKiouZXMuc291dGhlYXN0YXNpYS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYImKi5lcy5qYXBhbmVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKCouZXMubm9ydGhldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJCouZXMudWtzb3V0aC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIqKi5lcy5mcmFuY2VjZW50cmFsLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgioqLmVzLmF1c3RyYWxpYWVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJiouZXMuY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiQqLmtiLmVhc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJyoua2Iud2VzdGV1cm9wZS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIkKi5rYi53ZXN0dXMyLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgioqLmtiLnNvdXRoZWFzdGFzaWEuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJioua2IuamFwYW5lYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgigqLmtiLm5vcnRoZXVyb3BlLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiQqLmtiLnVrc291dGguYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKioua2IuZnJhbmNlY2VudHJhbC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIqKi5rYi5hdXN0cmFsaWFlYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiYqLmtiLmNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIYKi52cGNlLmVsYXN0aWMtY2xvdWQuY29tgiwqLnZwY2UuYXVzdHJhbGlhZWFzdC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIoKi52cGNlLmNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYImKi52cGNlLmVhc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLCoudnBjZS5mcmFuY2VjZW50cmFsLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgigqLnZwY2UuamFwYW5lYXN0LmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgioqLnZwY2Uubm9ydGhldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLCoudnBjZS5zb3V0aGVhc3Rhc2lhLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiYqLnZwY2UudWtzb3V0aC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIpKi52cGNlLndlc3RldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJioudnBjZS53ZXN0dXMyLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgjMqLnByaXZhdGVsaW5rLmF1c3RyYWxpYWVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLyoucHJpdmF0ZWxpbmsuY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgi0qLnByaXZhdGVsaW5rLmVhc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMyoucHJpdmF0ZWxpbmsuZnJhbmNlY2VudHJhbC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIvKi5wcml2YXRlbGluay5qYXBhbmVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMSoucHJpdmF0ZWxpbmsubm9ydGhldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMyoucHJpdmF0ZWxpbmsuc291dGhlYXN0YXNpYS5henVyZS5lbGFzdGljLWNsb3VkLmNvbYItKi5wcml2YXRlbGluay51a3NvdXRoLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgjAqLnByaXZhdGVsaW5rLndlc3RldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CLSoucHJpdmF0ZWxpbmsud2VzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIgKi5lYXN0dXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJCouYXBtLmVhc3R1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIrKi5hcHAtc2VhcmNoLmVhc3R1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIrKi5lbnQtc2VhcmNoLmVhc3R1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIjKi5lcy5lYXN0dXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CIyoua2IuZWFzdHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiUqLnZwY2UuZWFzdHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiwqLnByaXZhdGVsaW5rLmVhc3R1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIoKi5zb3V0aGNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIsKi5hcG0uc291dGhjZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CMyouYXBwLXNlYXJjaC5zb3V0aGNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIzKi5lbnQtc2VhcmNoLnNvdXRoY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgisqLmVzLnNvdXRoY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgisqLmtiLnNvdXRoY2VudHJhbHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgi0qLnZwY2Uuc291dGhjZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CNCoucHJpdmF0ZWxpbmsuc291dGhjZW50cmFsdXMuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJSouZW50LmVhc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKCouZW50Lndlc3RldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJSouZW50Lndlc3R1czIuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKyouZW50LnNvdXRoZWFzdGFzaWEuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJyouZW50LmphcGFuZWFzdC5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIpKi5lbnQubm9ydGhldXJvcGUuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJSouZW50LnVrc291dGguYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKyouZW50LmZyYW5jZWNlbnRyYWwuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CKyouZW50LmF1c3RyYWxpYWVhc3QuYXp1cmUuZWxhc3RpYy1jbG91ZC5jb22CJyouZW50LmNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbYIkKi5lbnQuZWFzdHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tgiwqLmVudC5zb3V0aGNlbnRyYWx1cy5henVyZS5lbGFzdGljLWNsb3VkLmNvbTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGLBgNVHR8EgYMwgYAwPqA8oDqGOGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3JsMD6gPKA6hjhodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLmNybDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwfQYIKwYBBQUHAQEEcTBvMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wRwYIKwYBBQUHMAKGO2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3J0MAwGA1UdEwEB/wQCMAAwggECBgorBgEEAdZ5AgQCBIHzBIHwAO4AdQB9PvL4j/+IVWgkwsDKnlKJeSvFDngJfy5ql2iZfiLw1wAAAXga2KctAAAEAwBGMEQCIB93L4W6mTOLtl96qgtPLn/BEchh2g3xx97zHrr4fjPGAiB7NNv2QZhG2V6ecT25QF9odHxt35HB0T68R6Ao9NfwsAB1AFzcQ5L+5qtFRLFemtRW5hA3+9X6R9yhc5SyXub2xw7KAAABeBrYpusAAAQDAEYwRAIgc5PK/joftQu+m1IXg0ANj25uiy/KlRZSZtlvIojqpBECID/dr70d7fy+j00AbezNcdG7GI5FAt/X+m/34DVlLWg4MA0GCSqGSIb3DQEBCwUAA4IBAQAl93cH7lGF4y9MyonKhDR6h7azf4BTz7552uwdaT9JYKdUYzLnlRm3NeDiGoFr+kyVeg/gjU2I8QF/0gQ+Ro2U//9rJO5UGQutd2i9Mx0bis+h2jWu6B3qsd9LBnsnRzDO0s0OhblAJ6t015NOX/VA51Ysle+B33XT2XYOB6YfvWQJU1N8s6dLrsxOw+0G+ub7q8FJ9bBPN079aR8rK0+7qmhqSQprOFsIBUbFWRoICL5J9vdIlTRkERyHNThM/LlyRE3aB207z/cq+T80+wOxVN3dxCosyXrzJtiTUhJAePt9VIv8LiFl8awTFirZ6pz9ugiiNozlC5Fu7CZN5LkF
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIE6jCCA9KgAwIBAgIQCjUI1VwpKwF9+K1lwA/35DANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0yMDA5MjQwMDAwMDBaFw0zMDA5MjMyMzU5NTlaME8xCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxKTAnBgNVBAMTIERpZ2lDZXJ0IFRMUyBSU0EgU0hBMjU2IDIwMjAgQ0ExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwUuzZUdwvN1PWNvsnO3DZuUfMRNUrUpmRh8sCuxkB+Uu3Ny5CiDt3+PE0J6aqXodgojlEVbbHp9YwlHnLDQNLtKS4VbL8Xlfs7uHyiUDe5pSQWYQYE9XE0nw6Ddng9/n00tnTCJRpt8OmRDtV1F0JuJ9x8piLhMbfyOIJVNvwTRYAIuE//i+p1hJInuWraKImxW8oHzf6VGo1bDtN+I2tIJLYrVJmuzHZ9bjPvXj1hJeRPG/cUJ9WIQDgLGBAfr5yjK7tI4nhyfFK3TUqNaX3sNk+crOU6JWvHgXjkkDKa77SU+kFbnO8lwZV21reacroicgE7XQPUDTITAHk+qZ9QIDAQABo4IBrjCCAaowHQYDVR0OBBYEFLdrouqoqoSMeeq02g+YssWVdrn0MB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADB2BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBABggrBgEFBQcwAoY0aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNydDB7BgNVHR8EdDByMDegNaAzhjFodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxSb290Q0EuY3JsMDegNaAzhjFodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxSb290Q0EuY3JsMDAGA1UdIAQpMCcwBwYFZ4EMAQEwCAYGZ4EMAQIBMAgGBmeBDAECAjAIBgZngQwBAgMwDQYJKoZIhvcNAQELBQADggEBAHert3onPa679n/gWlbJhKrKW3EX3SJH/E6f7tDBpATho+vFScH90cnfjK+URSxGKqNjOSD5nkoklEHIqdninFQFBstcHL4AGw+oWv8Zu2XHFq8hVt1hBcnpj5h232sb0HIMULkwKXq/YFkQZhM6LawVEWwtIwwCPgU7/uWhnOKK24fXSuhe50gG66sSmvKvhMNbg0qZgYOrAKHKCjxMoiWJKiKnpPMzTFuMLhoClw+dj20tlQj7T9rxkTgl4ZxuYRiHas6xuwAwapu3r9rxxZf+ingkquqTgLozZXq8oXfpf2kUCwA/d5KxTVtzhwoT0JzI8ks5T1KESaZMkE4f97Q=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsBCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7PT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbRTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/EsrhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJFPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0lsYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQkCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
    -----END CERTIFICATE-----
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elastic-cloud
  namespace: istio-system
spec:
  exportTo:
    - istio-system
    - monitoring
  hosts:
    - REDACTED.westeurope.azure.elastic-cloud.com
  gateways:
    - mesh
    - istio-system/egress
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: elastic-cloud
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - istio-system/egress
          port: 80
      route:
        - destination:
            host: REDACTED.westeurope.azure.elastic-cloud.com
            port:
              number: 9243
          weight: 100
---
```

Logs from pod 
```
 istio-proxy [2021-03-28T10:53:24.063Z] "POST /_bulk HTTP/1.1" 200 - via_upstream - "-" 1309 252 31 31 "-" "elasticsearch-ruby/7.11.2 (RUBY_VERSION: 2.6.6; linux x86_64; Faraday v1.3.0)" "REDACTED" "REDACTED.westeurope.azure.elastic-cloud.com:80" "10.4.3.51:8080" outbound|80|elastic-cloud|istio-egressgateway.istio-system.svc.cluster.local 10.4.1.174:48368 20.50.174.29:80 10.4.1.174:35754 - -
```
I would assume that the `outbound` `80` `elastic-cloud` would detect the PortLevelSettings on the destinationrule, that is `mode: ISTIO_MUTUAL`

Logs from egressgateway

```
 [2021-03-28T10:52:16.263Z] "POST /_bulk HTTP/2" 200 - via_upstream - "-" 18437 1979 15 14 "10.4.3.200" "elasticsearch-ruby/7.11.2 (RUBY_VERSION: 2.6.6; linux x86_64; Faraday v1.3.0)" "REDACTED" "REDACTED.w 
 esteurope.azure.elastic-cloud.com:80" "20.50.174.29:9243" outbound|9243||REDACTED.westeurope.azure.elastic-cloud.com 10.4.3.51:53142 10.4.3.51:8080 10.4.3.200:38344 REDACTED.westeurope.azure.elastic-cloud.com  
```
