### ISSUE TITLE
audit the permissions granted to Kiali server and the operator

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3871]
We should do an audit of all the permissions granted to the kiali server and the operator and make sure we have everything we need but nothing more.

* Server: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/role.yaml
* Server read-only: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
* Operator: https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml

Make sure we update all the different yamls out there with these permissions - including the kubernetes templates and helm charts and OLM metadata

* https://github.com/kiali/helm-charts/tree/master/kiali-operator/templates
* https://github.com/kiali/helm-charts/tree/master/kiali-server/templates
* https://github.com/kiali/kiali-operator/tree/master/roles/default/kiali-deploy/templates/kubernetes
* https://github.com/kiali/kiali-operator/tree/master/manifests

**Comment by jmazzitelli** [comment]
Where the roles are defined:

```
$ ls -1 \
  kiali-operator/manifests/kiali-{upstream,community}/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml \
  kiali-operator/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml \
  kiali-operator/roles/{default,v1.24}/kiali-deploy/templates/{kubernetes,openshift}/{role,role-viewer,role-controlplane}.yaml \
  helm-charts/kiali-{operator,server}/templates/{clusterrole,role,role-viewer,role-controlplane}.yaml \
  2>/dev/null
```

Results in:
```
helm-charts/kiali-operator/templates/clusterrole.yaml
helm-charts/kiali-server/templates/role-controlplane.yaml
helm-charts/kiali-server/templates/role-viewer.yaml
helm-charts/kiali-server/templates/role.yaml
kiali-operator/manifests/kiali-community/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
kiali-operator/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
kiali-operator/manifests/kiali-upstream/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
kiali-operator/roles/default/kiali-deploy/templates/kubernetes/role-controlplane.yaml
kiali-operator/roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
kiali-operator/roles/default/kiali-deploy/templates/kubernetes/role.yaml
kiali-operator/roles/default/kiali-deploy/templates/openshift/role-controlplane.yaml
kiali-operator/roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
kiali-operator/roles/default/kiali-deploy/templates/openshift/role.yaml
kiali-operator/roles/v1.24/kiali-deploy/templates/kubernetes/role-viewer.yaml
kiali-operator/roles/v1.24/kiali-deploy/templates/kubernetes/role.yaml
kiali-operator/roles/v1.24/kiali-deploy/templates/openshift/role-viewer.yaml
kiali-operator/roles/v1.24/kiali-deploy/templates/openshift/role.yaml
```

**Comment by jmazzitelli** [comment]
PRs:
* https://github.com/kiali/kiali-operator/pull/287
* https://github.com/kiali/helm-charts/pull/62

Below are some permissions I still have questions on. I would like ask: Do we need these permissions? Below is a copy of the server's permissions (taken from a copy of the server helm chart's role.yaml). I hide lines that I already confirmed or know we need - you can ignore the blank lines.  What you see here are the ones I am not sure of. So I need to know if we need these or not.

```
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints

  - nodes
  - pods
  - pods/log
  - pods/proxy
  - replicationcontrollers
  - services
  verbs:



  - patch
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create
  - post
- apiGroups: ["extensions", "apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:



  - patch
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs:



  - patch











- apiGroups: ["apps.openshift.io"]
  resources:
  - deploymentconfigs
  verbs:



  - patch
















- apiGroups: ["iter8.tools"]
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch






```
