### ISSUE TITLE
OpenID integration issue with large tokens (caused by a long list of groups)

### ISSUE THREAD

**Issue by somejfn** [kiali/kiali#3874]
**Describe the bug**

With a Kiali instance deployed with the operator,  with openid integration (in my case keycloak) and groups being returned for RBAC purposes, the login process fails if the token being returned is larger than ~2894 characters  (encoded).   In my case, large tokens are returned because we have a lot of groups being returned and it could be common to reach  8K characters.

Ref: discussion https://github.com/kiali/kiali/discussions/3870

**Versions used**
Kiali: 1.32
Istio: 1.9.2
Kubernetes flavour and version: Kubeadm 1.19.2

**To Reproduce**
1. Deploy a Kiali instance with OpenID auth against a Keycloak endpoint
2. Make sure to return group membership information in the openid client so it is part of the token body
3. Create a test user in keycloak
4. Create a series of groups, assign them to the test user up to the point the array is ~1500 characters
5. Try to login.  Once authenticated, rather than getting the kiali UI you are redirected back to the Kiali login page.  No error logged.

Notes:
- See the ingress annotation below were needed allow the large token through nginx. 
- You can reproduce the problem with rbac disabled as long as the large token is returned

My kilia CR
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    helm.sh/chart: kiali-operator-1.32.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.32.0"
    app.kubernetes.io/version: "v1.32.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
annotations:
  ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  api:
    namespaces:
      exclude:
      - "istio-operator"
      - "kube.*"
      - "default"
  auth:
    strategy: "openid"
    openid:
      client_id: "kiali-lab"
      issuer_uri: "https://keycloak-001.kd.io/auth/realms/kubernetes"
      insecure_skip_verify_tls: true
      username_claim: "email"
      disable_rbac: false
      scopes: ["openid", "groups", "email"]
  deployment:
    logger:
      log_level: debug
    accessible_namespaces:
    - '**'
    image_version: "v1.32.0"
    ingress_enabled: true
    override_ingress_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: my-nginx-ingress
          nginx.ingress.kubernetes.io/secure-backends: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
          nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
      spec:
        tls:
        - hosts:
          - kiali.my-nginx-ingress.lab01.kd.io
          secretName: kiali-tls
        rules:
        - host: kiali.my-nginx-ingress.lab01.kd.io
          http:
            paths:
            - path: /kiali
              backend:
                serviceName: kiali
                servicePort: 20001
```

**Expected behavior**
The JWT token size should not be a problem and allow Kiali UI login
