### ISSUE TITLE
does Kiali need access to HPA resources?

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3877]
As part of our [security audit](https://github.com/kiali/kiali/issues/3871) of our Kiali SA permissions, I came across:

```
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
```

The only server-side code and PRs that touch HPA resource objects [is here](https://github.com/kiali/kiali/search?l=Go&q=autoscaler) - but I don't know if this code is used anymore. It is old (introduced 3 years ago it looks like), and I don't see it used in the UI as you [see here](https://github.com/kiali/kiali-ui/search?q=autoscaler). Can someone confirm if we really need this permission/code? If not, we should consider this technical debt that should be removed both in Go code and more importantly the SA permissions.
