### ISSUE TITLE
Unable to create virtual service through Kiali UI.  Istio 1.9.2 admission fails with "subset name is invalid: 1.0"

### ISSUE THREAD

**Issue by somejfn** [kiali/kiali#3908]
**Describe the bug**
I was testing the creation of virtual services through Kiali and this was working just fine before on older Istio releases but now it fails admission control creating the simplest VS (see below).  In Kiali v1.33 logs (debug enabled):
```
2021-04-19T14:46:24Z DBG Detected Istio version [1.9.2-15c0cc2ec638bb16f39cd39972ba3c71834af878-Clean]
2021-04-19T14:48:02Z ERR admission webhook "validation.istio.io" denied the request: configuration is invalid: subset name is invalid: 1.0
2021-04-19T14:48:02Z ERR admission webhook "validation.istio.io" denied the request: configuration is invalid: subset name is invalid: 1.0
```

The VS created (all options left to default values but this view):

![kvs](https://user-images.githubusercontent.com/15197608/115256910-a5935b80-a0fd-11eb-9cc7-36255bf19e73.png)

**Versions used**
Kiali: v1.33 (via v1.33 operator)
Istio: 1.9.2
Kubernetes flavour and version: Kubeadm 1.19.2
Other note:  I just upgraded the Kiali environment from v1.32/v1.33

**To Reproduce**
1. Select a service from Kiali UI
2. Create a request routing
3. In my case I have set an exact host header match to a random hostname
4. See Isio admission control error

**Expected behavior**

Virtual service config  generated through UI should be valid.

My kiali CR:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    helm.sh/chart: kiali-operator-1.32.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.32.0"
    app.kubernetes.io/version: "v1.32.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
annotations:
  ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  api:
    namespaces:
      exclude:
      - "kube.*"
      - "saas.*"
      - "default"
  auth:
    strategy: "openid"
    openid:
      client_id: "kubernetes"
      issuer_uri: "https://keycloak-001.kd.io/auth/realms/kubernetes"
      insecure_skip_verify_tls: true
      username_claim: "email"
      disable_rbac: false
      scopes: ["openid", "groups", "email"]
  deployment:
    logger:
      log_level: debug
    accessible_namespaces:
    - '**'
    image_name: "internal.io/quay.io/kiali/kiali"
    image_version: "v1.33.0"
    ingress_enabled: false
  istio_component_namespaces:
    grafana: istio-system
    istiod: istio-system
    prometheus: istio-system
    tracing: istio-system
  server:    
    web_port: "80"
    web_fqdn: "kiali.a9igw.k8slab01.kd.io"
    web_schema: "http"
  external_services:
    grafana:
      in_cluster_url: "http://grafana.istio-system:3000"
      url: "http://grafana.a9igw.k8slab01.kd.io"
```

**Comment by somejfn** [comment]
Note the frontend service the virtual service is calling has these "app" and "version" labels set:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http-8080
  selector:
    app: frontend
    version: "1.0"
```

**Comment by lucasponce** [comment]
Hi, thanks for the issue, perhaps it's missing a sanity check in the "1.0" version.
Is that the version of the workload, isn't it ?

**Comment by somejfn** [comment]
Hi Lucas.  That version label is found in the Deployment object:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    version: "1.0"
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: "1.0"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        version: "1.0"
    spec:
      containers:
      - image: docker-test.internal.io/jfn/parrot:0.1
        imagePullPolicy: IfNotPresent
        name: parrot
        ports:
        - containerPort: 8080
          name: http-8080
```
