### ISSUE TITLE
Support for Istio's discoverySelectors

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3914]
**Is your feature request related to a problem? Please describe.**
In Istio 1.10, a new `discoverySelectors` configuration was introduced. (See [Istio 1.10 docs](https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig), [design document](https://docs.google.com/document/d/1S3GPCUBmTmvh09NmpuMCG3vwDTNkVeRhGT3lbLyA4qs/edit?resourcekey=0-a8iMutRwjQElYN5dlgEDdw#heading=h.gryauiau89tc), and the [merged PR implementing the feature](https://github.com/istio/istio/pull/29802)).

The `discoverySelectors` option limits the set of namespaces that Istio processes. If I understand correctly, this means that only the _selected_ namespaces will be part of the mesh.

**Describe the solution you'd like**
Currently, Kiali assumes that the Istio ControlPlane is given access to all namespaces. Despite this, Kiali can be configured with a restricted set of namespaces (aka `accessible_namespaces`). 

However, if Istio's `discoverySelectors` configuration is set, it's **probably** desired that Kiali takes into accounts this setting to also properly limit namespace visibility, to make scoped validations, to treat any service outside the configured set as external to the mesh, etc.

**Describe alternatives you've considered**
We could leave Kiali as is and ask users to use the `accessible_namespaces` option.

**Comment by lucasponce** [comment]
It's interesting.
I think we need to explore how to integrate in the future.

Note that in a previous Istio Meetup one user described a real scenario where he would like to see how a migration into a ServiceMesh is going, meaning that showing namespaces and workloads that are part of the mesh and which not is also a business goal that Kiali addresses today.

So, I guess we'll have users that may want to see only namespaces/workloads in the mesh, or users that may see both.

**Comment by jshaughn** [comment]
As I understand it it's not necessarily for visibility but rather for efficiency.  The control plane can't distinguish namespaces that are and are not in the mesh (I guess), and so it just assumes everything is in the mesh.  And that increases what it needs to watch.  In OSSM I believe we are explicitly told which namespace are in the mesh, but upstream did not have anything similar.

As for what we do with DiscoverSelectors, I guess we could minimally display them, and potentially configure them.  As for our accessible_namespaces, it would seem that that could be automatically narrowed to be a proper subset of Istio's discoveredNamespaces.

A useful blog: https://istio.io/latest/blog/2021/discovery-selectors/

GIven the 1.10 release, I'm moving this to the backlog.

**Comment by lucasponce** [comment]
I think this is related with the main discussion https://github.com/kiali/kiali/discussions/4081

It may be a followup task, but first in the discussion there should be a design proposal about how to represent control planes in Kiali (from configuration, registration, etc), and also how to visualize them.

This task can be a task related the "registration" of new control planes into Kiali.

Keep it open, but I've removed the "backlog" label until discussion can progress.

**Comment by nrfox** [comment]
Perhaps a first step for support could be simply respecting the discovery selectors if they exist and `accessible_namespaces` hasn't been set. This default behavior could be used to limit Kiali's namespaces to what is selected by the discovery selectors if `accessible_namespaces` is not set. That way, the default would follow Istio and the `accessible_namespaces` field could be used to override it in the case where you want Kiali to see workloads outside the mesh. The operator would need to be updated as well if it sets `accessible_namespaces` by default.

**Comment by jmazzitelli** [comment]
We'd need to be careful about how accessible_namespaces is processed. Very important setting that the operator deals with and does alot of processing around. I would say do not look for an unset value but instead introduce some special keyword or value that goes in the accessible_namespaces setting (similar to how we use the `**` special marker to indicate "all namespaces").

Note also that this "special processing" that the operator does includes adding roles to the namespaces in order for Kiali server to see those namespaces. If the operator cannot determine what namespaces are included when istio uses discovery selectors, then it won't be able to create the roles to give Kiali access to those namespaces. So this may be more difficult than it originally appears.

**Comment by israel-hdez** [comment]
> If the operator cannot determine what namespaces are included when istio uses discovery selectors

I would rule out processing discovery selectors in the operator, because that would mean that the kiali-operator requires Istio to be installed before creating a KialiCR, but we haven't required this. I think nowadays is quite possible to install Kiali first and then Istio.... Unless we want to depend on Istio being installed first?

Personally, I'd lean towards processing the discovery selectors within the back-end.

**Comment by nrfox** [comment]
> Personally, I'd lean towards processing the discovery selectors within the back-end.

Agree on doing this in the back-end. One large benefit of respecting discovery selectors is in reducing the size of the kube cache and kiali's resource footprint especially now that kiali supports cluster scoped caching. 

I'd propose that the discovery selectors be an additional filter when `accessible_namespaces == **`. Discovery selectors would be used to filter the kiali cache watches to only those namespaces matching the discovery selectors. Kiali would still have access to those namespaces so it would just be a resource optimization. If you wanted to limit Kiali's access to specific namespaces you'd still need to set `accessible_namespaces`. In the case of `accessible_namespaces != **`, I don't think Kiali needs to do anything with discovery selectors since you are already limiting the set of namespaces that Kiali watches by what it can access.

**Comment by jmazzitelli** [comment]
We have several "selectors" settings in Kiali. We should think about eliminating/combining some of them. The Istio discoverySelector seems like something we would want to use, but let's not forget that Kiali has the ability to limit the scope of what Kiali can see. Do we still want to maintain that capability?

For example, a mesh might include 100 namespaces, but perhaps someone only wants Kiali to see 50 of them? I don't know if that's a valid use case or not. If not, then we could just say, "we use the Istio discoverySelector to determine what Kiali has access to. Otherwise, Kiali has access to all namespaces in the cluster". We could then deprecate things like accessible_namespaces and all the includes/excludes we have in the Kiali CR.

**Comment by nrfox** [comment]
> I don't know if that's a valid use case or not. If not, then we could just say, "we use the Istio discoverySelector to determine what Kiali has access to.

I haven't heard of that and that doesn't seem like something that is worth supporting and regardless IMO being able to simplify all the other ways that Kiali can narrow it's namespace scope is a worthwhile tradeoff.

Today the cache looks at the `accessible_namespaces` field to determine if it is cluster scoped or not so if the `accessible_namespaces` field is being deprecated then Kiali will either need a `cluster scoped` flag or the cache will need to do something like a cluster wide `Get Namespaces` to determine if it is cluster scoped or not.

**Comment by jmazzitelli** [comment]
> Kiali will either need a `cluster scoped` flag

I envision we could do something like this in Kiali CR (to replace everything else namespace selector wise!):

```yaml
spec:
  deployment:
    use_istio_discovery_selectors: true
```

If that setting is "true" then Kiali can look in the istio ConfigMap (the configmap found in the istio_namespace - we have settings already that point to this configmap) and grab the discoverySelectors and use those where ever we need to get a list of namespaces (e.g. we use the list of namespaces those selectors return in the place of accessiblie_namespaces)

If that setting is "false" then we do the same things we'd do if accessible_namespaces is set to "**" (i.e. assume we can see all namespaces cluster-wide).

In this case we can make obsolete the label_selector_include/exclude settings as well as the namespace.include/exclude and that cache namespace list.

**Comment by jshaughn** [comment]
As a premise, Kiali should only be interested in namespaces that are in-mesh, therefore namespaces that Istio is caring about.  Prior to Discovery Selectors, or for users not using them, all namespaces are basically in-mesh for Istio.  But users didn't really care because istio itself doesn't really make it obvious.  But then they ask to narrow the set in Kiali, because they open up the Kiali UI and it's made very obvious.  So either for security reasons or just to simplify the Kiali UI they use our various options for declaring accessible namespaces.  The exception, of course is OSSM, and so I think we'd need to keep support as-is for OSSM 2.x. (crazy idea: perhaps the 2.4 version of Kiali should be the final version of Kiali for OSSM 2.x?)

I like where Mazz is going with this as a way to simplify our current namespace management; although necessary, it's confusing.  It may be the case that users want to restrict Kiali to a more narrow set than what is described in the discovery selectors, but I'm not sure we need to support that use case.  If we do then I'd suggest we keep our  label_selector_include/exclude settings.

I'm not actually sure we even need `spec.deployment.use_istio_discovery_selectors`.    I think maybe we should ALWAYS use them, because we should never be presenting namespaces that istio itself is not considering to be in-mesh.   If Kiali users see too many namespaces then the answer would be to tell the users to define discovery selectors (and of course, Kiali could help with this, right?).

I think the question then is just what kind of auth will Kiali have, cluster-wide or explicit access to the namespaces described by the discovery selectors?

```
spec:
  deployment:
    cluster_scope: true
```

If false we get permissions only to the namespaces defined by the discovery selectors, and set up explicit watches for the cache.

**Comment by jmazzitelli** [comment]
I'm going to do some thinking on this and see if I can come up with something to try out.

**Comment by jmazzitelli** [comment]
To configure Istio with discoverySelectors:

1. `kubectl edit cm istio -n istio-system`
2. Add this to the `data.mesh` yaml within the ConfigMap (each matchLabel/Expression is disjunctive i.e. evaluated as OR expressions):
```yaml
discoverySelectors:
- matchLabels:
    env: prod
    region: us-east1
- matchExpressions:
  - key: app
    operator: In
    values:
      - cassandra
      - spark
```

See the [k8s labels/selectors doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) for info on selectors and the [Istio docs](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig) for the [istio selector syntax](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#k8s-io-apimachinery-pkg-apis-meta-v1-LabelSelector) that mimics the [k8s label selector syntax](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#labelselectorrequirement-v1-meta)

**Comment by jmazzitelli** [comment]
To configure the operator watch for new namespaces (which may be necessary because the operator will have to re-examine the discoverySelectors to see if they match the new namespace), add this to `watches.yml` - but note the playbook to be run has to check to see if Kiali CR exists (it may not). The operator will be told to reconcile for every namespace, so the playbook needs to be fast.
```
- version: v1
  group: ""
  kind: Namespace
  playbook: playbooks/kiali-new-namespace-detected.yml
  reconcilePeriod: "0s"
  watchDependentResources: False
  watchClusterScopedResources: False
  watchAnnotationsChanges: True
```

**Comment by jmazzitelli** [comment]
Just more notes that I want to document.

Here's the ansible tasks used to obtain the discoverySelectors from istio configmap:

```yaml
  - name: Get the real istio_config_map_meshconfig
    vars:
      istio_config_map_resource: "{{ lookup(k8s_plugin, api_version='v1', kind='ConfigMap', namespace=kiali_vars.istio_namespace, resource_name=kiali_vars.external_services.istio.config_map_name) | default({}) }}"
    set_fact:
      istio_config_map_meshconfig: "{{ istio_config_map_resource.data.mesh | from_yaml }}"
    when:
    - istio_config_map_resource | length > 0
  - debug:
      msg: "Cannot read the Istio ConfigMap named [{{ kiali_vars.external_services.istio.config_map_name }}] from namespace [{{ kiali_vars.istio_namespace }}]."
    when:
    - istio_config_map_meshconfig is not defined
```

Then you can query k8s to get all the namespaces that match. Note this uses the new filter_plugin that I plan on submitting (parse_selectors):

```yaml
  - name: Find namespaces selected by the discovery selectors
    set_fact:
      discovery_selector_namespaces: "{{ (discovery_selector_namespaces|default([]) + query(k8s_plugin, kind='Namespace', label_selector=(item|join(',')))) | unique }}"
    vars:
      discovery_selectors: "{{ istio_config_map_meshconfig.discoverySelectors | parse_selectors }}"
    loop: "{{ discovery_selectors }}"

  - name: Get just the names of the discovered namespaces
    set_fact:
      discovery_selector_namespaces_names: "{{ discovery_selector_namespaces_names|default([]) + [item.metadata.name] }}"
    loop: "{{ discovery_selector_namespaces }}"
```

Because the namespace resources aren't needed, should consider another task to GC them:

```yaml
  - name: Garbage collect discovered namespaces to free up space
    set_fact:
      discovery_selector_namespaces: []
```

But at that point, the variable `discovery_selector_namespaces_names` is an array of namespace names - those are the namespaces that matched the discovery selector.

**Comment by jmazzitelli** [comment]
We may be ripping out the discovery selector processing in the operator itself. But just in case it needs to be resurrected, here's the bulk of the ansible code that did it.

This is the task that is used to process discovery selectors and then put the namespaces in accessible namespaces (`roles/default/kiali-deploy/tasks/get-discovery-selector-namespaces.yml`):

```yaml
# This will use the Istio ConfigMap meshConfig.discoverSelectors to discover namespaces that Kiali should be given access to.
# If the discoverySelectors are not defined, Kiali will be given cluster-wide access (i.e. the normal behavior with accessible_namespaces set to ['**']).
# If the discoverySelectors are defined but result in 0 namespaces discovered, then Kiali will ultimately only be given access to the control plane namespace.

- name: If we need the discoverySelectors, read the Istio ConfigMap and get meshConfig
  vars:
    istio_config_map_resource: "{{ ({'data': {'mesh': {}}}) if '**' not in kiali_vars.deployment.accessible_namespaces else (lookup(k8s_plugin, api_version='v1', kind='ConfigMap', namespace=kiali_vars.istio_namespace, resource_name=kiali_vars.external_services.istio.config_map_name, errors='warn') | default({})) }}"
  set_fact:
    istio_config_map_meshconfig: "{{ istio_config_map_resource.data.mesh | from_yaml }}"
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'
  - istio_config_map_resource.data is defined
  - istio_config_map_resource.data.mesh is defined
- fail:
    msg: "Cannot read the Istio ConfigMap named [{{ kiali_vars.external_services.istio.config_map_name }}] from namespace [{{ kiali_vars.istio_namespace }}]."
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'
  - istio_config_map_meshconfig is not defined

- name: Find namespaces selected by the discovery selectors
  vars:
    discovery_selectors: "{{ istio_config_map_meshconfig.discoverySelectors|default([]) | parse_selectors }}"
  set_fact:
    discovery_selector_namespaces: "{{ (discovery_selector_namespaces|default([]) + query(k8s_plugin, kind='Namespace', label_selector=(item|join(',')))) | unique }}"
  loop: "{{ discovery_selectors }}"
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'

- name: Get just the names of the discovered namespaces
  set_fact:
    discovery_selector_namespaces_names: "{{ discovery_selector_namespaces_names|default([]) + [item.metadata.name] }}"
  loop: "{{ discovery_selector_namespaces|default([]) }}"
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'

- name: Garbage collect discovered namespaces to free up space
  set_fact:
    discovery_selector_namespaces: []
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'
  - discovery_selector_namespaces is defined

- name: Use discovered namespaces for accessible_namespaces
  set_fact:
    kiali_vars: "{{ kiali_vars | combine({'deployment': {'accessible_namespaces': (discovery_selector_namespaces_names|default([]))}}, recursive=True) }}"
  when:
  - '"**" in kiali_vars.deployment.accessible_namespaces'
  - istio_config_map_meshconfig.discoverySelectors | default([]) | length > 0
```

And here is the parse_selectors filter used by the above Ansible task (`roles/default/kiali-deploy/filter_plugins/parse_selectors.py`):

```py
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from ansible.errors import AnsibleFilterError

ANSIBLE_METADATA = {
  'metadata_version': '1.1',
  'status': ['preview'],
  'supported_by': 'community'
}

# Given a list of label selectors in the standard k8s format, convert to the format that the k8s ansible collection wants.
# For example, given this input:
# - matchLabels:
#     foo: bar
# - matchLabels:
#     color: blue
#   matchExpressions:
#   - key: region
#     operator: In
#     values:
#     - east
#     - west
# an array will be returned with two items.
# The first is a list with one item that is "foo=bar".
# The second is a list with two items. The first item being "color=blue" and the second item being "region in (east, west)"
#
# See:
# * https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
# * https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html#parameter-label_selectors
def parse_selectors(value):
  # these are the selectors that should be OR'ed together - this is the final result returned back from this function
  selectorOr = []
  selectorOrIndex = 0

  # for each item in the selectors list, there can be one matchLabels and one matchExpressions (both can be there, or just one of them).
  for selectors in value:
    selectorOr.append([])

    # process the matchLabels - each results in "labelName=labelValue" strings
    if "matchLabels" in selectors:
      if (selectors["matchLabels"] is None) or (len(selectors["matchLabels"]) == 0):
        raise AnsibleFilterError("Selector matchLabels is empty")
      for k, v in selectors["matchLabels"].items():
        expr = k + "=" + v
        selectorOr[selectorOrIndex].append(expr)

    # process the matchExpressions - each results in something like "labelName notin (labelValue, labelValue2)"
    if "matchExpressions" in selectors:
      for me in selectors["matchExpressions"]:
        if "key" not in me:
          raise AnsibleFilterError("Selector matchExpression is missing 'key'")
        key = me["key"]

        if "operator" not in me:
          raise AnsibleFilterError("Selector matchExpression is missing 'operator'")
        operator = me["operator"].lower()

        if (operator == "in" or operator == "notin") and ("values" not in me or me["values"] is None or (len(me["values"]) == 0)):
          raise AnsibleFilterError("Selector matchExpression is missing a non-empty 'values'")
        values = me["values"] if "values" in me else []
        valuesStr = "("
        for i, v in enumerate(values):
          if i > 0:
            valuesStr += ","
          valuesStr += v
        valuesStr += ")"

        if operator == "in":
          selectorOr[selectorOrIndex].append(key + " in " + valuesStr)
        elif operator == "notin":
          selectorOr[selectorOrIndex].append(key + " notin " + valuesStr)
        elif operator == "exists":
          selectorOr[selectorOrIndex].append(key)
        elif operator == "doesnotexist":
          selectorOr[selectorOrIndex].append("!" + key)
        else:
          raise AnsibleFilterError("Selector matchExpression has invalid operator: " + operator)

    selectorOrIndex = selectorOrIndex + 1

  return selectorOr

# ---- Ansible filters ----
class FilterModule(object):
  def filters(self):
    return {
      'parse_selectors': parse_selectors
    }

# TEST
#first = {
#  "matchLabels":      { "sport": "football", "region": "west" },
#  "matchExpressions": [{ "key": "region", "operator": "In", "values": ["east" ]}, { "key": "sport", "operator": "Exists"}]
#}
#second = {
#  "matchLabels":      { "region": "east", "sport": "golf" },
#}
#third = {
#  "matchExpressions": [{ "key": "sport", "operator": "In", "values": ["baseball", "football" ]},{ "key": "region", "operator": "NotIn", "values": ["east" ]}]
#}
#fourth = {
#  "matchExpressions": [{ "key": "sport", "operator": "NotIn", "values": ["baseball", "football" ]},{ "key": "region", "operator": "Exists"},{ "key": "foo", "operator": "DoesNotExist"}]
#}
#print ("The following should be successful:")
#print (parse_selectors([first, second, third, fourth]))
#print ("The following should result in an error:")
#print (parse_selectors([{"matchExpressions": [{ "key": "sport", "operator": "XIn"}]}]))
```
