### ISSUE TITLE
override service name in kiali operator

### ISSUE THREAD

**Issue by rwong2888** [kiali/kiali#3920]
Kiali server helm chart has an override for the kiali service, but it looks like it is not being maintained.

I would like a kiali service name override in kiali operator because I am deploying kiali in multiple clusters on a multicluster service mesh and want the service names to be unique so they do not clash in mcs.

**Comment by jmazzitelli** [comment]
Can you explain more what you want?

I will say the name overrides in the server helm chart is something unique to the kiali server helm chart. The operator is not going to let you change the names of the resources.

But Kiali Operator is able to install Kiali in multiple clusters (and in fact in multiple namespaces in the same cluster) without problems. So we need to know what you are trying to do with more details.

**Comment by rwong2888** [comment]
So my setup is a 4 cluster multicluster mesh. 

On each cluster, I have kiali cluster URL -> istio gateway -> virtual service -> kiali service.

Each cluster has kiali deployed to it with the kiali server helm chart, overriding the kiali service name as kiali-[clustername].

The reason for overriding the kiali service name is to make it unique. Otherwise, if the kiali service name is kiali on all 4 clusters, when I hit the kiali cluster URL, the mcs routing kicks in and it could route to any of the 4 clusters instead of the specified cluster's kiali. When this happens, login does not work.

I would like to move to kiali operator as that looks directional, and kiali helm chart seems to have some issues with it. 
e.g. requiring deployment.pod_anti.hack.yes instead of simply deployment.affinity.pod_anti
https://github.com/kiali/helm-charts/blob/master/kiali-server/values.yaml#L33
https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/deployment.yaml#L138
```
      deployment:
        pod_anti:
          hack: yes
        affinity:
          pod_anti:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - prometheus
```

Migrating to kiali operator would be dependent upon this kiali service override feature.
