### ISSUE TITLE
Multi-cluster discovery leads to time out while fetching server configs, blocking access

### ISSUE THREAD

**Issue by rwong2888** [kiali/kiali#3947]
I installed kiali 1.33.1 and it is not loading on one cluster in nonprod and prod, but it works on every other cluster (although sometimes slow login times). This was same experience with 1.33.0 as well.

When I revert back to 1.32.0 it works.

The browser says:

> You are logged in, but there was a problem when fetching some required server configurations. Please, try refreshing the page.

All I see in the logs are

```
2021-04-26T19:00:50Z INF Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
```

Kiali server helm values

```
auth:
  openid:
    client_id: [redacted]
    disable_rbac: true
    issuer_uri: [redacted]
    username_claim: email
  strategy: openid
deployment:
  affinity:
    pod_anti:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - prometheus
          topologyKey: topology.kubernetes.io/zone
        weight: 100
  ingress_enabled: false
  node_selector:
    cloud.google.com/gke-nodepool: monitoring
  pod_anti:
    hack: true
  view_only_mode: true
external_services:
  grafana:
    auth:
      password: [redacted]
      type: basic
      username: admin
    in_cluster_url: http://prometheus-stack-core-grafana:80/
    url: https://core-forbes-development.grafana.forbes.com
  prometheus:
    url: http://core-prometheus:9090/
fullnameOverride: kiali-core
istio_namespace: istio-system
nameOverride: kiali-core
```
