### ISSUE TITLE
Reconciliation may fail when removing a namespace from a cluster immediately after removing it from spec.deployment.accessible_namespaces

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3949]
**Describe the bug**
After changes introduced by https://github.com/kiali/kiali-operator/pull/293 which was required to speed up Kiali reconciliation it is now possible that the reconciliation will fail when a namespace is removed from a cluster immediately after removing it from `spec.deployment.accessible_namespaces`. The failure is:
```
TASK [default/kiali-deploy : Remove Kiali label from namespaces that Kiali no longer has access to] ***
Monday 26 April 2021  13:00:51 +0000 (0:00:00.648)       0:00:56.297 **********
�[0;31mfatal: [localhost]: FAILED! => {"changed": false, "error": 403, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"namespaces is forbidden: User \\\\\"system:serviceaccount:kiali-operator:kiali-operator\\\\\" cannot create resource \\\\\"namespaces\\\\\" in API group \\\\\"\\\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"namespaces\"},\"code\":403}\\n'", "reason": "Forbidden", "status": 403}�[0m
```
There is a https://github.com/ansible-collections/kubernetes.core/issues/84 which will allow kiali operator to resolve this problem.

**Versions used**
Kiali UI
1.33.0 (3fee4558a3a4f606828768407038dbf6f412196a)
Kiali Server
v1.33.0-SNAPSHOT (60ecd61)
Istio: 1.9.3
Kubernetes flavor and version: (e.g. OpenShift Origin 3.9)
OCP 4.7
Kiali operator with changes from https://github.com/kiali/kiali-operator/pull/293

**To Reproduce**
1. Create e.g. 10 empty namespaces and add all of them to `spec.deployment.accessible_namespaces`
2. Wait for reconciliation to finish
3. Remove all 10 of them from `spec.deployment.accessible_namespaces` and remove IMMEDIATELY also all 10 namespaces from a cluster

**Expected behavior**
Reconciliation should be successful.

**Comment by jmazzitelli** [comment]
Once that [enhancement request](https://github.com/ansible-collections/kubernetes.core/issues/84) makes it into the k8s collection, we can implement a fix for this issue.

**Comment by jmazzitelli** [comment]
Here's the PR to implement the enhancement request: https://github.com/ansible-collections/kubernetes.core/pull/90

**Comment by jmazzitelli** [comment]
That PR has been merged into master of kubernetes collection. Now we just have to wait for it to be available in the ansible operator SDK base image that we use.

**Comment by jmazzitelli** [comment]
To implement this using that new feature in ansible kubernetes collection `k8s` task, use `state: patched` now when manipulating labels on namespaces. And note also below where we can get rid of that inner-if-statement checking if the namespace is in all-namespaces - this has a race condition anyway (the namespace may have been deleted while in that for loop) so there is no need to keep it around now that `state: patched` ensures it won't process the namespace if it doesn't exist.

https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L779
and
https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L804

```
- name: Remove Kiali label from namespaces that Kiali no longer has access to
  vars:
    # everything to the left of the = is the name of the label we want to remove
    the_namespace_label_name: "{{ current_label_selector | regex_replace('^(.*)=.*$', '\\1') }}"
  # if a namespace happened to have been deleted, we do not want to (nor can we) resurrect it, hence we check for its existence
  k8s:
    state: patched     <<<<<<<<< HERE
    definition: |
      {% for namespace in no_longer_accessible_namespaces %}
      {% if namespace in all_namespaces %}    <<<<< WE SHOULD BE ABLE TO REMOVE THIS IF-STMT
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          {{ the_namespace_label_name }}: null
      ...
      {% endif %}
      {% endfor %}
  when:
  - no_longer_accessible_namespaces is defined
  - current_label_selector is defined

- name: Create additional Kiali label on all accessible namespaces
  vars:
    namespaces: "{{ kiali_vars.deployment.accessible_namespaces }}"
    # everything to the left of the = is the label name; to the right is the label value
    the_namespace_label_name: "{{ kiali_vars.api.namespaces.label_selector | regex_replace('^(.*)=.*$', '\\1') }}"
    the_namespace_label_value: "{{ kiali_vars.api.namespaces.label_selector | regex_replace('^.*=(.*)$', '\\1') }}"
  k8s:
    state: patched     <<<<<<<<< HERE
    definition: |
      {% for namespace in namespaces %}
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          {{ the_namespace_label_name }}: {{ the_namespace_label_value }}
      ...
      {% endfor %}
  when:
  - '"**" not in kiali_vars.deployment.accessible_namespaces'
```

and

https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-remove/tasks/main.yml#L146

```
- name: Remove Kiali label from namespaces found in current accessible namespaces
  ignore_errors: yes
  vars:
    # everything to the left of the = is the name of the label we want to remove
    the_namespace_label_name: "{{ current_label_selector | regex_replace('^(.*)=.*$', '\\1') }}"
  # if a namespace happened to have been deleted, we do not want to (nor can we) resurrect it, hence we check for its existence
  k8s:
    state: patched     <<<<<<<<< HERE
    definition: |
      {% for namespace in current_accessible_namespaces %}
      {% if namespace in all_namespaces %}    <<<<< WE SHOULD BE ABLE TO REMOVE THIS IF-STMT
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          {{ the_namespace_label_name }}: null
      ...
      {% endif %}
      {% endfor %}
  when:
...
```
