### ISSUE TITLE
[operator] make sure we use community.kubernetes.k8s tasks correctly

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3976]
I just ran into [an interesting problem in a generic ansible playbook](https://github.com/ansible-collections/community.kubernetes/issues/426), but the problem can manifest itself in our operator. We need to check our operator's ansible code and make sure we aren't doing the same problem.

We must not use `k8s` tasks in our playbooks - we must either always specify the full name `community.kubernetes.k8s` or we must ensure the playbooks have this specification:

```
collections:
- community.kubernetes
```

as in:

```
 hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  collections:
  - community.kubernetes
...
```

The latter is preferable as suggested to me in the ansible slack room - so we should go through our ansible files and replace `community.kubernetes.k8s` with simply `k8s` but ensure we add the `collections: ["community.kubernetes"]` to the playbook.
