### ISSUE TITLE
Further lock down kiali server pod security

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4023]
Now that the Kiali Server [does not require write access](https://github.com/kiali/kiali/pull/4022) to any file system, we should lock down the pod security a bit more.

We should change these files:

* https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
* https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/deployment.yaml
* https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/deployment.yaml

such that in the Kiali Deployment's `kiali` container, we add these constraints:

```
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
```
