### ISSUE TITLE
web_fqdn for private urls

### ISSUE THREAD

**Issue by rwong2888** [kiali/kiali#4039]
Getting this error on a mcs setup. Kiali v1.34.1

> Not all remote clusters have reachable Kiali instances.
Hide Detail
Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL.

I set up web_fqdn as referenced below:

* https://github.com/kiali/kiali-operator/blob/54e951ebea725a8ac7b9ae683c7ba1160d54990e/deploy/kiali/kiali_cr.yaml#L821-L828
* https://github.com/kiali/kiali/discussions/4038#discussioncomment-768608
* https://github.com/kiali/kiali/issues/3947#issuecomment-841166343

Note:
I am not using a public URL. Is it possible to use internal URLs? Or service endpoints or IPs?
>Defines the public domain where Kiali is being served. 

Using ansible wrapper to kiali server helm chart:

```
release_values:
  server:
    web_fdqn: "{{ webFQDN }}"
```

And I see it in the kiali configmap

```
apiVersion: v1
data:
  config.yaml: |
    [...]
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_fdqn: https://miscellaneous-forbes-development.kiali.forbes.com
      web_root: /kiali
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kiali-server-miscellaneous
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kiali-miscellaneous
    app.kubernetes.io/instance: kiali-server-miscellaneous
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali-miscellaneous
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.34.1
    helm.sh/chart: kiali-server-1.34.1
    version: v1.34.1
  name: kiali-miscellaneous
  namespace: monitoring
```

**Comment by jmazzitelli** [comment]
That is not a valid value for web_fqdn. It is an FQDN, not a URL.

Please see: https://github.com/kiali/kiali-operator/blob/v1.34.0/deploy/kiali/kiali_cr.yaml#L821-L828

And I have no idea what this "error" is:

```
Getting this error on a mcs setup. Kiali v1.34.1

> you'll need to have one of your coworkers with Owner Permissions send an invite to jenkinscloud@forbes.com. They'll need to trigger the invite via this Invite Page.
```

**Comment by rwong2888** [comment]
It's a jinja wrapper. It gets evaluated to https://miscellaneous-forbes-development.kiali.forbes.com. See the configmap. 

Perhaps I need to drop the ```https://``` as mentioned in https://github.com/kiali/kiali-operator/blob/54e951ebea725a8ac7b9ae683c7ba1160d54990e/deploy/kiali/kiali_cr.yaml#L821-L828

But the cr yaml says it needs to be public, which I think may be the issue, as it is not public.

Sorry, bad copy paste. I have updated the description to properly reflect.

>Not all remote clusters have reachable Kiali instances.
Hide Detail
Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL.

**Comment by jmazzitelli** [comment]
> Perhaps I need to drop the `https://` as mentioned in https://github.com/kiali/kiali-operator/blob/54e951ebea725a8ac7b9ae683c7ba1160d54990e/deploy/kiali/kiali_cr.yaml#L821-L828

Exactly. `server.web_fqdn` is a FQDN (a domain name) not a URL... take away "https://" because that makes it a URL not a domain name. If you want to specify a schema (i.e. "https") that is what `server.web_schema` is for... again, consult that kiali_cr.yaml link for details on that setting.

**Comment by rwong2888** [comment]
I stripped out "https://" and still getting the warning message. I believe it is due to being an internal URL instead of an external URL.

What functionality am I losing out on if it cannot discover the other kialis?

Any way to overcome this?

**Comment by jmazzitelli** [comment]
@israel-hdez would know the answer to that

**Comment by israel-hdez** [comment]
On the operator templates, both the `web_fqdn` and the `web_schema` are needed so that the needed annotation is set. See: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/service.yaml#L8-L10

It's the same case when using helm charts: https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/service.yaml#L13-L19

You can manually set the `kiali.io/external-url` annotation on the Kiali service if it refuses to work.

**Comment by israel-hdez** [comment]
Also, to check what Kialis have the missing configuration, you can go to the "Mesh" page. Rows with plain text in the "Kiali" column (rather than links) are the Kialis with the missing config:

![](https://user-images.githubusercontent.com/23639005/111009503-6b45da00-8359-11eb-9fd6-759cc97d2c9e.png)

**Comment by israel-hdez** [comment]
@rwong2888 Is your issue solved?

**Comment by israel-hdez** [comment]
I'm closing.
If your issue is not solved yet, feel free to re-open.

**Comment by unckleg** [comment]
@rwong2888 

You are getting this error because you have typo in your config map. And for everyone else wondering:

```yaml
server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_fdqn: https://miscellaneous-forbes-development.kiali.forbes.com
      web_root: /kiali
````

**web_fdqn** part should be **web_fqdn**, also make sure to remove https part.
