### ISSUE TITLE
Provide separate label lookups for Istio components and normal applications

### ISSUE THREAD

**Issue by JordanFaust** [kiali/kiali#4045]
Kiali made changes to the [labels used to lookup applications](https://github.com/kiali/kiali/issues/3547) to allow users to control what label names are used in the lookup. This changes the lookup for both "Istio Components" and applications. While it is possible to change labels in an Istio deployment it is not easy and Istio more or less does not want you to do it. However, that does not mean applications also need to be limited to the same "app" label restriction. Kiali should offer separate configuration for the app/version labels used for looking up "Istio Components" and normal applications

**Describe the solution you'd like**
Provide separate configuration for the labels used to lookup the istio components. This should also support canary/revision deployment lookups of the istio components taking into considering the restrictions that the IstioOperator places on the labels on the istiod and other "Istio Components".

 
```
istio_labels:
  app_label_name: "app"
  version_label_name: "istio.io/rev"

app_labels:
  app_label_name: "app.kubernetes.io/name"
  version_label_name: "version"

external_services:
  istio:
    component_status:
      components:
      - app_label: "istiod"
        version_label: "1-7"
        is_core: true
        is_proxy: false
```

**Describe alternatives you've considered**

**Additional context**
It is already possible to deploy an instance of Kiali that is only focused on a subset of applications using an Istio revision through the use of the label_selector under the api config. This provides the missing pieces in finding applications by app/version labels and additionally the "Istio Components" using the more or less hardcoded labels used by the Istio Operator.
