### ISSUE TITLE
Possible false positive reported as violating KIA0202

### ISSUE THREAD

**Issue by ferrarimarco** [kiali/kiali#4049]
**Describe the bug**

Kiali is reporting a violation of the KIA0202 ([description](https://kiali.io/documentation/latest/validations/#_kia0202_this_host_has_no_matching_entry_in_the_service_registry_service_workload_or_service_entries), [source](https://github.com/kiali/kiali/blob/master/business/checkers/destinationrules/no_dest_checker.go)) rule on a DestinationRule that points to a ServiceEntry, which I believe it's a false positive.

The workload is running in a VM that I added to the Istio mesh.

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productpage
spec:
  hosts:
    - productpage.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
  resolution: DNS
  workloadSelector:
    labels:
      app: productpage
      instance-id: source-environment-vm
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.default.svc.cluster.local # <- Kiali reports the KIA0202 validation error here
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
...
```

**Versions used**
```
Kiali UI: 1.34.1 (cda505c688a0e8b6ce65dd80ca0203a5153d977d)
Kiali Server: v1.34.1 (31fc3596219485ab2e37d3968dc54910f3378992)
Kiali Container: v1.34.1

Istio: 1.10.0
Prometheus: 2.24.0
Kubernetes: v1.20.6-gke.1000
Grafana URL: N/A
Jaeger URL: N/A
```

**To Reproduce**
1. Provision a GKE cluster
2. Deploy the resources above
3. Open Kiali.
4. Open the Istio config page
5. Inspect the DestinationRule object
6. See the validation error

**Expected behavior**

Kiali shouldn't report a violation of the KIA0202, given that the hosts match.

Thanks!
