### ISSUE TITLE
I can't configure my custom prometheus

### ISSUE THREAD

**Issue by winds6206** [kiali/kiali#4060]
**Describe the bug**
Hi , I install istio in my GKE and everything is fine, but I wanna let my kiali to scrape my custom prometheus so modify default YAML file from istio as below

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    helm.sh/chart: kiali-server-1.29.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali-server
    version: "v1.29.0"
    app.kubernetes.io/version: "v1.29.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
data:
  config.yaml: |
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - '**'
      additional_service_yaml: {}
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      hpa:
        api_version: autoscaling/v2beta2
        spec: {}
      image_name: quay.io/kiali/kiali
      image_pull_policy: Always
      image_pull_secrets: []
      image_version: v1.29
      ingress_enabled: false
      logger:
        log_format: text
        log_level: info
        sampler_rate: "1"
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: istio-system
      node_selector: {}
      override_ingress_yaml:
        metadata: {}
      pod_annotations:
        sidecar.istio.io/inject: "false"
      pod_labels: {}
      priority_class_name: ""
      replicas: 1
      resources: {}
      secret_name: kiali
      service_annotations: {}
      service_type: ""
      tolerations: []
      version_label: v1.29.0
      view_only_mode: false
    #external_services:
    #  custom_dashboards:
    #    enabled: true
    external_services:
      custom_dashboards:
        prometheus:
          url: http://prometheus.monitoring.svc.cluster.local:9090
        namespace_label: "monitoring"
    identity:
      cert_file: ""
      private_key_file: ""
    istio_namespace: istio-system
    login_token:
      signing_key: CHANGEME
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
```

I modify this block, and deploy

```
    #external_services:
    #  custom_dashboards:
    #    enabled: true
    external_services:
      custom_dashboards:
        prometheus:
          url: http://prometheus.monitoring.svc.cluster.local:9090
        namespace_label: "monitoring"
```

when I open kiali UI again, all of about graph are pop up 
```
Cannot load the graph: Post "http://prometheus.istio-system:9090/api/v1/query": dial tcp: lookup prometheus.istio-system on 10.55.240.10:53: no such host
```

why kiali still scrape default prometheus, I try many method, but I still have no idea...

**Versions used**
Kiali: 1.29.0
Istio: 1.9.5
Kubernetes flavour and version: GKE 1.18.17-gke.700

**Expected behavior**

I expect Kiali can scrape my custom prometheus
