### ISSUE TITLE
Kiali doesn't fetch app and version information from WorkloadEntries

### ISSUE THREAD

**Issue by ferrarimarco** [kiali/kiali#4071]
**Describe the bug**

After deploying both Pods and WorkloadEntries with an `app` and `version` labels, [as Istio requires](https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements), I noticed that Kiali only loads the `version` information from the Pod, and not from the WorkloadEntry (that describes an instance of the same workload running in a VM).

![Screenshot 2021-06-07 at 12 38 37](https://user-images.githubusercontent.com/621939/121003040-57114d80-c78d-11eb-9e13-2f057390c34a.png)

Here are the related descriptors:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: whatever
  serviceAccount: bookinfo-gce
...
```

**Versions used**

```
Kiali UI
1.34.1 (cda505c688a0e8b6ce65dd80ca0203a5153d977d)
Kiali Server
v1.34.1 (31fc3596219485ab2e37d3968dc54910f3378992)
Kiali Container
v1.34.1
Components
Istio
1.10.0
Prometheus
2.24.0
Kubernetes
v1.20.6-gke.1000
```

**To Reproduce**
1. Deploy the above descriptors in a Kubernetes cluster.
2. Send traffic to the ServiceEntry or VirtualService exposing that workload.
3. Open the Versioned App Graph in Kiali.
4. Observe the results.

**Expected behavior**

Kiali should take the `app` and `version` labels defined in the WorkloadEntry into account.
