### ISSUE TITLE
Exposing workloads with ServiceEntries makes Kiali show non-existing Services

### ISSUE THREAD

**Issue by ferrarimarco** [kiali/kiali#4072]
**Describe the bug**

I deployed the [Bookinfo example application](https://github.com/istio/istio/tree/master/samples/bookinfo) to both a set of VMs and a Kubernetes cluster. I didn't deploy any Kubernetes Service. I'm using Istio ServiceEntries with `workloadSelector`s to expose both the instances of the app running in the VMs, and the ones running in Kubernetes.

Kiali shows non-existing services in the Versioned app graph and other graphs as well.

![Screenshot 2021-06-07 at 13 07 09](https://user-images.githubusercontent.com/621939/121006570-511d6b80-c791-11eb-8176-f847dcb6b94f.png)

There are multiple issues in the graph:

1. 100% of the traffic from the gateway is going to the `productpage` ServiceEntry.
2. The actual traffic that goes through the gateway should be what goes to the non-existing `prooductpage.default.svc.cluster.local` service.
3. `details`, `reviews`, and `ratings` Services should be ServiceEntries.

Relevant YAMLs:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productpage
spec:
  hosts:
    - productpage
    - productpage.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: productpage
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details
spec:
  hosts:
    - details
    - details.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ratings
spec:
  hosts:
    - ratings
    - ratings.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews
spec:
  hosts:
    - reviews
    - reviews.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: reviews
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/default-gateway
  http:
    - match:
        - uri:
            exact: /productpage
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
        - uri:
            prefix: /static
      route:
        - destination:
            host: productpage.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
    - details
  http:
    - route:
      - destination:
          host: details.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
    - ratings
  http:
    - route:
      - destination:
          host: ratings.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
      - destination:
          host: reviews.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: compute-engine
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: ratings
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: compute-engine
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: reviews
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: compute-engine
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: productpage
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: compute-engine
  serviceAccount: bookinfo-gce
...
```

**Versions used**
Kiali UI
1.34.1 (cda505c688a0e8b6ce65dd80ca0203a5153d977d)
Kiali Server
v1.34.1 (31fc3596219485ab2e37d3968dc54910f3378992)
Kiali Container
v1.34.1
Components
Istio
1.10.0
Prometheus
2.24.0
Kubernetes
v1.20.6-gke.1000

**To Reproduce**

1. Deploy the Bookinfo app on VMs
2. Deploy the above descriptors in a Kubernetes cluster
3. Deploy the Bookinfo `Deployment`s only (NOT SERVICES)
4. Generate traffic to the Gateway exposing the `productpage` service.
5. Observe the Versioned App Graph

**Expected behavior**

1. The traffic to be correctly reported to ServiceEntries.
2. Kiali not showing non-existing Services.
3. Kiali rendering ServiceEntries as ServiceEntries, not as Services.
