### ISSUE TITLE
[OIDC] Can't connect with Gsuite

### ISSUE THREAD

**Issue by ichasco-heytrade** [kiali/kiali#4100]
Hi, I follow the steps in this article:

https://kiali.io/documentation/latest/configuration/authentication/openid/#_using_with_google_cloud_platform_gke_oauth2

Versions:
* kiali: 1.35.0
* Istio: 1.10.0
* EKS: v1.19.6-eks-49a6c0

Auth configuration:
```
auth:
        strategy: "openid"
        openid:
          client_id: "XXXXXXXXXXXXXX.apps.googleusercontent.com"
          disable_rbac: true
          issuer_uri: "https://accounts.google.com"
          scopes: ["openid", "email"]
          username_claim: "email"
```

secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  oidc-secret: XXXXXXXXXXXXXXXXXXXXXXXXXX
```

Errors:
```
kiali-7bcd94894d-4mslb kiali 2021-06-14T09:19:27Z INF Not handling OpenId code flow authentication: State parameter is empty or invalid.
kiali-7bcd94894d-4mslb kiali 2021-06-14T09:19:27Z DBG The AES cookie is mising.
kiali-7bcd94894d-4mslb kiali 2021-06-14T09:19:30Z DBG OpenId token request failed with response: {
kiali-7bcd94894d-4mslb kiali   "error": "invalid_client",
kiali-7bcd94894d-4mslb kiali   "error_description": "Unauthorized"
kiali-7bcd94894d-4mslb kiali }
kiali-7bcd94894d-4mslb kiali 2021-06-14T09:19:30Z ERR Failure when retrieving user identity: request failed (HTTP response status = 401 Unauthorized)
kiali-7bcd94894d-4mslb kiali 2021-06-14T09:19:31Z DBG The AES cookie is mising.
```

Thanks
