### ISSUE TITLE
Graph dashboard reports wrong request distribution

### ISSUE THREAD

**Issue by schurmann** [kiali/kiali#4137]
**Describe the bug**

The "Service graph" shows the wrong request distribution. The service `echoserver` should not have ~43% of the traffic. I'm sending traffic from a pod in the same namespace towards `echoserver`. The routing is done with a `VirtualService` managed by flagger and routes all internal traffic towards `echoserver` to `echoserver-primary` and `echoserver-canary`.

```yaml
spec:
  gateways:
  - mesh
  hosts:
  - echoserver
  http:
  - route:
    - destination:
        host: echoserver-primary
      weight: 90
    - destination:
        host: echoserver-canary
      weight: 10
```
![service-graph](https://user-images.githubusercontent.com/8396695/123981024-4a65cb00-d9c2-11eb-9962-f14ed4326d76.png)

**Versions used**
Kiali: 1.36.0
Istio: 1.10.1
Kubernetes flavour and version: minikube v1.21.0

**To Reproduce**
1. Deploy three services: `echoserver`, `echoserver-canary`, `echoserver-primary`.
2. Deploy two pods `echoserver` and `echoserver-primary`. Services `echoserver` and `echoserver-primary` select pod `echoserver-primary`.  The service `echoserver-canary` selects pod `echoserver`.
3. Deploy a VirtualService like the one above.
4. Send traffic to echoserver.
5. Open the kiali dashboard with the "Service graph" view.
6. Verify that the traffic distribution is incorrect.

**Expected behavior**
A request distribution of ~10% to echoserver-canary and ~90% to echoserver-primary.
