### ISSUE TITLE
Kiali services missing connection info with calico network policy applied

### ISSUE THREAD

**Issue by stevegszabo** [kiali/kiali#4142]
**General remarks**

When I apply a calico network policy to the application namespace kiali seems to drop the connection information under services. The network policy includes a rule to allow istio-proxy to connect to istiod. There are no rules applied to the istio-system namespace. The application functions as expected with the policy in place - nothing is blocked.

**Describe the bug**

Not sure if this is a bug or if a network policy rule specific to istio/kiali is required in order for the service connections to be visible from kiali.

Based on the kiali [architecture](https://kiali.io/documentation/latest/architecture/) there should be nothing blocking istio/kiali.

```
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  namespaceSelector: projectcalico.org/name in {'webapp', 'nginx-ingress', 'hashi-demo'}
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from all to kube-system for DNS
    protocol: UDP
    destination:
      selector: k8s-app == 'kube-dns'
      namespaceSelector: projectcalico.org/name == 'kube-system'
      ports:
      - 53
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from all to istio-system for istio-proxy
    protocol: TCP
    destination:
      selector: app == 'istiod'
      namespaceSelector: projectcalico.org/name == 'istio-system'
      ports:
      - 15012
```

```
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: presentation
  namespace: hashi-demo
spec:
  selector: app == 'presentation'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from presentation to application
    protocol: TCP
    destination:
      selector: app == 'application'
      namespaceSelector: projectcalico.org/name == 'hashi-demo'
      ports:
      - 5000
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from nginx to presentation
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'ingress-nginx'
      namespaceSelector: projectcalico.org/name == 'nginx-ingress'
    destination:
      ports:
      - 80
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from istio ingress gateway to presentation
    protocol: TCP
    source:
      selector: app == 'istio-ingressgateway'
      namespaceSelector: projectcalico.org/name == 'istio-system'
    destination:
      ports:
      - 80

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: application
  namespace: hashi-demo
spec:
  selector: app == 'application'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from application to data
    protocol: TCP
    destination:
      selector: app == 'data'
      namespaceSelector: projectcalico.org/name == 'hashi-demo'
      ports:
      - 5432
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from presentation to application
    protocol: TCP
    source:
      selector: app == 'presentation'
      namespaceSelector: projectcalico.org/name == 'hashi-demo'
    destination:
      ports:
      - 5000

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: data
  namespace: hashi-demo
spec:
  selector: app == 'data'
  types:
  - Ingress
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from application to data
    protocol: TCP
    source:
      selector: app == 'application'
      namespaceSelector: projectcalico.org/name == 'hashi-demo'
    destination:
      ports:
      - 5432
```

With policy rule in place:

![kiali-no-connection](https://user-images.githubusercontent.com/10410711/124149930-1096d200-da5f-11eb-8a75-f403af5b1a45.png)

With no policy rule in place:

![kiali-with-connection](https://user-images.githubusercontent.com/10410711/124149954-142a5900-da5f-11eb-8d5b-4cf714bdec88.png)

**Versions used**
Kiali: quay.io/kiali/kiali:v1.29
Istio: docker.io/istio/pilot:1.9.1
Kubernetes flavour and version: Kubernetes v1.21.2 running locally deployed using kubeadm

**To Reproduce**

**Expected behavior**
