### ISSUE TITLE
The namespaces that begins with `kube` are hidden (example: kubeless and kubeless-fn)

### ISSUE THREAD

**Issue by chermed** [kiali/kiali#4159]
**Describe the bug**
The namespaces that begin with `kube` are hidden from the UI
Kubeless is a serverless framework for kubernetes all workloads are in the two namespaces `kubeless` and `kubeless-fn`

**Versions used**
Kiali UI: 1.34.1 (cda505c688a0e8b6ce65dd80ca0203a5153d977d)
Kiali Server: v1.34.1 (31fc3596219485ab2e37d3968dc54910f3378992)
Kiali Container: v1.34.1
Components
Istio: 1.10.2
Prometheus: 2.21.0
Kubernetes: v1.19.9-gke.1900

**To Reproduce**
1. Go to to your kubernetes cluster
2. Create two namespvaes `kubeless` and `kubeless-fn`
3. Open the kiali dashboard `istioctl d kiali`
4. Go to the dashboard
5. The two namespaces are missing

**Expected behavior**
The only namespaces that should be hidden are` kube-system` `istio-system` and `kube-public`

I tried to force the namespace in the config but it doesn't show anything:
```
apiVersion: v1
data:
  config.yaml: |
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - 'kubeless-fn'
      additional_service_yaml: {}
```
