### ISSUE TITLE
Session logs out after 5 minutes

### ISSUE THREAD

**Issue by dicolasi** [kiali/kiali#4170]
I am using Kiali v1.3.6. Everything works correctly but every 5 minutes I see the following banner (and got logged out):

![Screenshot 2021-07-12 at 09 37 32 (1)](https://user-images.githubusercontent.com/54740533/125408842-3a32f000-e3b3-11eb-829c-03f110c4590f.png)

## Update configuration

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  auth:
    strategy: openid
    openid:
      disable_rbac: true
      client_id: "kiali-client"
      issuer_uri: https://auth.{{ .Values.jxRequirements.ingress.domain }}/auth/realms/engineering-realm
      username_claim: "email"
      authentication_timeout: 60
  deployment:
    ingress_enabled: false
    logger:
      log_level: info
    accessible_namespaces:
      - "jx-staging"
      - "istio-system"
      - "knative-serving"
    hpa:
      spec:
        maxReplicas: 2
        minReplicas: 1
        targetCPUUtilizationPercentage: 90
  istio_component_namespaces:
    prometheus: monitor
    grafana: monitor
  external_services:
    grafana:
      auth:
        type: "basic"
        username: "kiali"
        password: <secret>
      enabled: true
      in_cluster_url: http://kube-prometheus-stack-grafana.monitor.svc.cluster.local
      url: https://grafana.{{ .Values.jxRequirements.ingress.domain }}
    prometheus:
      auth:
        type: none
      url: http://prometheus-operated.monitor.svc.cluster.local:9090
    tracing:
      auth:
        type: none
      enabled: true
      use_grpc: true
      in_cluster_url: http://tracing.istio-system/jaeger
```

**Comment by jmazzitelli** [comment]
> I am using Kiali v1.3.6. Everything works correctly but every 5 minutes I see the following banner (and got logged out):

Just to clarify - I believe you mean `v1.36.0`

**Comment by dicolasi** [comment]
Correct @jmazzitelli. Apologies

**Comment by aljesusg** [comment]
@dicolasi confguration

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  auth:
    strategy: openid
    openid:
      disable_rbac: true
      client_id: "kiali-client"
      issuer_uri: https://auth.{{ .Values.jxRequirements.ingress.domain }}/auth/realms/engineering-realm
      username_claim: "email"
      authentication_timeout: 60
  deployment:
    ingress_enabled: false
    logger:
      log_level: info
    accessible_namespaces:
      - "jx-staging"
      - "istio-system"
      - "knative-serving"
    hpa:
      spec:
        maxReplicas: 2
        minReplicas: 1
        targetCPUUtilizationPercentage: 90
  istio_component_namespaces:
    prometheus: monitor
    grafana: monitor
  external_services:
    grafana:
      auth:
        type: "basic"
        username: "kiali"
        password: secret:kiali:grafana-password
      enabled: true
      in_cluster_url: http://kube-prometheus-stack-grafana.monitor.svc.cluster.local
      url: https://grafana.{{ .Values.jxRequirements.ingress.domain }}
    prometheus:
      auth:
        type: none
      url: http://prometheus-operated.monitor.svc.cluster.local:9090
    tracing:
      auth:
        type: none
      enabled: true
      use_grpc: true
      in_cluster_url: http://tracing.istio-system/jaeger
```
