### ISSUE TITLE
Workload Entry graph nodes display only "latest" version

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4206]
**Describe the bug**
When a `WorkloadEntry` generated from `istioctl workload entry configure ...` appears on the graph, the version displayed is always "latest" despite properly labeling the `WorkloadGroup` and `WorkloadEntry` objects with e.g. `version: v1`.

**Versions used**
Kiali: `1.36`
Istio: `1.10`
Kubernetes flavour and version: `1.21`

**To Reproduce**
1. Add a `WorkloadEntry` VM to the mesh with a version label and send traffic to it
2. Navigate to the graph and observe the node with "latest" as its version.

**Expected behavior**
Expected to see the graph node for the `WorkloadEntry` workload to display the proper version.

Note telemetry has the wrong `source_canonical_revision="latest"` label but the right `version="v1"` label.

The cause for this seems to be that when the workload entry VM files are created with `istioctl workload entry configure`, the `"service.istio.io/canonical-version"` label gets generated but not the `"service.istio.io/canonical-revision"` label.

mesh.yaml
```
...
ISTIO_METAJSON_LABELS: '{"app":"ratings","service.istio.io/canonical-name":"ratings","service.istio.io/canonical-version":"v1","version":"v1"}'
```

This may be more of an upstream issue but I wanted to post the workaround here in case others run into this same issue.

**Workaround**
A workaround is to add the `"service.istio.io/canonical-revision"` to your `WorkloadGroup`/`WorkloadEntry` objects
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: details-v1
  namespace: bookinfo
spec:
  metadata:
    labels:
      app: details
      version: v1
      service.istio.io/canonical-revision: v1
```

It might be possible for Kiali to use both `source_canonical_revision` and `service_istio_io_canonical_revision` as `service_istio_io_canonical_revision` is correctly labeled with the right version?
