### ISSUE TITLE
Scripts not loading (404) on openid_error when Kiali is hosted in a subfolder (web_root: /kiali)

### ISSUE THREAD

**Issue by stevensystems** [kiali/kiali#4215]
**Describe the bug**
When using a sub-directory to host kiali (e.g. web_root: /kiali), some statics files are still referenced using the root "/" path, and cannot be loaded (404).

![image](https://user-images.githubusercontent.com/76811102/126973881-7a129be3-6913-44c2-ba0f-e42d9e248322.png)

**Versions used**
Kiali: v1.37.0
Istio: 1.10.3
Kubernetes flavour and version: (AKS V. 1.19.11)

**To Reproduce**
1. Install Kiali operator using Helm chart:
```sh
kubectl create namespace kiali-operator
helm install \
    --set cr.create=false \
    --set cr.namespace=istio-system \
    --namespace kiali-operator \
    --repo https://kiali.org/helm-charts \
    kiali-operator \
    kiali-operator
```
2. Setup Kiali with an openid provider and web_root "/kiali"
```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  version: "default" 
  istio_namespace: "istio-system"
  api:
    namespaces:     
      exclude:
      - "istio-operator"
      - "kube-.*"
      - "kiali-operator"
      - "cert-manager"
  auth:
    strategy: "openid"
    openid:
      client_id: "<client id>"
      issuer_uri: "https://sts.windows.net/<tenant id>/"
      username_claim: preferred_username
      api_token: "access_token"     
      additional_request_params:
        resource: "6dae42f8-4368-4678-94ff-3960e28e3630"
  secret_name: "kiali"
  deployment:
    ingress_enabled: false
    image_pull_policy: "IfNotPresent"
    namespace: "monitoring-system"
    replicas: 1
    logger:
      log_level: info
      log_format: text
      sampler_rate: "1"

    view_only_mode: true
    external_services:
      custom_dashboards:
        enabled: true
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
      web_fqdn: mykialihost.****azure.com
      web_port: 443
      web_schema: "https"
```
3. Create a new user on your openid provider, that has no access to kiali.
4. Open the developer toolbar of your browser and start tracing network traffic
4. Login to "Kiali" with the newly created user from step 3.
5. Verify network traffic: 
    Static resources and env.js are loaded from root "/" and returning with an 404 (not found).

It might be that this behavior is not only related to open_id configurations, but I didn't check that. 

**Expected behavior**
The resources are referenced using the configured sub-directory (web_root) and loading correctly.

**Comment by jmazzitelli** [comment]
Just to confirm - in your step 2 - that is a snippet from your Kiali CR correct? You set `spec.server.web_root` in the Kiali CR which the operator processes. In other words, you are not directly editing the ConfigMap correct?

**Comment by stevensystems** [comment]
> Just to confirm - in your step 2 - that is a snippet from your Kiali CR correct? You set `spec.server.web_root` in the Kiali CR which the operator processes. In other words, you are not directly editing the ConfigMap correct?

Yes, that is absolutly correct. It's a part of my Kilai CR, that is processed by the kiali operator.

**Comment by stevensystems** [comment]
> > Just to confirm - in your step 2 - that is a snippet from your Kiali CR correct? You set `spec.server.web_root` in the Kiali CR which the operator processes. In other words, you are not directly editing the ConfigMap correct?
> 
> Yes, that is absolutly correct. It's a part of my Kilai CR, that is processed by the kiali operator.

I updated step 2, and included the complete Kiali CR. Openid has been setup with Azure AD following the steps in https://kiali.io/documentation/latest/configuration/authentication/openid/#_using_with_azure_aks_and_aad. 

Maybe it's also important to known, that I am using an Istio gateway as ingress:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring-gateway
  namespace: monitoring-system
spec:
  selector:
    istio: ingressgateway-monitoring
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "mykialihost.****azure.com"
    tls:
      httpsRedirect: true    
  - port:
      number: 443
      name: https-443
      protocol: https
    tls:            
      mode: SIMPLE
      credentialName: ingress-cert-monitoring
    hosts:      
      - mykialihost.****azure.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:                                                                                                                                                                                                       
  name: kiali
  namespace: monitoring-system
spec:
  hosts:  
  - "mykialihost.****azure.com"
  gateways:
  - monitoring-gateway
  http:
  - headers:
      request:
        set:
          X-Forwarded-Port: "443"
    match:
    - uri:
        prefix: "/kiali"
    route:
    - destination:
        host: kiali.monitoring-system.svc.cluster.local
        port:
          number: 20001
    timeout: 30s
```
