### ISSUE TITLE
[molecule] make sure tests set up Kiali CR for ServiceMesh properly

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4225]
This may not be needed now, but I am documenting this in case we need to do this.

When installing Kiali via ServiceMesh (aka OSSM), the Kiali CR has a few fields set automatically. We should set these fields in the Kiali CR that molecule creates so we integrate properly when testing within a OSSM environment.

We already do some of this today - we set `spec.external_services.tracing` and `spec.external_services.prometheus` with the appropriate credentials required to access them.

There are some settings that are not set but should be. The ones I can think of are:

```yaml
spec:
  external_services:
    istio:
      config_map_name: ?
      istio_sidecar_injector_config_map_name: ?
      istiod_deployment_name: ?
  ```

**Comment by jmazzitelli** [comment]
Here's settings that ServiceMesh 2.1 operator will set in kiali cr:

```
spec:
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces: []
    image_pull_policy: ""
    ingress_enabled: true
    namespace: istio-system
  external_services:
    grafana:
      auth:
        password: ...
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: https://grafana.istio-system.svc:3000
      url: https://grafana-istio-system.apps.abc.com
    istio:
      config_map_name: istio-custom
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-custom
      istiod_deployment_name: istiod-custom
      url_service_version: http://istiod-custom.istio-system:15014/version
    prometheus:
      auth:
        password: ...
        type: basic
        use_kiali_token: false
        username: internal
      url: https://prometheus.istio-system.svc:9090
    tracing:
      auth:
        password: ...
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: https://jaeger-query.istio-system.svc
      namespace: istio-system
      service: ""
      url: https://jaeger-istio-system.apps.abc.com
  installation_tag: Kiali [istio-system]
  istio_namespace: istio-system
  version: v1.36
```

**Comment by jmazzitelli** [comment]
To determine the values at runtime, get the name of the SMCP found in the control plane namespace:

```
oc get smcp -n istio-system -o jsonpath={.items[0].metadata.name}
```

Then that name is used to fill in the values:

```
    istio:
      config_map_name: istio-${SMCP_NAME}
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-${SMCP_NAME}
      istiod_deployment_name: istiod-${SMCP_NAME}
      url_service_version: http://istiod-${SMCP_NAME}.${CONTROL_PLANE_NAMESPACE}:15014/version
```
