### ISSUE TITLE
Kiali unable to get service details and health information

### ISSUE THREAD

**Issue by shanky53** [kiali/kiali#4228]
**Describe the bug**
Kiali gives error when accessing dashboard and opening services tab.

2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: httpbin-7cd65fcc88-w44pv]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: ingress-nginx-controller-84ff66d54c-4kbns]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: ingress-nginx-controller-84ff66d54c-4kbns]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2021-07-28T08:28:42Z ERR unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port

For UI issues please also add a screenshot that shows the issue.
Services Tab
![image](https://user-images.githubusercontent.com/6241313/127290642-9aeb8286-3fa3-49ed-acf2-ce625a4d4f47.png)
Other Tabs
![image](https://user-images.githubusercontent.com/6241313/127291209-8e8d927c-15cc-49bd-8b6f-0bf80f6449a4.png)

**Versions used**
Kiali: 1.36.2
Istio: 1.10.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) (1.21.3) (minikube)

**To Reproduce**
Install istio using helm chart
Install kiali-server using helm chart with following values:

```
values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.36.2
      version_label: v1.36.2
      pod_annotations:
        sidecar.istio.io/inject: "false"
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      ingress_enabled: true
      logger:
        log_level: "debug"
      override_ingress_yaml:
        metadata:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/service-upstream: "true"
            nginx.ingress.kubernetes.io/upstream-vhost: kiali.istio-system.svc.cluster.local
      secret_name: kiali
    istio_namespace: istio-system
    server:
      port: 20001
      metrics_enabled: true
      metrics_port: 80
      web_root: /kiali
      web_fqdn: kiali.local
    external_services:
      prometheus:
        url: http://prometheus-server.istio-system
      custom_dashboards:
        enabled: true
```

**Expected behavior**
opening kiali dashboard should run without any errors

**Comment by xeviknal** [comment]
Hello there,

it looks like your KubeAPI doesn't have access to your control plane namespace. Kiali does a PodProxy or PortForward from kiali pod to istiods. This call goes through the KubeAPI. If you have some protection between the KubeAPI and the istiod pods, kiali can't fetch certain information.

Check the FAQ entry we have with regards to this specific situation: https://kiali.io/documentation/latest/faq/#google-cloud-private-cluster

Can you please clarify which Kubernetes flavour and version are you using? are you using minikube with openshift?

**Comment by shanky53** [comment]
Thank you @xeviknal for the response,

Well I am testing everything locally via minikube running as docker container on a ubuntu machine. kubernetes version is 1.21.3

I looked at the docs and it's specific to GKE. Where can I find a bit more generalised documentation or installation guide?

**Comment by xeviknal** [comment]
Does this work for you?

```
kubectl port-forward -n istio-system ${ISTIOD_POD} 15014
curl http://localhost:15014/debug/syncz
```

**Comment by shanky53** [comment]
Hi @xeviknal 

Yes, it does.

It gives info of the two pods that are running with istio sidecar

**Comment by shanky53** [comment]
I noticed that this doesn't happen if I use the kiali addon file for istio

[kiali.yaml](https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/kiali.yaml)

**Comment by xeviknal** [comment]
How did you install the previous non-working kiali? It might be because of lack of permissions for kiali to use the `pod/port-forward` subresource.

**Comment by shanky53** [comment]
Using flux.

Setting the chart's source referencing to the github repo

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  # The interval at which to check the upstream for updates
  interval: 30m
  # The repository URL, can be a HTTP/S or SSH address
  url: https://github.com/kiali/helm-charts
  # The Git reference to checkout and monitor for changes
  # (defaults to master)
  # For all available options, see:
  # https://toolkit.fluxcd.io/components/source/api/#source.toolkit.fluxcd.io/v1beta1.GitRepositoryRef
  ref:
    branch: master
```

Then creating a helmrelease.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  releaseName: kiali
  chart:
    spec:
      chart: ./kiali-server
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  - name: ingress-nginx
    namespace: default
  - name: prometheus
  interval: 5m
  values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.36.0
      version_label: v1.36.0
      pod_annotations:
        sidecar.istio.io/inject: "false"
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      ingress_enabled: false
      logger:
        log_level: "debug"
      override_ingress_yaml:
        metadata:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/service-upstream: "true"
            nginx.ingress.kubernetes.io/upstream-vhost: kiali.istio-system.svc.cluster.local
      secret_name: kiali
    istio_namespace: istio-system
    kubernetes_config:
      excluded_workloads:
      - "CronJob"
      - "DeploymentConfig"
      - "ReplicationController"
    server:
      port: 20001
      metrics_enabled: true
      metrics_port: 9090
      web_root: /kiali
      # web_fqdn: kiali.local
    external_services:
      prometheus:
        url: http://prometheus-server.istio-system:9090
      custom_dashboards:
        enabled: true
```
