### ISSUE TITLE
helm-charts and istio addons doesn't have default grafana in_cluster_url defined

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4261]
I think we have another inconsistency with the definition of a default value. In this case, the grafana `in_cluster_url`.

The CR document says the default value is appropriately set:

```yaml
#      enabled: true
#      health_check_url: ""
#      in_cluster_url: "http://grafana.istio-system:3000"
#      is_core: false
#      url: ""
```
from https://github.com/kiali/kiali-operator/blob/0bcf8f0a91b939346b43d82a468cb4b0f4a37b92/deploy/kiali/kiali_cr.yaml#L524

However, there is no default value set in the defaults main:

```yaml
      health_check_url: ""
      in_cluster_url: ""
      is_core: false
      url: ""
```
from https://github.com/kiali/kiali-operator/blob/0bcf8f0a91b939346b43d82a468cb4b0f4a37b92/roles/default/kiali-deploy/defaults/main.yml#L134

And then, in the server side, we don't have any default value:
https://github.com/kiali/kiali/blob/3a5b136c095990eaaddfe174594279a7a3a83974/config/config.go#L462-L468

Therefore, it looks like we got a gap having grafana enabled but with an empty `in_cluster_url` when kiali is installed via both helm-charts and istio addons.

I've just used the default helm installation with istio 1.11-beta-3 and I got the masthead warning saying grafana is not there. Checking the configmap, I see no `in_cluster_url` setting and therefore kiali server has an empty string there. Curling and empty string obviously gives you a non 200 response status code.

Am I doing something wrong? If not, I guess we should backport it to 1.38.

There is no problem when installing kiali via the operator:
```yaml
- name: Set default Grafana in_cluster_url
  set_fact:
    kiali_vars: "{{ kiali_vars | combine({'external_services': {'grafana': {'in_cluster_url': 'http://grafana.' + kiali_vars.istio_namespace + ':3000'}}}, recursive=True) }}"
  when:
    kiali_vars.external_services.grafana.in_cluster_url == ""
```

from https://github.com/kiali/kiali-operator/blob/0bcf8f0a91b939346b43d82a468cb4b0f4a37b92/roles/default/kiali-deploy/tasks/main.yml#L279-L283

@jmazzitelli does this make sense to you?
