### ISSUE TITLE
Jaeger unreachable

### ISSUE THREAD

**Issue by kfirfer** [kiali/kiali#4270]
Installed kiali with helm chart version: 1.38.1
Tried to override this yaml value:
```
external_services:
  tracing:
    in_cluster_url: 'http://jaeger-operator-jaeger-query.efk.svc.cluster.local:16686'
    url: 'https://efk-jaeger.XXXXX.com'
```

And its seems like Jaeger unreachable

When I port-forward `svc/jaeger-operator-jaeger-query 16686`, and open up the browser, I could reach jaeger UI

The logs from kiali:
```
{"level":"error","time":"2021-08-11T08:53:12Z","message":"Error fetching availability of the tracing service: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: received the unexpected content-type \"text/html; charset=utf-8\""}
```

**Comment by kfirfer** [comment]
Hi @jmazzitelli 
Im using istio 1.10.3
And Jaeger version 1.24 , I also tried 1.22 but same results

**Comment by kfirfer** [comment]
Thanks! @xeviknal 

Its worked when I changed the values.yaml of the kiali to use http istead grpc:
```
external_services:
  tracing:
    in_cluster_url: 'http://jaeger-operator-jaeger-query.efk.svc.cluster.local:16686/'
    url: 'https://efk-jaeger.tatzan.com'
    use_grpc: false
```


Would be nice to see better warning message that indicate its tried to connect to a grpc connection

Anyway, Im closing the issue, thanks again

**Comment by xeviknal** [comment]
@kfirfer didn't the usage of grpc worked with port 16685? The integration would be faster.
You probably need to add `/jaeger` as well.

```
external_services:
  tracing:
    in_cluster_url: 'http://jaeger-operator-jaeger-query.efk.svc.cluster.local:16685/jaeger'
    url: 'https://efk-jaeger.tatzan.com'
    use_grpc: true
```
