### ISSUE TITLE
Migrate to non-beta Ingress API, or remove Ingress support in operator and helm charts

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4277]
Kubernetes/kubectl has been outputting the following warning:

`Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

Nowadays, Kubernetes v1.22 is already available. So, both the Operator and Helm charts will generate an Ingess resource that won't work for this latest k8s version.

We should either update the operator and helm charts to use the new API version, or remove Ingress support to let people expose Kiali as best suit their needs.

**Comment by jmazzitelli** [comment]
> We should either update the operator and helm charts to use the new API version, or remove Ingress support to let people expose Kiali as best suit their needs.

We've already done this. See:

* https://github.com/kiali/kiali/issues/3706
* https://github.com/kiali/kiali-operator/pull/252
* https://github.com/kiali/helm-charts/pull/41
* https://github.com/kiali/helm-charts/pull/95

> Kubernetes/kubectl has been outputting the following warning:

The reason for this is:

https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/ingress.yaml#L4-L8

So we've already migrated - we are just backward compatible so things work for those people that want to install on k8s 1.18 and under.

**Comment by israel-hdez** [comment]
@jmazzitelli That's weird, because I tried on minikube v1.21 and I got that warning :-/
Unless `helm template` does not evaluate for capabilities?

**Comment by jmazzitelli** [comment]
`helm template` doesn't evaluate that. And that's also why when you build you get the warning - because [the helm linter](https://github.com/kiali/helm-charts/blob/master/Makefile#L75) also doesn't connect to a cluster while doing the validation.

**Comment by israel-hdez** [comment]
OK, then, let's close this.

**Comment by ngocketit** [comment]
Is it still relevant? I installed version v1.38.1 on EKS with Kubernetes 1.21 and Ingress didn't get created. 
```
Message:               Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Ingress.extensions \\"kiali\\" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified","reason":"Invalid","details":{"name":"kiali","group":"extensions","kind":"Ingress","causes":[{"reason":"FieldValueRequired","message":"Required value: pathType must be specified","field":"spec.rules[0].http.paths[0].pathType"}]},"code":422}\n'
```
`helm get manifests` output:
```
# Source: kiali-operator/templates/kiali-cr.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    helm.sh/chart: kiali-operator-1.38.1
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali
    version: "v1.38.1"
    app.kubernetes.io/version: "v1.38.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
annotations:
  ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  deployment:
    accessible_namespaces:
    - '**'
    override_ingress_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/server-snippet: |
            listen 8000;
            if ( $server_port = 80 ) {
              return 308 https://$host$request_uri;
            }
      spec:
        rules:
        - host: abc.company.com
          http:
            paths:
            - backend:
                serviceName: kiali
                servicePort: 20001
              path: /
  istio_namespace: istio-system
  server:
    web_fqdn: https://abc.company.com
```
`kubectl api-versions` output:
```
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
argoproj.io/v1alpha1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
crd.k8s.amazonaws.com/v1alpha1
discovery.k8s.io/v1
discovery.k8s.io/v1beta1
events.k8s.io/v1
events.k8s.io/v1beta1
extensions/v1beta1
flowcontrol.apiserver.k8s.io/v1beta1
install.istio.io/v1alpha1
kiali.io/v1alpha1
metrics.k8s.io/v1beta1
monitoring.coreos.com/v1
monitoring.coreos.com/v1alpha1
networking.istio.io/v1alpha3
networking.istio.io/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1
node.k8s.io/v1beta1
policy/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
security.istio.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
vpcresources.k8s.aws/v1beta1
```
