### ISSUE TITLE
grafana-test fails - cannot look up grafana url successfull

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4289]
@leandroberetta can you confirm if you see this error too?

I am running the grafana-test molecule test on OpenShift 4.7 with istio 1.11.

It is failing.

When I look at the Kiali ConfigMap while the test is running, I see this in it:

```
spec.
  external_services:
    grafana:
        health_check_url: https://grafana.istio-system.svc:3000
        in_cluster_url: http://wrong.url
```

Notice the in_cluster_url is still the "wrong.url", but at the time I saw this, the molecule test was trying to test that the health check succeeds. I believe it failed at this assert: https://github.com/kiali/kiali-operator/blob/master/molecule/grafana-test/converge.yml#L125

I ran the molecule test like this:

1. `oc login` to an 4.7 OpenShift
2. Install Istio 1.11
3. Log into the OpenShift image registry (via docker login or podman login - get the login command via `make cluster-status`)
3. Build the latest images and push to the cluster: `make clean build cluster-push`
3. Run `make -e MOLECULE_SCENARIO="grafana-test" -e MOLECULE_USE_DEV_IMAGES="true" molecule-test`

PR that fixes the test: https://github.com/kiali/kiali-operator/pull/398
Backport PR: https://github.com/kiali/kiali-operator/pull/399
