### ISSUE TITLE
CRUD Permissions on events

### ISSUE THREAD

**Issue by prary** [kiali/kiali#4290]
**Query**
Not able to figure out why kiali-operator clusterrole needs CRUD on events. 
All the events generated by kiali-operator are automatically captured by kubernetes.
Why do this service account need DELETE, UPDATE Permission on events.

**Versions used**
Kiali: 1.36.0
Istio: N/A
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
N/A
**To Reproduce**
https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/clusterrole.yaml#L13 
**Expected behavior**
In case this is redundant then it should be removed.

**Comment by jmazzitelli** [comment]
These are permissions that were added during the initial operator implementation as they were required/added by the Operator SDK. It might be possible these aren't needed anymore. I do not know. If you'd like, take those out and see how the operator behaves. You would probably know pretty quickly if they are not needed -- to fully test, you'll have to run through an initial install (create the Kiali CR), update (modify something in the Kiali CR), and uninstall (delete the Kiali CR). [Running](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#run-molecule-tests) the "[config-values-test](https://github.com/kiali/kiali-operator/tree/master/molecule/config-values-test)" molecule test should do all that.

In fact, if you want to take it upon yourself and do a security audit of those other permissions, that would be greatly appreciated. Let us know if you see there are others that are not needed (I'm looking now and I'm not sure why the SDK would want these permissions on things like persistentvolumeclaims either - but I really don't know. We followed the initial SDK recommendations.)

**Comment by prary** [comment]
Hi @jmazzitelli, 

Deleted both the resources events and pvc and i don't see any issue with kiali installation and deletion.

We can optimize permissions being granted to operator serviceaccount, if we use resourceName to the best e.g rolebinding is one the thing. 

Let's assume we are using kiali-operator in read-only mode  then

Permissions granted delete, update any role and rolebinding 
```
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  {{- if or (and (.Values.cr.create) (has "**" .Values.cr.spec.deployment.accessible_namespaces)) (.Values.clusterRoleCreator) }}
  - clusterrolebindings
  - clusterroles
  {{- end }}
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

We know for sure operator is authorised to perform CRUD on ```kiali``` and ```kiali-controlplane``` rolebinding. Hence optimise permissions should be:-
```
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - rolebindings
  - roles
  verbs:
  - create
 
- apiGroups: ["rbac.authorization.k8s.io"]
  resourceNames:
  - kiali
  - kiali-controlplane
  resources:
  - rolebindings
  verbs:
  - delete
  - get
  - list
  - patch
```
Would be extremely happy to audit and raise PR for the same.
