### ISSUE TITLE
Kiali Operator: Pods attempt to use auth secret when external service disabled

### ISSUE THREAD

**Issue by mjnagel** [kiali/kiali#4298]
**General remarks**

I am not certain if this is intended behavior as this could be considered a "misconfigured Kiali object", but it seems like it could be more robust.

**Describe the bug**

If a user creates a `Kiali` object that has an external service disabled but also provides a `auth.password` that contains a secret, the operator will generate a pod that attempts to use this secret - resulting in a CreateContainerConfigError.

**Versions used**
Kiali: 1.37.0
Istio: 1.9.7
Kubernetes flavour and version: k3s version v1.21.2-k3s1

**To Reproduce**
1. Deploy Kiali operator.
2. Create a Kiali yaml that contains:
```yaml
cr:
  spec:
    external_services:
      grafana:
        enabled: false
        auth:
          username: "admin"
          password: "secret:grafana-kiali-secret:password"
```
3. Apply the yaml and you should see a pod created with CreateContainerConfigError due to failing to find the secret.

**Expected behavior**
I would expect that when an external service is disabled, none of the values under the yaml block for that service are used at all. This is definitely something I can (and should) handle with better conditionals around when lines are added to my yaml but still seems like unexpected behavior that the auth secret is trying to be used when the service is disabled.
