### ISSUE TITLE
Setting Kiali read-only does not take effect

### ISSUE THREAD

**Issue by openstack-test** [kiali/kiali#4341]
**Describe the bug**
Kiali configuration view_only_mode: true does not take effect and can still be modified or edited

**Versions used**
Kiali:  v1.29.0
Istio:  1.9.6
Kubernetes version: 1.16.3

**To Reproduce**
1. Configure access control by referring to the official document.
https://kiali.io/documentation/latest/configuration/authentication/anonymous/
```
......
    strategy: anonymous
deployment:
      accessible_namespaces:
      - '**'
      view_only_mode: true
......
```

2. Deploy
```
kubectl apply -f .
```

3. Validation
It can still be edited on the system interface, read-only does not take effect
![image](https://user-images.githubusercontent.com/12166405/132671616-4e46dbb9-fd61-459c-9a80-b7e1b1f7d110.png)

Is this a Bug? How do we solve this? I need some help, thank

**Expected behavior**
The system interface is read-only and cannot be modified
