### ISSUE TITLE
can additional_request_params contain camelCase? If so, we need to fix the operator

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4349]
In PR https://github.com/kiali/kiali-operator/pull/289 we introduced a new setting in the Kiali CR `spec.auth.openid.additional_request_params` seen [here](https://github.com/kiali/kiali-operator/blob/v1.39.0/roles/default/kiali-deploy/defaults/main.yml#L32).

Question: can these additional request parameters be camelCase? (e.g. `thisIsCamelCaseParam`)? For example, is this ever possible?

```
spec:
  auth:
    openid:
      additional_request_params:
        someCamelCaseParam: "the-value"
```

If so, there is a bug in the operator that needs to be fixed. We need to ensure we retain the camelCase key name (by default the operator will convert all camelCase keys to snake_case). The fix would be to add a snippet of code in the operator similar to [this snippet](https://github.com/kiali/kiali-operator/blob/v1.39.0/roles/default/kiali-deploy/tasks/main.yml#L81-L93).
