### ISSUE TITLE
Client certificate based kubeconfig usage

### ISSUE THREAD

**Issue by libesz** [kiali/kiali#4359]
**Is your feature request related to a problem? Please describe.**
The current Kubernetes API client in Kiali can be only configured to use the bearer token method. I would like to use also kubeconfigs with a client certificate instead of a token.

**Describe the solution you'd like**
During the testing of https://github.com/kiali/kiali/issues/4323, I found out that Kiali does not support certificate based kubeconfigs, it deals only with the token (no matter that remote or normal API access is used). This is usually enough but if the source of the kubeconfig is not based on the projected, auto-mounted, service account token, but coming from external entity, it may have a client certificate in it. This may be an easy change for the Kiali codebase.

**Describe alternatives you've considered**
External automation may be able to install the RBAC resources in the target cluster, including a Kiali SA, using the certificate based kubeconfig, than fetch the SA token from the API and configure it for the Kiali pod.

**Additional context**
In our case, Kiali will not run directly in the mesh cluster. Our systems are providing certificate based kubeconfigs for the mesh cluster. Said that, it would be very convenient if we could just plug that into Kiali.

Such cert based kubeconfigs are [also a standard way](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs) of authentication/authorization in Kubernetes
 Example:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0t[...]
    server: https://s6662[...]
  name: remote
contexts:
- context:
    cluster: remote
    namespace: default
    user: remote
  name: remote
current-context: remote
kind: Config
preferences: {}
users:
- name: remote
  user:
    client-certificate-data: LS0tL[...]
    client-key-data: LS0tLS1CRUdJTiBS[...]
```
