### ISSUE TITLE
Install kiali , get some unnomarl logs

### ISSUE THREAD

**Issue by zackzhangkai** [kiali/kiali#4362]
**Describe the bug**
When install Kiali with helm chart. The warning logs as below:

```bash
2021-09-16T10:07:04Z WRN GetPodProxyStatus is failing for [namespace: csminstalltest] [pod: reviews-v1-56b6cb7f4c-rq9nf]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
```

After add the `pods/proxy` the role disappeared.

Referenced PR https://github.com/kiali/helm-charts/pull/107

**Versions used**
Kiali: 1.34.1
Istio: 1.10.4
Kubernetes flavour and version: Kubernetes 1.18

**To Reproduce**

1. Go to https://github.com/kiali/helm-charts/tree/master/kiali-server , install kiali server.
2. Values.yaml as follows:

```yaml
# 'fullnameOverride' is deprecated. Use 'deployment.instance_name' instead.
# This is only supported for backward compatibility and will be removed in a future version.
# If 'fullnameOverride' is not "kiali" and 'deployment.instance_name' is "kiali",
# then 'deployment.instance_name' will take the value of 'fullnameOverride' value.
# Otherwise, 'fullnameOverride' is ignored and 'deployment.instance_name' is used.
fullnameOverride: "kiali"

# This is required for "openshift" auth strategy.
# You have to know ahead of time what your Route URL will be because
# right now the helm chart can't figure this out at runtime (it would
# need to wait for the Kiali Route to be deployed and for OpenShift
# to start it up). If someone knows how to update this helm chart to
# do this, a PR would be welcome.
kiali_route_url: ""

#
# Settings that mimic the Kiali CR which are placed in the ConfigMap.
# Note that only those values used by the Helm Chart will be here.
#

istio_namespace: "" # default is where Kiali is installed

auth:
  openid: {}
  openshift: {}
  strategy: anonymous

deployment:
  # This only limits what Kiali will attempt to see, but Kiali Service Account has permissions to see everything.
  # For more control over what the Kial Service Account can see, use the Kiali Operator
  accessible_namespaces:
  - "**"
  additional_service_yaml: {}
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  hpa:
    api_version: "autoscaling/v2beta2"
    spec: {}
  image_name: image.cestc.cn/csm/kiali/kiali
  image_pull_policy: "Always"
  image_pull_secrets: []
  image_version: v1.34.1
  ingress_enabled: false
  instance_name: "kiali"
  logger:
    log_format: "text"
    log_level: "info"
    time_field_format: "2006-01-02T15:04:05Z07:00"
    sampler_rate: "1"
  node_selector: {}
  override_ingress_yaml:
    metadata: {}
  pod_annotations: 
    sidecar.istio.io/inject: "false"
  pod_labels: {}
  priority_class_name: ""
  replicas: 1
  resources: {}
  secret_name: "kiali"
  service_annotations: {}
  service_type: ""
  tolerations: []
  version_label: v1.34
  view_only_mode: false

external_services:
  custom_dashboards:
    enabled: true

identity: {}
  #cert_file:
  #private_key_file:

login_token:
  signing_key: ""

server:
  port: 20001
  metrics_enabled: true
  metrics_port: 9090
  web_root: ""

```
