### ISSUE TITLE
Error loading Graph - Namespace [kube-state-metrics] is excluded for Kiali

### ISSUE THREAD

**Issue by sathieu** [kiali/kiali#4384]
**Describe the bug**

Kiali CR has two parameters to configure namespace visibility.

The defaults (using kiali operator) are:

```yaml
cr:
  api:
# Allows for controlling what namespaces/projects are returned by Kiali.
#
# 'exclude' is optional and takes a list of namespaces to be excluded from the list
# of namespaces provided by the API and UI. Regex is supported. This does not affect
# explicit namespace access.
#
# 'label_selector' is optional and takes a string value of a Kubernetes label selector
# (e.g. "myLabel=myValue") which is used when fetching the list of available namespaces.
# This does not affect explicit namespace access.
# Note that if you do not set this but deployment.accessible_namespaces does not have the
# special "all namespaces" entry of "**" then this label_selector will be set
# to a default value of "kiali.io/[<deployment.instance_name>.]member-of=<deployment.namespace>"
# where [<deployment.instance_name>.] is the instance name assigned to the Kiali installation
# if it is not the default 'kiali' (otherwise, this is omitted) and <deployment.namespace>
# is the namespace where Kiali is to be installed.
# If deployment.accessible_namespaces does not have the special value of "**"
# then the Kiali operator will add a new label to all accessible namespaces - that new
# label will be this label_selector.
    namespaces:
      - istio-operator
      - kube.*
      - openshift.*
      - ibm.*
      - kial-operator

  deployment:
# A list of namespaces Kiali is to be given access to.
# These namespaces have service mesh components that are to be observed by Kiali.
# You can provide names using regex expressions matched against all namespaces the operator can see.
# The default makes all namespaces accessible except for some internal namespaces that typically should be ignored.
# NOTE! If this has an entry with the special value of "**" (two asterisks), that will denote you want
# Kiali to be given access to all namespaces via a single cluster role (if using this special value of "**",
# you are required to have already granted the operator permissions to create cluster roles and cluster role bindings).
    accessible_namespaces:
      - '**'
```

When viewing a graph of the prometheus-stack namespace, which access the kube-state-metrics namespace, the following error is raised:

> Error loading Graph - Namespace [kube-state-metrics] is excluded for Kiali

The expected behavior is to not have kube-state-metrics in the dropdown menu (✔️ ), but to not raise an error when showing a graph.

Workaround: Set `cr.api.namespaces=[]`.

**Versions used**
Kiali: v1.40.1
Istio:1.11.2
Kubernetes flavour and version:  1.21.5 (kubespray)
