### ISSUE TITLE
Kiali Operator - Add ability to specify image SHA in Kiali CRs

### ISSUE THREAD

**Issue by Kaezon** [kiali/kiali#4392]
**Is your feature request related to a problem? Please describe.**
I am trying to deploy Kiali Operator and a Kiali CR into a cluster which uses the k-rail admission webhook.
By default, this requires all image references to be immutable references.
I tried adding the sha to the end of the image_version value, but it seems that value is used in the creation of one or more other resources, and generates an error.

**Describe the solution you'd like**
A new value, perhaps **spec.deployment.image_sha**, which could be used to build an immutable image reference.

**Describe alternatives you've considered**
I can obviously exempt Kiali pods from this security requirement, but removing security isn't a great long-term solution.

**Additional context**
My Kiali CR:

```yaml
cr:
  spec:
    istio_component_namespaces:
      prometheus: prometheus
      grafana: prometheus
      jaeger: observability
    istio_namespace: istio-system
    auth:
      strategy: anonymous
    deployment:
      image_name: [REDACTED]/kiali/kiali
      image_version: v1.40.1@sha256:192fd980ace8b91dfc2991db24122bcc4b08655509eb18cd8b836c80eca2c9c0
      accessible_namespaces: ["**"]
      ingress_enabled: false
      service_type: ClusterIP
      secret_name: kiali
      namespace: istio-system
    identity:
      cert_file: ""
      private_key_file: ""
    external_services:
      grafana:
        url: http://grafana.{{.Values.domain}}
      tracing:
        in_cluster_url: "http://jaeger-query.observability.svc.cluster.local:16686"
        service: "jaeger-query"
        url: http://jaeger.{{.Values.domain}}/jaeger
      prometheus:
        custom_metrics_url: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
        url: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
    api:
      namespaces:
        exclude:
          - istio-operator
          - kiali-operator
          - kube-.*
```

The error:
```
Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Secret \\"kiali-signing-key\\" is invalid: metadata.labels: Invalid value: \\"v1.40.1@sha256:192fd980ace8b91dfc2991db24122bcc4b08655509eb1XXX\\": a valid label must be an empty string or consist of alphanumeric characters, \'-\', \'_\' or \'.\', and must start and end with an alphanumeric character (e.g. \'MyValue\', or \'my_value\', or \'12345\', regex used for validation is \'(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\')","reason":"Invalid","details":{"name":"kiali-signing-key","kind":"Secret","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \\"v1.40.1@sha256:192fd980ace8b91dfc2991db24122bcc4b08655509eb1XXX\\": a valid label must be an empty string or consist of alphanumeric characters, \'-\', \'_\' or \'.\', and must start and end with an alphanumeric character (e.g. \'MyValue\', or \'my_value\', or \'12345\', regex used for validation is \'(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\')","field":"metadata.labels"},{"reason":"FieldValueInvalid","message":"Invalid value: \\"v1.40.1@sha256:192fd980ace8b91dfc2991db24122bcc4b08655509eb1XXX\\": a valid label must be an empty string or consist of alphanumeric characters, \'-\', \'_\' or \'.\', and must start and end with an alphanumeric character (e.g. \'MyValue\', or \'my_value\', or \'12345\', regex used for validation is \'(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\')","field":"metadata.labels"}]},"code":422}\n'
```

**Comment by jmazzitelli** [comment]
This is actually a good enhancement request. We call it running in a "disconnected" environment, others call it "air-gapped" - but whatever you call it, it would be nice to specify the image SHA (for both operator and kiali server images). This may affect the Kiali CR (adding potentially a new setting or we could just handle the image_version better to support SHAs) and will require a change to the helm charts (operator and server).

**Comment by jmazzitelli** [comment]
@Kaezon one workaround may be to set the version_label field yourself. I haven't tested, but based on the error message you posted that the operator was hitting, that's because the version label is invalid (doesn't follow k8s syntax for labels). But if you set the version_label yourself (overriding the one the operator was using by default) that might just solve the problem - and that could be the official answer to this issue, too (i.e. might not need any thing special to do).

So - set this in the Kiali CR (leaving the rest of your Kiali CR as is) and see what happens: https://github.com/kiali/kiali-operator/blob/v1.40.0/deploy/kiali/kiali_cr.yaml#L390-L398

**Comment by jmazzitelli** [comment]
I will update the helm charts and the operator to support digest hashes for image containers. We will need something like a `image_digest` setting - if this is set, it will be assumed the image_version is really a hash digest with the digest value provided (usually the image_digest will be `sha256` but it presumably can be other digest types - so we will allow support for other digest types).

From k8s docs: https://kubernetes.io/docs/concepts/containers/images/#updating-images

```
To make sure the Pod always uses the same version of a container image,
you can specify the image's digest; replace <image-name>:<tag> with <image-name>@<digest>
(for example, image@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2).
```

So, in the case of the Kiali CR we can provide something like:

```
spec:
  deployment:
    image_version: 45b23dee08af5e4
    image_digest: sha256
```

With image_digest set to something other than empty string, the code will insert its value in the container URI. So in this case: `@sha256` will be inserted before the colon `:` - the image_version will appear after the colon as usual.
