### ISSUE TITLE
Show propagation status for each istio config (when pilot status is enabled)

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4457]
When istio is installed with the status info enabled, istio pilot injects to each istio config the following info related to the number of proxies where that config is synced with. I think this information is pretty close to the istio sync health we have for sidecars but from the other perspective, from config perspective. 

This bit response to the question: "is this piece of config synced with all the sidecars?" I think this is precious informations to have when troubleshooting the mesh itself.

See one example:

```yaml
.....
spec:
  hosts:
    - rollouts-demo-vsvc1.local
  gateways:
    - rollouts-demo-gateway
  http:
    - name: primary
      route:
        - destination:
            host: rollouts-demo-stable
            port:
              number: 15372
status:
  conditions:
    - type: Reconciled
      status: 'True'
      lastProbeTime: '2021-10-27T15:43:21.226092578Z'
      lastTransitionTime: '2021-10-27T15:43:21.226092750Z'
      message: 8/8 proxies up to date.
  observedGeneration: '1'
```

`message: 8/8 proxies up to date.`

I propose to add this information in:
1) Istio config list: in the configuration tooltip
![Screenshot of Kiali Console (28)](https://user-images.githubusercontent.com/613814/139105077-33d5fdad-bd83-4ca5-b138-26c1d7cd33f2.png)

2) Add it into the details page. similarly to what we have with istio native validation errors. In a section within the sidepanel.
