### ISSUE TITLE
"More than one Gateway for the same host port combination" even with different ports

### ISSUE THREAD

**Issue by lgenasi** [kiali/kiali#4466]
We have a Gateway which has two Servers with the same hosts but different ports, like so.

```yaml
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: istio-ingressgateway-https
  namespace: istio-system
spec:
  servers:
  - port:
      number: 443
      protocol: HTTPS
      name: https
    hosts:
    - host.name.com
    tls:
      mode: SIMPLE
      credentialName: certificate
      minProtocolVersion: TLSV1_2
  - port:
      number: 80
      protocol: HTTP
      name: http
    hosts:
    - host.name.com
    tls:
      httpsRedirect: true
  selector:
    istio: ingressgateway
```

This config is displaying a warning for **KIA0301 - More than one Gateway for the same host port combination** even though the ports are different. 

I believe the issue is here in [multi_match_checker.go](https://github.com/kiali/kiali/blob/master/business/checkers/gateways/multi_match_checker.go#L103). It's only setting `port` if `intutil.Convert(serverDef.Port.Number)` _does_ return an error, where it should be setting it if it _doesn't_ return an error. This means that `port` is being set to 0 for all servers even if port is defined correctly, causing the port to not be considered in the match.
```
var port int
if serverDef.Port != nil {
	if n, e := intutil.Convert(serverDef.Port.Number); e != nil {
		port = n
	}
}
```
