### ISSUE TITLE
"Could not fetch services list" Error in Service view when selecting some namespaces

### ISSUE THREAD

**Issue by maxbischoff** [kiali/kiali#4570]
After upgrading our Kiali to v1.44 the Service view does not show any Services anymore, when some namespaces are selected. For other namespaces (e.g. only `istio-system`) the Service list is rendered correctly.

![Screenshot 2021-12-08 at 09 58 01](https://user-images.githubusercontent.com/12122170/145367768-8e4d8db0-3d04-4e3c-929c-665ed8451f14.png)

![Screenshot 2021-12-08 at 09 58 10](https://user-images.githubusercontent.com/12122170/145367782-8def4274-ebbc-4aef-8b7e-c96a6591fe36.png)

The browser console shows following log:

```
main.3c0ceb9f.chunk.js:1 Could not fetch services list: 
value @ main.3c0ceb9f.chunk.js:1
(anonymous) @ main.3c0ceb9f.chunk.js:1
Promise.catch (async)
value @ main.3c0ceb9f.chunk.js:1
value @ main.3c0ceb9f.chunk.js:1
value @ main.3c0ceb9f.chunk.js:1
os @ 2.69e58466.chunk.js:2
du @ 2.69e58466.chunk.js:2
t.unstable_runWithPriority @ 2.69e58466.chunk.js:2
Wi @ 2.69e58466.chunk.js:2
hu @ 2.69e58466.chunk.js:2
Zs @ 2.69e58466.chunk.js:2
(anonymous) @ 2.69e58466.chunk.js:2
t.unstable_runWithPriority @ 2.69e58466.chunk.js:2
Wi @ 2.69e58466.chunk.js:2
Yi @ 2.69e58466.chunk.js:2
Hi @ 2.69e58466.chunk.js:2
eu @ 2.69e58466.chunk.js:2
notify @ 2.69e58466.chunk.js:2
t.notifyNestedSubs @ 2.69e58466.chunk.js:2
t.handleChangeWrapper @ 2.69e58466.chunk.js:2
m @ 2.69e58466.chunk.js:2
(anonymous) @ 2.69e58466.chunk.js:2
setActiveNamespaces @ main.3c0ceb9f.chunk.js:1
n.onToggle @ main.3c0ceb9f.chunk.js:1
(anonymous) @ 2.69e58466.chunk.js:2
(anonymous) @ 2.69e58466.chunk.js:2
main.3c0ceb9f.chunk.js:1 Could not fetch services list: 
value @ main.3c0ceb9f.chunk.js:1
(anonymous) @ main.3c0ceb9f.chunk.js:1
Promise.catch (async)
value @ main.3c0ceb9f.chunk.js:1
value @ main.3c0ceb9f.chunk.js:1
n.handleRefresh @ main.3c0ceb9f.chunk.js:1

```

The network tab shows requests to `api/namespaces/<evil-namespace>/services` actually going through with `200 OK` and showing a json response:

```json
{"namespace":{"name":"<evil-namespace>","labels":null,"annotations":null},"services":[{"name":"test-no-istio","namespace":"<evil-namespace>","istioSidecar":false,"appLabel":true,"additionalDetailSample":null,"healthAnnotations":{},"labels":null,"selector":{"app":"test-no-istio"},"istioReferences":[],"kialiWizard":"","serviceRegistry":"Kubernetes"},{"name":"test","namespace":"<evil-namespace>","istioSidecar":false,"appLabel":true,"additionalDetailSample":null,"healthAnnotations":{},"labels":null,"selector":{"app":"test"},"istioReferences":[],"kialiWizard":"","serviceRegistry":"Kubernetes"},{"name":"test-no-istio","namespace":"<evil-namespace>","istioSidecar":false,"appLabel":true,"additionalDetailSample":null,"healthAnnotations":{},"labels":null,"selector":{"app":"test-no-istio"},"istioReferences":[],"kialiWizard":"","serviceRegistry":"Kubernetes"},{"name":"test","namespace":"<evil-namespace>","istioSidecar":false,"appLabel":true,"additionalDetailSample":null,"healthAnnotations":{},"labels":null,"selector":{"app":"test"},"istioReferences":[],"kialiWizard":"","serviceRegistry":"Kubernetes"}],"validations":{}}
```

I have replaced the namespace name with `<evil-namespace>`, as it is a tenant namespace which's name I cannot share.

**Versions:**

Kiali: v1.44.0

```sh
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (17 proxies)
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.7
```

**Comment by lucasponce** [comment]
Would you see any other endpoint failing in the browser ?
Anything in the Kiali log ?

**Comment by maxbischoff** [comment]
The logs show only some port-forward failures, which I wanted to report separately, as I think they are unrelated:

```
E1209 09:45:53.587471       1 portforward.go:400] an error occurred forwarding 14837 -> 15014: error forwarding port 15014 to pod e431a5438e8a6e163f298237f9848d14ff6383999eae180191eac96820177f06, uid : failed to execute portforward in network namespace "/var/run/netns/cni-aec6da67-a43b-b3bf-fb22-883a173c8e4a": failed to connect to localhost:15014 inside namespace "e431a5438e8a6e163f298237f9848d14ff6383999eae180191eac96820177f06", IPv4: dial tcp4 127.0.0.1:15014: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
```

These occur from time to time. When opening the Services Windows I see following log:

```
2021-12-09T11:30:42Z TRC GetServiceRequestRates [namespace: <evil-namespace>] [service: sample-nginx] [ratesInterval: 60s] [queryTime: 2021-12-09 11:30:42.423823014 +0000 UTC m=+6754.233725845]
2021-12-09T11:30:42Z TRC [Prom] getRequestRatesForLabel: rate(istio_requests_total{destination_service_name="sample-nginx",destination_service_namespace="<evil-namespace>"}[60s]) > 0
2021-12-09T11:30:42Z TRC [Prom Cache] SetServiceRequestRates [namespace: <evil-namespace>] [service: sample-nginx] [ratesInterval: 60s] [queryTime: 2021-12-09 11:30:42.423823014 +0000 UTC m=+6754.233725845]
```

The networking tab in my browser dev-tools shows no failed requests at all (all have status `200`)

**Comment by lucasponce** [comment]
@maxbischoff it looks like the kiali pod can't query the istiod pod to fetch the status information.
do you have a way to reproduce this error ? or do you have some extra security between kiali pod, istiod pod and data plane pod ?

**Comment by lucasponce** [comment]
Does this FAQ https://kiali.io/docs/faq/general/#what-do-i-need-to-run-kiali-in-a-private-cluster help ?

**Comment by lucasponce** [comment]
Minikube with Istio 1.12 and Kiali 1.44 (updated used the Kiali operator):
![image](https://user-images.githubusercontent.com/1662329/145394427-3a97aeec-a000-4463-9bfa-ad2faf1e4d02.png)
![image](https://user-images.githubusercontent.com/1662329/145394466-b034cde0-d2e0-4974-803b-fa1772253be7.png)
![image](https://user-images.githubusercontent.com/1662329/145394502-7215a976-0ca5-4477-addc-554877dc5dbf.png)

I'd need more details about your installation, and how different is from one based in the Istio demo profile.

I have the suspect that the 15014 port is closed or may be you have it configured in a different port ? In Kiali 1.44 Kiali can define in which port istiod is listening (in case that your pod is using a different one).

**Comment by maxbischoff** [comment]
I have not changed the default istiod port, and security relevant settings (especially RBAC and the Service Account) are unchanged from my working `v1.38.0` installation of Kiali.

I installed Kiali using helm with following values into the namespace `kiali`:

```yaml
istio_namespace: istio-system
  auth:
    strategy: openid
    openid:
      # omitted since (most likely irrelevant)
  api:
    namespaces:
      label_selector: kiali=enabled
  deployment:
    # only bind the ClusterRole for viewing resources to the kiali-SA
    view_only_mode: true
    priority_class_name: cluster-support
    ingress:
      enabled: true
      class_name: ""
      additional_labels:
        ingress-domain: system
      override_yaml:
        metadata:
          annotations:
            ingress.kubernetes.io/ssl-redirect: "true"
            # enable sticky sessions
            traefik.ingress.kubernetes.io/affinity: "true"
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "500Mi"
  external_services:
    prometheus:
      url: http://prometheus-system.monitoring
    istio:
      component_status:
        enabled: false
      root_namespace: istio-system
  server:
    web_schema: https
    web_root: "/"
    web_fqdn: <omitted>
```

When starting a pod with an image containing `kubectl` in the `kiali` namespace using the `kiali` ServiceAccount, port-forwarding works to the 15014 port on istiod
