### ISSUE TITLE
Number of regex.Compile() calls in multi_match_checker scales quadratically with hosts checked

### ISSUE THREAD

**Issue by maxbischoff** [kiali/kiali#4592]
Since we had problems with Kiali using very much CPU while still being very slow, I analyzed performance in our cluster using pprof.

I found that when checking for host conflicts in istio Gateways, every comparison of two hosts incorporates two regex.Compile() calls (one for each host name) that are quite slow. You can see the impact in my pprof graph (the regex Compiles make up 109 seconds of CPU time, of my 20 second capture, I assume that is because the code is run in parallel since I loaded multiple views in parallel) in the red box:

![profile002](https://user-images.githubusercontent.com/12122170/145985329-8bbcc9df-2173-4c13-bb3f-9a119d6578b1.png)

This problem is only really appearing when l having a large number of hosts in Gateways, and is already partly mitigated by https://github.com/kiali/kiali/pull/4578. In our multi-tenant setup we have a Gateway resource that exposes the same two hosts to many namespaces (playground namespaces for our users that can expose VirtualServices on a shared gateway in the same wildcard domain):

```yaml
- port:
    name: https
    number: 443
    protocol: HTTPS
  hosts:
    - "playground-user1/*.example-cluster1.com"
    - "playground-user1/*.example-mesh1.com"
    - "playground-user2/*.example-cluster1.com"
    - "playground-user2/*.example-mesh1.com"
    # ...
    - "playground-user800/*.example-cluster1.com"
    - "playground-user800/*.example-mesh1.com"
- port:
    name: http
    number: 80
    protocol: HTTP
  hosts: # same as above
```

With this configuration and https://github.com/kiali/kiali/pull/4578 already applied we still have ~800 comparisons of `*.example-cluster1.com` with `*.example-mesh1.com` that each incorporate two `regexp.Compile()` calls per Port.

This makes this issue much more apparent than I would expect it to be in other setups.
I have implemented a caching mechanism for `regexp.Regexp` objects that fixes the problem in my setup, a PR will follow shortly.
