### ISSUE TITLE
Wrong API Url in Rancher Multi-Cluster setup

### ISSUE THREAD

**Issue by eumel8** [kiali/kiali#4594]
Kiali: 1.44
Kubernetes: 1.20.12
Istio: 1.12.0

I have installed Kiali in Istio Downstream cluster managed by Rancher. When I klick on Mesh menu in the Kiali UI the remote cluster is named but the endpoint is not reachable. The following error occured in log:

```
2021-12-14T18:50:44Z WRN Cannot describe the 'istio-system' namespace on cluster 'mcsps-test-k8s-06': the server could not find the requested resource (get namespaces istio-system)
```

I discovered Rancher API and observed the following request:

```
{"auditID":"xxxxx","requestURI":"/k8s/clusters/c-f7r9g:443/api/v1/namespaces/istio-system?timeout=15s","user":{"name":"u-xxxx","group":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":[""],"username":[""]}},"method":"GET","remoteAddr":"10.42.1.16:43210","requestTimestamp":"2021-12-14T19:00:40Z","responseTimestamp":"2021-12-14T19:00:40Z","responseCode":404,"requestHeader":{"Accept":["application/json, */*"],"Accept-Encoding":["gzip"],"Impersonate-Group":["system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-xxxx"],"User-Agent":["kiali/v0.0.0 (linux/amd64) kubernetes/$Format"],"X-Forwarded-For":["10.42.1.1"],"X-Forwarded-Host":["rancher.mcsps.de"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Server":["traefik-psx84"],"X-Real-Ip":["10.42.1.1"]},"responseHeader":{"Content-Type":["application/json"],"X-Api-Cattle-Auth":["true"],"X-Content-Type-Options":["nosniff"]}}
```

My remote secret looks like this:

```
apiVersion: v1
kind: Config
clusters:
- name: "mcsps-test-k8s-06"
  cluster:
    server: "https://rancher.mcsps.de/k8s/clusters/c-f7r9g"

users:
- name: "mcsps-test-k8s-06"
  user:
    token: "kubeconfig-u-xxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

contexts:
- name: "mcsps-test-k8s-06"
  context:
    user: "mcsps-test-k8s-06"
    cluster: "mcsps-test-k8s-06"

current-context: "mcsps-test-k8s-06"
```

Compared kubectl with `describe namespaces istio-system` command I'm pretty sure somewhere in Kiali the API Url is rewritten with port 443 at the end, which works in plain Kubernetes API endpoint but not in Rancher, where this value is on the wrong place:

```/k8s/clusters/c-f7r9g:443/api/v1/namespaces/istio-system```

Couldn't found the right intention somewhere around https://github.com/kiali/kiali/blob/master/business/mesh.go#L531
