### ISSUE TITLE
feat(multitenancy): support additional metric label for prometheus

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4664]
## Background
>This is a feature proposal of multi-clusters and multi-meshes.

In our production environment, prometheus has large storage which can be used to receive metrics of multi-mesh or clusters. We distinguish mesh by  label `mesh` and cluster by label `cluster` like below:
![image](https://user-images.githubusercontent.com/48784001/149944727-4bf34066-92b2-4b08-b28e-8a7d63672ad7.png)

### Multi-Meshs with Multi-Clusters

**Relationship(Prometheus:Mesh:Kiali:Cluster): 1:1:N:M** (N<=M)
We distinguish metrics by additional `mesh` and `cluster` label
![image](https://user-images.githubusercontent.com/48784001/149954563-6cb4aae1-9597-4351-8a81-3b0f91544179.png)

### Single Mesh with Multi-Clusters

**Relationship(Prometheus:Mesh:Kiali:Cluster): 1:1:1:N**  
We distinguish metrics by additional `cluster` label
![image](https://user-images.githubusercontent.com/48784001/149954923-7c4637fe-ce81-4c1f-9956-7824ff330e50.png)

In kiali, it seems like we miss some additional dimensions option for receiving multi-clusters/meshes in one prometheus.

For example:
I deploy kiali with cluster `kubernetes` to observe it in meshA, the other cluster is not deployed with kiali in meshB. These two clusters are running the same apps/services/workloads in the same namespaces. Their metrics are recieved in the same prometheus.

Namespace Graph will show the other cluster`s graph(which has the namespace):
![image](https://user-images.githubusercontent.com/48784001/149940057-da7f8185-1565-4308-b557-486fec54d54d.png)

NodeGraph will show the other node`s graph(which has the same node name):
![image](https://user-images.githubusercontent.com/48784001/149940750-f88cc7f3-b31d-4588-9d07-5a0c6155df48.png)
## Changes
Add additional labels in configuration, which is a `[]map[string]string`:

``` yaml
prometheus:
  auth:
    ca_file: ''
    insecure_skip_verify: false
    password: ''
    token: ''
    type: none
    use_kiali_token: false
    username: ''
  cache_duration: 10
  cache_enabled: true
  cache_expiration: 300
  custom_headers: {}
  health_check_url: ''
  additional_label:
    - key1: value1
    - key2: value2
  is_core: true
  thanos_proxy:
    enabled: false
    retention_period: 7d
    scrape_interval: 30s
  url: ''

```

In `graph/telemetry/istio/istio.go` :
Take below as an example:
``` go
		case graph.NodeTypeWorkload:
			query = fmt.Sprintf(`sum(rate(%s{reporter="destination"%s,destination_workload_namespace="%s",destination_workload="%s"%s} [%vs])) by (%s) %s`,
				metric,
				destCluster,
				namespace,
				n.Workload,
				additionalLabels,
				int(duration.Seconds()), // range duration for the query
				groupBy,
				idleCondition)
```
We add one more field `additionalLabels` which is generated by config or request like: `,key1="value1",key2="value2"`.

This will help multi-clusters/multi-mesh scenarios, for distinguishing different clusters and different meshes.

In the future, if multi-clusters or multi-mesh are distinguished by addtional labels, even we can add two more dimensions `mesh` and `cluster`on the left of Namespace, choose the seletced mesh/cluster/namespace to show graphs:

**Relationship between mesh and cluster and namespaces is **N:M:H** N<=M<=H**

![image](https://user-images.githubusercontent.com/48784001/149943768-1396973b-545a-4d08-8018-ae18ae526d61.png)

Multitenancy is a complex task for changes would be large. For example, we should interact with multi-ClusterAPI to manage multi-meshes CRDs. But additional labels to compute metrics/graph in multi-meshes would be a start. After that interations with multi-ClusterAPI can be planed.

Even if multitenancy is not planed to make it happen, I think additional custom labels to prometheus for custom restrictions (no matter what the restrictions are, just for extending restrictions rules) is important as well. Standard metrics and labels sometimes are not satisfied with some scenarios.
