### ISSUE TITLE
namespace excludes default regexes should only filter out namespaces that "starts-with" the patterns.

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4714]
A namespace "akube-foo" doesn't show up in Kiali.

The problem is the processing of the `spec.api.namespaces.exclude` setting. The default contains `kube-.*` but the server is not considering this as `^kube-.*` which is what users expect.

We should not always assume custom-set exclude regexes should begin with `^`. But we should change the defaults to include that since people are going to assume we only disallow namespaces that start with "kube-" (since those are special names in k8s environments) but not disallow namespaces that simply include "kube-" in the middle of the name (since those are NOT special names in k8s environments). The same holds true for the other settings.

So the fix is simple - the default should be:

```
  api:
    namespaces:
      exclude:
      - "^istio-operator"
      - "^kube-.*"
      - "^openshift.*"
      - "^ibm.*"
      - "^kiali-operator"
```
 
Thus all settings will only match those namespaces that START WITH those regexes.
