### ISSUE TITLE
DestinationWeight on route doesn't have a valid service (host not found)

### ISSUE THREAD

**Issue by wansuiye** [kiali/kiali#474]
**General remarks**

**Describe the bug**
the virtualservice work well, but kiali show the error:"DestinationWeight on route doesn't have a valid service (host not found)".
![image](https://user-images.githubusercontent.com/11864894/44901296-920f0880-ad39-11e8-9cf5-39da0e9d2112.png)

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: configserver
spec:
  hosts:
  - "configserver.test.io"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
         port:
           number: 8888
         host: configserver.infra.svc.cluster.local
---
```

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: 0.6
Istio: 1.0.1
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**

**Expected behavior**
