### ISSUE TITLE
"More than one Gateway for the same host port combination" even with different ports

### ISSUE THREAD

**Issue by dex4er** [kiali/kiali#4786]
This is #4466 again:

```yaml
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: istio-ingressgateway-https
  namespace: istio-system
spec:
  servers:
  - port:
      number: 443
      protocol: HTTPS
      name: https
    hosts:
    - host.name.com
    tls:
      mode: SIMPLE
      credentialName: certificate
      minProtocolVersion: TLSV1_2
  - port:
      number: 80
      protocol: HTTP
      name: http
    hosts:
    - host.name.com
    tls:
      httpsRedirect: true
  selector:
    istio: ingressgateway
```

and I'm getting `KIA0301: More than one Gateway for the same host port combination`:

![image](https://user-images.githubusercontent.com/174367/156760812-c0f7e1ed-1117-429b-b625-8dd34175719a.png)

Versions:

Kiali UI 1.47.0 (d37fff0dad452ed0bc1b122d4543fc40bd0b8510)
Kiali Server v1.47.0 (31da692118694362f1a04b25f2d661edc5e8c11f)
Kiali Container v1.47.0
Components
Prometheus 2.24.1
Kubernetes v1.20.15-gke.300
