### ISSUE TITLE
Jaeger - namespace_selector not working for services in istio-system

### ISSUE THREAD

**Issue by davtex** [kiali/kiali#4935]
Internal query to Jaeger and sometimes external query to Jaeger is missing namespace if the selected service/application/workload is in istio-system namespace despite "namespace_selector" being set to "true".

I do not have issues with any other namespaces, e.g. developer-poratl-uat -> I always have "service=service.namespace" in query:
```
Application:
https://jaeger.infra.dc.uat.k8s.XYZ/search?limit=100&service=devportaluseraccountmfe.developer-portal-uat&start=1649304127750000
http://jaeger-query.jaeger:16686/api/traces?end=1649325727000000&limit=100&service=devportaluseraccountmfe.developer-portal-uat&start=1649304127000000

Workload:
https://jaeger.infra.dc.uat.k8s.XYZ/search?limit=100&service=devportaluseraccountmfe.developer-portal-uat&start=1649304174563000
http://jaeger-query.jaeger:16686/api/traces?end=1649325910000000&limit=500&service=devportaluseraccountmfe.developer-portal-uat&start=1649325310000000

Services:
https://jaeger.infra.dc.uat.k8s.XYZ/search?service=devportaluseraccountmfe.developer-portal-uat&start=1649304400096000&limit=100
http://jaeger-query.jaeger:16686/api/traces?end=1649326011000000&limit=100&service=devportaluseraccountmfe.developer-portal-uat&start=1649325411000000
```

Problem is only with istio-system, where namespace is always missing with exception of Application's external query:
```
Application:
https://jaeger.infra.dc.uat.k8s.XYZ/search?limit=100&service=istio-ingressgateway.istio-system&start=1649304450753000
http://jaeger-query.jaeger:16686/api/traces?end=1649326141000000&limit=100&service=istio-ingressgateway&start=1649304541000000

Workload:
https://jaeger.infra.dc.uat.k8s.XYZ/search?service=istio-ingressgateway&start=1649304627157000&limit=100
http://jaeger-query.jaeger:16686/api/traces?end=1649326227000000&limit=500&service=istio-ingressgateway&start=1649304627000000

Services:
https://jaeger.infra.dc.uat.k8s.XYZ/search?limit=100&service=istio-ingressgateway&start=1649304671673000
http://jaeger-query.jaeger:16686/api/traces?end=1649326331000000&limit=100&service=istio-ingressgateway&start=1649304731000000
```

I've tried moving istio-ingressgateway to different namespace to eliminate possibility that it's some labeling issue or  something and it worked -> as soon as I moved it to "kiali" namespace, query had "service=istio-ingressroute.kiali" in it. So as far as I can say, "namespace_selector" functionality is somehow broken for services inside namespace defined in "istio_namespace" Kiali config.

I have also tried removing my label selector, "whitelist_istio_system" parameter, component_status etc. -> it did not have any impact. Only solution was to move istio-ingressgateway to different NS.

I am using v1.48 Kiali Operator with following Kiali CR:
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
  generation: 1
  labels:
    argocd.argoproj.io/instance: kiali
  name: kiali
  namespace: istio-system
spec:
  api:
    namespaces:
      label_selector: istio-injection=enabled
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: '**'
    image_name: XYZ/kiali/kiali
    image_pull_secrets:
    - harbor-secret
    image_version: v1.48.0
    ingress:
      class_name: infra-traefik
      enabled: true
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: "false"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  external_services:
    grafana:
      enabled: false
    istio:
      component_status:
        components:
        - app_label: istiod
          is_core: true
          is_proxy: false
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
        - app_label: istio-eastwestgateway
          is_core: true
          is_proxy: true
        enabled: true
    prometheus:
      auth:
        insecure_skip_verify: true
      url: https://prometheus.infra.dc.uat.k8s.XYZ
    tracing:
      enabled: true
      in_cluster_url: http://jaeger-query.jaeger:16686
      namespace_selector: true
      url: https://jaeger.infra.dc.uat.k8s.XYZ
      use_grpc: false
      whitelist_istio_system:
      - jaeger-query
      - istio-ingressgateway
      - istio-eastwestgateway
  istio_labels:
    app_label_name: app
    version_label_name: version
  istio_namespace: istio-system
  server:
    web_fqdn: kiali.infra.dc.uat.k8s.XYZ
    web_root: /
    web_schema: https
```

istioctl:
client version: 1.12.2
control plane version: 1.13.2
data plane version: 1.13.2 (90 proxies)
kubectl:
Client Version: v1.22.5
Server Version: v1.20.4
