### ISSUE TITLE
Keycloak: OpenId provider: json: duplicate key 'iss' in object

### ISSUE THREAD

**Issue by enterdv** [kiali/kiali#4964]
**Describe the bug**
Trying to configure openid authentication with keycloak with [this](https://kiali.io/docs/configuration/authentication/openid/) manual. When I click _Log In With OpenID_ i see error message
`Authentication failed: cannot parse the payload of the id_token from the OpenId provider: json: duplicate key 'iss' in object`

Logs in kiali
```
ERR Not handling OpenId code flow authentication: %s%!(EXTRA string=no authorization code is present)
```

**Versions used**
helm-chart kiali/kiali-server version 1.49.0

**kiali configuration**
```
auth:
  strategy: "openid"
  openid:
    client_id: "kiali.<domain>"
    disable_rbac: true
    issuer_uri: "https://<domain>/auth/realms/keycloak"
    scopes: [ "openid" ]
    username_claim: "email"
    authentication_timeout: 60
```
kiali is behind nginx-ingress controller if it matters

KEYCLOAK_IDENTITY cookie:
```
{
  "exp": 1650314281,
  "iat": 1650278281,
  "jti": "0612262d-3802-4515-b4cf-48c06115f45c",
  "iss": "https://<domain>/auth/realms/keycloak",
  "sub": "f8365ffd-9324-4000-8da6-fa04d2090d04",
  "typ": "Serialized-ID",
  "session_state": "48225564-fb44-43c4-b791-77f2920b2daf",
  "state_checker": "V3XXYryci08qkOIQVVGcJJgCMYlbeNtQgtEFgnfa7rM"
}
```

What am I doing wrong?
