### ISSUE TITLE
validation error when using .svc hostnames in Destination Rule

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4975]
Installed OSSM 2.2 which installs this Destination Rule out of box in istio-system:

```yaml
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: disable-mtls-jaeger-collector
  namespace: istio-system
#...
spec:
  host: jaeger-collector.istio-system.svc # <--- look here
  trafficPolicy:
    tls: {}
```

This causes a validation error:

![image](https://user-images.githubusercontent.com/2029470/164196622-7f3a4c86-58a4-496e-a6a7-ecb3c9ee08cc.png)

When I remove ".svc" from the `spec.host` value, the validation error goes away.
