### ISSUE TITLE
Allow overriding `spec.strategy` via operator/CR

### ISSUE THREAD

**Issue by mjnagel** [kiali/kiali#5011]
Currently there does not seem to be a way to override the `spec.strategy` for the Kiali CR (deploying via the operator).

When deploying with a single replica for Kiali, the default strategy set is:
```yaml
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

This causes downtime since this allows for the single replica to be unavailable. If there were a way to override this via the CR spec that would be ideal. I'm not sure what the default may be with different numbers of replicas, but I think regardless it would be nice to have the ability to customize this.
