### ISSUE TITLE
Sidecar usage extension for the kiali operator.

### ISSUE THREAD

**Issue by libesz** [kiali/kiali#5028]
Hi!
 I would like to discuss a generic extension possibility to the Kiali operator. The PromQL API that I would like to integrate Kiali to, is requesting a API bearer token that is expiring very often. Since Kiali is not able (and I guess also not planning to be able 😄 ) to renew tokens or exchange API keys to tokens, I am thinking on another solution. (see previous ticket from our colleague: https://github.com/kiali/kiali/issues/4677). 
 So the idea would be that:
* the integrator (us) is implementing the token renewal magic and a (transparent) proxy as part of a sidecar container in the kiali pod
* prometheus endpoint would point to this sidecar (i.e. localhost)
* the integrator configures the sidecar container in the kiali cr

Having the sidecar in a standalone pod would need it's own authentication and TLS on it's HTTP interface to avoid misuse. Implementing it as a classic proxy sidecar seems to be cleaner.

This could be done via adding a new kiali operator config object which let's the integrator to add a complete container to the kiali pod spec. This would be very similar to what [additional_service_yaml](https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml#L220) does with the kiali service object.

**Comment by jmazzitelli** [comment]
I don't fully grok the proposed solution, but... wouldn't it be simpler to just update the Kiali CR with the new prometheus credentials? The operator will see the change and immediately propagate the new credentials down to the Kiali ConfigMap and automatically restart the Kiali pod so it picks up the new credentials. This is already supported. You would just need to patch the Kiali CR with the new credentials in the `spec.external_services.prometheus.auth` section. Or am I missing something?

**Comment by israel-hdez** [comment]
> wouldn't it be simpler to just update the Kiali CR with the new prometheus credentials?

My guess is that it comes down to efficiency.

I note that @libesz says that the token expires "very often". The typical expiration I've seen for these cases is 5 minutes. You will want to roll out a fresh token before the old one expires to avoid the situation when Kiali can no longer reach Prometheus, so let's assume that you refresh every 4 minutes. That's 15 updates in an hour. The operator will use way much more resources for all these reconciliations (which may also flood the kubeapi), than the resources a sidecar may use by doing a simple request to refresh a token. Also, a sidecar can refresh on-demand (i.e. if nobody uses Kiali for some time, no need to refresh the token).

@libesz I would like to ask if your Prometheus lives in the same cluster where Kiali would live? If it does, I may think that it is easier to connect Kiali directly to prometheus (skipping whatever thing is securing it), and protect the Prometheus API only for incomig out-of-cluster requests. If not possible... well... we need to think about it...

**Comment by libesz** [comment]
I was not aware that config change in Kiali CR triggers the kiali pod's restart, good to know! However as @israel-hdez said it would be great to run this exchange on demand. I would avoid flooding our IAM system when no one is using the kiali dashboard (I assume otherwise Kiali does not pull prometheus data). This is a managed service so a lot of instances are going to be installed eventually by different customers. As this proxy would sit in the data path, it would be fully on-demand.

The tokens are valid for 20minutes in this scenario, and I think it would be a bad UX to wait for kiali restarts in every 20 minutes. With a single kiali pod, it takes 20-30 seconds to become Ready in our system. Or do we have any HA solution to overcome on this part?

@israel-hdez the thing what provides PromQL API is also an external managed service, with a remote endpoint (the one we asked the custom http headers for last year 🙂).

**Comment by jmazzitelli** [comment]
> This could be done via adding a new kiali operator config object which let's the integrator to add a complete container to the kiali pod spec. This would be very similar to what [additional_service_yaml](https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml#L220) does with the kiali service object.

I think if this is all you need to get done what you need, it would be the simplest solution and easiest for us to implement on the Kiali side. We'd have to figure out what the Kiali CR yaml would look like for this. Perhaps something like `spec.deployment.pod_sidecar_yaml` - you would then provide a full named container yaml and the operator would simply "pass through" that yaml to the Deployment. So I envision something like:

```yaml
spec:
  deployment:
    pod_sidecar_yaml:
      name: my_sidecar
      image: your/sidecar/image:v1.0
      command: ...
      ...and whatever else needs to go in this named container...
```

When Kiali operator creates the Kiali Server Deployment, it would add this as a container to the list of existing Kiali containers (of which there is only one - the main kiali server binary).

```yaml
kind: Deployment
metadata:
  name: kiali
spec:
  template:
    spec:
      containers:
      - name: kiali
        image: quay.io/kiali/kiali:v1.50.0
        command: ['/opt/kiali/kiali', '-config', '/kiali-configuration/config.yaml']
      ### HERE IS WHERE THE SIDECAR YAML WILL GO ###
      - name: my_sidecar
        image: your/sidecar/image:v1.0
        command: ....
        ...and the rest....
```

Is this what you need and will work for your use-case?

Would there ever be a need to define multiple sidecars/containers? The above example only supports 1. I suppose we could support multiple as a generic solution:

```yaml
spec:
  deployment:
    additional_pod_containers_yaml:
    - name: my_sidecar
      image: your/sidecar/image:v1.0
      command: ...
      ...and whatever else needs to go in this named container...
    - name: my_sidecar2
      image: your/sidecar2/image:v2.2
      command: ...
      ...and whatever else needs to go in this second named container...
```
