### ISSUE TITLE
Duplicate service node in graph view

### ISSUE THREAD

**Issue by denniseffing** [kiali/kiali#505]
I deployed a small sample application consisting of three services:
- mts-frontend
- mts-booking-order
- mts-dishes (3 instances, round robin load balancer)

The `mts-booking-order` service communicates with the `mts-dishes` service (mesh internal communication) while `mts-booking-order`, `mts-dishes` and `mts-frontend` can be reached from the outside via Istio ingress gateway configuration.

Today, I was testing the Istio failure injection which led to the following virtual service configuration:
```yaml
################################################################################
# Istio virtual service configuration with injected outages for dishes service
################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mts-routes
spec:
  hosts:
  - mts.local
  - mts.local:31380
  - mts.local:31390
  - mts-dishes.default.svc.cluster.local
  gateways:
  - mesh
  - mts-gateway
  http:
  - match:
    - uri:
        prefix: /api/services/rest/dishmanagement/
      headers:
        username: 
          exact: fault.injection
    - sourceLabels:
        app: mts-booking-order
    fault:
      abort:
        httpStatus: 500
        percent: 100
    rewrite:
      uri: /
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /api/services/rest/dishmanagement/
    rewrite:
      uri: /
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /api
    rewrite:
      uri: /mythaistar
    route:
    - destination:
        host: mts-booking-order.default.svc.cluster.local
        port:
          number: 8081
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: mts-frontend.default.svc.cluster.local
        port:
          number: 80
```

**Describe the bug**
The resulting Kiali service graph visualization after issuing some requests looks like this:
![grafik](https://user-images.githubusercontent.com/5879568/45775243-694ea480-bc4f-11e8-8e52-57915341d224.png)

When not displaying any preceding requests, the service graph looks like this:
![grafik](https://user-images.githubusercontent.com/5879568/45775289-9c913380-bc4f-11e8-9fe1-bd514cce8970.png)

As you can see in the first picture, the service `mts-dishes` is drawn twice. I couldn't find any information about the octagon representation.

Is this intended behavior?

**Versions used**
Kiali: v0.6
Istio: v1.0.2
Kubernetes flavour and version: v1.10

**To Reproduce**
I am not sure how to reproduce this behavior yet.

**Expected behavior**
`mts-dishes` is only drawn once (i.e. one node).

Edit: The same issue does not occur when injecting delays.
