### ISSUE TITLE
istio gateway and it's service is not consider as an app

### ISSUE THREAD

**Issue by H01001000** [kiali/kiali#5102]
In kiali, it will have a box that bound an app, but for the istio gateway and its service, the app box did not show.

**Comment by lucasponce** [comment]
Hi, @H01001000 I'd say it depends on the labels (app and version) used by the workloads.

Could you attach some screenshots about what you get in Kiali, and also which versions of Istio/Kiali are you using?

Thanks

**Comment by H01001000** [comment]
verisons:
I am running istio 1.13.4 and kiali 1.45

context:
I am running cloudflare tunnel and route all traffic to istio gateway service. I have two gateway called istio-ingressgateway-public and istio-ingressgateway-private

I have label both service, deployment and pod with the app label 

<details>
<summary>IstioOperator config</summary>

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: ghcr.io/resf/istio
  profile: minimal
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    pilot:
      k8s: # each components have to set this
        affinity: &affinity
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - arm64
                        - amd64
                weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - arm64
                        - amd64
    ingressGateways:
      - name: istio-ingressgateway-public
        k8s:
          affinity: *affinity
          hpaSpec:
            minReplicas: 2
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: istio-ingressgateway-public
                - path: spec.scaleTargetRef.name
                  value: istio-ingressgateway-public
            - kind: Deployment
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: istio-ingressgateway-public
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-public
                - path: spec.selector.matchLabels.istio
                  value: istio-ingressgateway-public
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-public
                - path: spec.template.metadata.labels.istio
                  value: istio-ingressgateway-public
            - kind: Service
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: istio-ingressgateway-public
                - path: spec.selector.app
                  value: istio-ingressgateway-public
                - path: spec.selector.istio
                  value: istio-ingressgateway-public
        enabled: true
      - name: istio-ingressgateway-private
        k8s:
          affinity: *affinity
          hpaSpec:
            minReplicas: 2
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-private
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-private
                - path: metadata.labels.istio
                  value: istio-ingressgateway-private
                - path: spec.scaleTargetRef.name
                  value: istio-ingressgateway-private
            - kind: Deployment
              name: istio-ingressgateway-private
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-private
                - path: metadata.labels.istio
                  value: istio-ingressgateway-private
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-private
                - path: spec.selector.matchLabels.istio
                  value: istio-ingressgateway-private
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-private
                - path: spec.template.metadata.labels.istio
                  value: istio-ingressgateway-private
            - kind: Service
              name: istio-ingressgateway-private
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-private
                - path: metadata.labels.istio
                  value: istio-ingressgateway-private
                - path: spec.selector.app
                  value: istio-ingressgateway-private
                - path: spec.selector.istio
                  value: istio-ingressgateway-private
        enabled: true

```
</details>


![2022-05-23 15_32_16-Kiali Console](https://user-images.githubusercontent.com/48591478/169767451-5bfa8fc7-e7c6-421b-9e2c-225eddb1a917.png)
