### ISSUE TITLE
KIA0104 validation not being triggered for unknown hostnames

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5106]
[The documentation of the KIA0104 validation](https://kiali.io/docs/features/validations/#kia0104---this-host-has-no-matching-entry-in-the-service-registry) gives the understanding that users should see an error if an AuthorizationPolicy has unknown hosts. However, when using the example YAML provided in the same documentation, Kiali does not give any error.

It is also possible to use this minimal YAML to test:

```yaml
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: foo
  namespace: bookinfo
spec:
  rules:
  - to:
    - operation:
        hosts:
        - missing.hostname
```
