### ISSUE TITLE
"This subset's labels are not found in any matching host" - DestinationRule and ServiceEntry

### ISSUE THREAD

**Issue by artursitarski** [kiali/kiali#5131]
Kiali configs validator shows `This subset's labels are not found in any matching host` error for DestinationRule in combination with ServiceEntry and VirtualService:

<img width="1134" alt="Screenshot 2022-05-30 at 14 00 32" src="https://user-images.githubusercontent.com/2012391/170988589-02d3fdeb-d3c0-4c78-8128-83354e3baede.png">

ServiceEntry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: app-rpc.app.cluster-1a
  namespace: app
spec:
  endpoints:
  - address: XXX.us-east-1.elb.amazonaws.com
    labels:
      cluster: cluster-1a
    ports:
      data: 443
  hosts:
  - app-rpc.app.svc.cluster-1a.global
  location: MESH_INTERNAL
  ports:
  - name: data
    number: 8765
    protocol: TCP
  resolution: DNS
```

VirtualService:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-rpc-icc
  namespace: app
spec:
  hosts:
  - app-rpc
  - app-rpc.app
  gateways:
  - app/ingress-app
  - mesh
  http:
  - route:
    - destination:
        host: app-rpc.app.svc.cluster-1b.global
        subset: cluster-1b
      weight: 0
    - destination:
        host: app-rpc.app.svc.cluster-1a.global
        subset: cluster-1a
      weight: 0
    - destination:
        host: app-rpc.app.svc.cluster.local
      weight: 100
```

DestinationRule:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-rpc.app.cluster-1a
  namespace: app
spec:
  host: app-rpc.app.svc.cluster-1a.global
  subsets:
  - labels:
      cluster: cluster-1a
    name: cluster-1a
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: app-rpc.app
```

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-app
  namespace: app
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - app/app-rpc.app
    port:
      name: grpc
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-icc-app
      mode: SIMPLE
```
