### ISSUE TITLE
web_root with slash: openid redirects to web_root without 

### ISSUE THREAD

**Issue by Morriz** [kiali/kiali#5229]
When applying `web_root: /kiali`, the openid redirect is made to `.../kiali?...` instead of `.../kiali/?...`.

Dump of relevant parts of Kiali CR:
```yaml
server:
  web_root: /kiali/
  # with slash doesn't change the outcome one bit:
  # web_root: /kiali/
  web_fqdn: some.doma.in
```
