### ISSUE TITLE
kiali sends basic auth headers when `grafana.auth.type: bearer` is set

### ISSUE THREAD

**Issue by Morriz** [kiali/kiali#5230]
If, as according to the docs, we set
```yaml
grafana:
  auth:
    type: bearer
```
We expect kiali to forward the bearer token it was given, but instead kiali seems to send a basic auth header to grafana:
```
error from Grafana (401): Invalid Basic Auth Header
```

**Comment by jshaughn** [comment]
cc @israel-hdez

**Comment by israel-hdez** [comment]
@Morriz I'm wondering if this is still an issue for you?

To my eye, there is a configuration issue, because the right config should look like:
```yaml
spec:
  external_services:
    grafana:
      auth:
        type: bearer
```

Some people in the team do testing using auth-protected external services, so it is known that this should be working. Although, I'm unsure this would misbehave under some env-related configuration.
