### ISSUE TITLE
mTLS TCP traffic not showing lock icon

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5240]
### Problem definition
Sending http and tcp traffic, with mesh-wide mTLS enabled. Kiali is not showing the lock icon for the tcp traffic: 
![Screenshot from 2022-06-23 15-37-23](https://user-images.githubusercontent.com/49480155/175329144-bbdf565e-7196-48a5-88e7-f3ae45a72efa.png)

This behavior is the same for other graph types. Without the Services nodes:

![Screenshot from 2022-06-23 15-37-50](https://user-images.githubusercontent.com/49480155/175329181-e4b09f6f-8011-4e23-a06a-98ea1a40f2c7.png)

App graph:
![Screenshot from 2022-06-23 15-38-23](https://user-images.githubusercontent.com/49480155/175329193-4efe5081-06e5-4b82-a749-5ee6521cb2c4.png)

Workload graph:
![Screenshot from 2022-06-23 15-38-37](https://user-images.githubusercontent.com/49480155/175329204-24933ddf-1ece-4494-9cd2-bef8b0023a18.png)

Service graph:
![Screenshot from 2022-06-23 15-38-55](https://user-images.githubusercontent.com/49480155/175329210-d080a8ed-23d2-4a2b-b4b5-49b07801e4ec.png)

The prometheus traces shows that the connection_security_policy is set just for the reporter source, but not for the reporter destination:

`istio_tcp_sent_bytes_total{destination_service_name="tcpserver"}`
![Screenshot from 2022-06-23 15-39-23](https://user-images.githubusercontent.com/49480155/175329253-c4d575b7-9b49-41db-bbf9-dbb4f4bd26fb.png)

Regarding kiali documentation, the reporter destination is what it is looking for, so the information is in the telemetry:  https://kiali.io/docs/faq/graph/#which-lock-icons-should-i-see-when-i-enable-the-kiali-graph-security-display-option 

The Connection Security policy filter shows like this uses mTLS (In development branch) https://github.com/josunect/kiali/tree/issue5187 

![Screenshot from 2022-06-23 15-46-35](https://user-images.githubusercontent.com/49480155/175329277-7b84ba93-83c1-4e61-9641-4c7c3a9316df.png)

## How to reproduce it

This example is based on the following github issue: https://github.com/istio/istio/issues/22082
We will create 3 apps:
- Debugbox: An image meant for debugging.
- Tcpserver: An istio tcp echo server written in Go. 
- Httpserver: A http server. 

### Prerrequisites
mTLS should be enabled. It can be mesh-wide enabled: 

```
kubectl apply -n istio-system -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF
```

### Steps

```
kubectl create ns test
kubectl label namespace test istio-injection=enabled
kubectl create -f test.yaml
```

test.yaml
```

apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver
  namespace: test
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  namespace: test
  labels:
    app: httpserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugbox
  namespace: test
---
apiVersion: v1
kind: Service
metadata:
  name: debugbox
  namespace: test
  labels:
    app: debugbox
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: debugbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugbox
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugbox
  template:
    metadata:
      labels:
        app: debugbox
    spec:
      containers:
      - name: debugbox
        image: markeijsermans/debug
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  namespace: test
  labels:
    app: tcpserver
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: tcpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpserver
  template:
    metadata:
      labels:
        app: tcpserver
    spec:
      containers:
      - name: tcpserver
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcpserver
  namespace: test


```

## Generate requests from debugbox:
Http

`kubectl exec $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"`

Telnet

Install first:
`kubectl exec $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- apt install telnet -y`

Open session:
`kubectl exec -it $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- telnet tcpserver 9000`
