### ISSUE TITLE
Add drop all capabilities in container securityContexts

### ISSUE THREAD

**Issue by rjferguson21** [kiali/kiali#5247]
Fixes https://github.com/kiali/kiali/issues/5247

In order to improve security posture of Kiali deployments created by Kiali I am proposing the addition of the following to the container securityContexts. 

```
securityContext:
  capabilities:
    drop:
      - all
```

I  believe this to be the list of files that would need to be touched:    
* https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
* https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/deployment.yaml
* https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/deployment.yaml
* https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/deployment.yaml

Note: I am including the Kiali deployments created by both the operator and helm chart, as well as the operator itself.

**Comment by jmazzitelli** [comment]
Note also this trivial tidbit - virtually all the yaml in the kiali codebase does not indent yaml lists that extra indentation level. So the yaml to add would be:

```yaml
securityContext:
  capabilities:
    drop:
    - all      <<<---- don't add an extra level of indentation here
```
