### ISSUE TITLE
kiali-ui should have a contextpath and allow to customize

### ISSUE THREAD

**Issue by clyang82** [kiali/kiali#526]
I have a case to integrate some ui together and expose them by using the same ingress controller. here is an example ingress file:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
  annotations:
      kubernetes.io/ingress.class: xxx
spec:
  rules:
    - http:
        paths:
          - path: /console
            backend:
              serviceName: kiali
              servicePort: 20001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali-static-ingress
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
  annotations:
      kubernetes.io/ingress.class: xxx
spec:
  rules:
    - http:
        paths:
          - path: /static
            backend:
              serviceName: kiali
              servicePort: 20001
```
from the above example, the path '/static' and '/console' are very common path. if the 2 applications have the same path, we cannot expose them by the same ingress controller.

If the application have the contextpath, then we can use the following way to achieve this goal. Take 'kiali' as an example to explain:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
  annotations:
      kubernetes.io/ingress.class: xxx
      icp.management.ibm.com/rewrite-target: /kiali
spec:
  rules:
    - http:
        paths:
          - path: /kiali
            backend:
              serviceName: kiali
              servicePort: 20001
 ```
so we should have a contextpath for the application. for kiali application, can we consider to have a contextpath? Thanks.
