### ISSUE TITLE
Workloads and services do not report details 

### ISSUE THREAD

**Issue by fernandovillarreal-up** [kiali/kiali#5277]
Hello, I'm using kiali version 1.41.0 installed using the official helm chart. 

This is the information from the UI
Kiali UI: 1.41.0 (11084aa8bcf0fad2c844b56d00ed03c0e770c2a5)
Kiali Server: v1.41.0 (a972e5cf6d54517e585986a1653d80d8a9a0ff0a)
Kiali Container: v1.41.0
Components: Prometheus: 2.28.1
Kubernetes: v1.21.12-eks-a64ea69

Istio version: 1.13.1

We are also using calico's network policy, but the error happens before we defined some network rules.

This are the values we are setting for the deployment

```
auth:
  strategy: anonymous
deployment:
  image_name: 123456789012.dkr.ecr.us-west-2.amazonaws.com/quay.io/kiali/kiali
  image_version: v1.41.0
  replicas: 2
  override_ingress_yaml:
    metadata:
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/group.name: "infra-services"
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:123456789012:certificate/xxxxxxxx-aaaa-bbbb-cccc-yyyyyyyyyyyy"
        alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
        alb.ingress.kubernetes.io/healthcheck-path: "/kiali/healthz"
        alb.ingress.kubernetes.io/subnets: "subnet-xxxxxxxxxxxxxxxxx, subnet-yyyyyyyyyyyyyyyyy"
    spec:
      rules:
        - host: "kiali..........."
          http:
            paths:
              - path: /*
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: kiali
                    port:
                      number: 20001
  resources:
    requests:
      cpu: "40m"
      memory: "128Mi"
    limits:
      memory: "1Gi"
      cpu: "400m"
  hpa:
    spec:
      minReplicas: 3
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
  affinity:
    pod_anti:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - kiali
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - kiali
            topologyKey: topology.kubernetes.io/zone
  view_only_mode: true
  service_type: "NodePort"
external_services:
  istio:
    config_map_name: istio-1-13-1
    component_status:
      components:
      - app_label: "istio-ingressgateway-1-13-1"
        is_core: true
        is_proxy: true
        namespace: istio-system
      - app_label: "istio-egressgateway-1-13-1"
        is_core: false
        is_proxy: true
        namespace: istio-system
  prometheus:
    url: "http://rancher-monitoring-prometheus.cattle-monitoring-system:9090"
    auth:
      insecure_skip_verify: true
  tracing:
    # Enabled by default. Kiali will anyway fallback to disabled if
    # Jaeger is unreachable.
    enabled: true
    # Jaeger service name is "tracing" and is in the "telemetry" namespace.
    # Make sure the URL you provide corresponds to the non-GRPC enabled endpoint
    # if you set "use_grpc" to false.
    in_cluster_url: 'http://jaeger-staging-query.tla-monitor:443/'
    use_grpc: false
    # Public facing URL of Jaeger
    url: 'https://jaeger....../'
istio_namespace: "istio-system"

```
**Error description:**
While I browse a service I get this error: "Could not fetch Service Details". One of the links fails, the URL is this one: http://localhost:20001/kiali/api/namespaces/upwork-services/services/hellods?validate=true

When I do a curl from inside the kiali container I get this after ~40 seconds:
curl: (52) Empty reply from server

If a make the same call without the validate=true it works fine and I get a json object with the result.

The same happens when I browse a workload with this error: "Could not fetch Health/IstioConfig"

The URL with the issue is:
http://localhost:20001/kiali/api/namespaces/upwork-services/istio?objects=gateways,authorizationpolicies,peerauthentications,sidecars,requestauthentications,envoyfilters&validate=true&workloadSelector=app%3DhelloDS,app.kubernetes.io%2Fcomponent%3Dbackend,app.kubernetes.io%2Finstance%3Dhellods-depl-staging,app.kubernetes.io%2Fmanaged-by%3DHelm,app.kubernetes.io%2Fname%3DhelloDS,app.kubernetes.io%2Fpart-of%3DhelloDS,app.kubernetes.io%2Fversion%3D4.0.13-SNAPSHOT-master-hybrid-0efd5460-v3,app.upwork.com%2Fapp-family%3Dagora,app.upwork.com%2Fbounded-context%3DPLATFORM,app.upwork.com%2Fchart-name%3Dservice-deployment,app.upwork.com%2Fenvironment%3Dstaging,app.upwork.com%2Fruntime%3Deks,helm.sh%2Fchart%3Dservice-deployment-0.1.24,istio.io%2Frev%3D1-13-1,pleng5203%3Dmass-rollouts-06,redeploy%3DPLENG5203A,rollouts-pod-template-hash%3D59fc486d45,sidecar.istio.io%2Finject%3Dtrue,version%3D4.0.13-SNAPSHOT-master-hybrid-0efd5460-v3

Same thing happens with this URL, if I remove the validate=true the server responds immediatelly with the JSON object.

Any hint would be much appreciated.
