### ISSUE TITLE
upgrading kiali via Kiali CR may not work - needs a more solid implementation

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5369]
Scenario: In the context of Maistra, suppose I install an SMCP 2.0 which gets me a 2.0 control plane that runs fine. Now suppose I want to upgrade to a 2.1 control plane. I can just edit the SMCP's version field and change it so it goes from "2.0" to "2.1". The Maistra operator knows how to upgrade the control plane. Part of this upgrade means the Kiali CR `spec.version` will (or at least should - it's a question if the Maistra operator has a bug here, but ignore that for now) change (in the 2.0 -> 2.1 example, the Maistra operator will change the Kiali CR `spec.version` from `1.24` to `1.36`).

In this case, the Kiali Operator should "upgrade" kiali from a 1.24 install to a 1.36 install. Today, I'm not sure what the Kiali operator will do in this case. I think (not sure) what it will do is simply create/update resources based on the 1.36 playbook. But that isn't good enough. Because it is possible that the resources are different between 1.24 and 1.36 (for example, there may be some OpenShift resources that a 1.24 playbook creates but 1.36 no longer uses). It may work fine today, but I could see potential problems in the future (even if we aren't hitting those problems today with our current versions of Kiali).

So I think what we should do is if the Kiali Operator sees that the `spec.version` changes, it should run the "remove" playbook for the old version and then run the "create" playbook for the new version. This will ensure the old Kiali version is removed and the new Kiali version is installed. Essentially an "upgrade" becomes a "uninstall/install" under the covers. Because right now there is no knowledge in one playbook of resources created/managed in an older playbook (and we want to keep it that way).

**Comment by jmazzitelli** [comment]
The way I think we can solidify the upgrade scenario described, is right above [the playbook task that runs the create role](https://github.com/kiali/kiali-operator/blob/v1.54.0/playbooks/kiali-deploy.yml#L53-L57) is to run the remove role if the spec.version field changed. So something like this:

(note, we might need to add a status.kialiVersion to the status field - i don't think we store that in status today-- the alternative is to look at the configmap)

```yaml
  - name: If upgrade is in progress then run the old version-specific remove role
    include_role:
      name: "{{ _kiali_io_kiali.spec.version }}/kiali-remove"
    when:
    - skip_reconciliation is not defined or skip_reconciliation == False
    - _kiali_io_kiali.status.kialiVersion is defined
    - _kiali_io_kiali.spec.version != _kiali_io_kiali.status.kialiVersion

  - name: Run the version-specific deploy role
    include_role:
      name: "{{ version }}/kiali-deploy"
    when:
    - skip_reconciliation is not defined or skip_reconciliation == False
```
