### ISSUE TITLE
add capabilities-drop explicitly to deployment

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5399]
we should add the following to the kiali server deployment yaml (and probably to the operator metadata too - I don't think the operator needs this either).

```
        securityContext:
          capabilities:
            drop:
            - ALL
```

Files to touch:
* https://github.com/kiali/kiali-operator/blob/v1.55.0/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml#L58
* https://github.com/kiali/kiali-operator/blob/v1.55.0/roles/default/kiali-deploy/templates/openshift/deployment.yaml#L58
* https://github.com/kiali/kiali-operator/blob/v1.55.0/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L240
* (and the kiali-upstream and kiali-community manifests, too, just like the kiali-ossm one above)
