### ISSUE TITLE
Kiali does not work well with Google Anthos Service Mesh

### ISSUE THREAD

**Issue by gidesh** [kiali/kiali#5404]
Hello team,

We are on Google's GKE Kubernetes cluster. And we are also using Google's Istio offering called Anthos Service Mesh. This is a managed offering of istio where the control plane is managed by Google.

We deployed Kiali through the Kiali operator and CRD and we have seen that when it's just a handful of workloads, it can show us the required information about graphs and other visualization.

However, when we added all our workloads into the mesh, Kali became unusable and we were not able to see any traffic visualization

We tried bumping the resources but that did not help either.

All we see in the kiali pods are the following warning

```
kiali-7c79cb774b-hc8jr kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: platform-metrics] [pod: vmstorage-jldp-14]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-4rn9h kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: mobile-apps] [pod: stubs-things-we-love-64b7d98866-945tl]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-hc8jr kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: enablement] [pod: stubs-greetings-ui-7f4fffd7f-rfvhl]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-4rn9h kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: platform-metrics] [pod: vmselect-jldp-7]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-4rn9h kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: mobile-apps] [pod: stubs-things-we-love-64b7d98866-vw82w]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-hc8jr kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: catalogue-feeds] [pod: stubs-interface-01p-collator-5969f45c7-4rw69]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-hc8jr kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: mobile-apps] [pod: stubs-skus-7dfc5b4b89-28xzz]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-prdrj kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: catalogue] [pod: stubs-ratings-collator-6f65fffd7b-nfbd4]: unable to find any healthy Pilot instance "}
kiali-7c79cb774b-4rn9h kiali {"level":"warn","time":"2022-08-23T12:09:16Z","message":"GetPodProxyStatus is failing for [namespace: platform] [pod: microservice-manager-webhooks-697c497fb-qzwvh]: unable to find any healthy Pilot instance "}
```

We are not sure if this is the problem with Kiali being unable to visualize with a lot of workloads in the mesh or is it just the sheer size of our cluster?

Any help would be appreciated

**Comment by jmazzitelli** [comment]
Seems like Kiali cannot talk to a healthy istiod pod.

What does `kubectl get pods -n istio-system` say? Do you see anything odd about the istiod pods?

You also didn't mention what version of Istio and Kiali you are using -- that may be helpful to know

**Comment by nrfox** [comment]
Also curious if you were seeing those warnings before you scaled up or only afterward? If there's connection issues between kiali and istiod you should see them before.

**Comment by jshaughn** [comment]
...and can you give us an idea of the cluster size? # namespaces, rough number of services-per-namespace, etc.  Note that Kiali makes heavy use of Prometheus for traffic visualization and metrics.  You may want to ensure Prometheus has enough resources as well.

**Comment by gidesh** [comment]
@jmazzitelli 

Since we are using Google's Anthos Service Mesh, `istiod` is managed by them. `istio-system` namespace does not have any pods.

Apologies for not mentioning earlier, that we use kiali `v1.42.0` and our istio is `1.12.7-asm.2-distroless `, the `1.12.7` is the istio version, and `asm` in the tag is the Google's Anthos Service Mesh that I spoke about.

@nrfox 

Yes, we still see these warnings. The logs that I put in the OP are from our nonprod cluster and when I check in the prod cluster which only has a handful of workloads in the mesh, I can see the visualization in kiali and I also see warnings :sweat_smile: 

@jshaughn 

Our cluster has around 150 nodes and we have around 110 namespaces and around 1400 services. On average around 15 - 20 services per namespace.
We will try and up the resources of our Prometheus instance to see if that makes it any better. We did see some OOM kills maybe that could be a reason. We use VictoriaMetrics and we saw OOM kills on the vmselect component which is the querier which is configured to Kiali. We will get back once we try that out.

**Comment by jmazzitelli** [comment]
For the record, here's where the error message comes from - you can see where its trying to find an istiod to talk to:
https://github.com/kiali/kiali/blob/master/kubernetes/istio.go#L69

**Comment by nrfox** [comment]
I think there's two things going on here.

1. Kiali can't connect to istiod. This probably has something to do with how ASM exposes istiod and how Kiali expects to connect to it. Kiali uses the kube api to port forward to one of the istiod pods and get info from the registry. If the istiod pods don't live inside of the same cluster as Kiali then this approach may not work.
2. Kiali is getting OOM killed when there's issues connecting to istiod. This needs some more investigation but my guess is you'll see this more with the more istio config you have and is the main cause of the slowdown you're seeing aside from the istiod connection problem.

**Comment by jshaughn** [comment]
@gidesh , thanks for the information.  Although Kiali has been putting a lot of effort into scalability, the changes have mainly been introduced in more recent versions, and continue with the upcoming release (v1.56).  Increasing limits may improve the situation but I can't guarantee that anything you do will solve your issues.  I can say that more recent versions may help both performance and usability for larger topologies (new graph layouts, behind-the-scenes perf improvements, etc).  But I realize that it's not usually possible to move forward either Istio versions or Kiali versions in a managed env.  For Istio 1.12 the latest recommended Kiali release is v1.44, whish is still prior to scale work.  Later Kiali versions could work, but often-times there will be issues with config validations due to changes in Istio.

**Comment by gidesh** [comment]
Thanks, folks, I appreciate the quick responses

@jmazzitelli @nrfox 

>. But I have a feeling all you need to do is tell Kiali where your Istio control plane is (set the spec.istio_namespace to where all the control plane pods (including istiod) are) and it "should" work.

Is there a way I can instruct kiali to check for an HTTP location for eg `https://asm-hydrogen-veri-en1-asm-<gibberish>.a.run.app:443/validate`. I did not see anything in the `istio.go` file. Basically what is happening currently with managed control plane in ASM is that all the validating and mutating webhook are configured to an endpoint which is a cloud function or a cloud run (_serverless thingies not sure which one of them_) 

This is what our webhook config looks like 
```
➜ kg validatingwebhookconfiguration istiod-istio-system-mcp -o yaml | k neat                                                                                                                                                                                                                           [23/08/22 | 18:05:28]
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: istiod
    istio: istiod
    istio.io/owned-by: mesh.googleapis.com
    istio.io/rev: asm-managed
    release: istio
  name: istiod-istio-system-mcp
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    url: https://asm-hydrogen-veri-en1-asm-<gibberish>.a.run.app:443/validate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.istio.io
  rules:
  - apiGroups:
    - security.istio.io
    - networking.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```
We did not see this break when there were relatively fewer workloads in the mesh ie when we had around 200 microservices, but it breaks with more microservices in the mesh, we added 200 more, so currently around 419 microservices. When I say microservice it means a k8s deployment+service

I can see that CPU utilization has increased a lot and we let kiali run without any limits so that we don't throttle it.

![image](https://user-images.githubusercontent.com/27279015/186223110-5a8baec9-039a-4ba7-9747-388ce8bf9a10.png)

So not quite sure what could be wrong.

@jshaughn 

I will try `v1.44` to see if anything changes
