### ISSUE TITLE
[demo] need strict security context for demos

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5426]
Try to install travel demo on OpenShift 4.11. You get these warnings:

```
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "control" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "control" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "control" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "control" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

We need to add securityContext settings to the deployments for the demos - the travel demo for sure and probably [the other ones](https://github.com/kiali/demos), too.

So the pod containers should have the following security contexts:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
```
