### ISSUE TITLE
Kiali Helm Chart OIDC Issuer URI Construction

### ISSUE THREAD

**Issue by lamc** [kiali/kiali#5447]
Hello!

I was setting up the openid auth strategy with no rbac for my kiali server, and I came across something that I think would be of value to highlight here. 

I was configuring the issuer uri as: `https://[company_name].okta.com` as per openid documentation stating it should be the auth server's base url. 

Values.yaml below:

```
auth:
  openid:
    client_id: '${parameters.CLIENT_ID}'
    disable_rbac: true
    authorization_endpoint: "https://[company_name].okta.com/oauth2/default/v1/authorize"
    issuer_uri: "https://[company_name].okta.com"
    scopes: ["openid", "email", "profile"]
    username_claim: "email"
  openshift: {}
  strategy: "openid"
```

However, I would get this error returned back:
`Authentication failed: Failure when retrieving user identity: request failed (HTTP response status = 400 Bad Request)`

I checked the secret was created, and mounted to the kiali deployment. updated configmap mounted to kiali deployment as well and did a rollout restart in case it didn't pick up latest configmap changes.

Then I thought to modify the issuer_uri to `https://newscorp.okta.com/oauth2/default` and this fixed my issue, and the auth flow worked seamlessly. 

I'm not sure if there is an issue with the kiali auth backend where the construction of the token endpoint is wrong using the issuer_uri hence it couldn't properly get the user information? I was looking for some clarifications or insight on this so going forward I'll keep a mental note of it! thank you! :)
