### ISSUE TITLE
Validate that Kiali installs as an add-on for Ambient

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5504]
- Documentation: https://istio.io/latest/blog/2022/get-started-ambient/ 
  - https://www.youtube.com/watch?v=nupRBh9Iypo
- start by running ambient without any waypoint proxies

Versions: 

- Istio Ambient V 0.0.0 
- Ambient 0.0.0 shipped Kiali 1.55

https://github.com/istio/istio/labels/area%2Fambient

**Comment by josunect** [comment]
Steps followed for installation (From scratch):

- [Download](https://gcsweb.istio.io/gcs/istio-build/dev/0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82) istio ambient
- Create kind cluster:

```
kind create cluster --config=- <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ambient
nodes:
- role: control-plane
- role: worker
- role: worker
EOF
```
- Install Istio with ambient profile
```
bin/istioctl install --set profile=ambient \
                   --set components.egressGateways[0].name=istio-egressgateway \
                   --set components.egressGateways[0].enabled=true
```

- Install addons and kiali
```
kubectl apply -f samples/addons/prometheus.yaml 
kubectl apply -f samples/addons/grafana.yaml 
kubectl apply -f samples/addons/jaeger.yaml
kubectl apply -f samples/addons/kiali.yaml 
```
- Install load balancer metallb 
```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.5/config/manifests/metallb-native.yaml
kubectl get pods -n metallb-system --watch
docker network inspect -f '{{.IPAM.Config}}' kind
```

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.0-172.18.0.1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```

- Install Testing demos: 
`hack/istio/install-testing-demos.sh -c kubectl`

- Port forward of kiali svc: 
`kubectl port-forward svc/kiali 20001:20001 -n istio-system`

Access Kiali: 

![image](https://user-images.githubusercontent.com/49480155/193048567-38031db6-6ed8-4d69-8e1b-7a74f8e3aed7.png)
