### ISSUE TITLE
Can we exclude the some accessible namespaces in kiali CR with some labelSelector?

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5516]
This is a community-suggested enhancement request. The idea is the person wants to be able to exclude from the list of namespaces those namespaces that match a label selector. So a new setting would have to be added - something like this:

```yaml
api:
  namespaces:
    exclude_label_selector: "mylabel=myvalue"
```

Or perhaps more generally, support multiple selectors:

```yaml
api:
  namespaces:
    exclude_label_selectors:
    - mylabel=myvalue
    - myotherlabel=myothervalue
```

Any namespace that matches any exclude label selector would be hidden from view.

Code where this new excludes setting would be used would be here - so this is where the new feature's code would be added:

https://github.com/kiali/kiali/blob/v1.57.0/business/namespaces.go#L138-L150

### Discussed in https://github.com/kiali/kiali/discussions/5470

<div type='discussions-op-text'>

<sup>Originally posted by **amantayal5** September 15, 2022</sup>
We are using Kiali server model to deploy kiali and we want to exclude some namespaces in the cluster which have a certain label.
Can we add this capability? Or if it is already present, can you redirect me to its documentation as I couldn't find it?
</div>

**Comment by jshaughn** [comment]
OK, after some discussion with @jmazzitelli I'll offer up my opinion...

I think the trend may be that more and more installs will set `deplyment.accessible_namespaces` to `**`.  As such, I think the `deplyment.accessible_namespaces` setting is probably OK as is, and we don't need to add label-based setting of `accessible_namespaces`.  But given that `**` makes all namespaces accessible I think we could provide more robust options to narrow down that set of namespaces for the end user (api consumer).  So, I'm +1 for the change.  I think we should have:

```
api:
  namespaces:
    include: [list of regexes for namespaces you want to see]
    exclude: [list of regexes for namespaces you don't want to see]
    label_selector: deprecated, use label_selector_include
    label_selector_include: k8s label selector for namespaces you want to see
    label_selector_exclude: k8s label selector for namespaces you don't want to see
```

The `include` settings are ignored when `accessible_namespaces` is explicit because in that case `accessible_namespaces` is already defining the included namespaces. (note, they are actually reserved for internal use and may be set by the kiali operator)

The `exclude` settings are always viable for reducing the set of `accessible_namespaces`.

The deprecation of `api.label_selector` can be long term.  It will be a back-compat synonym for the more descriptive `label_selector_include`.  If both are set then `label_selector` will be ignored.
