### ISSUE TITLE
Kiali CR contains empty status, degraded health ArgoCD

### ISSUE THREAD

**Issue by AllexVeldman** [kiali/kiali#5560]
Starting with Kiali-operator v1.57.1, ArgoCD started showing that the Kiali CR health was degraded.
Looking into the CR status I found that it contains an entry like this:
```
    - lastTransitionTime: '2022-10-14T11:56:24Z'
      message: ''
      reason: ''
      status: 'False'
      type: Failure
```
combined with the ArgoCD resource customisation [here](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/kiali.io/Kiali/health.lua) this results in a degraded health state reported while kiali seems to work just fine.

**Comment by nrfox** [comment]
@jmazzitelli you mind taking a look at this to confirm?

I wonder if an additional `Failure` condition was added with a package bump for ansible operator sdk? Either way I think you'll want to check the type of the condition first and then look at success/failure for that condition. Looks like there's 3 different conditions: `Running`, `Successful`, and `Failure`.

Example:
```
  status:
    conditions:
    - ansibleResult:
        changed: 19
        completion: 2022-10-17T16:16:17.070282
        failures: 0
        ok: 99
        skipped: 105
      lastTransitionTime: "2022-10-17T16:15:50Z"
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: Last reconciliation succeeded
      reason: Successful
      status: "True"
      type: Successful
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: ""
      reason: ""
      status: "False"
      type: Failure
```
To check if the Kiali CR is in a good state you'll want to check for `condition.Type == Successful && condition.Status == "True"`. For bad state: `condition.Type == Failure && condition.Status == "True"`.

`Running` is different from the previous two since it is always `True` when the operator is reconciling that CR. To check if the CR is actively being reconciled, `condition.Type == Running && condition.Reason == Running`.
