### ISSUE TITLE
View for Waypoint proxies

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5576]
Does Kiali need a new view for Waypoint proxies? I think it would be interesting, as they are part of the data plane, and not really about the application itself.

This is how it is seen at the moment: 
```
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
 name: productpage
spec:
 gatewayClassName: istio-mesh
 listeners:
 - name: default
   port: 80
   protocol: HTTP
   allowedRoutes:
     namespaces:
       from: All
EOF
```

![image](https://user-images.githubusercontent.com/49480155/196644810-12a97a5d-c40b-4d1d-aef3-d3a6f64a6093.png)
