### ISSUE TITLE
openshift auth timeout customizations

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5650]
see: https://docs.openshift.com/container-platform/4.11/authentication/configuring-internal-oauth.html#oauth-configuring-internal-oauth_configuring-internal-oauth

There are two settings in OAuth objects that control access token timeouts/duration:

```yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    accessTokenMaxAgeSeconds: 172800
    accessTokenInactivityTimeout: 400s 
```

We should look into how we can configure something like the above but for the OAuthClient (note: the above is OAuth, we create a OAuthClient):

https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/oauth.yaml

Here's the OAuthClient docs:

https://docs.openshift.com/container-platform/4.11/rest_api/oauth_apis/oauthclient-oauth-openshift-io-v1.html#oauthclient-oauth-openshift-io-v1

We also need to make the timeout customizable (it is hardcoded at 10 seconds): 

https://github.com/kiali/kiali/blob/v1.48/business/openshift_oauth.go#L62

**Comment by jmazzitelli** [comment]
Going to add these three settings in the Kiali CR:

```yaml
spec:
  auth:
    openshift:
      auth_timeout: 10
      #token_inactivity_timeout:
      #token_max_age:
```

Will be documented in our schema doc here: https://github.com/kiali/kiali-operator/pull/593/files#diff-4a77030088e1e5e4093fec04397adc99d95c017fb6bc8e63c8e0c401f9a6517e
