### ISSUE TITLE
OpenID with google - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mattseymour** [kiali/kiali#5694]
I have configured a GCP Openid login application for auth with Kiali. The configuration is setup and working as expected.

The Kiali CR entry looks something like this: (which i belive is correct).

```yaml
    openid:
      client_id: "********-********.apps.googleusercontent.com"
      disable_rbac: true
      insecure_skip_verify_tls: false
      issuer_uri: "https://accounts.google.com"
      scopes: [ "openid", "email" ]
      username_claim: "email"
      password: secret:kiali:oidc-secret
```
The following I assume should work but on login i get the following error message.

```
Login unsuccessful: the OpenID token was rejected: Get "https://accounts.google.com/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

Is there a solution to this error appearing as a result of a login attempt.
