### ISSUE TITLE
OpenID with Azure AD: "no authorization code is present"

### ISSUE THREAD

**Issue by claudiuavat1** [kiali/kiali#5707]
We have configured an Azure AD application and we are stuck at the step where Kiali has to process the authorization code.

The redirect from Azure AD looks to be correct:
`https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/authorize?client_id=<clientID>&response_type=code&redirect_uri=https://<fqdn>/kiali&scope=openid+profile+email&nonce=<...>&state=<..>&sso_reload=true`
   -> `https://<fqdn>/kiali?code=0.ARI......&state=<...>&session_state=<...>`

But the login fails in the UI with _Authentication failed: request failed (HTTP response status = 401 Unauthorized)_, while the service logs show only this error **_ERR Not handling OpenId code flow authentication: no authorization code is present_**.

Kiali version: v1.59.0

The auth configuration we are using:
```
strategy: "openid"
openid:
  api_token: "access_token"
  client_id: "<clientID>"
  disable_rbac: true
  http_proxy: "<corporate_proxy>"
  https_proxy: "<corporate_proxy>"
  insecure_skip_verify_tls: true
  password: secret:<ns>:oidc-secret
  authentication_timeout: 300
  authorization_endpoint: "https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/authorize"
  token_endpoint: "https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/token"
  issuer_uri: "https://login.microsoftonline.com/<tenantID>/v2.0"
  scopes:
  - openid
  - profile
  - email
  username_claim: "preffered_username"
```

I also tested with _web_fqdn_, _web_schema_ and _web_port_, but it appears the values are autodetected correctly anyway.

Any help / guidance would be greatly appreciated. Thank you!
