### ISSUE TITLE
Multicluster - cluster configuration

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5738]
Kiali needs to configure connections to multiple kubernetes clusters. This issue covers how Kiali will do that.

Epic: #5618 

PRs:
* server: https://github.com/kiali/kiali/pull/5752
* operator: https://github.com/kiali/kiali-operator/pull/609
* helm charts: https://github.com/kiali/helm-charts/pull/189

**Comment by jmazzitelli** [comment]
I'm going to think up something here to see how we can notify Kiali about which clusters are configured with their credentials and perhaps some extension points for future needs (like adding additional config/metadata around each cluster definition)

**Comment by jmazzitelli** [comment]
Just wanted to document this... here's how these cluster secrets (to be used by Kiali in order to authenticate to remote clusters):

```
istioctl x create-remote-secret --name remote-cluster-name --context my-context --namespace istio-system
```

Results in something like this:

```yaml
# This file is autogenerated, do not edit.
apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: remote-cluster-name
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-remote-cluster-name
  namespace: istio-system
stringData:
  remote-cluster-name: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CR...QotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://192.168.59.254:8443
      name: remote-cluster-name
    contexts:
    - context:
        cluster: remote-cluster-name
        user: remote-cluster-name
      name: remote-cluster-name
    current-context: remote-cluster-name
    kind: Config
    preferences: {}
    users:
    - name: remote-cluster-name
      user:
        token: eyJhbGciOiJSU...Yzpv5Q3GmsN-JeVg166A
---
```
