### ISSUE TITLE
Missing line in Kiali CRD

### ISSUE THREAD

**Issue by M4thG33k** [kiali/kiali#5796]
I apologize if this is the incorrect place to submit this issue, but since the kiali-operator project does not have an issue tracker, I'm not sure where to report this.

Concerning the CRD [definition](https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml#L996), I believe there is a missing `properties` key between lines 999 and 1000. That is,, starting at line 996, this:

```
                    properties:
                      autodetect_secrets:
                        description: "Settings to allow cluster secrets to be auto-detected. Secrets must exist in the Kiali deployment namespace."
                        type: object
                          enabled:
                            description: "If true then remote cluster secrets will be autodetected during the installation of the Kiali Server Deployment. Any remote cluster secrets found in the Kiali deployment namespace will be mounted to the Kiali Server's file system. If false, you can still manually specify the remote cluster secret information in the 'clusters' setting if you wish to utilize multicluster features."
                            type: boolean
```

should be this:

```
                    properties:
                      autodetect_secrets:
                        description: "Settings to allow cluster secrets to be auto-detected. Secrets must exist in the Kiali deployment namespace."
                        type: object
                        properties: # <---------------------------------- the added line
                          enabled:
                            description: "If true then remote cluster secrets will be autodetected during the installation of the Kiali Server Deployment. Any remote cluster secrets found in the Kiali deployment namespace will be mounted to the Kiali Server's file system. If false, you can still manually specify the remote cluster secret information in the 'clusters' setting if you wish to utilize multicluster features."
                            type: boolean
```

If this file is not auto-generated somehow, I'm more than happy to submit a pull request to fix this issue. Thanks!
