### ISSUE TITLE
Make kiali-operator volumes configurable in the helm charts

### ISSUE THREAD

**Issue by monotek** [kiali/kiali#5810]
We want to run all our containers, which use an emptyDir volume, with a configured sizeLimit.

All containers should also set the scurityContext "readOnlyRootFilesystem: true".

This is not possible with the current kiali operator helm chart, as it trys to write to /tmp and the runner volume is mounted to /tmp/ansible-operator/runner, leaving /tmp read only when enabling "readOnlyRootFilesystem: true".

A possible fix could look like: https://github.com/kiali/helm-charts/pull/197

**Comment by jmazzitelli** [comment]
So the main purpose for this feature is to be able to ensure readOnlyRootFilesystem can be set to true, correct?

I would suggest the new values for the chart should be grouped together to make it clear the main purpose of this is the support the location where the ansible runner stores its logs - it isn't for just ad-hoc volumes to be mounted.

We should just provide volume definition details to mount the ansible logs directory where you want it.

So rather than have these independently specified as generic volumes:

```yaml
# runner volume config
runnerVolume:
  emptyDir: {}

# Extra Volume Mounts
extraVolumeMounts: []
  # - name: tmp
  #   mountPath: /tmp

# Extra Volumes
extraVolumes: []
  # - name: tmp
  #   emptyDir:
  #     sizeLimit: 100Mi
```

We should put the related settings under a main group setting like this (see below) to identify it for the purpose it will be used; also, make sure you comment these with enough detail to explain to the user what these are used for. This is just off the top of my head - i have no idea if this will work or if this is the best way, but the point is, try to get it so we can provide the mount details so they can be customized, but set the defaults to use emptyDir, and put them all in a group that makes it clear this defines the information necessary to mount the logs.

```yaml
# Defines the volume that will be used to store the Ansible log files.
# See https://kubernetes.io/docs/concepts/storage/volumes for valid
# volume types and mount points.
ansibleLogsVolume:
  volumeType:
    emptyDir: {}
  mountPath: /tmp
```

Have the defaults set to emptyDir and /tmp so it maintains backward compatibility.

So `ansibleLogsVolume.volumeType` defines what goes in here: https://github.com/kiali/helm-charts/blob/v1.63.0/kiali-operator/templates/deployment.yaml#L106 (this could includes things like your sizeLimit setting or whatever else the volumeType supports).

`ansibleLogsVolume.mountPath` defines what goes in here: https://github.com/kiali/helm-charts/blob/v1.63.0/kiali-operator/templates/deployment.yaml#L59

No need to define the name of the volume - it can remain defined as "runner" in the Deployment. This is just to define the volume where the ansible runner puts the logs.

This is all assuming I understand your use-case :) I assume you only need to re-define the mount point for the ansible runner (you don't need additional volumes, correct? You only need to customize the configuration of the volume that is already defined). If you need additional volumes, then I would like to understand more fully that use-case.
