### ISSUE TITLE
L4 Telemetry is "backwards"

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#5822]
Arguably, istio metrics are backwards (https://github.com/istio/istio/pull/32549), but :shrug: 

What I did:

Shell ---> Echo. 
I sent a few bytes from shell to echo and got 100s back

In the graph, on the edge from shell --> Echo I see: Sent: 14. Recv: 0.1

I expect: Sent: 0.1, Recv: 14

**Comment by jshaughn** [comment]
We will look at this as part of the evaluation of Ambient support.

**Comment by howardjohn** [comment]
:+1: sounds great. Just to clarify though this applies to sidecars as well

**Comment by jshaughn** [comment]
>  Just to clarify though this applies to sidecars as well

Yep, it's more a scheduling thing...

**Comment by jshaughn** [comment]
@josunect Do you want to look at this and see if you agree that our TCP traffic/byte rates may actually be backwards?

**Comment by josunect** [comment]
@jshaughn sure, I will have a look!

**Comment by josunect** [comment]
With the following example: 

```
kubectl create ns test
kubectl label namespace test istio.io/dataplane-mode=ambient
kubectl create -f test.yaml -n test

kubectl create ns sidecars
kubectl label namespace sidecars istio-injection=enabled
kubectl create -f test.yaml -n sidecars
```

test.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugbox
---
apiVersion: v1
kind: Service
metadata:
  name: debugbox
  labels:
    app: debugbox
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: debugbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugbox
  template:
    metadata:
      labels:
        app: debugbox
    spec:
      containers:
      - name: debugbox
        image: markeijsermans/debug
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  labels:
    app: tcpserver
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: tcpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpserver
  template:
    metadata:
      labels:
        app: tcpserver
    spec:
      containers:
      - name: tcpserver
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcpserver
```

Send some traffic: 
```

kubectl exec $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

kubectl exec -it $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- telnet tcpserver 9000



kubectl exec $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

kubectl exec -it $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- telnet tcpserver 9000
```

Result: 

![image](https://github.com/kiali/kiali/assets/49480155/75ea247f-78f7-4bcf-af26-b2bcfc5ac62b)

Sidecar ns: 

![image](https://github.com/kiali/kiali/assets/49480155/dcdaebd5-e010-4da0-bc3b-9d3dab995aa1)

Ambient: 

![image](https://github.com/kiali/kiali/assets/49480155/639427fe-a8d4-4d9e-b594-3120862fe720)

Queries: 

 ```
sum(rate(istio_tcp_sent_bytes_total{reporter="source",destination_workload_namespace="test",destination_workload="httpserver",destination_cluster="Kubernetes"}[60s])) by (source_workload)

sum(rate(istio_tcp_received_bytes_total{reporter="source",destination_workload_namespace="test",destination_workload="httpserver",destination_cluster="Kubernetes"}[60s])) by (source_workload)
```
