### ISSUE TITLE
[Cypress] Test procedure: Add validation references to K8S Gateways validations

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5868]
The reason for creating this issue is to not lose this test procedure, which might be worth automating using Cypress.

Pre-requisites: 

Install Gateway API CRDs:

```
kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.6.1" | kubectl apply -f -; }
```

Install bookinfo demo on bookinfo namespace

Then, create the following K8s Gateway objects that has some colliding hostnames and host port combinations:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-1
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-2
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-3
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
```

Expect to see the same validations references as shown in the PR description.

_Originally posted by @leandroberetta in https://github.com/kiali/kiali/issues/5853#issuecomment-1433575712_
