### ISSUE TITLE
Some confusion about Classify metrics by request

### ISSUE THREAD

**Issue by mark8s** [kiali/kiali#5904]
### Bug Description

Hello everyone, I encountered some problems when using [Classify metrics by request](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/) these days, I don't know if it is a bug.

My requirement is like this, I want to divide my request into two groups, the group A condition is to judge whether there is a header with a specified name (assuming the header name is 'end-user'), and the grouping condition of the other group B is The request method is Get, and the request path is healthy. If the conditions of group A are met, I will assign a value of `x-gray` to the custom indicator `x-route`. Similarly, if the conditions of the above group B are met, I will assign the value of `x-normal` to the custom indicator `x-route`.

My configuration is like this:

```yaml
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.11.*'
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.attributegen
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "attributes": [
                      {
                        "output_attribute": "x_route",
                        "match": [
                          {
                            "value": "x-gray",
                            "condition": "size(request.headers['end-user']) > 0"
                          },
                          {
                            "value": "x-normal",
                            "condition": "request.url_path == '/health' && request.method == 'GET'"
                          }
                        ]
                      }
                    ]
                  }
              vm_config:
                runtime: envoy.wasm.runtime.null
                code:
                  local: { inline_string: "envoy.wasm.attributegen" }
```

```shell
/ $ curl -v  reviews:9080/health
*   Trying 10.21.146.92:9080...
* Connected to reviews (10.21.146.92) port 9080 (#0)
> GET /health HTTP/1.1
> Host: reviews:9080
> User-Agent: curl/7.81.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Servlet/3.1
< content-type: application/json
< date: Mon, 13 Mar 2023 07:07:21 GMT
< content-language: en-US
< content-length: 32
< x-envoy-upstream-service-time: 13
< server: envoy
< 
* Connection #0 to host reviews left intact
{"status": "Reviews is healthy"}/ $
```

![image](https://user-images.githubusercontent.com/47961301/224631287-81719682-69f4-4a9d-ade3-57254b8e101d.png)

When I use kiali to observe the graphics, there is a problem with the display. It stands to reason that an `x-route` icon should be displayed, but it is not displayed here.

![image](https://user-images.githubusercontent.com/47961301/224631616-4294ebb0-2772-45a0-b2e3-a379fdb49604.png)

### Version

```prose
$ istioctl version
client version: 1.11.5
control plane version: 1.11.5
data plane version: 1.11.5 (8 proxies)

$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

@jshaughn @jmazzitelli  Can you guys help me to have a look?
