### ISSUE TITLE
Kiali not able to get Grafana password from secret

### ISSUE THREAD

**Issue by Hronom** [kiali/kiali#5926]
Kiali not able to get Grafana password from secret using `secret:*` notation as [described here](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services) 

I use helm `kiali-server` version `1.65.0`, chart from `https://kiali.org/helm-charts` deployed in `istio-system` namespace.

Here is my secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: kiali-secret
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  adminPassword: eHh4
```

```
fullnameOverride: kiali
auth:
  strategy: anonymous
deployment:
  accessible_namespaces:
    - '**'
  additional_service_yaml: {}
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  configmap_annotations: {}
  custom_secrets: []
  host_aliases: []
  hpa:
    api_version: autoscaling/v2beta2
    spec: {}
  image_pull_policy: Always
  ingress:
    additional_labels: {}
    class_name: nginx
    override_yaml:
      metadata: {}
  ingress_enabled: false
  instance_name: kiali
  logger:
    log_level: "warning"
    log_format: "text"
    sampler_rate: "1"
    time_field_format: "2006-01-02T15:04:05Z07:00"
  namespace: istio-system
  node_selector: {}
  pod_annotations: {}
  pod_labels:
    sidecar.istio.io/inject: "true"
  priority_class_name: ""
  replicas: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi
  secret_name: kiali
  security_context: {}
  service_annotations: {}
  service_type: ""
  tolerations: []
  view_only_mode: true
external_services:
  prometheus:
    url: "http://prometheus-prometheus.istio-system.svc.cluster.local:9090/"
  grafana:
    auth:
      username: admin
      password: secret:kiali-secret:adminPassword
      type: basic
    enabled: true
    # Grafana service name is "grafana" and is in the "telemetry" namespace.
    in_cluster_url: "http://grafana.istio-system.svc.cluster.local:3000/"
    # Public facing URL of Grafana
    url: "https://xxx.com/"
    dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Mesh Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Wasm Extension Dashboard"
  custom_dashboards:
    enabled: true
  istio:
    root_namespace: istio-system
    component_status:
      components:
        - app_label: "istiod"
          is_core: true
          is_proxy: false
        - app_label: "istio-ingressgateway-internal"
          is_core: true
          is_proxy: true
          namespace: istio-ingress
        - app_label: "istio-ingressgateway-public"
          is_core: true
          is_proxy: true
          namespace: istio-ingress
      enabled: true
istio_namespace: istio-system
kiali_feature_flags:
  certificates_information_indicators:
    enabled: true
    secrets:
      - cacerts
      - istio-ca-secret
  clustering:
    enabled: true
  disabled_features: []
  validations:
    ignore:
      - KIA1201
login_token:
  signing_key: CHANGEME00000000
```
