### ISSUE TITLE
OpenID: ERR Not handling OpenId code flow authentication: no authorization code is present

### ISSUE THREAD

**Issue by im-Amitto** [kiali/kiali#5976]
Config:
```
strategy: "openid"
openid:
  authentication_timeout: 300
  client_id: "<client-id>.apps.googleusercontent.com"
  disable_rbac: true
  issuer_uri: "https://accounts.google.com"
  scopes: ["openid", "email"]
  username_claim: "sub"
  .
  .
  .
 login_token:
   signing_key: <16 byte token>
server:
  metrics_enabled: true
  metrics_port: 9090
  port: 20001
  web_root: /kiali
  web_port: 80
```

I can see that OAuth is redirecting fine and have the needed code in the param but Kiali is still throwing `ERR Not handling OpenId code flow authentication: no authorization code is present`
```
http://example.com/kiali?state=763305ce1d4babff842a87bd0efcc9a8851a7f05ea553c534302c9c7-230403123716&code=<code>&scope=email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&hd=example.com&prompt=none
```
