### ISSUE TITLE
Grafana link is not available in Kiali

### ISSUE THREAD

**Issue by ThomasJohnA** [kiali/kiali#5988]
Grafana configuration added as external service in kiali spec as per the document - https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/ 
Still the grafana link is missing in Kiali workloads Inbound page.
Kiali  v1.65.0
Istio  1.17.1

Kiali logs does not have any error trace related to Grafana.

**Comment by jmazzitelli** [comment]
There is very little here for us to go on to try to replicate this to see if it is indeed a bug or just a user configuration error (which is usually the case). We need replication procedures. What is your configuration? How did you install Kiali? What are you expecting to see but do not?

When you log into Kiali UI, what log messages do you see in the server? Are there any errors you see in the Kiali UI (particularly in the masthead)?

**Comment by jmazzitelli** [comment]
I don't know if this is related, but I'll link this here just in case:
*  https://github.com/kiali/kiali/issues/5030

**Comment by jmazzitelli** [comment]
Based on that other issue, I would say - turn on debug logging in the Kiali server and then look at the server logs. I suspect you will start to see Grafana-related messages.

**Comment by ThomasJohnA** [comment]
I am using Kiali helm chart for deployment.
To reproduce the issue -
- Open Kiali GUI
- Navigate to "Workloads"
- Select workload name
- Select "Inbound Metrics" tab
Expectation is to have grafana link as in below picture
![image](https://user-images.githubusercontent.com/129847041/229820507-493337e3-ac4d-4801-95bc-3b98902cebc0.png)

In my Kiali, the link is not available (refer below pic), even after having below grafana config in Kiali.
external_services:
    grafana:
      enabled: true
       in_cluster_url: 'http://prometheus-operator-grafana.namespace:80'
      url: 'https://grafana.mydomain.com'
![image](https://user-images.githubusercontent.com/129847041/229820835-039992c9-11e9-4828-a482-1e379eec6da0.png)

Below the Kiali logs:
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Adding a RegistryRefreshHandler"}
2023/04/04 12:47:38 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Kiali: Version: v1.65.0, Commit: 312d1b55709d39b8afcc40d07e392de71bf3433e, Go: 1.19.6"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Using authentication strategy [openid]"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Some validation errors will be ignored [KIA1201]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community."}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Initializing Kiali Cache"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Adding a RegistryRefreshHandler"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"[Kiali Cache] Waiting for cluster-scoped cache to sync"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"[Kiali Cache] Started"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"[Kiali Cache] Kube cache is active for namespaces [.*]"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Server endpoint will start at [:20001/]"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Server endpoint will serve static content from [/opt/kiali/console]"}
{"level":"info","time":"2023-04-04T12:47:38Z","message":"Starting Metrics Server on [:9090]"}
{"level":"info","time":"2023-04-04T12:49:26Z","message":"[Prom Cache] Enabled"}
{"level":"info","time":"2023-04-04T13:37:38Z","message":"[Kiali Cache] Updating cache with new token"}
{"level":"info","time":"2023-04-04T13:37:38Z","message":"[Kiali Cache] Waiting for cluster-scoped cache to sync"}
{"level":"info","time":"2023-04-04T13:37:39Z","message":"[Kiali Cache] Started"}
{"level":"warn","time":"2023-04-04T14:06:53Z","message":"Configured OpenID provider informs some of the configured scopes are unsupported. Users may not be able to login."}

However, I can see the grafana url in Kiali about windows.

**Comment by jmazzitelli** [comment]
> I had same error message in Kiali GUI and it is resolved now by having proper Grafana configuration in Kiali. After that the error message is no longer there in GUI and in logs as well.

Interesting. So you got the configuration in place so you no longer see that error message, you see the Grafana link in the About Box (which I assume when you click that link, it works and takes you to Grafana), and yet you do not see the Grafana link in the Metrics tab?

That does sound like a regression.

**Comment by ThomasJohnA** [comment]
> > I had same error message in Kiali GUI and it is resolved now by having proper Grafana configuration in Kiali. After that the error message is no longer there in GUI and in logs as well.
> 
> Interesting. So you got the configuration in place so you no longer see that error message, you see the Grafana link in the About Box (which I assume when you click that link, it works and takes you to Grafana), and yet you do not see the Grafana link in the Metrics tab?
> 
> That does sound like a regression.

Yes, you are right.

**Comment by amanhigh** [comment]
I am facing same issue as well. Setup Kiali and Prometheus using Helm. 

Resolved all erros in Notification and Control Plane is not showing any error.

![SNAG--2023-04-09-000](https://user-images.githubusercontent.com/409973/230754594-c2faa59a-066e-4752-85fb-b408576ed9f3.jpg)

Yet No Link in Metrics Page.

![SNAG--2023-04-09-001](https://user-images.githubusercontent.com/409973/230754597-48353ac5-28e5-4752-95a0-d4a4cfe27fda.jpg)

**Comment by leandroberetta** [comment]
Hello @ThomasJohnA @amanhigh I was trying to reproduce this with no luck yet, I see the Grafana link in the workloads metrics.

Can you share the response to the following api call?

http://localhost:20001/kiali/api/grafana

There you should see the links to the available dashboard that Kiali UI then offers to the users.

**Comment by leandroberetta** [comment]
Hi @ThomasJohnA and @amanhigh, are you still facing this issue?.

**Comment by ThomasJohnA** [comment]
> Hi @ThomasJohnA and @amanhigh, are you still facing this issue?.

@leandroberetta, Yes, issue still persists.

**Comment by leandroberetta** [comment]
> > Hi @ThomasJohnA and @amanhigh, are you still facing this issue?.
> 
> @leandroberetta, Yes, issue still persists.

Can you help me sharing the information I asked before? is to understand what our backend is responding to the frontend. Thanks.

**Comment by ThomasJohnA** [comment]
> > > Hi @ThomasJohnA and @amanhigh, are you still facing this issue?.
> > 
> > 
> > @leandroberetta, Yes, issue still persists.
> 
> Can you help me sharing the information I asked before? is to understand what our backend is responding to the frontend. Thanks.
@leandroberetta, Could you please guide on how to do api call on Grafana from Kiali?

**Comment by vyom-soft** [comment]
Hello,
The same issue is true for Prometheus. External prometheus is also not recognised by Kiali.
I installed Kiali, the Kiali-Operator via HelmChart.  [kiali-operator](https://kiali.io/docs/installation/installation-guide/install-with-helm/#install-with-operator)
I modified the CM of kiali and provided the prometheus path.
As per document to hook external Prometheus does not work [Proemtheus-external](https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/) It keep on looking for predefined prometheus location.
Any suggestion.

**Comment by jmazzitelli** [comment]
> Is there possibility to set those path via Helm Install

Yes. Any value that can set in the Kiali CR (see the [Kiali CR reference here](https://kiali.io/docs/configuration/kialis.kiali.io/)) can be passed via helm using `--set` option so an initial Kiali CR can be created immediately at the time the operator is installed via helm. This is already documented in the [kiali.io documentation here](https://kiali.io/docs/installation/installation-guide/install-with-helm/#install-with-operator) where it says:

```
The kiali-operator Helm Chart mirrors all settings of the Kiali CR as chart values
that you can configure using regular --set flags. For example, the Kiali CR has
a spec.server.web_root setting which you can configure in the kiali-operator Helm
Chart by passing --set cr.spec.server.web_root=/your-path to the helm install command.
```

A prometheus setting would be something like `--set cr.spec.external_services.prometheus.url=<your url>`

@vyom-soft All that said, your problem is likely not related to the OP. There are no "links" to the prometheus to show in the Kiali UI - if your prometheus isn't configured, you simply will not see the graph and other bad things will happen. This isn't the issue with grafana links not showing - I suspect the grafana issue is a bug, the prometheus issue is likely a misconfiguration. I suggest starting a separate github discussion thread on your issue so as not to pollute the grafana issue being discussed here (which, again, I think is quite possibly a bug).

**Comment by hhovsepy** [comment]
For having "View in Grafana" link, there should be  'dashboards:' section in kiali config's 'grafana:' section:
```
grafana:
.....
    dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        - name: Istio Mesh Dashboard
        - name: Istio Control Plane Dashboard
        - name: Istio Performance Dashboard
        - name: Istio Wasm Extension Dashboard```

**Comment by leandroberetta** [comment]
> For having "View in Grafana" link, there should be 'dashboards:' section in kiali config's 'grafana:' section:
> 
> ```
> grafana:
> .....
>     dashboards:
>         - name: Istio Service Dashboard
>           variables:
>             namespace: var-namespace
>             service: var-service
>         - name: Istio Workload Dashboard
>           variables:
>             namespace: var-namespace
>             workload: var-workload
>         - name: Istio Mesh Dashboard
>         - name: Istio Control Plane Dashboard
>         - name: Istio Performance Dashboard
>         - name: Istio Wasm Extension Dashboard
> ```

I think this is needed to see the dashboards in the actions button on the control plane namespace card:

![image](https://user-images.githubusercontent.com/1286393/235157197-b7351be6-82e5-473f-b396-fd99ba2b8e46.png)

For the "View in Grafana" button in the metrics tab, with having configured Grafana in the CR is enough according to my tests.

So, I started a fresh installation, with no Grafana and I couldn't see the link, then I configured according to the docs:

https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/

And the link appeared, for my local env, the following configuration was applied:

```
  external_services:
    grafana:
      enabled: true
      in_cluster_url: http://grafana.istio-system:3000/
      url: http://localhost:3000
```

@ThomasJohnA try to do a curl to the following URL, just to see what the backend responds to the frontend:

`curl http://<INSERT_KIALI_URL_HERE>/kiali/api/grafana
`

Is your Kiali using some kind of authentication? If that is an issue, can you try putting Kiali in anonymous mode to do this test?.

https://kiali.io/docs/configuration/authentication/anonymous/

**Comment by jshaughn** [comment]
If there is anything we can do to make this more clear on kiali.io let's use this issue for that work.

**Comment by leandroberetta** [comment]
@hhovsepy is right about the need of certain dashboards defined in Kiali for the link to appear.

The Kiali operator configured the dashboards in the Kiali configmap when there is a presence of some Grafana configuration in the Kiali CR. Using the Helm charts, all configuration should be provided by the user so for this reason I didn't have to add this before (I generally use the operator).

The needed dashboards for the Services and Workloads are:

```
dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
```

I'm not really sure for Applications which dashboard should go, for the Metrics section in Applications to have the Grafana link, the following configuration needs to be applied in one of the dashboards:

```
dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          app: "var-app"
```

So, our docs (https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/) definitely needs some improvements. For this, I created the following issue: https://github.com/kiali/kiali/issues/6082.

I think we need to understand better (at least me), about the Applications metrics and which dashboard to use (if corresponds to use any, will check how are we are getting those metrics).

**Comment by amanhigh** [comment]
> Can you share the response to the following api call?
> 
> http://localhost:20001/kiali/api/grafana

Hi @leandroberetta I tried testing with API you provided and i am not getting any external links.

Response for this API is

`{"externalLinks":[]}`

I am going to try out above steps and share if it resolves the issue.

**Comment by amanhigh** [comment]
I have tried to modify kiali-crd to add `spec.external_services.grafana.dashboards` section. I followed CRD reference [here](https://kiali.io/docs/configuration/kialis.kiali.io/).

However i still don't see Grafana Links. Below is my complete CRD. Please suggest changes if any.

```
# https://kiali.io/docs/configuration/kialis.kiali.io/
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    accessible_namespaces:
      - "**"
    ingress:
      class_name: "traefik"
      enabled: true
      override_yaml:
        metadata:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
  server:
    web_fqdn: "kiali.docker"

  auth:
    strategy: anonymous

  external_services:
    prometheus:
      # Prometheus service name is "prometheus-server" and is in the "default" namespace
      url: "http://prometheus-server.default"
      health_check_url: "http://prometheus-server.default/-/healthy"
    grafana:
      enabled: true
      # Grafana service name is "grafana" and is in the "default" namespace.
      in_cluster_url: "http://grafana.default/"
      # Public facing URL of Grafana
      url: "http://grafan.docker/"
      health_check_url: "http://grafana.default/api/health"
      auth:
        type: "basic"
        username: "aman"
        password: "aman"
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            namespace: "var-namespace"
            workload: "var-workload"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
    tracing:
      # Enabled by default. Kiali will anyway fallback to disabled if
      # Jaeger is unreachable.
      enabled: true
      # Jaeger service name is "jaeger-query" and is in the "default" namespace.
      use_grpc: true #Give GRPC endpoint below
      in_cluster_url: "http://jaeger-query.default:16685/jaeger"
      # Public facing URL of Jaeger
      url: "http://jaeger.docker/"
```

Original CRD without dashboard section is [here](https://github.com/amanhigh/go-fun/blob/master/Kubernetes/services/files/istio/kiali-crd.yml).

My Grafana [Config](https://github.com/amanhigh/go-fun/blob/master/Kubernetes/services/grafana.yml) used in helm install.

Pleases suggest what changes i can make in Kiali or Grafana config for Grafana Links to Appear.

**Comment by hhovsepy** [comment]
In my previous comment I put a wrong formatting of dashboards section's content, there were wrong additional spaces before '-name', sorry for the confusion:
Here is the correct format:

```
      grafana:
        auth:
          ca_file: /kiali-cabundle/service-ca.crt
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        - name: Istio Mesh Dashboard
        - name: Istio Control Plane Dashboard
        - name: Istio Performance Dashboard
        - name: Istio Wasm Extension Dashboard
        enabled: true
        health_check_url: ''
        in_cluster_url: http://grafana.istio-system:3000
        is_core: false
        url: http://grafana-istio-system.apps.ocp.test.redhat.com
```

**Comment by jmazzitelli** [comment]
> I put a wrong formatting of dashboards section's content, there were wrong additional spaces

FYI: you can always check the validation of your Kiali CR using our validation tool. This way if you have any problems with spacing or indentation, this tool will tell you with error messages: https://kiali.io/docs/configuration/kialis.kiali.io/#validating-your-kiali-cr

For example, before you actually deploy your Kiali CR, you can run this to test that it is valid against the latest "master" version of the CRD:

```
bash <(curl -sL https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/bin/validate-kiali-cr.sh) \
  -crd https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/crd/kiali.io_kialis.yaml \
  --kiali-cr-file ./my-kiali-cr.yaml \
  -n istio-system
```

Run this for the --help details:

```
$ bash <(curl -sL https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/bin/validate-kiali-cr.sh) --help

/dev/fd/63 [option...]

  -ce|--client-exe
      The path to the client executable. Should be a path to either a "oc" or "kubectl" executable.
  -crd|--crd-location
      The file or URL location where the Kiali CRD is. This CRD must include the schema.
      If not specified, the internally defined CRD is used.
  -kcf|--kiali-cr-file
      The file of the Kiali CR to test.
  -kcn|--kiali-cr-name
      The name of an existing Kiali CR to test.
  -n|--namespace
      The namespace where the existing CR is or where the test CR will be created.
      Default: "default"
  -pc|--print-crd
      If true, then this script will just print the CRD used to validate. It will not validate anything.
      Default "false"
```

**Comment by amanhigh** [comment]
@leandroberetta I retried but i am unfortunately not able to get it working. I don't see much difference between dashboard section which i shared and that shared by @hhovsepy . However i still retried by copying dashboard section and `is_core` to match the shared config. Detailed Configs are shared below.

I am getting same results that graphs are working but no Grafana Links.

![SNAG--2023-05-28-040](https://github.com/kiali/kiali/assets/409973/da5b4e66-4d86-4a6c-821a-7962fed48702)

All Containers
![SNAG--2023-05-28-041](https://github.com/kiali/kiali/assets/409973/9c5abfb2-f655-4941-b142-8208891875c5)

All Services
![SNAG--2023-05-28-042](https://github.com/kiali/kiali/assets/409973/01608944-efd0-4a3b-be10-87e8c5ffa14c)


<details>
<summary>CRD Config</summary>

```
# https://kiali.io/docs/configuration/kialis.kiali.io/
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    accessible_namespaces:
      - "**"
    ingress:
      class_name: "traefik"
      enabled: true
      override_yaml:
        metadata:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
  server:
    web_fqdn: "kiali.docker"

  auth:
    strategy: anonymous

  external_services:
    prometheus:
      # Prometheus service name is "prometheus-server" and is in the "default" namespace
      url: "http://prometheus-server.default"
      health_check_url: "http://prometheus-server.default/-/healthy"
    grafana:
      enabled: true
      is_core: false
      # Grafana service name is "grafana" and is in the "default" namespace.
      in_cluster_url: "http://grafana.default/"
      # Public facing URL of Grafana
      url: "http://grafan.docker/"
      health_check_url: "http://grafana.default/api/health"
      auth:
        type: "basic"
        username: "aman"
        password: "aman"
      dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        - name: Istio Mesh Dashboard
        - name: Istio Control Plane Dashboard
        - name: Istio Performance Dashboard
        - name: Istio Wasm Extension Dashboard
    tracing:
      # Enabled by default. Kiali will anyway fallback to disabled if
      # Jaeger is unreachable.
      enabled: true
      # Jaeger service name is "jaeger-query" and is in the "default" namespace.
      use_grpc: true #Give GRPC endpoint below
      in_cluster_url: "http://jaeger-aman-query.default:16685/jaeger"
      # Public facing URL of Jaeger
      url: "http://jaeger.docker/"
```
</details>

<details>
<summary> CRD Test </summary>

```
bash <(curl -sL https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/bin/validate-kiali-cr.sh) \
  -crd https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/crd/kiali.io_kialis.yaml \
  --kiali-cr-file ./kiali-crd.yml \   
  -n istio-system
=== SETTINGS ===
KIALI_CRD_LOCATION=https://raw.githubusercontent.com/kiali/kiali-operator/master/crd-docs/crd/kiali.io_kialis.yaml
KIALI_CR_FILE=./kiali-crd.yml
KIALI_CR_NAME=
NAMESPACE=istio-system
PRINT_CRD=false
=== SETTINGS ===
Using 'kubectl' located here: /home/linuxbrew/.linuxbrew/bin/kubectl
...
Validating the CR:
----------
teTestiali.kiali.io/kiali created
----------
Kiali CR [./kiali-crd.yml] is valid.
```
</details>

<details>
<summary> External Links API Response</summary>
`{"externalLinks": []}`
</details>
