### ISSUE TITLE
Support client certificate authentication against Prometheus

### ISSUE THREAD

**Issue by vCra** [kiali/kiali#5995]
When prometheus is secured with Client Certificate Authentication (e.g. mTLS) it is not possible to configure Kiali to Authenticate against it (or the Authentication configuration is not present in the Documentation)

It should be possible to specify a set of x509 certificates in the Prometheus configuration.

An example could look like the following

```
spec:
  external_services:
    prometheus:
      url: "https://metrics.telemetry:9090/"
      auth:
        ca_file: /etc/prometheus/tls/ca.crt
        cert_file: /etc/prometheus/tls/client.crt
        key_file: /etc/prometheus/tls/client.key
        serverName: prometheus-server
```
