### ISSUE TITLE
validation error (KIA0401) when AutoMtls is enabled in istio MeshConfig

### ISSUE THREAD

**Issue by bethmage** [kiali/kiali#6006]
Kiali: v1.65.0 (312d1b55709d39b8afcc40d07e392de71bf3433e)
Istio: 1.17.1

Kiali shows a validation error (KIA0401) for missing mesh-wide destination rule. 
This is misleading when:
**mesh-wide PeerAuthentication Policy** is pressent in istio-namespace
and
**enableAutoMtls: true** set in the istio MeshConfig

[Auto mTLS](https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/#auto-mtls)

![Screenshot 2023-04-07 at 16 04 28](https://user-images.githubusercontent.com/2519342/230625949-44cc8bc6-a99a-4734-ba3e-79905c0d3cd4.png)

**PeerAuthentication in istio-system namespace**

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
```
**MeshConfig ConfigMap** 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
...

data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      holdApplicationUntilProxyStarts: true
      proxyMetadata: {}
      tracing:
        zipkin:
          address: jaeger-collector.k8s-monitoringbackend-dev:9411
    enableAutoMtls: true
    enablePrometheusMerge: false
    enableTracing: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```
