### ISSUE TITLE
Kiali Crashing in sidecar validation (without a sidecar)

### ISSUE THREAD

**Issue by shardulsrivastava** [kiali/kiali#6010]
I have a kiali instance that crashes during sidecar validations for a service that doesn't even have a sidecar resource. From the code, it seems to be crashing at this [line](https://github.com/kiali/kiali/blob/master/business/checkers/sidecars/egress_listener_checker.go#L99) .

**Istio Version :** 1.17.2
**Kiali Version:** 1.61.2

## Screenshot
<img width="1512" alt="Screenshot 2023-04-11 at 02 28 10" src="https://user-images.githubusercontent.com/9951135/231024798-feeb91de-22df-48c2-911f-06f1741ea4d5.png">

## Logs
<details>
  <summary>Error Logs</summary>
Error logs:

```go
panic: runtime error: index out of range [1] with length 1

goroutine 378474 [running]:
github.com/kiali/kiali/business/checkers/sidecars.getHostComponents(...)
        /home/runner/work/kiali/kiali/business/checkers/sidecars/egress_listener_checker.go:99
github.com/kiali/kiali/business/checkers/sidecars.EgressHostChecker.validateHost({0xc00debd4a0, 0xc094f95cb0, {0xc022af2000, 0xb1d, 0xc00}}, {0xc033399f40, 0x38}, 0xc03b7c9f20?, 0x1dcc6ba?)
        /home/runner/work/kiali/kiali/business/checkers/sidecars/egress_listener_checker.go:64 +0x2d4
github.com/kiali/kiali/business/checkers/sidecars.EgressHostChecker.Check({0xc00debd4a0, 0xc094f95cb0, {0xc022af2000, 0xb1d, 0xc00}})
        /home/runner/work/kiali/kiali/business/checkers/sidecars/egress_listener_checker.go:33 +0x36e
github.com/kiali/kiali/business/checkers.SidecarChecker.runChecks({{0xc036db4000, 0x634, 0x6a0}, {0xc08f1cf2d0, 0xe, 0xe}, {0xc00ed21b00, 0x1e, 0x20}, 0xc03b7c9f20, ...}, ...)
        /home/runner/work/kiali/kiali/business/checkers/sidecars_checker.go:72 +0x415
github.com/kiali/kiali/business/checkers.SidecarChecker.runIndividualChecks({{0xc036db4000, 0x634, 0x6a0}, {0xc08f1cf2d0, 0xe, 0xe}, {0xc00ed21b00, 0x1e, 0x20}, 0xc03b7c9f20, ...})
        /home/runner/work/kiali/kiali/business/checkers/sidecars_checker.go:49 +0x98
github.com/kiali/kiali/business/checkers.SidecarChecker.Check({{0xc036db4000, 0x634, 0x6a0}, {0xc08f1cf2d0, 0xe, 0xe}, {0xc00ed21b00, 0x1e, 0x20}, 0xc03b7c9f20, ...})
        /home/runner/work/kiali/kiali/business/checkers/sidecars_checker.go:25 +0x58
github.com/kiali/kiali/business.runObjectChecker({0x2080c00?, 0xc05020d6c0})
        /home/runner/work/kiali/kiali/business/istio_validations.go:310 +0xc6
github.com/kiali/kiali/business.runObjectCheckers({0xc05014fce0, 0xe, 0x0?})
        /home/runner/work/kiali/kiali/business/istio_validations.go:298 +0x7d
github.com/kiali/kiali/business.(*IstioValidationsService).GetValidations(0xc03aec6f50, {0x209bb98, 0xc03b7c8ff0}, {0xc032ebcba4, 0x6}, {0xc032ebcbb4, 0xb}, {0x0, 0x0})
        /home/runner/work/kiali/kiali/business/istio_validations.go:122 +0x10b1
github.com/kiali/kiali/handlers.ServiceDetails.func1()
        /home/runner/work/kiali/kiali/handlers/services.go:108 +0xba
created by github.com/kiali/kiali/handlers.ServiceDetails
        /home/runner/work/kiali/kiali/handlers/services.go:106 +0x3ce
```

</details>

## Istio Configuration
Here is the virtual service and gateway resource I have:

<details>
  <summary>Virtual Service</summary>
  
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    ....
  labels:
     ....
  name: mci-api
  namespace: my-ns
spec:
  gateways:
    - mci-api
    - mesh
  hosts:
    - mci-api.staging.example.com
    - mci-api-k8s.my-ns.svc.cluster.local
  http:
    - route:
        - destination:
            host: mci-api-k8s.my-ns.svc.cluster.local
            port:
              number: 80
```
</details>

<details>
  <summary>Gateway</summary>
  
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
     ....
  labels:
     ....
  name: mci-api
  namespace: my-ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - mci-api.staging.example.com
      port:
        name: http-mci-api
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - mci-api.staging.example.com
      port:
        name: https-mci-api
        number: 443
        protocol: HTTP
```
</details>

Would appreciate any pointers as to what may be wrong here.
