### ISSUE TITLE
Auto-enable find/hide filters via Kiali CR

### ISSUE THREAD

**Issue by djfinnoy** [kiali/kiali#6012]
The `Kiali` CR allows us to create pre-defined hide/find filters via `cr.spec.kiali_feature_flags.ui_defaults.graph`.
A feature I feel is missing, is the ability to autmatically enable these filters.

In our Kiali instance, we really want to automatically hide traffic from outside of the selected namespaces.
So we do the following:

```
kiali-operator:
  cr:
    spec:
      kiali_feature_flags:
        ui_defaults:
          metrics_per_refresh: "10m"
          graph:
            hide_options:
              - description: "Hide unselected namespaces"
                expression: "outside"
          namespaces:
            - istio-system
            - backend-apps
            - frontend-apps
```

The user then has to select the hide options manually.
What I would love to see, is a third key under `hide_options` that allows us to toggle auto-enabling. Eg:

```
- description: "Hide unselected namespaces"
  expression: "outside"
  auto-enable: true
```
