### ISSUE TITLE
[operator] look into ansible "turbo" mode and removing ansible loops

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6032]
Yes, turbo mode :) Blast from the 80s past, there may not be a "turbo" button on your PC anymore, but it looks like Ansible has an experimental feature "turbo mode". We should look into this and see how it affects the Kiali operator.

see: https://github.com/ansible-collections/kubernetes.core/blob/main/docs/ansible_turbo_mode.rst

Word is the main problems appear to be related to memory consumption (wrt turbo mode) and is still considered experimental.

But I was also told (and can confirm based on https://github.com/kiali/kiali-operator/pull/636) that refactoring/removing ansible loops provides potentially even more performance gains. So that should also be considered as part of work on this issue.

PRs for this issue that help speed up the operator:
* https://github.com/kiali/kiali-operator/pull/636
* https://github.com/kiali/kiali-operator/pull/637
* https://github.com/kiali/kiali-operator/pull/639

backport PRs:
* https://github.com/kiali/kiali-operator/pull/638

**Comment by jmazzitelli** [comment]
While doing this, if the experimental nature of this turbo mode is not something we want, we should look at using the async/poll/wait features of the `k8s` task - that supports the ability to process things asynchronously. I'm not sure if it would help much, but we should look into it.

**Comment by jmazzitelli** [comment]
> While doing this, if the experimental nature of this turbo mode is not something we want, we should look at using the async/poll/wait features of the `k8s` task - that supports the ability to process things asynchronously. I'm not sure if it would help much, but we should look into it.

Well, we can forget that - `async` is not supported with the `k8s` task:

Run this playbook:

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  collections:
  - kubernetes.core

  tasks:
  - name: Does async work?
    async: 60
    poll: 0
    k8s:
      state: absent
      kind: ConfigMap
      namespace: default
      name: foo
```

and you get:

```
TASK [Does async work?] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "async is not supported for this task."}
```
