### ISSUE TITLE
Multicluster - Istio Configs duplicated

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6063]
Setup a multicluster env.
Create an Istio config in one of clusters, for instance PeerAuth.

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: bookinfo
spec:
  mtls:
    mode: STRICT
``` 
The configs will show duplicated for both clusters.
The issue is coming from Istio Registry status, where both PeerAuth objects are returned for both clusters. https://github.com/kiali/kiali/blob/master/business/istio_config.go#L210

![Screenshot from 2023-04-26 11-39-05](https://user-images.githubusercontent.com/604313/234536456-69bee935-576c-40a9-bbae-ec30b3fa7671.png)

Reported by cc @josunect
