### ISSUE TITLE
get operator to process namespaces faster at intialization

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6081]
I just noticed how slow the operator could be at startup when running in a cluster with many namespaces (like hundreds or thousands of namespaces).

This is because the operator now processes new namespaces (it watches the cluster for new namespaces and will kick off reconciliations of all Kiali CRs for the new namespaces via its [new ansible playbook](https://github.com/kiali/kiali-operator/blob/master/playbooks/kiali-new-namespace-detected.yml)).

There is some throttling the operator tries to do (it won't kick off a reconciliation if a new namespace shows up within 1 minute of another namespace showing up - see the trick being used with `current_timestamp_string` [here](https://github.com/kiali/kiali-operator/blob/master/playbooks/kiali-new-namespace-detected.yml#L32)). However, just the initial ansible playbook execution for each namespace to check takes about 1 to 2 seconds to complete. For a cluster with 600 namespaces, when the operator starts up it will be notified of 600 "new" namespaces and thus take about 600 to 1200s (10 to 20 minutes) to execute the ansible playbook for each namespace.

I see there is an ansible loop being used here - past experience shows me that is a major time sink within ansible. We should refactor that. But there may be some other things we can do to make this go faster.

We also might want to have some kind of switch that turns off this feature of checking new namespaces - maybe an environment variable in the operator to tell it to disable this new namespace check (??)

**Comment by jmazzitelli** [comment]
I submitted an enhancement request to the ansible operator SDK to help solve this startup issue: https://github.com/operator-framework/operator-sdk/issues/6416

However, even if something gets implemented, it will be a while before it makes its way downstream which is where we will eventually need it.

So, that said, I think we should consider using the workaround I list in that issue, where I say,

```
A workaround would be to require the user to put a label on the namespaces that you want the
operator to automatically detect. When doing this, I would be able to use the already existing
"selector" feature of watches.yaml
(see https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/).
But this would require the user to know ahead of time that their namespaces should be labeled
properly, it would require the user to have permission to label namespaces, and it would require
users to "pollute" their namespace labels sets just for supporting the operator (this is something
that customers may not want to do). So, while the workaround is viable, it is not ideal.
```

I think if we have add a selector in watches.yaml like below, it might be good enough:

```yaml
# Watching new namespaces so the operator can determine if they should be accessible to Kiali
- version: v1
  group: ""
  kind: Namespace
  playbook: playbooks/kiali-new-namespace-detected.yml
  reconcilePeriod: "0s"
  manageStatus: False
  watchDependentResources: False
  watchClusterScopedResources: False
  watchAnnotationsChanges: False
  selector:
    matchExpressions:
    - key: "kiali.io/member-of"
      operator: "Exists"
      values: []
```

`kiali.io/member-of` is a label that is created by the operator when labeling namespaces (all namespaces in AN will be labeled with this). I think if you create a namespace with that label already on it, that's fine (I think, would need to test it) - and that would trigger the automatic reconciliation of the Kiali CR.

Note that, due to the unfortunate way Kiali defines the default label, this will only work for Kiali installs with the default `deployment.instance_name` of "kiali". If you install Kiali with a different instance name, this selector won't match (because the label name is `kiali.io/<instance-name>.member-of`. Maybe we can just have a different label that we watch in this watches.yaml? So instead of `kiali.io/member-of` we instead match something like `kiali.io/namespace` (with any value you want).
