### ISSUE TITLE
[operator] speed up the setting up of configuration

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6132]
I have noticed the operator is slow while "Setting up configuration" (After [this status task](https://github.com/kiali/kiali-operator/blob/v1.67.0/roles/default/kiali-deploy/tasks/main.yml#L172-L174) -- basically its [all this code here](https://github.com/kiali/kiali-operator/blob/v1.67.0/roles/default/kiali-deploy/tasks/main.yml#L181-L838)).

This just does a lot of setting of defaults and things like that. Basic stuff. Try to speed this up by doing some ansible tricks. This code isn't complicated, so even if we dive out into jinja to do it, it shouldn't make the ansible code much more complicated. But there has to be a way that makes this faster.

**Comment by jmazzitelli** [comment]
here's a sample ansible task that can be used to combine multiple tasks that are used to determine default values at runtime. This is the kind of thing I think we can do to speed things up:

```yaml
---
- hosts: localhost

  tasks:

  - set_fact:
      is_openshift: true
      kiali_vars:
        subdict:
          k1: v1
        another_value: ""
        config:
          some_value: ""
          hello: world
          subconfig:
            bye: universe
        x_value: "boo"

  - name: Set defaults
    vars:
      kiali_vars_yaml: |-
        {# Initialize the yaml to be the same as kiali_vars #}
        {{ kiali_vars | to_nice_yaml }}

        {# If config.some_value is empty, set it to redhat if is_openshift, otherwise set it to k8s #}
        {% if kiali_vars.config.some_value == '' %}
        {{ kiali_vars | combine({'config': {'some_value': ('redhat' if is_openshift|bool else 'k8s')}}, recursive=True) | to_nice_yaml }}
        {% endif %}

        {# If another_value is empty and is_openshift, set it to RedHat, otherwise, leave it alone #}
        {%- if kiali_vars.another_value == '' and is_openshift %}
        another_value: RedHat
        {% endif %}

        {# If x_value is not defined, set it to RacerX, otherwise, append -X to it #}
        {%- if kiali_vars.x_value is not defined %}
        x_value: RacerX
        {% else %}
        x_value: {{ kiali_vars.x_value }}-X
        {% endif %}
    set_fact:
      kiali_vars: "{{ kiali_vars_yaml|from_yaml }}"

  - debug:
      var: kiali_vars
```
