### ISSUE TITLE
molecule test failure - changing security context not working

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6155]
Noticed a failure in the molecule test that tests the security context can be customized. Need to figure out if this is just a side-effect of k8s or we really do have a bug.

Customizing the security context [here](https://github.com/kiali/kiali-operator/blob/v1.67.0/molecule/config-values-test/converge.yml#L156-L167) and testing it was changed [here](https://github.com/kiali/kiali-operator/blob/v1.67.0/molecule/config-values-test/converge.yml#L284-L293)

Notice `spec.containers[0].securityContext.readOnlyRootFilesystem` wants to be customized to false but ends up being true. This is what I saw in the deployment's template, which does show it is true (but should be false):

```yaml
kind: Deployment
spec:
  template:
    spec:
      containers:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true

```
