### ISSUE TITLE
Use ExecPlugin for remote cluster secret

### ISSUE THREAD

**Issue by frauniki** [kiali/kiali#6193]
Can I use ExecPlugin for remote cluster secrets in Kiali?

I have tried using remote cluster secret in a Kiali multi cluster configuration and it does not work properly.
I am using AWS EKS and would like to use the ExecPlugin provided by AWS to access the remote cluster.
The commands required for ExecPlugin are installed via Kiali's init container.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate-authority-data>
    server: <server-url>
  name: test
contexts:
- context:
    cluster: test
    user: test
  name: test
current-context: test
kind: Config
preferences: {}
users:
- name: test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - token
        - -i
        - test
      command: /var/custom-commands/aws-iam-authenticator
      env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_DEFAULT_REGION
          value: ap-northeast-1
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

I checked the Kiali source code and it looks like the remote secret parse ignores methods other than user token.
https://github.com/kiali/kiali/blob/9ce7013534aee7df2cd66345b2e6161ad3719dd5/kubernetes/secret.go#L20-L46

Is it possible to support ExecPlugin in Kiali's remote cluster secrets?
