### ISSUE TITLE
OpenID token gets rejected cause of unexpected audience claim

### ISSUE THREAD

**Issue by msr-financial-com** [kiali/kiali#6226]
I wanted to use Authelia as OpenID provider. I wanted it to secure Kiali(Istio service mesh Dashboard). But i am getting the following errors when trying to sign in:(These logs are from kiali)

> 2023-05-31T07:29:14Z WRN Authentication rejected: the OpenID token was rejected: the OpenId token has an unexpected audience claim; got '[kiali-dashboard]'
> Wed, May 31 2023 9:29:14 am | 2023-05-31T07:29:14Z DBG Not handling OpenId code flow authentication: no authorization code is present
> Wed, May 31 2023 9:29:14 am | 2023-05-31T07:29:14Z TRC The AES cookie is missing.

I also opened an discussion on authelia github repository:
https://github.com/authelia/authelia/discussions/5507

This answer shows the problem:
https://github.com/authelia/authelia/discussions/5507#discussioncomment-6048710

My authelia config:
```
    identity_providers:
      oidc:
        hmac_secret: this_is_a_secret
        issuer_private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          -----END RSA PRIVATE KEY-----
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enable_client_debug_messages: true
        clients:
          - id: kiali-dashboard
            secret: this_is_a_secret
            public: false
            authorization_policy: one_factor
            audience: []
            scopes:
              - openid
              - groups
              - email
              - profile
              - offline_access
            redirect_uris:
              - https://kiali/kiali
            grant_types:
              - refresh_token
              - authorization_code
            response_types:
              - code
            response_modes:
              - form_post
              - query
              - fragment
            userinfo_signing_algorithm: none
```
            
Kiali Client config:
```
          auth:
            strategy: openid
            openid:
              client_id: "kiali-dashboard"
              issuer_uri: "https://issuerurl/"
              disable_rbac: true
              insecure_skip_verify_tls: true
              username_claim: "email"
```
