### ISSUE TITLE
Verify Kiali using Istio 1.18 Ambient alpha

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6241]
Ref. #5476 

Steps (minikube): 

- Install istio 1.18: 
`istio/install-istio-via-istioctl.sh -c kubectl` Including --set profile=ambient
- Install bookinfo: 
`kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml -n bookinfo`

- Istio Ambient is detected: 
![image](https://github.com/kiali/kiali/assets/49480155/3a37e7ba-eed3-4b3b-a8de-9e27d8d8d143)

- Out of mesh 
![image](https://github.com/kiali/kiali/assets/49480155/21211d86-eb30-4b02-aaf3-93edd9cae938)

- No graph: 
![image](https://github.com/kiali/kiali/assets/49480155/f8602487-dfe3-48c8-92af-2e0af85f8631)

- Label namespace: 
`kubectl label namespace bookinfo istio.io/dataplane-mode=ambient`

- Detected ztunnel: 
![image](https://github.com/kiali/kiali/assets/49480155/e8fb318a-1659-443b-babf-2af4f29f2288)

- Send some traffic: 
`kubectl exec deploy/sleep -- curl -s http://istio-ingressgateway.istio-system/productpage | head -n1`
`kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1`
`kubectl exec deploy/notsleep -- curl -s http://productpage:9080/ | head -n1`

- Graph (In minikube): 
![image](https://github.com/kiali/kiali/assets/49480155/b22095ba-0533-40be-bd63-c927a2a859b3)

- Graph (In kind with 2 nodes): 
![image](https://github.com/kiali/kiali/assets/49480155/b7fc16bf-d8c2-47b7-b6b2-02927a9a0055)

- Waypoint. It is possible to generate a namespace waypoint with: 
`istioctl x waypoint generate --namespace bookinfo`

Or, apply: 

```
kubectl apply -n bookinfo -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: namespace
  namespace: bookinfo
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
EOF
```
![image](https://github.com/kiali/kiali/assets/49480155/2cd40e9a-3dc0-49d5-8c76-01014d85031b)
