### ISSUE TITLE
Kiali Graph UI incorrectly shows `version: unknown` label

### ISSUE THREAD

**Issue by bangau1** [kiali/kiali#626]
**Describe the bug**
The Kiali Graph UI showns my workload to have `version: unknown`

**Versions used**
Kiali: v0.9.1
Istio: 1.0.0
Kubernetes flavour and version: GKE v1.10.7-gke.6

**To Reproduce**
1. Go to Kiali url
2. Click on "Graph"
3. Select one of the workload
4. See the `version` label has `unknown` value

<img width="630" alt="screen shot 2018-11-05 at 10 51 34" src="https://user-images.githubusercontent.com/352737/47977088-ceb80100-e0e8-11e8-8453-71e7b26b2c71.png">

**Expected behavior**
The Kiali Graph UI should shown the `version:<stable or canary>`
I have set the config.yaml to be this value
```
kubectl exec -it -n istio-system kiali-8cc798ffb-9t859 -- cat /kiali-configuration/config.yaml
server:
  port: 20001
  static_content_root_directory: /opt/kiali/console
  cors_allow_all: true
external_services:
  grafana:
    display_link: true
    url: <redacted>
  jaeger:
    url: <redacted>
  prometheus_service_url: http://prometheus-server.kube-system.svc.cluster.local:80
istio_labels:
  version_label_name: track
```
As you can see, the `version_label_name` is set to `track` label.
My workload already has the `track` label, as stated by this screenshot in kiali workload UI
<img width="907" alt="screen shot 2018-11-05 at 10 54 51" src="https://user-images.githubusercontent.com/352737/47977181-4be37600-e0e9-11e8-9bfc-125db95fed51.png">
