### ISSUE TITLE
Don't understand the behavior when forming external service names on the graph when using `ServiceEntry`

### ISSUE THREAD

**Issue by obervinov** [kiali/kiali#6314]
Hi!
I am creating a `ServiceEntry` for a more detailed `PassthroughCluster`, and I would be very grateful if you would explain to me the behavior when forming the names of `ExternalService` on the graph.

In the case when I create `ServiceEntry` for `HTTP/HTTPS` traffic, the names on the graph are formed equivalent to the name `ServiceEntry`
```yml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: amazon-com
spec:
  hosts:
  - amazon.com
  - "*.amazon.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
```
![image](https://github.com/kiali/kiali/assets/49606362/9285296b-e624-43ba-81da-b6ead1e8d016)

In the case when I create a `ServiceEntry` for `TCP` traffic, I get a situation where the name `ExternalService` is formed in a strange way - just leaving only part of the value from the `hosts` field
```yml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: amazon-s3
spec:
  hosts:
  - "*.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  - name: http
    number: 80
    protocol: HTTP
  resolution: NONE
```
<img width="1043" alt="Снимок экрана 2023-06-27 в 18 54 41" src="https://github.com/kiali/kiali/assets/49606362/6a706072-1f85-415f-8807-e2abb932a7d1">
<img width="1511" alt="Снимок экрана 2023-06-27 в 18 57 44" src="https://github.com/kiali/kiali/assets/49606362/39ce779a-d00c-4477-8470-a440c1e0d8e9">

If I use a fully qualified domain name instead of a wildcard, then I also get only part of the value of the hosts field as the name.
```yml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: amazon-s3
spec:
  hosts:
  - "s3.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  - name: http
    number: 80
    protocol: HTTP
  resolution: NONE
```
<img width="470" alt="Снимок экрана 2023-06-27 в 19 01 43" src="https://github.com/kiali/kiali/assets/49606362/9c88eea8-0386-4324-9e84-0a8c4cd36493">

Why, in the case of `TCP` traffic, do I get such an unobvious behavior when forming names on the graph?
And how do I get an informative name and at the same time leave the use of the wildcard domain?

```
Kiali v1.65.7 (640aa206d9fafa17021b4cd2a10c8ddc5627792e)
Kiali Container v1.65.7
Service Mesh Istio 1.17.1
Istio 1.17.1
Prometheus 2.42.0
Kubernetes v1.21.14
```
Thanks!

**Comment by jshaughn** [comment]
> Why, in the case of TCP traffic, do I get such an unobvious behavior when forming names on the graph?

I guess due to a potential bug :-)    Will need to investigate.  Service Entry nodes are tricky.  It looks here like Kiali is unable to detect that the requests are being handled by a service entry and that is why you are seeing service nodes, not service entry nodes.  It could also have something to do with the telemetry being generated by Istio for these requests.  If you know [how to look at prometheus directly](https://kiali.io/docs/faq/graph/#queryprom) you could take a look at the `sum(istio_tcp_sent_bytes_total{source_workload="nameOfTheSourceWorkloadAbove"}) by (destination_service, destination_service_name, reporter)`

**Comment by obervinov** [comment]
I took a look at the istio metrics in prometheus and got this result
<img width="1520" alt="Снимок экрана 2023-06-28 в 11 50 30" src="https://github.com/kiali/kiali/assets/49606362/ec244465-71b1-4e05-b282-f850d7415811">

`destination_service_name="*"`

It looks like the reason is how istio defines and writes to prometheus destination_service_name

**Comment by obervinov** [comment]
I have studied the documentation in more detail and it looks like the root of the problem is that I am incorrectly configuring the service entry for TCP traffic.
https://istio.io/latest/docs/reference/config/networking/service-entry/#ServicePort
https://istio.io/latest/blog/2018/egress-tcp/
https://istio.io/latest/docs/reference/config/analysis/ist0134/

It seems that the hosts specification as such does not play a significant role, since for a correct specification with a TCP port, it is necessary to additionally specify the addresses specification.
With a fully described specification, the value in hosts can be written more informative
```yml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: amazon-s3
spec:
  hosts:
  - s3.amazonaws.com
  addresses:
  - 52.222.0.0/16
  - 52.192.0.0/12
  - 52.216.0.0/14
  - 52.220.0.0/15
  - 52.223.0.0/17
  - 52.208.0.0/13
  - 52.223.128.0/18
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 443
    protocol: TCP
  resolution: NONE
```
@jshaughn, thank you so much for your help!
