### ISSUE TITLE
Support Pre-Aggregated Rate Metric `istio_requests:rate5m`?

### ISSUE THREAD

**Issue by diranged** [kiali/kiali#6342]
In larger Istio environments, Prometheus aggregation becomes a requirement. In these environments, the `istio_requests_total` metric becomes problematic because of the way recorded metrics are handled during counter resets. See https://github.com/istio/istio.io/issues/10101 for context.

Would the Kiali team be willing to consider an alternative approach where instead of using `istio_requests_total`, Kiali could optionally use a pre-rate()’d metric with a configurable name? Eg, `istio_requests:rate5m`?

**Comment by jmazzitelli** [comment]
@diranged I'm not familiar with the pre-rated calc'ed metrics... What does the basic prom query look like with the new name? Is it JUST the name changes (e.g. a count query would simply go from `count(istio_request_totals)` to `count(istio_requests:rate5m`)? Or is there other syntactic changes when accessing a pre-rated metric?

If it is just a name change, then Kiali should easily be able to accommodate customized names.

cc @jshaughn 

We might want to think about how to do this for other metrics, if needed (are there other metrics that would need to be pre-rated for large clusters?)

**Comment by jmazzitelli** [comment]
if it's just a name change, then I suggest we add something to the Kiali CR to support multiple metrics, because I can see the possibility that multiple metrics will be renamed.... something like:

```yaml
spec:
  external_services:
    prometheus:
      metric_names:
        istio_requests_total: my_custom_istio_requests:rate5m
        istio_tcp_received_bytes_total: my_custom_istio_tcp_received_bytes:rate2m
        ...and others....
```

Thus, when a metric name needs to be determined in the server, it can do a simple map lookup rather than using the existing hardcoded name where the default is the hardcoded name itself:

So instead of using `"istio_requests_total"` the code would use `getPromMetricName("istio_requests_total")`
```go
func getPromMetricName(name string) string {
  if realName, ok := config.ExternalServices.Prometheus.MetricNames[name]; ok {
    return realName
  } else {
    return name
}
```

This will support 0, 1, or many customized pre-calced metrics.

Of course, all of this is assuming there are no other syntactic changes needed in the queries - i.e. the only thing that changes in the prom query is the name of the metric itself.

**Comment by diranged** [comment]
@jmazzitelli,
  The challenge is that it's not just that the metric name changes - the fundamental value changes. In this case, we're taking a `counter` with a ton of high cardinality values (`pod`, `pod_name`, `instance`) and re-recording it into a pre-aggregated `gauge` metric (see https://github.com/istio/istio.io/issues/10101#issuecomment-979049885):

```yaml
      - record: "workload:istio_requests_rate_1m"
        expr: |
          sum without(instance,kubernetes_namespace,kubernetes_pod_name) (irate(istio_requests_total[1m]))
```

  So now instead of accessing `sum(rate(istio_requests_total{}[1m]))` for example, you'd access `sum(istio_requests:rate1m{})`. No need for the `rate()` function anymore because that work has been done for you.

**Comment by jmazzitelli** [comment]
> No need for the `rate()` function anymore because that work has been done for you.

OK, then that fundamentally invalidates my suggestion. That makes it more difficult because it requires modifications to the queries depending on the semantics of the metric.

**Comment by jmazzitelli** [comment]
To see the complexity involved, see the graph generator (and this isn't all of it - there are all the [appenders](https://github.com/kiali/kiali/tree/master/graph/telemetry/istio/appender) to have to deal with also as well as the metric graphs): https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go

**Comment by diranged** [comment]
Yes -  I agree that it's not a terribly great situation to be in.. Unfortunately the docs at https://istio.io/latest/docs/ops/best-practices/observability/#federation-using-workload-level-aggregated-metrics do not address the issue with aggregating `counters`... but pre-calculating the `rate()` seems to be a requirement to make the data accurate.

I hate `if/else` statements on this kind of thing ... but for anyone running Istio at any kind of real scale, a combination of [aggregated metrics](https://istio.io/latest/docs/ops/best-practices/observability/#federation-using-workload-level-aggregated-metrics) and pre-calculating the [rate()](https://github.com/istio/istio.io/issues/10101#issuecomment-979049885) seems to be the only sane answer. I could see a flag in Kiali that allows the user to tell it that the `rate()` has been done already, and also rename the metrics?

**Comment by diranged** [comment]
Even the Istio team points out that this kind of optimization may be necessary at https://istio.io/latest/docs/ops/best-practices/observability/#optimizing-metrics-collection-with-recording-rules..

**Comment by jmazzitelli** [comment]
Oh, I'm not denying it isn't needed for optimizing things. I'm just saying it would require a lot of work and testing to get something like this in Kiali.

@jshaughn would know the issues involved in refactoring the prometheus metric querying within Kiali.

**Comment by jshaughn** [comment]
It's interesting.  For sure we'd like to accommodate large installations, and for sure this would be a tricky thing to support. 

The aggregation approach ties together the duration and metric, whereas Kiali typically allows you to select your duration from a drop down.  @diranged , are you aggregating to different durations, like 1m, 5m, 1h, etc... ?   So, to do this it may actually take configuring a custom metric to a specific duration.  And as you mentioned above, it's not just a metric name change but a query change as well.  And we have lots of places where we sort of "build" the query, I'm sure it would be an effort.  And we would still require the same labels as we do now, so the aggregation TS would still need to supply the required labels.

**Comment by diranged** [comment]
@jshaughn So - thinking more about this, it seems actually quite reasonable for Kiali to support these pre-aggregated metrics, but at the same time require that the operator include `rate1m`, `rate5m`, `rate1h` (at a minimum). I could see a change in Kiali to support this, and then a change to the Istio docs with a _better_ recommendation for how to handle metric aggregation at scale.

**Comment by jshaughn** [comment]
`istio_requests_total` is only one of the metrics used by Kiali to generate rates.  Are you also aggregating other metrics, like the TCP metrics?  Are you doing anything for the histograms, which are the biggest offenders of storage and cardinality?

**Comment by diranged** [comment]
Here's our current set of recording rules.. 

1. For `_total` metrics we are recording them as `rate()`...
2. For Histograms and Gauges (`_bucket`, `_count`, `_sum`) we are leaving them as is, just summing without the `pod/instance` cardinality

The real offender in a large environment is the `pod` and `instance` cardinality...

```yaml
spec:
  groups:
  - interval: 1m
    name: istio.metricsAggregation-rules
    rules:
    - expr: sum without(instance, pod) (irate(istio_requests_total[5m]))
      record: workload:istio_requests:rate5m
    - expr: sum without(instance, pod) (irate(istio_requests_total[5m]))
      record: workload:istio_requests:increase5m
    - expr: sum without(instance, pod) (irate(istio_tcp_connections_closed_total[5m]))
      record: workload:istio_tcp_connections_closed:rate5m
    - expr: sum without(instance, pod) (irate(istio_tcp_connections_closed_total[5m]))
      record: workload:istio_tcp_connections_closed:increase5m
    - expr: sum without(instance, pod) (irate(istio_tcp_connections_opened_total[5m]))
      record: workload:istio_tcp_connections_opened:rate5m
    - expr: sum without(instance, pod) (irate(istio_tcp_connections_opened_total[5m]))
      record: workload:istio_tcp_connections_opened:increase5m
    - expr: sum without(instance, pod) (irate(istio_tcp_received_bytes_total[5m]))
      record: workload:istio_tcp_received_bytes:rate5m
    - expr: sum without(instance, pod) (irate(istio_tcp_received_bytes_total[5m]))
      record: workload:istio_tcp_received_bytes:increase5m
    - expr: sum without(instance, pod) (irate(istio_tcp_sent_bytes_total[5m]))
      record: workload:istio_tcp_sent_bytes:rate5m
    - expr: sum without(instance, pod) (irate(istio_tcp_sent_bytes_total[5m]))
      record: workload:istio_tcp_sent_bytes:increase5m
    - expr: sum without(instance, pod) (irate(envoy_cluster_upstream_cx_rx_bytes_total[5m]))
      record: workload:envoy_cluster_upstream_cx_rx_bytes:rate5m
    - expr: sum without(instance, pod) (irate(envoy_cluster_upstream_cx_rx_bytes_total[5m]))
      record: workload:envoy_cluster_upstream_cx_rx_bytes:increase5m
    - expr: sum without(instance, pod) (irate(envoy_cluster_upstream_cx_tx_bytes_total[5m]))
      record: workload:envoy_cluster_upstream_cx_tx_bytes:rate5m
    - expr: sum without(instance, pod) (irate(envoy_cluster_upstream_cx_tx_bytes_total[5m]))
      record: workload:envoy_cluster_upstream_cx_tx_bytes:increase5m
    - expr: sum without(instance, pod) (irate(envoy_server_hot_restart_epoch[5m]))
      record: workload:envoy_server_hot_restart_epoch:rate5m
    - expr: sum without(instance, pod) (irate(envoy_server_hot_restart_epoch[5m]))
      record: workload:envoy_server_hot_restart_epoch:increase5m
    - expr: sum without(instance, pod) (istio_request_bytes_bucket)
      record: workload:istio_request_bytes_bucket
    - expr: sum without(instance, pod) (istio_request_bytes_count)
      record: workload:istio_request_bytes_count
    - expr: sum without(instance, pod) (istio_request_bytes_sum)
      record: workload:istio_request_bytes_sum
    - expr: sum without(instance, pod) (istio_request_duration_milliseconds_bucket)
      record: workload:istio_request_duration_milliseconds_bucket
    - expr: sum without(instance, pod) (istio_request_duration_milliseconds_count)
      record: workload:istio_request_duration_milliseconds_count
    - expr: sum without(instance, pod) (istio_request_duration_milliseconds_sum)
      record: workload:istio_request_duration_milliseconds_sum
    - expr: sum without(instance, pod) (istio_response_bytes_bucket)
      record: workload:istio_response_bytes_bucket
    - expr: sum without(instance, pod) (istio_response_bytes_count)
      record: workload:istio_response_bytes_count
    - expr: sum without(instance, pod) (istio_response_bytes_sum)
      record: workload:istio_response_bytes_sum
    - expr: sum without(instance, pod) (envoy_cluster_upstream_cx_active)
      record: workload:envoy_cluster_upstream_cx_active
    - expr: sum without(instance, pod) (envoy_cluster_upstream_cx_connect_fail)
      record: workload:envoy_cluster_upstream_cx_connect_fail
    - expr: sum without(instance, pod) (envoy_cluster_upstream_cx_total)
      record: workload:envoy_cluster_upstream_cx_total
    - expr: sum without(instance, pod) (envoy_server_initialization_time_ms_bucket)
      record: workload:envoy_server_initialization_time_ms_bucket
    - expr: sum without(instance, pod) (envoy_server_initialization_time_ms_count)
      record: workload:envoy_server_initialization_time_ms_count
    - expr: sum without(instance, pod) (envoy_server_initialization_time_ms_sum)
      record: workload:envoy_server_initialization_time_ms_sum
    - expr: sum without(instance, pod) (galley_validation_passed)
      record: workload:galley_validation_passed
    - expr: sum without(instance, pod) (go_goroutines)
      record: workload:go_goroutines
    - expr: sum without(instance, pod) (istio_build)
      record: workload:istio_build
```
