### ISSUE TITLE
Ambient Mesh - TCP Traffic 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6415]
Epic task: 
https://github.com/kiali/kiali/issues/5476

Ref. https://github.com/istio/istio/issues/48097
https://github.com/istio/istio/issues/50076

L4 traffic in Ambient Mesh is all reported as TCP traffic, even http traffic. 
TCP traffic is not reported.  

In this example, the same applications are deployed in a namespace with istio injection enabled (namespace sidecars) and also in the a namespace with ambient annotations (namespace traffic). 
From the debug box:
- we send http traffic to the httpserver application
- We establised a telnet connection with tcpserver and some bytes are sent.

This is the result: 

![image](https://github.com/kiali/kiali/assets/49480155/a1584343-75bf-4cba-bad8-4ccf51e28d35)

How to reproduce it: 

```
kubectl create ns ambient
kubectl create ns sidecars

# Label namespace
kubectl label namespace sidecars istio-injection=enabled
kubectl label namespace ambient istio.io/dataplane-mode=ambient

# Create apps
kubectl apply -f ~/dev/deployments/traffic.yaml -n ambient
kubectl apply -f ~/dev/deployments/traffic.yaml -n sidecars

# Install telnet
kubectl exec $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- apt install telnet -y
kubectl exec $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- apt install telnet -y

# http traffic
kubectl exec $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

kubectl exec $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

# tcp traffic
kubectl exec -it $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- telnet tcpserver 9000
kubectl exec -it $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- telnet tcpserver 9000
```

traffic.yaml: 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugbox
---
apiVersion: v1
kind: Service
metadata:
  name: debugbox
  labels:
    app: debugbox
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: debugbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugbox
  template:
    metadata:
      labels:
        app: debugbox
    spec:
      containers:
      - name: debugbox
        image: markeijsermans/debug
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  labels:
    app: tcpserver
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: tcpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpserver
  template:
    metadata:
      labels:
        app: tcpserver
    spec:
      containers:
      - name: tcpserver
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcpserver
```
