### ISSUE TITLE
oidc redirect to http always with port 443

### ISSUE THREAD

**Issue by z9fr** [kiali/kiali#6489]
I have setup kiali using helm chart and have setup a proxy from istio gateway to expose the traffic to outside. 

i have openid setup for authentication as well. but the issue is the redirect url sent from kiali is always http i dont see any way to configure this. but my application runs on https. 

```yaml
auth:
  openid:
    client_id: client_secret
    client_secret: client_secret
    issuer_uri: my_issuer
    scopes:
      - openid
      - email
    username_claim: email
  openshift:
    client_id_prefix: kiali
  strategy: openid
external_services:
  custom_dashboards:
    enabled: true
  grafana:
    enabled: false
  istio:
    root_namespace: istio-system
  prometheus:
    url: http://prometheus.istio-system.svc.cluster.local:9090
  tracing:
    enabled: true
    in_cluster_url: http://jaeger-query.jaeger.svc.cluster.local:16686
    use_grpc: true
kiali_route_url: ""
login_token:
  signing_key: Jv6bjpjKBd8xtOQP
server:
  metrics_enabled: true
  metrics_port: 9090
  port: 20001
  web_root: /

```

this is how my values looks like im using the helm chart https://kiali.org/helm-charts (kiali-server)

below is how the virtual service looks like

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-ingress
  namespace: sloco-ent
spec:
  hosts:
    - "dashboard.example.com"
  gateways:
    - mygatway
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001

```

I have tried to look for an parameter which foces this redirect url to be an https url but it still is http. i am using cognito for openid provider and i cannot add a http url as a redirect url

```
curl https://dashboard.example.com/api/auth/openid_redirect
<a href="https://testidp1234.auth.eu-west-1.amazoncognito.com/oauth2/authorize?client_id=client_id&amp;response_type=code&amp;redirect_uri=http%3A%2F%2Fdashboard.example.com%3A443&amp;scope=openid+email&amp;nonce=9531ca899314de6cbd8016bb309bb10165de98bc6f80eab111c43c41&amp;state=state">Found</a>.
```

the weird thing about this url is check how the redirect url looks.
http://dashboard.example.com:443

the port is https 443 but the protocol is http
