### ISSUE TITLE
Kiali 1.66: error from Grafana (401): Unauthorized 

### ISSUE THREAD

**Issue by schroedt** [kiali/kiali#6552]
Hi *,

I am facing an error in kiali 1.66, installed via [HELM](https://kiali.org/helm-charts):
![grafik](https://github.com/kiali/kiali/assets/6430367/5f9d2205-6f19-4d89-bd08-c477a98fd88d)

```
kubectl -n istio-system logs -f  pod/kiali-7b6bd79f4-gtv2p
{"level":"info","time":"2023-08-31T19:27:37Z","message":"Adding a RegistryRefreshHandler"}
2023/08/31 19:27:37 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2023-08-31T19:34:50Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:34:50Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:34:50Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:09Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:09Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:09Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:18Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:18Z ERR error from Grafana (401): Unauthorized
2023-08-31T19:37:18Z ERR error from Grafana (401): Unauthorized
```

**Configuration**
```
    apiVersion: kiali.io/v1alpha1
    kind: Kiali
    metadata:
      name: kiali
      annotations:
        ansible.sdk.operatorframework.io/verbosity: "1"
    spec:
      istio_namespace: "istio-system"
      version: "default"
      auth:
        strategy: "openid"
        openid:
          authentication_timeout: 300
          client_id: "kubernetes-cluster"
          disable_rbac: false
          insecure_skip_verify_tls: false
          issuer_uri: "https://keycloak.example.de/realms/example"
          scopes: ["openid", "profile", "email"]
          username_claim: "email"
      api:
        namespaces:
          exclude:
          - istio-operator
          - kube-.*
          - openshift.*
          - ibm.*
          - tigera-operator
          - istio-system
          - kiali-operator
      deployment:
        accessible_namespaces: ["**"]
    #    image_name: ""
        image_pull_policy: "IfNotPresent"
    #    image_version: "operator_version"
        ingress_enabled: false
        instance_name: "kiali"
        logger:
          log_level: warn
          log_format: text
          sampler_rate: "1"
          time_field_format: "2006-01-02T15:04:05Z07:00"
        namespace: "istio-system"
        replicas: 1
        secret_name: "kiali"
        verbose_mode: "2"
        view_only_mode: false
      external_services:
        custom_dashboards:
          discovery_auto_threshold: 10
          discovery_enabled: auto
          enabled: true
          is_core: false
          namespace_label: "kubernetes_namespace"
          prometheus:
            auth:
              ca_file: ""
              insecure_skip_verify: false
              password: ""
              token: ""
              type: "none"
              use_kiali_token: false
              username: ""
            cache_duration: 10
            cache_enabled: true
            cache_expiration: 300
            custom_headers: {}
            health_check_url: ""
            is_core: true
            url: ""
        grafana:
          auth:
            ca_file: ""
            insecure_skip_verify: false
            password: "superSecret"
            token: ""
            type: "basic"
            use_kiali_token: false
            username: "kiali"
          dashboards:
          - name: "Istio Service Dashboard"
            variables:
              namespace: "var-namespace"
              service: "var-service"
          - name: "Istio Workload Dashboard"
            variables:
              namespace: "var-namespace"
              workload: "var-workload"
          - name: "Istio Mesh Dashboard"
          - name: "Istio Control Plane Dashboard"
          - name: "Istio Performance Dashboard"
          - name: "Istio Wasm Extension Dashboard"
          enabled: true
          health_check_url: ""
          in_cluster_url: "http://grafana.istio-system.svc.cluster.local:3000/"
          is_core: false
          url: "https://grafana-istio.example.de/"
        istio:
          component_status:
            components:
            - app_label: istiod
              is_core: true
              is_proxy: false
            - app_label: istio-ingressgateway
              is_core: true
              is_proxy: true
            #- app_label: istio-egressgateway
            #  is_core: false
            #  is_proxy: true
            enabled: true
          config_map_name: "istio"
          envoy_admin_local_port: 15000
          #istio_canary_revision:
            #current:
            #upgrade:
          istio_identity_domain: "svc.cluster.local"
          istio_injection_annotation: "sidecar.istio.io/inject"
          istio_sidecar_annotation: "sidecar.istio.io/status"
          istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
          istiod_deployment_name: "istiod"
          url_service_version: ""
        prometheus:
          auth:
            ca_file: ""
            insecure_skip_verify: false
            password: ""
            token: ""
            type: "none"
            use_kiali_token: false
            username: ""
          cache_duration: 10
          cache_enabled: true
          cache_expiration: 300
          custom_headers: {}
          health_check_url: ""
          is_core: true
          thanos_proxy:
            enabled: false
            retention_period: "7d"
            scrape_interval: "30s"
          url: ""
        tracing:
          auth:
            ca_file: ""
            insecure_skip_verify: false
            password: ""
            token: ""
            type: "none"
            use_kiali_token: false
            username: ""
          enabled: true
          in_cluster_url: "http://tracing.istio-system.svc.cluster.local/jaeger"
          is_core: false
          namespace_selector: true
          url: "https://jaeger-istio.example.de/"
          use_grpc: false
          whitelist_istio_system: ["jaeger-query", "istio-ingressgateway"]
      login_token:
        expiration_seconds: 3600
        signing_key: ""
      server:
        address: ""
        audit_log: true
        cors_allow_all: false
        gzip_enabled: true
        metrics_enabled: true
        metrics_port: 9090
        port: 20001
        web_fqdn: ""
        web_history_mode: ""
        web_port: ""
        web_root: ""
        web_schema: ""
```

I create a **local** kiali user (non OIDC) and can login at `https://grafana-istio.example.de/ `with `kiali` / `superSecret`.
![grafik](https://github.com/kiali/kiali/assets/6430367/16cd6a33-3d54-4ca6-b2a6-8a7642d917ba)

Curl for `http://grafana.istio-system.svc.cluster.local:3000/` from within the cluster works as well and returns the login-page:

```
alpine:~# curl http://grafana.istio-system.svc.cluster.local:3000/
<a href="/login">Found</a>.
```
