### ISSUE TITLE
Tempo support for gRPC Tempo client

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6578]
With the following settings: 

```
  tracing:
    enabled: true
    provider: "tempo"
    use_grpc: true
```

The Tempo client is not working. 
The client uses the .proto specific to Jaeger.
