### ISSUE TITLE
Double istio rev in configmap name

### ISSUE THREAD

**Issue by laptubi** [kiali/kiali#6669]
Hello.

istio installed via helm

```
  values:
    revision: "1-18-0"
```

kiali

```
  values:
    allowAdHocKialiImage: true
    resources:
      limits:
        cpu: 1
    cr:
      create: true
      namespace: istio-system
      spec:
        istio_namespace: istio-system
        external_services:
          istio:
            config_map_name: "istio-1-18-0"
            istiod_deployment_name: "istiod-1-18-0"
            istio_sidecar_injector_config_map_name: "istio-sidecar-injector-1-18-0"
```

i receive this error from kiali log.

`ERR Error getting mesh config: configmap "istio-1-18-0-1-18-0" not found`

i do not understand why rev is doubled in configmap name?
