### ISSUE TITLE
Is there a way to disable admin login/authentication?

### ISSUE THREAD

**Issue by Yshayy** [kiali/kiali#671]
It can be useful when putting an authentication proxy (like https://github.com/bitly/oauth2_proxy) in front of Kiali.

**Comment by lucasponce** [comment]
Thanks @Yshayy for your comment.
Kiali is trying to delegate on rbac (kubernetes/openshift) also to centralize what a user can see (user can see namespaces a,b,c but not d) and do (you can edit istio config in a,b but not in c,d).
I wonder that using an authentication proxy would be for scenarios of readonly and access to all ?
I mean, I guess motivation of this is to use some kind of SSO mechanism across several apps ?

**Comment by pilhuhn** [comment]
I think this is related to  https://github.com/kiali/kiali/issues/652  and especially to https://github.com/kiali/kiali-ui/pull/830 - @Yshayy does the later provide you what you need?

And if so, could you please describe your setup so that we can link to it?  Or even provide a piece of doc for Kiali.io?

Of course what @lucasponce wrote still applies.

**Comment by Yshayy** [comment]
Sure, thanks for the quick response :)
Our setup use istio 1.0.2 + kubernetes (based on Istio helm chart).

We've added OAuth2 proxy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  ...
  template:
    spec:
      containers:
      - name: oauth2-proxy
        image: webhostingcoopteam/oauth2_proxy
        command: ["oauth2_proxy"]
        args: ["-http-address", "0.0.0.0:80", "-email-domain", "{comapnyDomain}", "-upstream", "http://kubernetes.default.svc.cluster.local", "-client-id", "{client-id}", "-client-secret", "{client-secret}", "-cookie-secret", "{random-secret}"]
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - name: oauth2-proxy
      port: 80
      targetPort: 80
```

And then we use istio virtual service for each of istio tools (grafana, prom, kiali, tracing):

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {tool}
spec:
  hosts:
  - "{tool}.{my-external-domain}"
  gateways:
  - ingress.default.svc.cluster.local
  - mesh
  http:
  - match:
    - gateways:
      - mesh
    route:
    - destination:
        host: {tool}.istio-system.svc.cluster.local
        port:
          number: {tool-port}
  - match:
    - gateways:
      - ingress.default.svc.cluster.local
    route:
    - destination:
        host: oauth2-proxy.default.svc.cluster.local
```

That way, developers that want to access these service externally to the cluster need to pass Google login with domain validation (can be other auth solution).
The use case for us is providing observability to our developers (only read-only), it's extremely useful when monitoring/inspecting/debugging microservices and their relations.

I'll check the solution described in  kiali/kiali-ui#830, not sure I understand it completely, does the server allow anonymous access?

**Comment by pilhuhn** [comment]
@Yshayy Thanks for sharing!!

I understand the comment from @jmazzitelli that you need to [remove those lines](https://github.com/kiali/kiali/blob/282a03514d52628f2673166ba9f360b48cf9d08f/deploy/openshift/deployment.yaml#L42-L51)  from `deployment.yaml` to put the server into "anonymous mode".
See last paragraph of the description of  kiali/kiali-ui#830

**Comment by Yshayy** [comment]
After removing it, I still need to pass the login screen, but any user/pass combination works

**Comment by jmazzitelli** [comment]
> I still need to pass the login screen

You need to upgrade Kiali to avoid the login screen - this was recently fixed. see: https://issues.jboss.org/browse/KIALI-1958

So if you install Kiali 0.11.0, and you give someone a URL, they won't need to enter anything in the login screen.

**Comment by stephen-dahl** [comment]
set the `AUTH_STRATEGY` env var to `anonymous`

**Comment by xeor** [comment]
@Yshayy did you find a good way of doing this? I'm trying to do the same thing, but using keycloak and using the istio helm install.. No luck so far

**Comment by jshaughn** [comment]
@xeor Did using the 'anonymous' AUTH_STRATEGY not work for you?

**Comment by xeor** [comment]
@jshaughn didnt try it yet.. I was hoping there was a solution, but still use the kiali that comes with the istio helm chart. Looks like I haveto do kiali on the side then.. :) thanks

**Comment by jmazzitelli** [comment]
Istio now ships with v0.20. Or use the Kiali Operator. In either case, use auth_strategy = anonymous

See https://www.kiali.io/documentation/getting-started/#_login_options

**Comment by omerlh** [comment]
istio chart (v1.2.2) set the `auth_strategy` to `login` without the ability to modify it:
```
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    auth:
      strategy: "login"
```
