### ISSUE TITLE
Kiali logs error: ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found

### ISSUE THREAD

**Issue by aleksandermiszkiewicz** [kiali/kiali#6776]
Hello, 

I install Kiali on my GKE cluster. It seems that most of configuration is correct but all the time Kiali is logging error that it can not find `istio-1-18-2-1-18-2` configmap. This is true, there is no ` istio-1-18-2-1-18-2` configmap there is only `istio-1-18-2` configmap. 

### Versions: ###

* Kiali version: 1.73.0
* Istio: 1.18.2

### The logs from the Kiali: ###

> {"level":"info","time":"2023-10-25T13:57:35Z","message":"Adding a RegistryRefreshHandler"}
> 2023-10-25T13:57:35Z INF Kiali: Version: v1.73.0, Commit: 2e54c9e768905ad47338a1641c6777c3f2fbcc9c, Go: 1.20.5
> 2023-10-25T13:57:35Z INF Using authentication strategy [anonymous]
> 2023-10-25T13:57:35Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
> 2023-10-25T13:57:35Z INF Some validation errors will be ignored [KIA1301]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
> 2023-10-25T13:57:35Z INF Initializing Kiali Cache
> 2023-10-25T13:57:35Z INF Adding a RegistryRefreshHandler
> 2023-10-25T13:57:35Z INF [Kiali Cache] Waiting for cluster-scoped cache to sync
> 2023-10-25T13:57:35Z INF [Kiali Cache] Started
> 2023-10-25T13:57:35Z INF [Kiali Cache] Kube cache is active for cluster: [Kubernetes]
> 2023-10-25T13:57:35Z INF Server endpoint will start at [:20001/kiali]
> 2023-10-25T13:57:35Z INF Server endpoint will serve static content from [/opt/kiali/console]
> 2023-10-25T13:57:35Z INF Starting Metrics Server on [:9090]
> 2023-10-25T13:58:34Z INF [Prom Cache] Enabled
> 2023-10-25T13:58:35Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T13:58:59Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T13:58:59Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T13:59:03Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T13:59:13Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T14:00:03Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T14:01:03Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T14:02:03Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found
> 2023-10-25T14:03:03Z ERR Error getting mesh config: configmap "istio-1-18-2-1-18-2" not found

### The configuration of `Kiali CR` looks like this: ###

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  installation_tag: "Kiali - View Only"
  istio_namespace: "istio-system"
  api:
    namespaces:
      exclude:
        - "^kube-.*"
        - "^kiali-operator"
  auth:
    strategy: "anonymous"
  external_services:
    custom_dashboards:
      enabled: true
    istio:
      component_status:
        enabled: true
        components:
          - app_label: "istiod"
            is_core: true
            is_proxy: false
            namespace: istio-system
          - app_label: "istio-ingressgateway-ext-1-18-2"
            is_core: true
            is_proxy: true
            namespace: istio-ingress-ext
          - app_label: "istio-ingressgateway-int-1-18-2"
            is_core: true
            is_proxy: true
            namespace: istio-ingress-int
      istio_api_enabled: true
      istio_identity_domain: svc.cluster.local
      istio_sidecar_annotation: sidecar.istio.io/status
      url_service_version: http://istiod-1-18-2.istio-system:15014/version
      config_map_name: istio-1-18-2
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-1-18-2
      istiod_deployment_name: istiod-1-18-2
      root_namespace: istio-system
    prometheus:
      enabled: true
      url: "http://prometheus-operated.monitoring.svc.cluster.local:9090/"
    tracing:
      enabled: false
    grafana:
      enabled: false
  deployment:
    accessible_namespaces: ["**"]
    view_only_mode: true
    instance_name: "kiali"
    image_name: "us-east1-docker.pkg.dev/mesh/quay.io/kiali/kiali"
    image_pull_policy: "IfNotPresent"
    image_version: "v1.73.0"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: 1
        memory: "1Gi"
    logger:
      log_level: "info"
      log_format: "text"
      sampler_rate: "1"
      time_field_format: "2006-01-02T15:04:05Z07:00"
    namespace: istio-system
    tolerations:
      - key: "workload"
        value: "services"
        effect: "NoSchedule"
    affinity:
      node:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload
                  operator: In
                  values:
                    - services
  kiali_feature_flags:
    certificates_information_indicators:
      enabled: true
      secrets:
        - "cacerts"
        - "istio-ca-secret"
    clustering:
      autodetect_secrets:
        enabled: true
        label: "kiali.io/multiCluster=true"
    disabled_features: [ ]
    validations:
      ignore:
        - KIA1301
  server:
    observability:
      metrics:
        enabled: true
        port: 9090
    port: 20001
    web_root: /kiali
```

### Kiali API config ###

```
{
  "accessibleNamespaces": [
    "**"
  ],
  "authStrategy": "anonymous",
  "clusters": {
    "Kubernetes": {
      "apiEndpoint": "https://10.213.232.1:443",
      "isKialiHome": true,
      "kialiInstances": [
        {
          "namespace": "istio-system",
          "operatorResource": "",
          "serviceName": "kiali",
          "url": "://:20001/kiali",
          "version": "v1.73.0"
        }
      ],
      "name": "Kubernetes",
      "network": "",
      "secretName": ""
    }
  },
  "deployment": {
    "viewOnlyMode": true
  },
  "gatewayAPIEnabled": true,
  "healthConfig": {
    "rate": [
      {
        "tolerance": [
          {
            "code": "5XX",
            "degraded": 0,
            "failure": 10,
            "protocol": "http",
            "direction": ".*"
          },
          {
            "code": "4XX",
            "degraded": 10,
            "failure": 20,
            "protocol": "http",
            "direction": ".*"
          },
          {
            "code": "^[1-9]$|^1[0-6]$",
            "degraded": 0,
            "failure": 10,
            "protocol": "grpc",
            "direction": ".*"
          },
          {
            "code": "^-$",
            "degraded": 0,
            "failure": 10,
            "protocol": "http|grpc",
            "direction": ".*"
          }
        ]
      },
      {
        "tolerance": [
          {
            "code": "5XX",
            "degraded": 0,
            "failure": 10,
            "protocol": "http",
            "direction": ".*"
          },
          {
            "code": "4XX",
            "degraded": 10,
            "failure": 20,
            "protocol": "http",
            "direction": ".*"
          },
          {
            "code": "^[1-9]$|^1[0-6]$",
            "degraded": 0,
            "failure": 10,
            "protocol": "grpc",
            "direction": ".*"
          },
          {
            "code": "^-$",
            "degraded": 0,
            "failure": 10,
            "protocol": "http|grpc",
            "direction": ".*"
          }
        ]
      }
    ]
  },
  "installationTag": "Kiali - View Only",
  "istioAnnotations": {
    "istioInjectionAnnotation": "sidecar.istio.io/inject"
  },
  "istioCanaryRevision": {},
  "istioConfigMap": "istio-1-18-2",
  "istioIdentityDomain": "svc.cluster.local",
  "istioLabels": {
    "appLabelName": "app",
    "injectionLabelName": "istio-injection",
    "injectionLabelRev": "istio.io/rev",
    "versionLabelName": "version"
  },
  "istioNamespace": "istio-system",
  "istioStatusEnabled": true,
  "kialiFeatureFlags": {
    "certificatesInformationIndicators": {
      "enabled": true,
      "secrets": [
        "cacerts",
        "istio-ca-secret"
      ]
    },
    "clustering": {
      "enable_exec_provider": false
    },
    "istioAnnotationAction": true,
    "istioInjectionAction": true,
    "istioUpgradeAction": false,
    "uiDefaults": {
      "graph": {
        "findOptions": [
          {
            "description": "Find: slow edges (\u003e 1s)",
            "expression": "rt \u003e 1000"
          },
          {
            "description": "Find: unhealthy nodes",
            "expression": "! healthy"
          },
          {
            "description": "Find: unknown nodes",
            "expression": "name = unknown"
          },
          {
            "description": "Find: nodes with the 2 top rankings",
            "expression": "rank \u003c= 2"
          }
        ],
        "hideOptions": [
          {
            "description": "Hide: healthy nodes",
            "expression": "healthy"
          },
          {
            "description": "Hide: unknown nodes",
            "expression": "name = unknown"
          },
          {
            "description": "Hide: nodes ranked lower than the 2 top rankings",
            "expression": "rank \u003e 2"
          }
        ],
        "impl": "cy",
        "settings": {
          "fontLabel": 13,
          "minFontBadge": 7,
          "minFontLabel": 10
        },
        "traffic": {
          "grpc": "requests",
          "http": "requests",
          "tcp": "sent"
        }
      },
      "list": {
        "includeHealth": true,
        "includeIstioResources": true,
        "includeValidations": true,
        "showIncludeToggles": false
      },
      "metricsPerRefresh": "1m",
      "metricsInbound": {},
      "metricsOutbound": {},
      "refreshInterval": "60s"
    },
    "validations": {
      "ignore": [
        "KIA1301"
      ],
      "SkipWildcardGatewayHosts": false
    }
  },
  "logLevel": "trace",
  "prometheus": {
    "globalScrapeInterval": 30,
    "storageTsdbRetention": 864000
  }
}
```

Istio control plane is installed in `istio-system` namespace while Istio ingress gateways, respectively in `istio-ingress-int` and `istio-ingress-ext` namespaces. 

### Few more screenshots. ###

`kubectl get deployments -n istio-system`
![image](https://github.com/kiali/kiali/assets/96211187/b68b0a6d-d44f-41b3-ba92-c31cc7722983)

`kubectl get pods -n istio-system`
![image](https://github.com/kiali/kiali/assets/96211187/03902df0-554b-485d-9d01-ca55becb5261)

`kubectl get cm -n istio-system`
![image](https://github.com/kiali/kiali/assets/96211187/b98f3254-08bf-44ad-952d-bbc1efc8bac7)

Do you have any ideas what is the problem ?
