### ISSUE TITLE
failed to update kiali since v1.67 if `current_label_selector_include` is not set

### ISSUE THREAD

**Issue by sylvainOL** [kiali/kiali#6778]
I've got the following kiali deployment:

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  finalizers:
  - kiali.io/finalizer
  name: kiali
  namespace: kiali
spec:
  auth:
    strategy: header
  deployment:
    accessible_namespaces:
    - '**'
    additional_service_yaml:
      externalName: kiali.xxx
    hpa:
      spec:
        maxReplicas: 2
        metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
        minReplicas: 1
    image_pull_policy: Always
    logger:
      log_level: debug
    pod_annotations:
      prometheus.io/scrape: "false"
  external_services:
    grafana:
      enabled: false
    istio:
      component_status:
        components:
        - app_label: istiod
          is_core: true
          is_proxy: false
          namespace: istio-system
        - app_label: istio-ingress
          is_core: true
          is_proxy: true
          namespace: istio-ingress
        - app_label: istio-ingress-no-auth
          is_core: true
          is_proxy: true
          namespace: istio-ingress
      root_namespace: istio-system
    prometheus:
      is_core: false
      url: http://prometheus-kube-prometheus-prometheus.monitoring-system.svc.cluster.local:9090
    tracing:
      enabled: false
      url: https://jaeger.xxx
  istio_namespace: istio-system
  server:
    observability:
      tracing:
        collector_url: http://grafana-agent.grafana-agent.svc.cluster.local:14268/api/traces
        enabled: true
```

up to version 1.66 of the operator, everything (install / upgrade) was fine but since v1.67, the upgrade fails with:

```console
TASK [default/kiali-deploy : Remove Kiali label from namespaces that Kiali no longer has access to] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:         ^
fatal: [localhost]: FAILED! => 
{"changed": false, 
"module_stderr": "Traceback (most recent call last):
  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1698247155.7248194-1439-154009858852526/AnsiballZ_k8s.py\", line 102, in <module>
    _ansiballz_main()
  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1698247155.7248194-1439-154009858852526/AnsiballZ_k8s.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1698247155.7248194-1439-154009858852526/AnsiballZ_k8s.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_k8s_payload_jjspfwfm/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 397, in <module>
  File \"/tmp/ansible_k8s_payload_jjspfwfm/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 393, in main
  File \"/tmp/ansible_k8s_payload_jjspfwfm/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 376, in execute_module
  File \"/tmp/ansible_k8s_payload_jjspfwfm/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py\", line 503, in set_resource_definitions
  File \"/tmp/ansible_k8s_payload_jjspfwfm/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py\", line 503, in <listcomp>
  File \"/usr/local/lib64/python3.8/site-packages/yaml/__init__.py\", line 93, in load_all
    yield loader.get_data()
  File \"/usr/local/lib64/python3.8/site-packages/yaml/constructor.py\", line 45, in get_data
    return self.construct_document(self.get_node())
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 27, in get_node
    return self.compose_document()
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 55, in compose_document
    node = self.compose_node(None, None)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File \"/usr/local/lib64/python3.8/site-packages/yaml/composer.py\", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File \"/usr/local/lib64/python3.8/site-packages/yaml/parser.py\", line 98, in check_event
    self.current_event = self.state()
  File \"/usr/local/lib64/python3.8/site-packages/yaml/parser.py\", line 425, in parse_block_mapping_first_key
    return self.parse_block_mapping_key()
  File \"/usr/local/lib64/python3.8/site-packages/yaml/parser.py\", line 438, in parse_block_mapping_key
    raise ParserError(\"while parsing a block mapping\", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
expected <block end>, but found ':'
  in \"<unicode string>\", line 7, column 5:
        : null
        ^
", 
"module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

when I enable debug, I can see:

```json
{
"invocation": {
        "definition": "---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: \"**\"\n  labels:\n    : null\n...\n",
        "module_args": {
            "definition": "---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: \"**\"\n  labels:\n    : null\n...\n",
            "state": "patched"
        },
        "state": "patched"
    }
}
```

According to https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L866, it shouldn't be launched as `current_label_selector_include` is not set in the config but when I look at how it's retrieved, it's actually retrieving an empty string:

```console
TASK [default/kiali-deploy : Find some current configuration settings] *********
task path: /opt/ansible/roles/default/kiali-deploy/tasks/main.yml:746
ok: [localhost] => {
    "ansible_facts": {
        "current_accessible_namespaces": [
            "**"
        ],
        "current_auth_strategy": "header",
        "current_cluster_wide_access": "",
        "current_image_name": "quay.io/kiali/kiali",
        "current_image_version": "v1.66.0",
        "current_instance_name": "kiali",
        "current_label_selector_include": "",
        "current_view_only_mode": false
    },
    "changed": false
}
```

thus `current_label_selector_include` is "`defined`" but is empty.
maybe we should add a test for empty string in `Remove Kiali label from namespaces that Kiali no longer has access to` (the only task where test `current_label_selector_include is defined` is performed and relevant in this case (`Do not allow user to change label_selector_include` has the same test but pass it here)

What do you think?
