### ISSUE TITLE
OpenID - GCP / GKE integration.- Not handling OpenId code flow authentication: no authorization code is present / invalid_client / Unauthorized

### ISSUE THREAD

**Issue by aleksandermiszkiewicz** [kiali/kiali#6826]
Hey,

I deployed Kiali on my private GKE cluster. I want to configure the OpenID connect authentication and I did it. But, when the user want to log in to the Kiali the Unauthorized response is received `https://kiali.dev.example.com/kiali/?openid_error=request+failed+%28HTTP+response+status+%3D+401+Unauthorized%29`

In the Kiali logs I can see this

```
2023-11-07T21:42:56Z DBG OpenId token request failed with response: {
  "error": "invalid_client",
  "error_description": "Unauthorized"
}
2023-11-07T21:42:56Z WRN Authentication rejected: request failed (HTTP response status = 401 Unauthorized)
```

Additionally, in the logs I can see the log:

`2023-11-07T21:42:51Z DBG Not handling OpenId code flow authentication: no authorization code is present`

I configured everything according to the docs https://kiali.io/docs/configuration/authentication/openid/#using-with-google-cloud-platform--gke-oauth2. 

The OpenID client-secret is present. I checked this using: `kubectl exec kiali-ff875874-4q9vt -n monitoring -- cat /kiali-secret/oidc-secret`

### Configuration

- Kiali 1.73
- GKE 1.27.4

My Kiali-CR configuration looks like this:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: monitoring
spec:
  installation_tag: "Kiali - View Only"
  istio_namespace: "istio-system"
  api:
    namespaces:
      exclude:
        - "^kube-.*"
        - "^kiali-operator"
  auth:
    strategy: "openid"
    openid:
      authentication_timeout: 300
      client_id: "xxx.apps.googleusercontent.com"
      disable_rbac: true
      issuer_uri: "https://accounts.google.com"
      scopes: [ "openid", "email" ]
      username_claim: "email"
      insecure_skip_verify_tls: false
      allowed_domains:
        - example.com
        - gcp.example.com
  external_services:
    custom_dashboards:
      enabled: true
    istio:
      component_status:
        enabled: true
        components:
          - app_label: "istiod"
            is_core: true
            is_proxy: false
            namespace: istio-system
          - app_label: "istio-ingressgateway-ext-1-18-2"
            is_core: true
            is_proxy: true
            namespace: istio-ingress-ext
          - app_label: "istio-ingressgateway-int-1-18-2"
            is_core: true
            is_proxy: true
            namespace: istio-ingress-int
      istio_api_enabled: true
      istio_identity_domain: svc.cluster.local
      istio_sidecar_annotation: sidecar.istio.io/status
      url_service_version: http://istiod-1-18-2.istio-system:15014/version
      config_map_name: istio-1-18-2
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-1-18-2
      istiod_deployment_name: istiod-1-18-2
      root_namespace: "istio-system"
    istio_labels:
      app_label_name: "app"
      injection_label_name: "istio-injection"
      injection_label_rev: "istio.io/rev"
      version_label_name: ""
    prometheus:
      enabled: true
      url: "http://prometheus-operated.monitoring.svc.cluster.local:9090/"
    tracing:
      enabled: false
    grafana:
      enabled: false
  deployment:
    accessible_namespaces: ["**"]
    view_only_mode: true
    instance_name: "kiali"
    image_pull_policy: "IfNotPresent"
    image_version: "v1.73.0"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: 1
        memory: "1Gi"
    logger:
      log_level: "trace"
      log_format: "text"
      sampler_rate: "1"
      time_field_format: "2006-01-02T15:04:05Z07:00"
    namespace: monitoring
  kiali_feature_flags:
    istio_injection_action: false
    certificates_information_indicators:
      enabled: true
      secrets:
        - "cacerts"
        - "istio-ca-secret"
    clustering:
      autodetect_secrets:
        enabled: true
        label: "kiali.io/multiCluster=true"
    disabled_features: [ ]
    validations:
      ignore:
        - KIA1301
  server:
    observability:
      metrics:
        enabled: true
        port: 9090
    port: 20001
    web_root: /kiali
    web_schema: https
    web_fqdn: kiali.dev.example.com
```

The VirtualService:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: kiali
  name: kiali
  namespace: monitoring
spec:
  gateways:
    - istio-ingress-int/ingress-config-gateway-int
  hosts:
    - kiali.dev.example.com
  http:
    - headers:
        request:
          set:
            X-Forwarded-Port: "443"
      route:
        - destination:
            host: kiali
            port:
              number: 20001
```

Any ideas what I missed ?
