### ISSUE TITLE
unable to proxy Istiod pods Make sure your Kubernetes API server has access to the Istio control plane through 8080 port

### ISSUE THREAD

**Issue by den-is** [kiali/kiali#6834]
Istio 1.18.5
Kiali v1.76.0
Kubernetes v1.28.3
Cilium v1.14.3

Fresh **helm** installs
Istio is installed in `istio-system` namespace
Kiali is installed in `monitoring` namespace

Getting errors:

```
2023-11-08T16:59:01Z ERR unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2023-11-08T16:59:06Z WRN Error getting proxy status from istiod. Proxy status may be stale. Err: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2023-11-08T16:59:16Z ERR Failed to call Istiod endpoint /debug/syncz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2023-11-08T16:59:21Z ERR Failed to call Istiod endpoint /debug/syncz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2023-11-08T16:59:26Z WRN Error getting proxy status from istiod. Proxy status may be stale. Err: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
```

I can config that kubernetes API has access to istiod 8080, testing from my workstation

```
k -n istio-system port-forward istiod-774dd88df4-28b42 8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080

curl -s http://localhost:8080/debug/syncz | jq
[
  {
    "cluster_id": "Kubernetes",
    "proxy": "istio-egress-56f7788444-2rrj2.istio-gateways",
    "proxy_type": "router",
    "istio_version": "1.18.5",
    ... omitted
  },
  {
    "cluster_id": "Kubernetes",
    "proxy": "istio-ingress-5bb48fddd-98bdn.istio-gateways",
    "proxy_type": "router",
    "istio_version": "1.18.5",
    ... omitted
  }
]
```
Checked ClusterRole[Binding] and ServiceAccount. Seems to be ok. SA gets "kiali" clusterrole, not "kiali-viewer".

**When I install Kiali into the `istio-system` namespace next to `istiod` everything is working!**

<details>
<summary><b>Kiali helm values:</b><i>(Click to expand)</i></summary>

```yaml
auth:
  strategy: anonymous

server:
  web_fqdn: kiali.10.1.1.33.nip.io

deployment:
  ingress:
    enabled: true
    class_name: nginx

external_services:
  grafana:
    enabled: true
    in_cluster_url: http://promstack-grafana.monitoring
    url: http://grafana.10.1.1.33.nip.io
    auth:
      type: basic
      username: admin
      password: admin
    dashboards:
    - name: "Istio Service Dashboard"
      variables:
        namespace: "var-namespace"
        service: "var-service"
    - name: "Istio Workload Dashboard"
      variables:
        namespace: "var-namespace"
        workload: "var-workload"
    - name: "Istio Mesh Dashboard"
    - name: "Istio Control Plane Dashboard"
    - name: "Istio Performance Dashboard"
    - name: "Istio Wasm Extension Dashboard"
  tracing:
    enabled: true
    in_cluster_url: http://jaeger-query.monitoring:16685
    use_grpc: true
    url: http://jaeger.10.1.1.33.nip.io
  prometheus:
    url: http://prometheus-operated.monitoring:9090
  istio:
    root_namespace: istio-system
    # ingresses are installed into a separate namespace so need to tell that to Kiali
    component_status:
      enabled: true
      components:
      - app_label: istiod
        is_core: true
        is_proxy: false
      - app_label: istio-ingressgateway
        is_core: true
        is_proxy: true
        namespace: istio-gateways
      - app_label: istio-egressgateway
        is_core: false
        is_proxy: true
        namespace: istio-gateways

```
</details>

**So what does it want? How to configure Kiali in namespace different from where `istiod` is?**
Checked docs and Kiali_CR several times already.
