### ISSUE TITLE
Include istio-waypoint gateway api class as a default 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6878]
Kiali validation error KIA1504 for the istio-waypoint gatewayClassName.

![image](https://github.com/kiali/kiali/assets/49480155/294293cd-dbb2-498f-8feb-5c1ba9a65d7f)

After creating a waypoint proxy:

`istioctl x waypoint apply -n bookinfo`

Should be added as a default, considering that Istio waypoint is still experimental? 

```
external_services:
  istio:
    gateway_api_classes:
     - name: Waypoint
       class_name: istio-waypoint
     - name: Istio
       class_name: istio  
```

Ref. https://github.com/kiali/kiali/issues/6757
