### ISSUE TITLE
Enhancing Kiali OIDC process

### ISSUE THREAD

**Issue by LR-PERSONAL** [kiali/kiali#6942]
### What do you want to improve?
Kiali OIDC secret ingestion process for OIDC process

### What is the current behavior?
Currently when setting up kiali with OIDC one of the required steps is to create a secret via kubectl. This is not optimal in envs where kiali is deployed in hundreds of clusters. 

### What is the new behavior?

The new behavior adds the option to inject secrets into kiali and its namespace with the aid of secret-store driver. Secret store driver is compatible with all secret management tools. This would make Kiali more compatible with enterprise and enhance its compatibility with external apps.

**Comment by nrfox** [comment]
Would this just be supporting mounting the secret as a file into the kiali pod and to have the kiali server read that file? @jmazzitelli I think this just what the kiali operator does with the oidc Secret right? I haven't tried this but it looks like if you mounted `/kiali-secret/oidc-secret` into the kiali server pod with the oidc secret as content then it'd work. If that does work then it should be added to the docs as an alternative way of configuring the OIDC secret.

**Comment by LR-PERSONAL** [comment]
Currently the volume for the path /kiali-secret is defined as secret so we cannot modify anything in it. I checked the code and as you said it should work by placing the secret in /kiali-secret/oidc-secret . Also yes the secrets store driver allows everyone to inject their secret  directly to /kiali-secret/oidc-secret or it can also generate a k8s secret that kiali can then use as it does now currently.

**Comment by LR-PERSONAL** [comment]
I believe if we mount the oidc secret in the path /kiali-secret/oidc-secret with custom secrets would work. The only other issue I see with this is how do you get 3rd party software to inject the secret there? Most of them either require deployment edit or extra pod annotations. -- Maybe adding a space for extra pod annotations (persumably customizable) could work with this approach ?

**Comment by jmazzitelli** [comment]
> The only other issue I see with this is how do you get 3rd party software to inject the secret there? Most of them either require deployment edit or extra pod annotations

I may not understand the question but... when you say "inject the secret there ... require deployment edit" -- putting the [custom secret details in the Kiali CR](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.custom_secrets) tells the Kiali Operator to do the deployment edit (see [here](https://github.com/kiali/kiali-operator/blob/v1.77.1/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml#L117-L120) and [here](https://github.com/kiali/kiali-operator/blob/v1.77.1/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml#L153-L160) for that code).

If you are not using the Kiali Operator but instead are only using the server helm chart, the server helm chart also provides [this feature](https://github.com/kiali/helm-charts/blob/v1.77.0/kiali-server/values.yaml#L39). See [here](https://github.com/kiali/helm-charts/blob/v1.77.0/kiali-server/templates/deployment.yaml#L126-L129) and [here](https://github.com/kiali/helm-charts/blob/v1.77.0/kiali-server/templates/deployment.yaml#L166-L171) for the template code. But recall that the recommended approach is to use the Kiali Operator; the Kiali [server helm chart is simply provided as a convenience](https://kiali.io/docs/installation/installation-guide/install-with-helm/#introduction)).

If the question is, "How does the secret itself get created?", that is out of scope for Kiali - how ever the secret gets created (if you use a third party secret management system, or whatever) doesn't matter to Kiali. As long as the secret exists in the Kiali namespace, that's all it cares about.

Speaking of extra pod annotations or pod labels (if those are needed for a third-party secret management system to create secrets), if those are needed, that can be done in the `deployment` section of the Kiali CR - see [deployment.pod_annotations](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.pod_annotations) and [deployment.pod_labels](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.pod_labels)

**Comment by jshaughn** [comment]
@LR-PERSONAL Did this answer the question?  I'm not sure there is work to do here.

**Comment by jshaughn** [comment]
Closing as Stale.

**Comment by rumstead** [comment]
@jshaughn can we re-open this? 

> I haven't looked into this yet, but what about this feature that already exists?
> 
> https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.custom_secrets
> 
> You can specify your own secrets here -- they will get mounted into the Kiali Server pod.

We also want to use secret CSI drivers to expose K8s secrets to our Kiali pods for our OIDC token. The CSI driver uses a pod's service account for authorization and will [only create the secret when there is a mount requested](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret). However, the Kiali helm chat doesn't allow us to add any volume mounts to have the CSI drive create the secret.  

> The secrets will only sync once you start a pod mounting the secrets. Solely relying on the syncing with Kubernetes secrets feature thus does not work. When all the pods consuming the secret are deleted, the Kubernetes secret is also deleted.

**Comment by jshaughn** [comment]
Hi @rumstead , I re-opened the issue so that we can maybe refine further what's being asked for.   It sounds like you need an extension to define volume mounts?  @jmazzitelli , any comment?

**Comment by jmazzitelli** [comment]
Would need a detailed use-case and explanation what is needed. Also we would need to examine the current kiali configuration settings to see if we already have something that will help.

**Comment by rumstead** [comment]
> Hi @rumstead , I re-opened the issue so that we can maybe refine further what's being asked for. It sounds like you need an extension to define volume mounts? @jmazzitelli , any comment?

Thank you!

> Would need a detailed use-case and explanation what is needed. Also we would need to examine the current kiali configuration settings to see if we already have something that will help.

Happy to expand. Let me try summarizing again and let me know what needs further explanation. 

## What do you want to improve?
Exposing OIDC secrets using vendor-agnostic enterprise-grade, secret management technologies. Specifically, ones that met the [Kubernetes Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/introduction) spec, e.g, a nonexhaustive list: Azure Key Vault, Hashicorp Vault, Google Secret Manager.

## What is the current behavior?
Currently when setting up kiali with OIDC one of the required steps is to [create a K8s secret containing your OIDC token](https://kiali.io/docs/configuration/authentication/openid/#setup-with-rbac). The helm chart doesn't allow users to customize volume mounts which restricts using the secret store CSI driver. 

## What is the new behavior?
To deploy the token in a scalable and secure manner, we want to leverage the secret CSI drivers backed by secret management tools. The secret CSI driver uses a pod's service account for authorization and will [only create the secret when there is a mount requested](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret). However, the kiali helm chat doesn't allow us to add any volume mounts which in turn doesn't trigger the secret creation.

**Comment by jmazzitelli** [comment]
OK, so this isn't adding custom containers, it adding custom volume mounts?

Can you provide an example of what you would like to see happen if this feature is implemented. In other words, what will the Kiali Deployment yaml look like? Is there a new volume mount? Is there metadata.annotations or labels that are needed? Is it only in the Deployment or do some other resources need to be touched?. An example yaml would be useful.

And what do you propose the server helm chart values.yaml would look like (what is the proposed new config settings)?

FWIW: I know absolutely nothing, zero, about this secret store CSI stuff - so you will need to provide details as if we are totally ignorant about it (because we are :)

**Comment by rumstead** [comment]
Sorry, this took me longer than it should have to carve out the time. Something along these lines would work. 

deployment template
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiali-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "kiali-server.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: {{ include "kiali-server.fullname" . }}
      labels:
        {{- include "kiali-server.labels" . | nindent 8 }}
        {{- if .Values.deployment.pod_labels }}
        {{- toYaml .Values.deployment.pod_labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.server.observability.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.server.observability.metrics.port | quote }}
        {{- else }}
        prometheus.io/scrape: "false"
        prometheus.io/port: ""
        {{- end }}
        kiali.io/dashboards: go,kiali
        {{- if .Values.deployment.pod_annotations }}
        {{- toYaml .Values.deployment.pod_annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kiali-server.fullname" . }}
      {{- if .Values.deployment.priority_class_name }}
      priorityClassName: {{ .Values.deployment.priority_class_name | quote }}
      {{- end }}
      {{- if .Values.deployment.image_pull_secrets }}
      imagePullSecrets:
      {{- range .Values.deployment.image_pull_secrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.deployment.host_aliases }}
      hostAliases:
      {{- toYaml .Values.deployment.host_aliases | nindent 6 }}
      {{- end }}
      containers:
      - image: "{{ .Values.deployment.image_name }}{{ if .Values.deployment.image_digest }}@{{ .Values.deployment.image_digest }}{{ end }}:{{ .Values.deployment.image_version }}"
        imagePullPolicy: {{ .Values.deployment.image_pull_policy | default "Always" }}
        name: {{ include "kiali-server.fullname" . }}
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        securityContext:
        {{- if .Values.deployment.security_context}}
        {{- toYaml .Values.deployment.security_context | nindent 10 }}
        {{- else }}
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        {{- end }}
        ports:
        - name: api-port
          containerPort: {{ .Values.server.port | default 20001 }}
        {{- if .Values.server.observability.metrics.enabled }}
        - name: http-metrics
          containerPort: {{ .Values.server.observability.metrics.port | default 9090 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ include "kiali-server.server.web_root" . | trimSuffix "/"  }}/healthz
            port: api-port
            {{- if (include "kiali-server.identity.cert_file" .) }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: {{ include "kiali-server.server.web_root" . | trimSuffix "/"  }}/healthz
            port: api-port
            {{- if (include "kiali-server.identity.cert_file" .) }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 30
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: "{{ include "kiali-server.logLevel" . }}"
        - name: LOG_FORMAT
          value: "{{ .Values.deployment.logger.log_format }}"
        - name: LOG_TIME_FIELD_FORMAT
          value: "{{ .Values.deployment.logger.time_field_format }}"
        - name: LOG_SAMPLER_RATE
          value: "{{ .Values.deployment.logger.sampler_rate }}"
        volumeMounts:
        - name: {{ include "kiali-server.fullname" . }}-configuration
          mountPath: "/kiali-configuration"
        - name: {{ include "kiali-server.fullname" . }}-cert
          mountPath: "/kiali-cert"
        - name: {{ include "kiali-server.fullname" . }}-secret
          mountPath: "/kiali-secret"
        - name: {{ include "kiali-server.fullname" . }}-cabundle
          mountPath: "/kiali-cabundle"
        {{- range .Values.deployment.custom_secrets }}
        - name: {{ .name }}
          mountPath: "{{ .mount }}"
        {{- end }}
        {{- range $key, $val := (include "kiali-server.remote-cluster-secrets" .) | fromJson }}
        - name: {{ $key }}
          mountPath: "/kiali-remote-cluster-secrets/{{ $val }}"
        {{- end }}
        {{- range .Values.clustering.clusters }}
        - name: {{ .name }}
          mountPath: "/kiali-remote-cluster-secrets/{{ .secret_name }}"
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources:
        {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: {{ include "kiali-server.fullname" . }}-configuration
        configMap:
          name: {{ include "kiali-server.fullname" . }}
      - name: {{ include "kiali-server.fullname" . }}-cert
        secret:
          {{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
          secretName: {{ include "kiali-server.fullname" . }}-cert-secret
          {{- else }}
          secretName: istio.{{ include "kiali-server.fullname" . }}-service-account
          {{- end }}
          {{- if not (include "kiali-server.identity.cert_file" .) }}
          optional: true
          {{- end }}
      - name: {{ include "kiali-server.fullname" . }}-secret
        secret:
          secretName: {{ .Values.deployment.secret_name }}
          optional: true
      - name: {{ include "kiali-server.fullname" . }}-cabundle
        configMap:
          name: {{ include "kiali-server.fullname" . }}-cabundle
      {{- if not (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
          optional: true
      {{- end }}
      {{- range .Values.deployment.custom_secrets }}
      - name: {{ .name }}
        secret:
          secretName: {{ .name }}
          optional: {{ .optional | default false }}
      {{- end }}
      {{- range $key, $val := (include "kiali-server.remote-cluster-secrets" .) | fromJson }}
      - name: {{ $key }}
        secret:
          secretName: {{ $val }}
      {{- end }}
      {{- range .Values.clustering.clusters }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secret_name }}
      {{- end }}
      {{- range .Values.deployment.volumes }}
      - name: {{ .name }}
        csi: {{ toYaml .csi | nindent 10 }}
      {{- end }}
      {{- if or (.Values.deployment.affinity.node) (or (.Values.deployment.affinity.pod) (.Values.deployment.affinity.pod_anti)) }}
      affinity:
        {{- if .Values.deployment.affinity.node }}
        nodeAffinity:
        {{- toYaml .Values.deployment.affinity.node | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.pod }}
        podAffinity:
        {{- toYaml .Values.deployment.affinity.pod | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.pod_anti }}
        podAntiAffinity:
        {{- toYaml .Values.deployment.affinity.pod_anti | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.node_selector }}
      nodeSelector:
      {{- toYaml .Values.deployment.node_selector | nindent 8 }}
      {{- end }}
...
```

Values.yaml
```yaml
deployment:
  volumes:
    - name: kiali-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "kiali-secretprovider"
```

Rendered deployment
```yaml
helm template . -s templates/deployment.yaml
---
# Source: kiali-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
  namespace: default
  labels:
    helm.sh/chart: kiali-server-0.0.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "${HELM_IMAGE_TAG}"
    app.kubernetes.io/version: "${HELM_IMAGE_TAG}"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: kiali
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: kiali
      labels:
        helm.sh/chart: kiali-server-0.0.0
        app: kiali
        app.kubernetes.io/name: kiali
        app.kubernetes.io/instance: kiali
        version: "${HELM_IMAGE_TAG}"
        app.kubernetes.io/version: "${HELM_IMAGE_TAG}"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: "kiali"
      annotations:
        checksum/config: 2147540c8b88004d82d1857b08096358f768c1cf9a3568e093de8e2f611cd6a1
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        kiali.io/dashboards: go,kiali
    spec:
      serviceAccountName: kiali
      containers:
      - image: "quay.io/kiali/kiali:${HELM_IMAGE_TAG}"
        imagePullPolicy: Always
        name: kiali
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        ports:
        - name: api-port
          containerPort: 20001
        - name: http-metrics
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /kiali/healthz
            port: api-port
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /kiali/healthz
            port: api-port
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "text"
        - name: LOG_TIME_FIELD_FORMAT
          value: "2006-01-02T15:04:05Z07:00"
        - name: LOG_SAMPLER_RATE
          value: "1"
        volumeMounts:
        - name: kiali-configuration
          mountPath: "/kiali-configuration"
        - name: kiali-cert
          mountPath: "/kiali-cert"
        - name: kiali-secret
          mountPath: "/kiali-secret"
        - name: kiali-cabundle
          mountPath: "/kiali-cabundle"
        - name: kiali-secret
          mountPath: "/mnt/secrets-store"
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
      volumes:
      - name: kiali-configuration
        configMap:
          name: kiali
      - name: kiali-cert
        secret:
          secretName: istio.kiali-service-account
          optional: true
      - name: kiali-secret
        secret:
          secretName: kiali
          optional: true
      - name: kiali-cabundle
        configMap:
          name: kiali-cabundle
          optional: true
      - name: kiali-secret
        secret:
          secretName: kiali-secret
          optional: false
      - name: kiali-secret
        csi: 
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: kiali-secretprovider
...
```
