### ISSUE TITLE
KIA1106- More than one Virtual Service for same host

### ISSUE THREAD

**Issue by michalromanowskiap** [kiali/kiali#6953]
### Describe the bug

We have multiple Virtual Services, that do not share `spec.hosts` (we don't have `*` either).  Although, we are seeing KIA1106 warning for every Virtual Service we have. I've read [issue #4711](https://github.com/kiali/kiali/issues/4711), where they had some problems with registries and multiple istiod instances. Currently, we have 3 instances, but this issue was somehow fixed.

Example of our VS manifest:
```yaml
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: servicename
  namespace: dev
spec:
  hosts:
    - servicename
    - servicename.dev
    - servicename.dev.svc.cluster.local
  http:
    - name: default
      route:
        - destination:
            host: servicename.dev.svc.cluster.local
            subset: default
          weight: 100
```

### Expected Behavior

There's no KIA1106 warning.

### What are the steps to reproduce this bug?

Not sure ;/

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** v1.75.0 (45d72534b0556c0425f52a1488811eb372c92e43)
- **Istio version:** 1.17.2
- **Kubernetes impl:** AKS
- **Kubernetes version:**  v1.27.3
- **Other notable environmental factors:**
