### ISSUE TITLE
Kiali render hostnames as individual service instead of serviceentry as whole

### ISSUE THREAD

**Issue by im-Amitto** [kiali/kiali#6962]
### Describe the bug
Loom Video :-> https://www.loom.com/share/2c1906c2ffe042dcbf6d96ca9e4f7ef4
A serviceentry is supposed to be visualised as single icon in graph does not matter how many number of hostnames it has in it.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api.headout.com
spec:
  hosts:
  - api.example.com
  - api.example2.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

It should be shown as a single icon but kiali is showing 1 service icon per hostname. It does not happen always. It does show the service entry as a single icon sometime but goes back to showing one icon per hostname on refresh.

### Expected Behavior
Single icon for a single service entry

### What are the steps to reproduce this bug?

1. Create a serviceentry with two hostname
2. Visualise the traffic

### Environment

- **Kiali version:** v1.76.1 (0f96891475ab41b10821ae8e1850572fbcd1505f)
- **Istio version:** 1.18.2
- **Kubernetes version:**  v1.28.4-eks-8cb36c9
- **Prometheus** 2.48.0
