### ISSUE TITLE
query_scope results in no metrics being displayed

### ISSUE THREAD

**Issue by CmdrSharp** [kiali/kiali#6990]
### Describe the bug

I have a multi-cluster setup with two distinct meshes, both sending data to a single Victoria Metrics instance (through Victoria Metrics Agent), with the additional `cluster` label to the distinct cluster name.

Both clusters run their own instance of Kiali. To fetch only the metrics relevant to them, they use `query_scope` to filter metrics based on this cluster label:

```yaml
                    query_scope:
                      cluster: "{{ name }}"
```

Unfortunately, this results in no metrics being displayed at all. When this scope is removed, metrics are displayed (but of course intermixed between the two clusters, so the data becomes erroneous). **Note that the function _does_ seem to work for traces**.
Looking in Grafana, all metrics are there and indeed filterable:

![CleanShot 2023-12-31 at 14 51 07](https://github.com/kiali/kiali/assets/5938745/fb88cffe-23ac-4ac7-a26b-bd15c8903eee)

Am I misunderstanding something regarding the function of `query_scope`, or have I run into a bug?

### Expected Behavior

Metrics should be displayed (but filtered)

### What are the steps to reproduce this bug?

1. Install Victoria Metrics Single
2. Install Victoria Metrics Agent, and set a `VMAgent` to send data to the `VMSingle` instance.
3. Setup Kiali with a `query_scope`

### Environment

- **Kiali version:** v1.78.0 (bbd0384dfdb243c3e6cbb8199438d07c2a196bd7)
- **Istio version:** 1.20.1
- **Kubernetes impl:** K0s
- **Kubernetes version:** v1.28.4+k0s
- **Other notable environmental factors:**
Victoria Metrics (Single) 1.96.0

### Manifests

**VMAgent**  
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  additionalScrapeConfigs:
    key: prometheus.yaml
    name: additional-scrape-configs
  arbitraryFSAccessThroughSMs: {}
  externalLabels:
    cluster: sehar01-dev01
  extraArgs:
    promscrape.streamParse: "true"
  image:
    tag: v1.96.0
  remoteWrite:
  - url: https://<REDACTED>/api/v1/write
  resources: {}
  scrapeInterval: 20s
  selectAllByDefault: true
```

**VMSingle**  
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metrics
  namespace: victoria-metrics
spec:
  image:
    pullPolicy: IfNotPresent
    repository: victoriametrics/victoria-metrics
    tag: v1.96.0
  removePvcAfterDelete: true
  retentionPeriod: 7d
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
```

**Kiali Helm Values**
```yaml
cr:
  create: true
  namespace: istio-system
  spec:
    server:
      web_fqdn: "{{ name }}.<REDACTED>"
      web_root: /kiali
      web_port: 443
      web_schema: https
    external_services:
      tracing:
        enabled: true
        provider: tempo
        use_grpc: false
        in_cluster_url: 'https://tempo.<REDACTED>'
        url: "https://grafana.<REDACTED>"
        query_scope:
          clusterID: "{{ name }}"
      prometheus:
        url: https://metrics.<REDACTED>
        health_check_url: https://metrics.<REDACTED>/health
        query_scope:
          cluster: "{{ name }}"
      grafana:
        enabled: true
        auth:
          type: basic
          username: "<REDACTED>"
          password: "secret:grafana-admin-user:admin-password"
        in_cluster_url: 'https://grafana.<REDACTED>'
        url: "https://grafana.<REDACTED>"
        dashboards:
        - name: "Istio Service Dashboard"
          variables:
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            namespace: "var-namespace"
            workload: "var-workload"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
      istio:
        component_status:
          enabled: true
          components:
          - app_label: "istiod"
            is_core: true
            is_proxy: false
            namespace: istio-system
          - app_label: "istio-public-ingressgateway"
            is_core: true
            is_proxy: true
            namespace: istio-ingress
          - app_label: "istio-private-ingressgateway"
            is_core: true
            is_proxy: true
            namespace: istio-ingress
        config_map_name: istio-1-20-1
        istio_sidecar_injector_config_map_name: "istio-sidecar-injector-1-20-1"
        istiod_deployment_name: "istiod-1-20-1"
        istio_canary_revision:
          current: 1-20-1
          upgrade: 1-20-1
    auth:
      strategy: "openid"
      openid:
        client_id: "<REDACTED>"
        issuer_uri: "https://login.microsoftonline.com/<REDACTED>/v2.0"
        api_token: access_token
        disable_rbac: true
    kiali_feature_flags:
      istio_upgrade_action: true
```

**Comment by CmdrSharp** [comment]
Almost immediately after I submitted this, I found that `istio_requests_total` does not have a cluster label. It _should_ - so that's more than a tad confusing. I'll try to figure out why and update the issue with a resolution for future googler's; but this is probably why I'm having issues.

**Comment by CmdrSharp** [comment]
OK, so for some reason, the labels that should be applied to _every metric scraped_ by Victoria Metrics isn't being applied to the Istio metrics. Why is a question for them; but here's an alternative solution to add this specific label with Istio:

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: cluster-name
  namespace: istio-system
spec:
  metrics:
  - overrides:
    - match:
        metric: ALL_METRICS
        mode: CLIENT
      tagOverrides:
        cluster:
          value: upstream_peer.cluster_id
    - match:
        metric: ALL_METRICS
        mode: SERVER
      tagOverrides:
        cluster:
          value: upstream_peer.cluster_id
    providers:
    - name: prometheus
```

Closing this out since it's not an issue with Kiali.
