### ISSUE TITLE
Kiali Server Helm Chart Support Custom NodePort

### ISSUE THREAD

**Issue by emreberber** [kiali/kiali#7093]
### What do you want to improve?

To be able to access the **Kiali** service with a `nodePort` that I specify.

### What is the current behavior?

You give the Service Type as **NodePort** and a random port is assigned.

### What is the new behavior?

Let's add NodePort in Values.yaml and use that port if it is set.

<hr>

In Values, we can get the **nodePort** value as follows

```
server:
  port: 20001
  nodePort: 32475
  observability:
    metrics:
      enabled: true
      port: 9090
      nodePort: 32476
  web_root: ""
```

We can use it in the **Service** as follows,

```
{{- if eq .Values.deployment.service_type nodePort }}
    nodePort: {{ .Values.server.nodePort }}
{{- end }}
```

When Kiali Server is deployed to hundreds of Kubernetes clusters, it would be very good to have this feature to access all clusters with the same nodePort, I am ready to send PR if it is ok for you. 🚀
