### ISSUE TITLE
Kiali operator does not preserve camel case on additional ingress labels

### ISSUE THREAD

**Issue by gurfm** [kiali/kiali#7145]
### Describe the bug

When adding additional ingress labels in the Kiali CR, such as:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
spec:
  deployment:
    ingress:
      additional_labels:
        camelCaseLabel: foo
```

the label names written in camel case are changed to snake case when propagated by the Kiali operator in the Kiali Route resource:

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kiali
  labels:
    camel_case_label: foo
```

### Expected Behavior

Camel case should be preserved:

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kiali
  labels:
    camelCaseLabel: foo
```

### Environment

We reproduced in Openshift 4.13 with OSSM (Maistra) 2.4 and Kiali 1.65, but from what I can see when looking at the kiali-operator code I believe all versions are impacted.

### Proposed fix

Please see PR https://github.com/kiali/kiali-operator/pull/741
