### ISSUE TITLE
[multi-Cluster AuthorizationPolicy] (KIA0106) when namespace SPIFFY is on remote cluster

### ISSUE THREAD

**Issue by michaelalang** [kiali/kiali#7152]
### Describe the bug

with multi-Cluster I noticed one thing in Kiali (NOTE: happens only in multi-Cluster setup)

* one defines it's service (bookinfo app)
* one defines an AuthorizationPolicy granting a SPIFFY of a not configured namespace on the cluster of the Kiali instance
* Kiali will always complain with `KIA0106` even though Istio will grant access accordingly as SPIFFY is handed to the destination namespace

![Kiali-RBAC-SPIFFE-multi-cluster](https://github.com/kiali/kiali/assets/94735640/93fe7ab3-3685-4e15-af3c-f26e3ebb072b)

### Expected Behavior

Kiali could report a warning instead that the SPIFFE cannot be verified due to not being configured locally.

### What are the steps to reproduce this bug?

1. deploy OSSM 2.4.5
2. deploy an AuthorizationPolicy
    ```
    apiVersion: security.istio.io/v1beta1
    kind: AuthorizationPolicy
    metadata:
      name: productpage-viewer
      namespace: bookinfo
    spec:
      rules:
      - from:
        - source:
            principals:
            - cluster.local/ns/west/sa/default
            - cluster.local/ns/east/sa/default
      selector:
        matchLabels:
          app: productpage
    ```
4. Istio will grant permission to access based upon the forwarded SPIFFY headers
    ```
    X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/west/sa/default;Hash=c51856eb61f92f6f9225ae2babdde6568a3a995d6f9e0799c26ccbc68e8f84c0;Subject=\"\";URI=spiffe://cluster.local/ns/east/sa/default"
    ```
### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 1.65.11 (1ec3a2cb167144d803b7f621fe6eb5ff5d79739f)**
- **Istio version: 2.4.5**
- **Kubernetes impl: OCP4.14** 
- **Kubernetes version: v1.27.10+28ed2d7** 
- **Other notable environmental factors: multi-Cluster setup**
