### ISSUE TITLE
Helm chart/operator does not support Adding an Inaccessible Cluster 

### ISSUE THREAD

**Issue by intonet** [kiali/kiali#7187]
### Describe the bug
Providing configuration for inaccessible cluster ( without secret ) for kiali-server helm values causing deployment to mount secrets to pod that not exist and pod Crashloop. 
My values.yaml:
```
clustering:
  clusters:
    - name: west
      accessible: false
  kiali_urls:
    - cluster_name: west
      instance_name: kiali
      namespace: istio-system
      url: https://kiali.monitoring.west.internal.xxx.com
```

When `clustering.clusters `leave unset, then cluster does not show up in kiali. 

### Expected Behavior

When, clustering.clusters.accessible=false or if not provided clustering.clusters.secret_name then secrets should not be mounted. 

### What are the steps to reproduce this bug?

1. Set values for clustering without secret 
2. Install via helm kiali-server

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**  v1.81.0
- **Istio version:**  Istio 1.20.2
- **Kubernetes impl:**  RKE2
- **Kubernetes version:** v1.26.9+rke2r1
- **Other notable environmental factors:** kiali chart 1.81.0
