### ISSUE TITLE
RoleBinding Verification Error in Kiali Operator Despite Correct Configuration

### ISSUE THREAD

**Issue by genfemme** [kiali/kiali#7295]
### Describe the bug

I am encountering an issue while deploying a Kiali Server via a Kiali Custom Resource (CR).
When applying the CR, the operation fails due to an RBAC configuration error, stating that the `kiali-viewer` role cannot be found, despite its existence. Additionally, I discovered that the` kiali-service-account`, which is crucial for Kiali's operation, does not generate any tokens, preventing proper authentication and authorization processes.

 ```
Kubectl get roles -n istio-system
NAME                  CREATED AT
istiod                2022-09-13T09:14:53Z
 istiod-istio-system   2022-09-13T09:13:38Z
kiali-controlplane    2024-04-23T07:11:00Z
 kiali-viewer          2024-04-23T07:10:59Z
```

```
k describe rolebindings.rbac.authorization.k8s.io -n istio-system kiali

 Name:         kiali
 Labels:       app=kiali
               app.kubernetes.io/instance=kiali
               app.kubernetes.io/name=kiali
               app.kubernetes.io/part-of=kiali
               app.kubernetes.io/version=v1.66.1
               version=v1.66.1
 Annotations:  <none>
 Role:
   Kind:  Role
   Name:  kiali-viewer
 Subjects:
   Kind            Name                   Namespace
   ----            ----                   ---------
   ServiceAccount  kiali-service-account  istio-system
```

```
k describe sa -n istio-system kiali-service-account 

Name:                kiali-service-account
Namespace:           istio-system
Labels:              app=kiali
                     app.kubernetes.io/instance=kiali
                     app.kubernetes.io/name=kiali
                     app.kubernetes.io/part-of=kiali
                     app.kubernetes.io/version=v1.66.1
                     version=v1.66.1
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

Error Message with 

> kubectl get kiali kiali -n istio-system -o jsonpath='{.status}'

```
  "lastTransitionTime": "2024-04-23T10:08:34Z",
      "message": "RoleBinding kiali: Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"roles.rbac.authorization.k8s.io \\\\\"kiali-viewer\\\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"kiali-viewer\",\"group\":\"rbac.authorization.k8s.io\",\"kind\":\"roles\"},\"code\":404}\\n'",
     "reason": "Failed",
     "status": "True",
     "type": "Failure"
  }

```

### Expected Behavior

The Kiali operator should successfully acknowledge and utilize the existing `kiali-viewer` role to configure the RoleBinding as specified in the CR. The `kiali-service-account `should automatically generate tokens upon creation.

### Environment
Kiali Operator version: 1.83.0
Istio version: 1.17.4
Kubernetes implementation: EKS
Kubernetes version: 1.28.3

**Comment by jmazzitelli** [comment]
Please provide actual replication procedures. Exactly what did you run (the commands to execute) in order to install the operator and Kiali server, and please indicate what the Kiali CR actually looks like.

I suspect this is not a bug. But without knowing exactly how this was installed, I can't tell.

Note also regarding this: `I discovered that the kiali-service-account, which is crucial for Kiali's operation, does not generate any tokens` - that isn't anything Kiali or its operator controls. Your k8s cluster should be generating the tokens for the service account.

**Comment by genfemme** [comment]
@jmazzitelli 

I used the following Helm values and included the Custom Resource (CR) definition as shown below, but the installation did not proceed as expected:

```

  application_name: kiali
  namespace: kiali-operator
  server: https://kubernetes.default.svc
  project_name: default
  chart:
    repository: https://kiali.org/helm-charts
    version: 1.66.1
  cr:
    namespace: istio-system
    name: kiali
    create: true
    spec:
      auth:
        strategy: "token"
      deployment:
        accessible_namespaces: [".*"]
        view_only_mode: false
      server:
        web_root: "/kiali"
      external_services:
        custom_dashboards:
          prometheus:
            url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
          grafana:
            url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"'

```      
  
            
 Therefore I had to apply the CR manually using kubectl apply. Here are the details of that CR:
  
  ```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: "token"
  deployment:
    accessible_namespaces: [".*"]
    view_only_mode: false
  server:
    web_root: "/kiali"
  external_services: 
     custom_dashboards:
       prometheus:
        url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
       grafana:
        url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
```
