### ISSUE TITLE
Kiali fails to watch Gateway due to `spec.servers[*].tls.mode: OPTIONAL_MUTUAL` setting

### ISSUE THREAD

**Issue by ngearhart** [kiali/kiali#7315]
### Describe the bug

When an Istio gateway has `spec.servers[*].tls.mode: OPTIONAL_MUTUAL`, Kiali will output the following then crash:

```
W0426 19:43:42.905227       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1beta1.Gateway: unknown value "\"OPTIONAL_MUTUAL\"" for enum istio.networking.v1beta1.ServerTLSSettings.TLSmode
E0426 19:43:42.905254       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1beta1.Gateway: failed to list *v1beta1.Gateway: unknown value "\"OPTIONAL_MUTUAL\"" for enum istio.networking.v1beta1.ServerTLSSettings.TLSmode
```

### What are the steps to reproduce this bug?

1. Create an Istio Gateway with `spec.servers[*].tls.mode: OPTIONAL_MUTUAL` enabled. For example:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public
  namespace: istio-system
spec:
  selector:
    app: public-ingressgateway
  servers:
  - hosts:
    - example.com
    port:
      name: https
      number: 8443
      protocol: HTTPS
    tls:
      caCertificates: /etc/certs/ca.crt
      mode: OPTIONAL_MUTUAL
      privateKey: /etc/certs/tls.key
      serverCertificate: /etc/certs/tls.crt
```
2. Run Kiali.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.82.0
- **Istio version:** 1.20.4
- **Kubernetes impl:** RKE2 with Canal
- **Kubernetes version:** 1.27.6+rke2r1
- **Other notable environmental factors:** N/A
