### ISSUE TITLE
[molecule] config-values-test fails when run on KinD

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7330]
This passes on OpenShift and minikube, but it failed when our GH Action ran the test on KinD.

```
TASK [If we are NOT configured with NodePort as service type, make sure there is no nodePort in the service] ***
fatal: [localhost]: FAILED! => {
    "assertion": "http_port.nodePort is not defined",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Comment by jmazzitelli** [comment]
I think the test assumption is incorrect. The test assumes if the service type is LoadBalancer on KinD that there will be no nodePort defined on the kiali service's spec.ports[name=http]. But there is. This is what I see:

Kiali CR:
```yaml
spec:
  deployment:
    service_type: LoadBalancer
```

Kiali ConfigMap (just mimics what we see in the Kiali CR):
```yaml
data:
  config.yaml: |
    deployment:
      service_type: LoadBalancer
```

The Kiali Service:
```yaml
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.12.208
  clusterIPs:
  - 10.96.12.208
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 31711       <====== THIS WAS UNEXPECTED
    port: 20001
    protocol: TCP
    targetPort: 20001
  - appProtocol: http
    name: http-metrics
    nodePort: 31503       <====== THIS WAS UNEXPECTED
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.18.255.71
```

I am unsure if this is simply KinD behavior that is expected or perhaps this is truly a bug and the operator is creating the nodePort when it should not. I think it is the former but I will double check. If this really is simply a bad test assumption, the fix is simple and need only be made to the test.

**Comment by jmazzitelli** [comment]
It does look like KinD simply defines a nodePort always. I create a Kiali CR with this:
```yaml
spec:
  deployment:
    accessible_namespaces:
    - '**'
    image_name: quay.io/kiali/kiali
    image_version: latest
    namespace: istio-system
    service_type: LoadBalancer
  istio_namespace: istio-system
  version: default
```

and the service becomes this (notice `nodePort` is defined in both ports):
```yaml
...
spec:
  ports:
  - appProtocol: http
    name: http
    nodePort: 31274
    port: 20001
    protocol: TCP
    targetPort: 20001
  - appProtocol: http
    name: http-metrics
    nodePort: 31015
    port: 9090
    protocol: TCP
    targetPort: 9090
```

The operator never even creates a nodePort for the http-metrics port, only for the main http port. So we know it didn't create that. And this is the template code the operator uses to determine if nodePort should be created:
```jinja
{% if kiali_vars.deployment.service_type is defined and kiali_vars.deployment.service_type == "NodePort" and kiali_vars.server.node_port is defined %}
    nodePort: {{ kiali_vars.server.node_port }}
{% endif %}
```
And the deployment.service_type in my Kiali CR is not "NodePort" (it is "LoadBalancer") so the operator isn't creating the nodePort here either.

So I will fix this test so it will skip this nodePort checking if on KinD.
