### ISSUE TITLE
Allow configuring additional environment variables in Kiali

### ISSUE THREAD

**Issue by jdgeisler** [kiali/kiali#7375]
### What do you want to improve?

We noticed CPU throttling in Kiali due to GOMAXPROCS not being configured correctly. In order to fix this, we had to set the GOMAXPROCS environment variable in Kiali, however the helm chart currently does not have the ability to set additional environment variables.

### What is the current behavior?

The current behavior is that there is no way to configure additional environment variables in Kiali that might be needed.

### What is the new behavior?

The intended new behavior is that additional environment variables can be set in the Kiali helm chart.

Like so:

```
extraEnvs:
  - name: GOMAXPROCS
    value: "2"
  - name: test
    value: "true"
```

```
env:
- name: ACTIVE_NAMESPACE
   valueFrom:
     fieldRef:
       fieldPath: metadata.namespace
- name: LOG_LEVEL
   value: "info"
- name: LOG_FORMAT
   value: "text"
- name: LOG_TIME_FIELD_FORMAT
   value: "2006-01-02T15:04:05Z07:00"
- name: LOG_SAMPLER_RATE
   value: "1"
- name: GOMAXPROCS
   value: "2"
- name: test
   value: "true"
```
