### ISSUE TITLE
Kiali 1.85.0 - Istio 1.22 : display istio resources V1 as V1Beta1

### ISSUE THREAD

**Issue by sbcp-training** [kiali/kiali#7398]
### Describe the bug

With Istio 1.22.0 a lot of resources as VS, DR, SE have been released in version V1. If we install the Kiali as addons with the helm chart in version 1.85.0, the istio resources are displayed in the Kiali UI with the version V1Beta1.
If we get the istio resources with the kubectl get vs, dr, se -A the version of all resources are V1.

### Expected Behavior
The version of the Istio resources displayed in the Kiali UI should be V1 and not V1Beta1

### What are the steps to reproduce this bug?

1. Install Istio in version 1.22.0
2. Install Kiali with the helm chart in version 1.85.0
3. Deploy a SE as below in your cluster:
```yaml
kind: ServiceEntry
apiVersion: networking.istio.io/v1
metadata:
  name: keycloak
  namespace: my-ns
spec:
  hosts:
    - identity.my-ns.xxxxxxx
  ports:
    - number: 443
      protocol: HTTPS
      name: https
  resolution: DNS
  exportTo:
    - .
```
4. If you get the resource with kubectl get service-entry keycloak -n my-ns -oyaml
You see the good version V1 for the resources.
5. In the Kiali, in the Istio Config tab, if you select the same resource, the version displayed to the top will be v1beta1
![image](https://github.com/kiali/kiali/assets/77682494/94a4cc62-a447-470b-836b-a878830cbbb5)

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 1.85.0 **
- **Istio version: 1.22.0 **
- **Kubernetes impl: EKS** 
- **Kubernetes version: 1.29**
