### ISSUE TITLE
The apiVersion value is not provided by istio/config API when the Istio object is created outside of Kiali

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#7452]
### Describe the bug

If you create any Istio object using `kubectl`, Kiali does not provide the `apiVersion` value of that Istio object when the Istio config list API is called by the application.

### Expected Behavior

Kiali has to provide `apiVersion` value of all Istio config items.

### What are the steps to reproduce this bug?

1. Create any Istio config object from kubectl, for example this simple AuthorizationPolicy:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: test
  namespace: bookinfo
  labels: {}
  annotations: {}
spec: {}
```
2. From your browser, open the Network section of Chrome/Firefox Dev Tools (click F12 + Network tab)
3. Navigate to the `Istio Config` page
4. In the Network tab section, click on the request `config?validate=true`
5. Verify that the `apiVersion` value of the AuthorizationPolicy is not present in the response

![image](https://github.com/kiali/kiali/assets/122779323/765709d9-b943-4991-aaee-4eb7deef442f)

### Environment

- **Kiali version:** 1.86
- **Istio version:** 1.22
- **Kubernetes impl:** OpenShift CRC
- **Kubernetes version:** 1.28
