### ISSUE TITLE
Kiali does not honour the OIDC groups 

### ISSUE THREAD

**Issue by anannaya** [kiali/kiali#7472]
We use the OIDC groups for authenticating/Authorising the kubernetes  resource access.  Something like 
_([jmazzitelli] I edited to use the proper triple-tick marks for proper yaml formatting)_
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-ro-oidc-groups-rolebinding
  namespace: ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ai-ro
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidcxxxxxxx.com
  namespace: default
```

And we use oauth2-proxy for authentication and passing it as a Authorizaion header in the request.  And it is working fine kiali `header` strategy  as well.  Only problem is Authorization does not happen with Groups configured . User is able to see the istio-config resources on other namespaces.
