### ISSUE TITLE
Grafana version checks don't use configured Grafana auth

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7475]
The version checks for Grafana don't use the configured Grafana auth: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.grafana.auth. These options should be used when checking the version.

### Discussed in https://github.com/kiali/kiali/discussions/7470

<div type='discussions-op-text'>

<sup>Originally posted by **llTimKramer** June 25, 2024</sup>
Hi,

I'm experiencing an issue with connecting Kiali to an external Grafana instance, which is publicly accessible but located in a different Kubernetes cluster. When authentication is enabled in Grafana, I receive a status 401 error. However, with anonymous access, everything works correctly. I’ve tried both basic authentication and bearer token methods, but both result in the same 401 error:

`logger=context userId=0 orgId=0 uname= t=2024-06-25T16:54:51.778872076Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=<IP> traceID=`

`logger=context userId=0 orgId=0 uname= t=2024-06-25T16:54:51.778958955Z level=info msg="Request Completed" method=GET path=/api/frontend/settings status=401 remote_addr=<IP> time_ms=0 duration=217.938µs size=102 referer= handler=/api/frontend/settings/ status_source=serve`

Kiali is deployed with the Kiali-operator. The Operator was installed with helm with default values.

Here are the relevant spec fields in the Custom Resource (CR):
_([jmazzitelli] I updated this by wrapping in triple-ticks so github will format the yaml properly, thus we can see the indentation and the values easier)_
```yaml
spec:
  auth:
    strategy: token
  deployment:
    accessible_namespaces:
    - '**'
  external_services:
    grafana:
      auth:
        password: secret:grafana-pw:password
        type: basic
        username: kiali
      dashboards:
      - name: Istio Service Dashboard
        variables:
          namespace: var-namespace
          service: var-service
      - name: Istio Workload Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
      - name: Istio Mesh Dashboard
      - name: Istio Control Plane Dashboard
      - name: Istio Performance Dashboard
      - name: Istio Wasm Extension Dashboard
      enabled: true
      url: https://<grafana-url>
```

I successfully queried the Grafana API within the cluster using both basic authentication and a bearer token. Despite this, I still encounter the 401 error when accessing through Kiali with authentication enabled.

Could you please assist in identifying the cause of this error and suggest a solution?

Thank you!
Tim

</div>

**Comment by jshaughn** [comment]
Hi @llTimKramer , this is a community project and there are no real support-level commitments on timeline.  Having said that, The hope would be in one of the next two releases.  So, hopefully by end of July.

**Comment by llTimKramer** [comment]
Hi @jshaughn,
I was aware that this is a community project but I was asked this question in our internal round and I thought I give it a try :) 

Thanks for the estimate and your great work!

**Comment by josunect** [comment]
I think even if Grafana is authenticated the check URLs doesn't need to be. For example, in Grafana cloud the check url is exposed in a different path which is unauthenticated.

I think we could use a config item to indicate if the check URL is authenticated or not.

Also, probably Prometheus and Jaeger would need to have the same behavior, I think.

**Comment by hchan** [comment]
I'm experiencing the same issue in v2.22.0
```
2026-01-08T08:15:42Z INF grafana version check failed: url=[https://grafana-pgplus-dev-byhsdhbkfhfcf3h0.eus2.grafana.azure.com//api/frontend/settings], code=[401]

```

**Comment by jmazzitelli** [comment]
> I'm experiencing the same issue in v2.22.0

There is no v2.22.0 right now - [latest version](https://github.com/kiali/kiali/releases) is v2.20.0 - look at the Kiali server pod logs (one of the first lines that are output) and see what version it says it is.

**Comment by hchan** [comment]
My bad ... mistype, I'm on v2.20.0

```
2026-01-08T16:27:31Z INF Kiali: Version: v2.20.0, Commit: 1d67614d370d83fd9b31074f3dff7471393ce1d2, Go: 1.24.4
```

**Comment by jshaughn** [comment]
@hchan, did you define the auth section in the config? See https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/#grafana-authentication-configuration

**Comment by hchan** [comment]
Yes, I was using `bearer` auth.  FYI, my Grafana is Azure Managed Grafana

**Comment by josunect** [comment]
@hchan what settings are you using? 

I've just tested it successfully with: 

```  
  grafana:
    enabled: true
    internal_url: INTERNAL_URL
    external_url: EXTERNAL_URL
    auth:
      type: bearer
      use_kiali_token: false
      token: mytoken
```

Or, it can be a secret as well: https://kiali.io/docs/faq/installation/#how-can-i-use-a-secret-to-pass-external-service-credentials-to-the-kiali-server
