### ISSUE TITLE
Move to node 20

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#7503]
### What do you want to improve?
Move node engine to node 20
```yaml
"engines": {
    "node": ">=20.0.0",
    "yarn": ">=1.0.0"
  }
```

![image](https://github.com/kiali/kiali/assets/3019213/1d897f83-82a1-4505-a457-4adfa2c2414f)

### What is the current behavior?

Project is using node 18

### What is the new behavior?

Use node 20
