### ISSUE TITLE
Kiali Graph showing incorrectly when we create Multiple Service entry with same hosts and different port

### ISSUE THREAD

**Issue by maneeshcdls** [kiali/kiali#7537]
### Describe the bug

I have created the below service entries 

_([jmazzitelli] I added the "```" markers below so the yaml is properly formatted by github)_
```yaml
FileServer :-
Metadata
  name: fileserver-serviceentry
spec:
  exportTo:
    - .
  hosts:
    - vm.test.local
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS

 RabbitMQ :-
 Metadata
  name: rmqserver-serviceentry
 spec:
  exportTo:
    - .
  hosts:
    - vm.test.local
  location: MESH_EXTERNAL
  ports:
    - name: amqp
      number: 15672
      protocol: HTTP
  resolution: DNS

 SQL server :-
 Metadata
  name: sqlserver-serviceentry
 spec:
  exportTo:
    - .
  hosts:
    - vm.test.local
  location: MESH_EXTERNAL
  ports:
    - name: tcp
      number: 1433
      protocol: TCP
  resolution: DNS
  ```

  after deploying this service entry on checking the traffic graph the edges go to sqlserver and then a refresh shows all edges going to rmqserver then a refresh is shows going to fileserver 
  
![image](https://github.com/user-attachments/assets/586474ca-31ca-477f-85d3-11230561231a)
![image](https://github.com/user-attachments/assets/8eadad82-1c5d-4bff-bde7-6b9b4e4ed40d)

I used time frame as 7 days and still showing same issue. not sure if kiali is separating service entries based on port

### Expected Behavior

Kiali should show edges to correct service entry

### What are the steps to reproduce this bug?

1. Create multiple service entry with same host and different ports
2. check kiali edges showing properly
3. …

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: V1.85
- **Istio version: 1.20
- **Kubernetes impl: Azure kubernetes
- **Kubernetes version: 1.28.3
