### ISSUE TITLE
VirtualService validation error "All routes should have weight" when the weights are 100/0

### ISSUE THREAD

**Issue by amyroh** [kiali/kiali#754]
**Describe the bug**
VirtualService "All routes should have weight" validation error happens when the weights are 100/0 (pretty common use case)

```
    http:
      route:
      - destination:
          host: ratings.default.svc.cluster.local
          subset: subset1
        weight: 100
      - destination:
          host: ratings.default.svc.cluster.local
          subset: subset2
```
Weight is `json:"weight,omitempty` and 0 value will not be included.  

```
type DestinationWeight struct {
	// REQUIRED. Destination uniquely identifies the instances of a service
	// to which the request/connection should be forwarded to.
	Destination *Destination `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	// REQUIRED. The proportion of traffic to be forwarded to the service
	// version. (0-100). Sum of weights across destinations SHOULD BE == 100.
	// If there is only destination in a rule, the weight value is assumed to
	// be 100.
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}
```

business/checkers/virtual_services/route_checker.go

```
                if weightCount > 0 && weightCount != destinationWeights.Len() {
                        valid = false
                        path := fmt.Sprintf("spec/%s[%d]/route", kind, routeIdx)
                        validation := buildValidation("All routes should have weight", "error", path)
                        validations = append(validations, &validation)
                }
```

The validation code should be updated to consider the case where one of the weights is 0.

**Comment by abonas** [comment]
@lucasponce @xcanalma fyi

**Comment by abonas** [comment]
@xeviknal

**Comment by hhovsepy** [comment]
In the case when "0" is explicitly set to weight, the overview page does not show error and looks like this:
![screenshot from 2018-12-21 11-45-26](https://user-images.githubusercontent.com/604313/50339987-5f239700-0519-11e9-82bd-099cc95f5538.png)

**Comment by xeviknal** [comment]
@amyroh first of all, thanks for opening an issue and contribute to make kiali better :top:  

After some research, I see that Istio allows to have DestinationWeights without weight if and only if the sum of the actual destinations is equal to 100. e.g. the following case is working alright:

```yaml
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: 90
        - destination:
            host: reviews
            subset: v2
        - destination:
            host: reviews
            subset: v3
          weight: 10
```

But the following one isn't:

```yaml
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: 10
        - destination:
            host: reviews
            subset: v2
        - destination:
            host: reviews
            subset: v3
          weight: 50
```
In this latest scenario, Istio is sending the traffic to subset `v1`.

Then I understand that we can remove the alert of 'All routes should have weight' since the alert 'Sum of the weight should be 100' is prevalent.

good point @amyroh !

cc/ @pilhuhn @lucasponce @burmanm
