### ISSUE TITLE
Kiali operator helmchart frequently changes the replica count when HPA is enabled

### ISSUE THREAD

**Issue by rkadam-infracloud** [kiali/kiali#7559]
### Describe the bug

When HPA is enabled in Kiali Operator helm chart CR after removing the `replicas` parameter, the number of replica continously bounce between 1 and min_replica count in HPA. 

### Expected Behavior
If HPA is enabled, it should set to min count and then add replica when the threshold is crossed by pods.

### What are the steps to reproduce this bug?

1. Install Kiali operator helm chart, initialy without HPA and replica count as 3
2. Remove replicas parameter and add HPA with min 3 and max 6 replica, any setting for CPU or memory threshold. At this point the CR looks like this
```
cr:
  create: true
  namespace: kiali-operator
  spec:
    deployment:
      hpa:
        spec:
          maxReplicas: 6
          minReplicas: 3
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 70
      resources:
        requests:
          memory: "1Gi"
        limits: 
          memory: "2Gi"
    istio_namespace: istio-system
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: "http://prometheus-server.prometheus:80/"
      tracing:
        enabled: false
      grafana:
        enabled: false
```
3. ideally the replica count should match min replica count in HPA. However, what actually happens is the replica count fluctuates continuously between 1 and 3

### Environment
Found this issue on argocd managed setup, but can be replicated with minikube too

- **Kiali version:** v1.83.0
- **Istio version:** 1.21.2
- **Kubernetes impl:**  v1.30.1
- **Kubernetes version:** v1.30.1
- **Other notable environmental factors:** Istio 1.21.2
