### ISSUE TITLE
[helm chart] - cis-k8s-v1.5.1 compliance - kiali ClusterRole has rule with wildcard match

### ISSUE THREAD

**Issue by lesaux** [kiali/kiali#7637]
### What do you want to improve?
 The helm chart Kiali ClusterRole is using :
 ```
 - apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - gateway.networking.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  ```

### What is the current behavior?

``` resources: ["*"]```
 is not allowed in a cis-k8s-v1.5.1 compliant cluster

### What is the new behavior?
can we better inventory the list of resources for these apiGroups?
