### ISSUE TITLE
External Links of Custom dashboard not visible

### ISSUE THREAD

**Issue by jmueducn** [kiali/kiali#7638]
### Describe the bug

I am testing the custom dashboard feature in Kiali, but the External Links that should appear within the custom dashboard are not visible. I have configured everything as per the documentation, including setting up the necessary dashboards in Grafana and annotating the StatefulSets, but the links do not show up in the Kiali dashboard.
https://github.com/kiali/kiali/discussions/7630
### Expected Behavior

The external links should be visible in the Kiali custom dashboard.

### Configuration

```
 custom_dashboards:
  - discoverOn: envoy_server_uptime
    externalLinks:
    - name: newdashboard
      type: grafana
    items:
    - chart:
        dataType: raw
        metricName: envoy_server_uptime
        name: Pods uptime
        spans: 12
    name: grafana-test
    runtime: GRAFANA
    title: Grafana metrics
```

### What are the steps to reproduce this bug?

1.Add the custom dashboard configuration as provided above.
2.Annotate the StatefulSets with kiali.io/dashboards: grafana-test.
3.Access the custom dashboard in Kiali.
![g1](https://github.com/user-attachments/assets/fbb3c074-e8e4-4419-a783-2082e3747d81)

### Environment

- **Kiali version: v1.67.0**
- **Istio version: 1.18.0**
- **Kubernetes impl: k3s1** 
- **Kubernetes version: v1.23.8** 
- **Other notable environmental factors: Prometheus:2.43.0**

**Comment by jmazzitelli** [comment]
Do you need to configure Grafana in a certain way to add some new dashboard in it?

**Comment by jmueducn** [comment]
> Do you need to configure Grafana in a certain way to add some new dashboard in it?

I think there is no need, add dashboard in Grafana UI is ok.

**Comment by hhovsepy** [comment]
The fix will be released with upcoming Kiali v1.89.1.

And for having External Links in Custom dashboards, there should be `variables:` in `externalLinks:`, like this:
```
    externalLinks:
    - name: newdashboard
      type: grafana
      variables:
        namespace: "var-namespace"
        service: "var-service"
        workload: "var-workload"
```
Note that for External Links in Application's Custom dashboards, there should be also a variable `app: "var-app"` and the `app` variable should exist on Grafana's custom dashboard as well.
Anyway, the custom dashboard "newdashboard" should exist on Grafana side.

In previous released versions of Kiali, when `variables:` are in `externalLinks:` configuration and Custom dashboard is also created on Grafana side, the External Links are displayed, but there is an issue with `app` and `workload` variables set in a link.
