### ISSUE TITLE
Valid Virtual Service Definition Fails Config Validation

### ISSUE THREAD

**Issue by daaasbu** [kiali/kiali#764]
**Describe the bug**
It appears that Kiali is failing to validate a virtual service. I modified the virtual service from the tutorial for accessing google over https. It appears to be working from the istio side of things just fine but is failing the validation in the UI. I'm also not sure if this is the reason it is not showing the graph view as well.

https://istio.io/docs/tasks/traffic-management/egress/#make-requests-to-the-external-services

![virtual service error](https://user-images.githubusercontent.com/7543162/50521882-90f2ab80-0a8d-11e9-951e-878c734cab72.png)  
  
The error displayed is:  
*VirtualService doesn't define any route protocol.*  

**Versions used**
kiali-ui 0.6.0 (7ebeee3bec89b26235995d393ad99908b8fdb470)  
kiali v0.6.0 (23643f7f6a099041692205ba5affa7b3a91cabdd)  
Components  
Istio 1.0.0  
Prometheus 2.3.1  
Kubernetes v1.10.9-gke.5  

**To Reproduce**

Here is the virtual service yaml file. when using kubectl describe, it outputs what you would expect, but when displayed in the kiali UI it cuts off after host.   
  ```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: avalara
spec:
  hosts:
  - sandbox-rest.avatax.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - sandbox-rest.avatax.com
    route:
    - destination:
        host: sandbox-rest.avatax.com
        port:
          number: 443
      weight: 100
```

**Expected behavior**
No validation error and the entire virtual service definition is shown.
