### ISSUE TITLE
[kiali-server helm chart] Add extra YAML objects

### ISSUE THREAD

**Issue by micolun** [kiali/kiali#7653]
### What do you want to improve?
It would be nice to be able to include extra objects through Kiali's helm values (e.g. istio gateway, istio virtual services)

### What is the current behavior?
Currently, extra objects are not supported in `kiali-server` helm chart, version `1.88.0`

### What is the new behavior?
The new behaviour would allow including extra YAML manifests through helm values:
example:

```yaml
# values.yaml
extraObjects:
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: kiali-gateway
      namespace: istio-system
---
# extra-list.yaml
{{- range .Values.extraObjects }}
---
{{ tpl (. | toYaml) $ }}
{{- end }}
```
or 
```yaml
# values.yaml
extraManifests:
  - |
    apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: kiali-gateway
      namespace: istio-system
---
# extra-manifest.yaml
{{ range .Values.extraManifests }}
---
{{ tpl . $ }}
{{ end }}

```
