### ISSUE TITLE
Kiali display "No inbound traffic"

### ISSUE THREAD

**Issue by erictarrence** [kiali/kiali#7660]
I have two questions after installing Kiali.
Why does it show No inbound traffic when the default namespace pod has sidecar installed?
Why does the number of applications shown in the monitor namespace show 0?

Kiali: Version: v1.87.0
Istio: Version: v1.23.0
kubernetes Version: v1.30.0

Kiali cm information is as follows:
```
    external_services:
      prometheus:
        # Prometheus service name is "metrics" and is in the "telemetry" namespace
        url: "http://prometheus-k8s.monitoring:9090/"
    external_services:
      grafana:
        enabled: true
        in_cluster_url: 'http://grafana.monitoring:3000/'
        # Public facing URL of Grafana
        url: 'http://grafana.monitoring:3000/'
    external_services:
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: istio-system
        component_status:
          enabled: true
          components:
          - app_label: "istiod"
            is_core: true
            is_proxy: false
          - app_label: "istio-ingressgateway-external"
            is_core: true
            is_proxy: true
            # default: namespace is undefined
            namespace: istio-ingress
      tracing:
        enabled: false
```
        
service/pod information is as follows:

```
gateway

# kubectl -n istio-ingress get svc --show-labels 
NAME            TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)                                      AGE    LABELS
gateway-istio   NodePort   172.23.6.13   <none>        15021:31162/TCP,80:32566/TCP,443:30138/TCP   2d3h   app=istio-ingressgateway-external,gateway.istio.io/managed=istio.io-gateway-controller,gateway.networking.k8s.io/gateway-name=gateway,istio.io/gateway-name=gateway

# kubectl -n istio-ingress get pod --show-labels 
NAME                            READY   STATUS    RESTARTS   AGE   LABELS
gateway-istio-58dddb66d-q47ns   1/1     Running   0          18m   app=istio-ingressgateway-external,gateway.networking.k8s.io/gateway-name=gateway,istio.io/gateway-name=gateway,pod-template-hash=58dddb66d,service.istio.io/canonical-name=gateway-istio,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=false
gateway-istio-58dddb66d-r4ggx   1/1     Running   0          18m   app=istio-ingressgateway-external,gateway.networking.k8s.io/gateway-name=gateway,istio.io/gateway-name=gateway,pod-template-hash=58dddb66d,service.istio.io/canonical-name=gateway-istio,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=false


default namespace

 kubectl get pod
NAME                                    READY   STATUS    RESTARTS        AGE
bookinfo-gateway-istio-d88664b9-rjx7t   1/1     Running   0               2d5h
busybox                                 1/1     Running   142 (19m ago)   5d22h
details-v1-65cfcf56f9-6mx7f             2/2     Running   0               2d6h
httpbin-648f469544-l7r8h                1/1     Running   0               2d3h
productpage-v1-d5789fdfb-zss6t          2/2     Running   0               2d6h
ratings-v1-7c9bd4b87f-pfjwc             2/2     Running   0               2d6h
reviews-v1-6584ddcf65-bcx6t             2/2     Running   0               2d6h
reviews-v2-6f85cb9b7c-tkd7t             2/2     Running   0               2d6h
reviews-v3-6f5b775685-2n9mz             2/2     Running   0               2d6h
sleep-5577c64d7c-cc8m4                  1/1     Running   0               22h

```

![image](https://github.com/user-attachments/assets/27a0c2b8-662e-4d7b-88f3-368a3977ae26)
