### ISSUE TITLE
Virtualservice's FQDN gateway validation error:"virtualservice is pointing to a no-existing gateway"

### ISSUE THREAD

**Issue by dreadbird** [kiali/kiali#767]
**General remarks**
The gateway `default` is created at namespace: `istio-system`,and the virtualservice is created at other namespaces.So,we used FQDN,like:`default.istio-system.svc.cluster.local`to describe the gateway which the virtualservice related.

**Describe the bug**
The gateway is created at ns: `istio-system`
```
apiVersion: networking.istio.io/v1alpha3                                                                                                                                                                                                                                      
kind: Gateway                                                                                                                                                                                                                                                                 
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  name: default                                                                                                                                                                                                                                                               
  namespace: istio-system"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.xip.io'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.xip.io'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

and the virtualservice yaml:

```
name: cas-service
createdAt: '2018-11-30T07:17:43Z'
resourceVersion: '22902650'
hosts:
  - service.inspurcloud.cn
gateways:
  - default.istio-system.svc.cluster.local
http:
  - match:
      - uri:
          prefix: /cas
    route:
      - destination:
          host: cas-service.cas.svc.cluster.local
          subset: stable
    timeout: 60s
  - match:
      - headers:
          cookie:
            regex: ^(.*\s*)?(cas-canary)(.*)?$
        uri:
          prefix: /cas
    route:
      - destination:
          host: cas-service.cas.svc.cluster.local
          subset: canary
    timeout: 60s
```

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/2113395/50571006-acd1b680-0dd9-11e9-9b34-db3f1bc95e08.png)

**Versions used**
Kiali:0.9
Istio:1.0.4
Kubernetes flavour and version: v1.11
