### ISSUE TITLE
Validations - Inconsistency between List and Details pages

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7685]
### Describe the bug

Istio Config Validations have inconsistency between List and Details pages when Istio Config objects have 'exportTo'.
Or when default mesh exported to local namespace.
This issue happens because Istio Config list calls validations for all namespaces, so the 'exportTo' per config is ignored.

### Expected Behavior
Validations should be consistent in all places.

### What are the steps to reproduce this bug?

1. Create 'bookinfo' and 'bookinfo2' namespaces.
2. In each of namespaces create any object with 'exportTo: .', for instance DR 
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: all.googleapis.com
spec:
  host: '*.googleapis.com'
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing www.googleapis.com
  exportTo:
  - '.'
```
3. See that List page shows validation warning (which is wrong, because those objects should not interact as both exported to own namespace), but the details page does not (which is correct).
![Screenshot from 2024-08-30 11-29-07](https://github.com/user-attachments/assets/a1b08873-9e69-4b58-b4ff-890c0ebc5229)
![Screenshot from 2024-08-30 11-28-47](https://github.com/user-attachments/assets/1e5304e3-7580-40ba-ab28-9ace5a445d05)

The same inconsistency is in Overview page.

### Environment

- **Kiali version: 1.90 snapshot, and v1.89, probably even older versions**
- **Istio version: 1.23**
