### ISSUE TITLE
Istio validations inconsisteny - exported to other namespace

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7690]
### Describe the bug

Istio config details page validations are not executed for 2 objects which are exported to different namespace.

### Expected Behavior
Even if Istio configs are exported to another namespaces, the validations should be done.

### What are the steps to reproduce this bug?

1. Create 'bookinfo' and 'bookinfo2' namespaces.
2. In 'bookinfo' create 2 DRs with different names but similar content both exporting to 'bookinfo2'
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: test
spec:
  host: '*.googleapis.com'
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing www.googleapis.com
  exportTo:
  - 'bookinfo2'
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: test2
spec:
  host: '*.googleapis.com'
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing www.googleapis.com
  exportTo:
  - 'bookinfo2'
  ```
3. You will see validation warning in list page, which is correct.
![Screenshot from 2024-08-30 18-23-14](https://github.com/user-attachments/assets/fe6c48fa-1853-442a-9ce9-34458c499490)
But not in a details page, which is bug.

### Environment

- **Kiali version: v1.90 snapshot, and v1.89, probably even older versions**
- **Istio version: 1.23, probably even older versions**
