### ISSUE TITLE
Discovery selectors use case 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7751]
### What do you want to improve?
The Kiali behavior when the discovery selectors doesn't include a namespace that is part of the mesh?

For example:
```
service mesh has namespaces A, B, C, istio-system.
I want Kiali instance X to only see A, istio-system.
I want Kiali instance Y to only see B, istio-system.
I want Kiali instance Z to only see C, istio-system.
```

### What is the current behavior?
In this example, bookinfo is part of the Mesh, but discovery selectors are not finding the namespace: 
```
deployment:
  discovery_selectors:
    default:
    - matchLabels:
        abc: def
        uvw: xyz
  view_only_mode: false
  cluster_wide_access: true
```
![image](https://github.com/user-attachments/assets/29c3f903-6d2f-4ad8-8a40-14c15b4de7d5)

![image](https://github.com/user-attachments/assets/d20eb06c-8f3d-450e-937c-197a3d7bb91b)

### What is the new behavior?
I think both views should be consistent, if user is able to see the bookinfo namespace in the Mesh view, probably also in the Overview, and not throwing an error.
