### ISSUE TITLE
Linearly increasing memory usage (Kiali v1.86.2, Istio 1.22.5, K8s 1.29.8)

### ISSUE THREAD

**Issue by freefood89** [kiali/kiali#7800]
### Describe the bug

Memory and CPU usage of kiali increases linearly over time

### Expected Behavior

I expect memory usage to correlate with UI usage or k8s usage, but not grow unbounded

### What are the steps to reproduce this bug?

1. Deploy Kiali operator
2. Deploy Kiali

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  external_services:
    prometheus:
      url: ***
  auth:
    strategy: anonymous
  deployment:
    view_only_mode: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 1Gi
```

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** v1.86.2 (e44498e9cab23ade6b82b1033d9860d1c32ecc19)
- **Kiali operator helm chart:** 1.86.2
- **Istio version:**  1.22.5
- **Kubernetes impl:** GKE
- **Kubernetes version:** v1.29.8-gke.1211000

![Screenshot 2024-10-08 at 7 41 27 PM](https://github.com/user-attachments/assets/d454f94a-96f7-4fc7-8a71-f73bcafe7def)

**Comment by nrfox** [comment]
Are you able to enable pprof to get a better view of what's causing the resource usage? I can't find where it's documented but you can follow the instructions here: https://github.com/kiali/kiali/pull/7105#issue-2123590924.

**Comment by jshaughn** [comment]
@ScriptingShrimp , Is this something you could test by establishing a long-running kiali instance, running probably bookinfo, and monitor the memory?  We may want to add the pprop go instrumentation (see Mazz for details)?

**Comment by freefood89** [comment]
> Are you able to enable pprof to get a better view of what's causing the resource usage? I can't find where it's documented but you can follow the instructions here: https://github.com/kiali/kiali/pull/7105#issue-2123590924.

Sorry I just saw this. I will remind myself to try it out within a week

**Comment by ScriptingShrimp** [comment]
Hello @freefood89 ,
currently I have no access to GKE but can try reproduce on different cloud provider. Will install same versions of the Istio and Kiali, will deploy some testing applications with dummy traffic (bookinfo + traffic generator) and will check as time goes. In 30 days time span I see there are multiple spikes, assuming pod gets restarted after some event (OOM?).

Please feel free to suggest some apps you are using, or anything which will help reproduce conditions close to your deployment.

**Comment by freefood89** [comment]
Yeah the pod is restarted on OOM. Sorry I haven't had a chance to enable pprof yet

**Comment by jmazzitelli** [comment]
Here's the new docs on the profiler that will be going out in the next release, in case it helps getting started with pprof:

https://staging.kiali.io/docs/configuration/debugging-kiali/#profiler

**Comment by ScriptingShrimp** [comment]
tracking internally as OSSM-8596

**Comment by jmazzitelli** [comment]
> tracking internally as OSSM-8596

Well, I wouldn't say tracking "internally" as that sounds very "un-open source like" - but I think you mean this is also being tracked in JIRA here: https://issues.redhat.com/browse/OSSM-8596

**Comment by freefood89** [comment]
Btw I finally got the profiler running. What do you want me to do? Maybe after running for a week I can send you the .pb output?

**Comment by ScriptingShrimp** [comment]
I was able to partially reproduce @freefood89 's  environment. Demo apps are up and running, can see traffic flowing. Will check periodically what will happen 
```
Kiali version: v1.86.0 
Kiali operator helm chart: 1.86.0
Istio version: 1.22.5
Kubernetes impl: OCP
Kubernetes version: v1.29.10+67d3387
```

**Comment by freefood89** [comment]
This kiali pod has been running about 46hrs

![Screenshot 2024-12-16 at 10 38 47 AM](https://github.com/user-attachments/assets/fbf5d12e-0d95-4ef3-b6d9-c6bd5b5c69b1)

![Screenshot 2024-12-16 at 10 41 03 AM](https://github.com/user-attachments/assets/0bb01d68-7af8-49ec-9a18-73edee31b42e)

**Comment by jshaughn** [comment]
Do you have tracing enabled with `use_grpc: true` ?  Just curious, I'm not seeing anything jump out but the biggest number is related to grpc.

**Comment by freefood89** [comment]
This is all I have for the Kiali CR:

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous
  deployment:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 64Mi
    view_only_mode: true
  external_services:
    prometheus:
      url: http://prometheus-operated.monitoring.svc.cluster.local:9090/
  server:
    profiler:
      enabled: true
```

Also, now the grpc NewClient is using 7M and total mem usage is 500M

![Screenshot 2024-12-17 at 1 05 47 PM](https://github.com/user-attachments/assets/52049ca7-338f-45e5-a54d-f250dd367271)
![Screenshot 2024-12-17 at 1 09 21 PM](https://github.com/user-attachments/assets/2268383d-7e54-41b9-af78-d3845218650b)
