### ISSUE TITLE
Alternative Workload controllers support

### ISSUE THREAD

**Issue by apolovov** [kiali/kiali#7820]
### What do you want to improve?

I want to use alternative workload controllers like [kruise](https://openkruise.io/docs/user-manuals/advanceddaemonset/) for handling workloads.

### What is the current behavior?
We use [kruise](https://openkruise.io/docs/user-manuals/advanceddaemonset/) for handling DaemonSets, but Kiali [uses the standard k8s api to fetch the original DS](https://github.com/kiali/kiali/blob/654d836513d220452de7ad3fa8d272887fb3382b/business/workloads.go#L868) during workload discovery.

### What is the new behavior?

Kiali could discover the api version from Pod's ownerReference to use it for original controller discovery.

```
  ownerReferences:
  - apiVersion: apps.kruise.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: controller-main
    uid: bc83975f-28e0-4dae-b588-1d08b7954861
```
