### ISSUE TITLE
Use multi-cluster secret if it exists in the namespace

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7877]
### What do you want to improve?

When you create a remote cluster secret for Kiali and when you are using helm, you need to manually specify the name of each secret in your Kiali deployment: https://github.com/kiali/helm-charts/blob/e73c85bb20a0b3c0b873c9876f74d4a3916b6abd/kiali-server/templates/deployment.yaml#L145-L154

When using the operator, if you label the secret correctly, the operator will do this for you. But it still requires "waking up" the operator and having it re-reconcile the Kiali CR.

Both deployment methods can be made simpler by
1. Allow multiple remote secrets to be specified in a single secret. Each "key" would be treated as a separate remote secret.
2. Always specify the remote secret volume in the Kiali deployment template but make the mount **optional**. This way when the user creates the remote secret with Kiali running, they can just restart the Kiali pod to have the remote secret mounted into the pod. If the secret does not exist then the pod will startup without it.

**Comment by jmazzitelli** [comment]
This issue could be useful when implementing another feature we are looking to do -- read my comment here for details: https://github.com/kiali/kiali/issues/6941#issuecomment-2734689344

**Comment by jmazzitelli** [comment]
Today, we can [already support multi-cluster secrets](https://github.com/kiali/kiali/blob/v2.7.1/kubernetes/cluster_secret.go#L76-L77) (that is, a single secret with multiple clusters defined within it).

I will propose we support a hardcoded/fixed secret name `kiali-multi-cluster-secret` as an option for users to use. If a user creates a secret with such a name, it does not need to be labeled with anything (e.g. no need for `kiali.io/multiCluster=true` label) but it does need to be in the namespace where the Kiali Server pod is. If such a secret exists, it will be mounted like any other remote cluster secret, and processed as one normally by the server.

Here's what such a secret can look like - this defines two clusters, `mazz-cluster` and `my-other-cluster`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: kiali-multi-cluster-secret
stringData:
  mazz-cluster: |
    apiVersion: v1
    kind: Config
    preferences: {}
    current-context: mazz-cluster
    contexts:
    - name: mazz-cluster
      context:
        cluster: mazz-cluster
        user: mazz-cluster
    users:
    - name: mazz-cluster
      user:
        token: <..........the long token string goes here..........>
    clusters:
    - name: mazz
      cluster:
        server: https://192.168.100.200:8443
        certificate-authority-data: <..........the long ca data goes here..........>
  my-other-cluster: |
    apiVersion: v1
    kind: Config
    preferences: {}
    current-context: my-other-cluster
    contexts:
    - name: my-other-cluster
      context:
        cluster: my-other-cluster
        user: my-other-cluster
    users:
    - name: my-other-cluster
      user:
        token: <..........the long token string goes here..........>
    clusters:
    - name: my-other-cluster
      cluster:
        server: https://192.168.101.202:8443
        certificate-authority-data: <.........the long ca data goes here..........>
```

For testing, You can generate a single cluster secret yaml via `hack/istio/multicluster/kiali-prepare-remote-cluster.sh -astv false --dry-run true -prr false -kcc current -rcc minikube`  (assuming you have "minikube" cluster) and edit it to have multiple ones
