### ISSUE TITLE
cluster [kubernetes] is not found or is not accessible for Kiali

### ISSUE THREAD

**Issue by Justwmz** [kiali/kiali#7886]
### Describe the bug
Trying to get Kiali working on the AKS cluster with the installed Istio addon.
We are using Azure Monitoring Workspace as a Prometheus instance. Inside the cluster, requests to Prometheus are proxied via an AAD Auth Proxy container.
In the Grafana I can see all the metrics from the Istio, but when trying to load the Traffic Graph, Kiali throws an error: cluster [kubernetes] is not found or is not accessible for Kiali.

<img width="1786" alt="image" src="https://github.com/user-attachments/assets/c1052a09-1e22-4f9f-9ff4-050bf5e60143">

On the home page, I see that for one of the namespaces Kiali can display some Traffic stats, but when it comes to the Traffic Graph it doesn't work. (idk if Kiali pulls this data from Prometheus)

<img width="1784" alt="image" src="https://github.com/user-attachments/assets/cb9736a5-8fe7-4c57-86cf-08888cdde8d4">

<img width="1788" alt="image" src="https://github.com/user-attachments/assets/82995018-2e8f-45b7-b16c-f4f9b1828edb">

### Expected Behavior

The Traffic Graph is supposed to be loaded.

### What are the steps to reproduce this bug?

1. Create an AKS Cluster with K8s version 1.30.0
2. Enable Istio Addon in the cluster
3. Configure Grafana + Prometheus inside of cluster
4. Add Prometheus for AMA agent to scrap metrics for istio
5. Install Kiali server 1.86 and adjust config to work with AM based Prometheus

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.86
- **Istio version:** 1.22
- **Kubernetes impl:** AKS
- **Kubernetes version:** 1.30.0
- **Other notable environmental factors:**
Kiali config:

```yaml
    additional_display_details:
    - annotation: kiali.io/api-spec
      icon_annotation: kiali.io/api-type
      title: API Documentation
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    clustering:
      autodetect_secrets:
        enabled: true
        label: kiali.io/multiCluster=true
      clusters: []
    deployment:
      accessible_namespaces:
      - '**'
      additional_service_yaml: {}
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      configmap_annotations: {}
      custom_secrets: []
      dns:
        config: {}
        policy: ""
      host_aliases: []
      hpa:
        api_version: autoscaling/v2
        spec: {}
      image_digest: ""
      image_name: quay.io/kiali/kiali
      image_pull_policy: Always
      image_pull_secrets: []
      image_version: v1.86
      ingress:
        additional_labels: {}
        class_name: nginx
        override_yaml:
          metadata: {}
      ingress_enabled: false
      instance_name: kiali
      logger:
        log_format: text
        log_level: info
        sampler_rate: "1"
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: aks-istio-system
      node_selector: {}
      pod_annotations: {}
      pod_labels:
        sidecar.istio.io/inject: "false"
      priority_class_name: ""
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      secret_name: kiali
      security_context: {}
      service_annotations: {}
      service_type: ""
      tolerations: []
      version_label: v1.86.0
      view_only_mode: false
    external_services:
      custom_dashboards:
        enabled: true
      istio:
        istio_injection_annotation: "istio.io/rev"
        istiod_deployment_name: "istiod-asm-1-22"
        config_map_name: "istio-asm-1-22"
        istio_sidecar_injector_config_map_name: "istio-sidecar-injector-asm-1-22"
        root_namespace: aks-istio-system
        component_status:
          enabled: true
          components:
          - app_label: istiod
            is_core: true
          - app_label: aks-istio-ingressgateway-internal
            is_core: true
            is_proxy: true
            namespace: aks-istio-ingress
      prometheus:
        url: http://azuremonitor-query.default.svc.cluster.local
      tracing:
        enabled: false
    identity:
      cert_file: ""
      private_key_file: ""
    istio_namespace: aks-istio-system
    kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
      disabled_features: []
      validations:
        ignore:
        - KIA1301
    login_token:
      signing_key: CHANGEME00000000
    server:
      observability:
        metrics:
          enabled: true
          port: 9090
      port: 20001
      web_root: /kiali
```

```
2024-11-03T20:31:52Z ERR cluster [kubernetes] is not found or is not accessible for Kiali: goroutine 1924 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/kiali/kiali/handlers.handlePanic({0x26e5f70, 0xc000be8b28})
	/home/runner/work/kiali/kiali/handlers/graph.go:86 +0x1ad
panic({0x1e65e80?, 0xc0014bb370?})
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/kiali/kiali/graph.CheckError(...)
	/home/runner/work/kiali/kiali/graph/util.go:38
github.com/kiali/kiali/graph/telemetry/istio/appender.addBadging(0xc0016ecb40, 0xc0016ecae0, 0xc000b63038)
	/home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:63 +0x445
github.com/kiali/kiali/graph/telemetry/istio/appender.IstioAppender.AppendGraph({0x236ed5c?}, 0xc0016ecb40, 0xc0016ecae0, 0xc000b63038)
	/home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:48 +0x73
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc0016ec930, {0x0, {0xc0012e6cc0, 0x6, 0x6}}, 0x0, 0x1, 0xc0016ec840, ...}, ...)
	/home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x674
github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x2374a39, 0x9}, {0x236ed5c, 0x5}, {{0xc0000d63d9, 0x15}, ...}, ...})
	/home/runner/work/kiali/kiali/graph/api/api.go:52 +0xf0
github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x2374a39, 0x9}, {0x236ed5c, 0x5}, {{0xc0000d63d9, 0x15}, {0xdf8475800, ...}}, ...})
	/home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2f3
github.com/kiali/kiali/handlers.GraphNamespaces({0x26e5f70, 0xc000be8b28}, 0xc000931200)
	/home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
net/http.HandlerFunc.ServeHTTP(0x237ebc7?, {0x26e5f70?, 0xc000be8b28?}, 0x120?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29
github.com/kiali/kiali/routing.NewRouter.metricHandler.func6({0x26e5ee0, 0xc0002542a0}, 0xc000931200)
	/home/runner/work/kiali/kiali/routing/router.go:246 +0x11f
net/http.HandlerFunc.ServeHTTP(0xc0009310e0?, {0x26e5ee0?, 0xc0002542a0?}, 0xc0005e6e00?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29
github.com/kiali/kiali/routing.NewRouter.AuthenticationHandler.Handle.func7({0x26e5ee0, 0xc0002542a0}, 0xc0009310e0)
	/home/runner/work/kiali/kiali/handlers/authentication.go:70 +0x31f
net/http.HandlerFunc.ServeHTTP(0x26f3480?, {0x26e5ee0?, 0xc0002542a0?}, 0x26be3b0?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x26e5ee0?, 0xc0002542a0?}, 0xc0016ec6f0?)
	/home/runner/work/kiali/kiali/server/server.go:185 +0x5c
net/http.HandlerFunc.ServeHTTP(0xc000930fc0?, {0x26e5ee0?, 0xc0002542a0?}, 0x41a298?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006ecf00, {0x26e5ee0, 0xc0002542a0}, 0xc000da1320)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x26df4c0, 0xc0010ea9a0}, 0xc000da1320)
	/home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x27e
net/http.HandlerFunc.ServeHTTP(0xc0006d25b0?, {0x26df4c0?, 0xc0010ea9a0?}, 0x6fc41a?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x471639?, {0x26df4c0, 0xc0010ea9a0}, 0xc000da1320)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc000da2510?}, {0x26df4c0?, 0xc0010ea9a0?}, 0x6?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000038a20, {0x26f3480, 0xc000970420})
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 597
	/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:3285 +0x4b4
```
