### ISSUE TITLE
envoy metrics tab missing when using user-monitoring prometheus in OpenShift

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7954]
On OpenShift, if you install Kiali, Istio, bookinfo normally, in the Kiali UI's Workload page for details-v1 workload, you'll see Envoy>Metrics tab with the envoy metrics.

If you then switch to using the user-montioring Prometheus that is built into OpenShift, the Envoy>Metrics tab disappears.

Here's how to see this (note - you need your OpenShift pull secret file on the filesystem so you can pass it to the crc hack script via the -p option).

1. Put your pull secret on the file system - I will assume it is in `$HOME/pull-secret.txt`
2. Install everything (CRC/OpenShift, Istio, Bookinfo demo, Kiali):
```bash
hack/crc-openshift.sh start --enable-cluster-monitoring true -p $HOME/pull-secret.txt
oc login -u kubeadmin -p kiali https://api.crc.testing:6443 --insecure-skip-tls-verify
podman login --tls-verify=false -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
hack/istio/install-istio-via-istioctl.sh -cp openshift
hack/istio/install-bookinfo-demo.sh -c oc -tg
make build build-ui cluster-push operator-create kiali-create
```
3. After Kiali starts, log into the Kiali UI (username and password are both `kiali`), go to the "details-v1" workload, and look at the Envoy tab - you should see a Metrics sub-tab showing you envoy metrics.
```bash
xdg-open https://kiali-istio-system.apps-crc.testing/console/namespaces/bookinfo/workloads/details-v1?tab=envoy
```

![image](https://github.com/user-attachments/assets/cdbac3cf-8908-4ce5-94bc-3ca23453bc3f)

4. Now that you see it working, switch over to using the user-monitoring Prometheus that is built into OpenShift (NOTE! If you somehow get a "failed to verify certificate" error in the server logs, you need [this PR](https://github.com/kiali/kiali/pull/7956) and then pass in `-pi true` to this command in addition to the other options)
```bash
hack/use-openshift-prometheus.sh -n bookinfo
```

5. Wait for the Kiali pod to restart (follow its progress via `oc get pods -n istio-system -l app=kiali`). Once it restarts, then go back to the Envoy tab and see the Metrics sub-tab is now missing:

```bash
xdg-open https://kiali-istio-system.apps-crc.testing/console/namespaces/bookinfo/workloads/details-v1?tab=envoy
```

**Comment by jmazzitelli** [comment]
I thought maybe the `external_services.custom_dashboards.prometheus` defaults weren't properly falling back to the `external_services.prometheus` settings, so I explicitly duplicated the prometheus settings in both places. It didn't help. The Envoy>Metrics tab still doesn't show up.

To see the "external_services" fields:
`$ oc get kiali kiali -n kiali-operator -oyaml | yq eval '.spec.external_services'`

```yaml
custom_dashboards:
  prometheus:
    auth:
      type: bearer
      use_kiali_token: true
    query_scope:
      mesh_id: mymesh
    thanos_proxy:
      enabled: true
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
prometheus:
  auth:
    type: bearer
    use_kiali_token: true
  query_scope:
    mesh_id: mymesh
  thanos_proxy:
    enabled: true
  url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
```

**Comment by jmazzitelli** [comment]
I think I found the issue:
```
2024-11-22T17:15:05Z ERR custom dashboard discovery failed, cannot load metrics for labels [{namespace="bookinfo",app="details",version="v1",mesh_id="mymesh"}]: Post "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/api/v1/query": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Comment by jmazzitelli** [comment]
With tracing enabled, and after setting the insecure flag, I can see the metrics getting retrieved, and I see the envoy_server_uptime, but yet the Metrics tab is still missing:

```yaml
  external_services:
    prometheus:
      auth:
        insecure_skip_verify: true      <<<============ set to true
        type: bearer
        use_kiali_token: true
      query_scope:
        mesh_id: mymesh
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091

```

```
2024-11-22T17:23:55Z TRC [Prom] GetMetricsForLabels: labels=[{namespace="bookinfo",app="details",version="v1",mesh_id="mymesh"}] metricNames=
[[vertx_http_server_connections tomcat_sessions_created_total jvm_threads_live_threads
pilot_info jvm_threads_live vertx_eventbus_handlers vertx_pool_ratio base:thread_count
envoy_server_uptime vendor:loaded_modules jvm_buffer_total_capacity_bytes go_info
nodejs_active_handles_total vertx_http_client_connections base:gc_complete_scavenger_count]]
```

**Comment by jmazzitelli** [comment]
The problem is here - the query we are executing returns 0 rows - without any metrics getting returned, Kiali server cannot know what dashboards should be used hence you don't see the Envoy>Metrics tab. Not sure why this query returns 0 rows when only using user-monitoring 

https://github.com/kiali/kiali/blob/v2.1.0/prometheus/client.go#L307

**Comment by jmazzitelli** [comment]
OK, the problem is the Prometheus timeseries is missing both "app" and "version" labels.

This query string of `envoy_server_uptime{namespace="bookinfo", mesh_id="mymesh"}` successfully shows metrics with namespace "bookinfo" and mesh_id of "mymesh": https://console-openshift-console.apps-crc.testing/monitoring/query-browser?query0=envoy_server_uptime%7Bnamespace%3D%22bookinfo%22%2C+mesh_id%3D%22mymesh%22%7D

But there is no app or version labels so this query string that Kiali uses returns 0 timeseries: `{namespace="bookinfo",app="details",version="v1",mesh_id="mymesh"}` as seen here: https://console-openshift-console.apps-crc.testing/monitoring/query-browser?query0=%7Bnamespace%3D%22bookinfo%22%2Capp%3D%22details%22%2Cversion%3D%22v1%22%2Cmesh_id%3D%22mymesh%22%7D

**Comment by jmazzitelli** [comment]
I think the answer is to just change the hack script so it keep the app and version labels. We need to enhance the PodMonitor object here: https://github.com/kiali/kiali/blob/v2.1.0/hack/use-openshift-prometheus.sh#L282-L307

Need to figure out the correct relabel entry (perhaps use some kind of regex that drops all labels except the app and version - right now there is a labeldrop that drops everything, which is probably why app and version are missing)

**Comment by jmazzitelli** [comment]
I tried this and still didn't work - I don't know how to get OpenShift's user-monitoring Prometheus to keep the app and version labels:

```diff
diff --git a/hack/use-openshift-prometheus.sh b/hack/use-openshift-prometheus.sh
index ab8f40cc7..035a225f8 100755
--- a/hack/use-openshift-prometheus.sh
+++ b/hack/use-openshift-prometheus.sh
@@ -305,7 +305,7 @@ spec:
       replacement: \$2:\$1
       sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
       targetLabel: __address__
-    - action: labeldrop
+    - action: labelkeep
       regex: "__meta_kubernetes_pod_label_(.+)"
     - sourceLabels: [__meta_kubernetes_namespace]
       action: replace
```

**Comment by jmazzitelli** [comment]
Getting close. This gave me the app and version labels:

```diff
diff --git a/hack/use-openshift-prometheus.sh b/hack/use-openshift-prometheus.sh
index ab8f40cc7..721ccdfb6 100755
--- a/hack/use-openshift-prometheus.sh
+++ b/hack/use-openshift-prometheus.sh
@@ -305,8 +305,16 @@ spec:
       replacement: \$2:\$1
       sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
       targetLabel: __address__
-    - action: labeldrop
-      regex: "__meta_kubernetes_pod_label_(.+)"
+    - sourceLabels:
+      - "__meta_kubernetes_pod_label_app"
+      - "__meta_kubernetes_pod_label_app_kubernetes_io_name"
+      action: replace
+      targetLabel: "app"
+    - sourceLabels:
+      - "__meta_kubernetes_pod_label_version"
+      - "__meta_kubernetes_pod_label_app_kubernetes_io_version"
+      action: replace
+      targetLabel: "version"
     - sourceLabels: [__meta_kubernetes_namespace]
       action: replace
       targetLabel: namespace
```

However, the actual values of the timeseries labels is `details;` and `v1;` (notice the ending semicolon).

Maybe I misunderstand the sourceLabels setting.

**Comment by jmazzitelli** [comment]
This works and I now see the Metrics tab:

```yaml
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      action: replace
      targetLabel: "app"
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      action: replace
      targetLabel: "version"
```
