### ISSUE TITLE
Spans missing References values when Tempo is used

### ISSUE THREAD

**Issue by mkralik3** [kiali/kiali#8112]
### Describe the bug
When Tempo, as external tracing, is used ( tempo native port `3200` on `tempo-sample-query-frontend.tracing-system.svc.cluster.local` service, `provider: tempo`), the References information is missing in the spans objects response from `api/namespaces/bookinfo/workloads/productpage-v1/spans?startMicros=1738580083377000&endMicros=1738580119339000&limit=20` endpoint.
![Image](https://github.com/user-attachments/assets/bd38c951-0a52-42f1-9584-caf495b31772)

When I use Jaeger port `16685` on `tempo-sample-query-frontend.tracing-system.svc.cluster.local` service (and not `provider: tempo` in kiali cr), the spans have References values
![Image](https://github.com/user-attachments/assets/b461b3a8-1de6-4858-be4d-bc9c8042c0fe)

### Expected Behavior
References list is not empty when Tempo is used

### What are the steps to reproduce this bug?
config with tempo:
```
tracing:
  enabled: true
  internal_url: 'http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:3200/'
  use_grpc: false
  external_url: 'http://tracing-ui-tracing-system.apps.user-rhos-d-08.servicemesh.rhqeaws.com/'
  provider: tempo
  tempo_config: {
    url_format: "jaeger"
  }
```

config with Jaeger port in tempo:
```
tracing:
  enabled: true
  internal_url: 'http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:16685/'
  use_grpc: true
  external_url: 'http://tracing-ui-tracing-system.apps.user-rhos-d-08.servicemesh.rhqeaws.com/'
```

### Environment
- **Kiali version: v2.4
- **Istio version: 1.24
OCP 4.17
