### ISSUE TITLE
Suppressing resources when configuring a multi cluster

### ISSUE THREAD

**Issue by lcroms** [kiali/kiali#8124]
Reporting guides I configured a multi cluster, but the resources for that cluster are not showing up and is not found or not accessible for Kiali
error occurs.  
Looking at the logs, it doesn't seem like the connection itself is failing. I'm getting the istio information for that cluster. 
What can I do to fix this issue?

Log information 

<img width="1769" alt="Image" src="https://github.com/user-attachments/assets/aa42f21c-0dc3-443e-bfaf-ee703090a612" />

The configuration was done with cr via operator and kiali-prepare-remote-cluster.sh to create a token secret for the remote cluster on the main cluster side.

Main cluster 
```
cr:
  create: true
  name: kiali
  namespace: ""
  annotations: {}
  spec:
    deployment:
      cluster_wide_access: true
      logger:
        log_level: "debug"
        log_format: "json"
    external_services:
      prometheus:
        url: "internal prometheus url"
    clustering:
      autodetect_secrets:
        enabled: true
        label: "kiali.io/multiCluster=true"
```

Remote cluster
`cr:
  create: true
  name: kiali
  namespace: ""
  annotations: {}
  spec:
    deployment:
      remote_cluster_resources_only: true`
