### ISSUE TITLE
[ambient] Inconsistency of Service Health between pages

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#8189]
### Describe the bug

In Ambient mode, there is inconsistency of Service health between Overview page and Service List/Details pages.
Even though the `health` result presents in responce from backend.

![Image](https://github.com/user-attachments/assets/9e6ea2bc-14c5-4c19-b22d-a355f2465112)
![Image](https://github.com/user-attachments/assets/c598b5d6-5e8c-43af-bd8e-7180e0cfae51)

### Expected Behavior
Service List and details pages should show the Health.

### What are the steps to reproduce this bug?

-   Install Istio Ambient
-   Install Kiali
-   Install bookinfo with:
-     istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true 
-   Modify ratings service to create a validation error:
```
cat <<NAD | kubectl -n bookinfo apply -f -
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9081
    name: http
  selector:
    app: ratings
NAD
```

### Environment
Kiali master,
Istio 1.24.3
