### ISSUE TITLE
[UI] Scroll in tables with sticky headers

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#8197]
### What do you want to improve?
After the UX meeting, there was the recommendation to use a scroll inside the table with sticky headers, instead the full page (Or subpage). This way, it would help to maintain the context. 

There are different pages where there is a full scroll: 

- Applications, Workloads, Services list pages:

![Image](https://github.com/user-attachments/assets/7e799949-2307-452f-84db-065c9fbbae4c)

- Envoy tab: 
![Image](https://github.com/user-attachments/assets/8ae4bed7-a773-4151-8cb4-59b0a1b87231)

- Another comment was to keep a max height when there are many pods in the details pages:

![Image](https://github.com/user-attachments/assets/e5d96703-656b-4364-b9a1-fca811e4e0f1)

Ex.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 12 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest  
          ports:
            - containerPort: 80
```

### What is the current behavior?
The scroll in created for the whole tab.

### What is the new behavior?
Use scroll just in table and keep a "sticky" header. Ex in ztunnel tab:

![Image](https://github.com/user-attachments/assets/9bf9a876-51d6-4a55-8e1d-cac5cdbfcc71)
