### ISSUE TITLE
Support merging of multiple Istio configmaps

### ISSUE THREAD

**Issue by clarenceb** [kiali/kiali#8248]
### What do you want to improve?

I want Kiali to support loading and merging multiple Istio ConfigMaps.

### What is the current behavior?

The current Kiali behaviour for discovering and loading the Istio configmap is as follows:

1. Check if a specific configmap has been configured in `external_serrvices.istio.config_map_name` in the Kiali configmap (usually called `kiali` in namespace `istio-system` but the namespace can be overridden).
2. If no specific istio revision name is found for the control plane, then default to the configmap name `istio`
3. If a specific istio revision name is found for the control plane then look for the configmap name `istio-<revision>`

See: https://github.com/kiali/kiali/blob/a9d4d81f33be15165414a400f437e31a9a983e15/istio/discovery.go#L78

Only a single istio configmap is loaded and parsed, see: https://github.com/kiali/kiali/blob/a9d4d81f33be15165414a400f437e31a9a983e15/istio/discovery.go#L89

### What is the new behavior?

Support loading and merging multiple Istio configmaps into a single `IstioMeshConfig` struct.

Each subsequent configmap takes priority  (overrides values) when merging into the final result.

This could be implemented in different ways.  One option is comma-separated list in the `kiali` configmap like so:

```yaml
external_serrvices:
  istio:
    config_map_name: istio-asm-1-23,istio-shared-configmap-asm-1-23
```

This is a bit hacky.

Or introduce a new list key like so:

```yaml
external_serrvices:
  istio:
    config_map_names:
    - istio-asm-1-23
    - istio-shared-configmap-asm-1-23
```

To be non-breaking, the existing `config_map_name` key could be retained but if `config_map_names` exists then use that instead.

### Why is this needed?

I am using the Kiali operator with the Azure Kubernetes Service (AKS) [Istio add-on](https://learn.microsoft.com/en-us/azure/aks/istio-about) - a managed add-on supported by Microsoft.  This Istio add-on disallows editing of the global Istio configmap in order to reduce the supported configurable service area.  Instead, a separate config file `istio-shared-configmap-<asm-revision>` is supported for users with a reduced configuration footprint, see: https://learn.microsoft.com/en-us/azure/aks/istio-meshconfig#allowed-supported-and-blocked-meshconfig-values

Specifically, I am setting `outboundTrafficPolicy.mode` to `REGISTRY_ONLY` and the Istio add-on detects this and enforces this policy.  However, Kiali always shows the outbound policy as `ALLOW_ANY` since it does not parse the AKS-specific configmap.  Also, I cannot see serviceentries rendered in the Traffic Graph which I believe is a result of this setting not being detected in Kiali.

Supporting the ability to load, parse and merge settings from more than one configmap would allow Kiali to work properly with the AKS managed istio add-on instead of having to self-install the upstream version of Istio.

This feature would be generic and not tied to AKS in any way since the request is just to support more than one config file to be parsed.  Both these config files exist in the same namespace.  In my cluster these are in the `aks-istio-system` namespace:

- `istio-asm-1-23` the system controlled configmap

```yaml
kind: ConfigMap
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod-asm-1-23.aks-istio-system.svc:15012
      gatewayTopology:
        numTrustedProxies: 1
      image:
        imageType: distroless
      tracing:
        zipkin:
          address: zipkin.aks-istio-system:9411
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    rootNamespace: aks-istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
metadata:
  name: istio-asm-1-23
  namespace: aks-istio-system
```

- `istio-shared-configmap-asm-1-23`  the user contolled configmap (optional)

e.g.

```yaml
kind: ConfigMap
apiVersion: v1
data:
  mesh: |-
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
metadata:
  name: istio-shared-configmap-asm-1-23
  namespace: aks-istio-system
```
