### ISSUE TITLE
Difference in Istio and Kiali Workload Name for Argo Rollouts

### ISSUE THREAD

**Issue by haughters** [kiali/kiali#8284]
### Describe the bug

Hello! I'm trying to perform canary deployments using Argo Rollouts with Istio. I'd like to use Kiali as a visualisation of traffic distribution mid rollout. The Traffic Graphs does not align with my expectations, and has 3 workloads - two idle and one non-existent.

When looking at the traffic graph with Idle Nodes on, I see 3 versions:
<img width="1490" alt="Graph" src="https://github.com/user-attachments/assets/456072a9-6918-4177-8703-1e9a3f9107d8" />

Two are ReplicaSets, identified by Kiali. The third with all traffic is the non-existent workload:
<img width="1275" alt="Telemetry Workload" src="https://github.com/user-attachments/assets/de98afd4-fa9e-47d6-a413-a881ce6ca1f2" />
<img width="925" alt="Telemetry Workload Not Found" src="https://github.com/user-attachments/assets/3994f9da-02df-4d6a-901f-b431c528917f" />

The ReplicaSets with the 'real' Workloads and correct versions exist, but report no traffic:
<img width="1286" alt="Real Workload" src="https://github.com/user-attachments/assets/47729483-f195-4bf1-b5ea-6e6ba1dd1bd2" />

I've done some digging, and found about a year ago, [Istio added some logic to specifically alter the workload name for Argo Rollouts to be the Rollout Name](https://github.com/istio/istio/pull/49256), not the ReplicaSets/Pods (Was surprised a CRD specific check was added here).  However [Kiali retrieves the workloads as the ReplicaSets](https://github.com/kiali/kiali/issues/5261#issuecomment-1254041578).

Should Istio and Kiali source the same data for the workload? I believe the above graphs are caused by this conflict between how Istio Telemetry and Kiali see these Workloads. I'm asking here as I was looking at the visualisation, but happy to ask on the Istio side too.

Any thoughts really welcome, I'd love to see a nice separated graph to make it clear to the end user if the traffic routing is working! 😊 Here it has some visibility because I'm using separate services, however in Subset mode, we have no visibility.

### Expected Behavior

Mid rollout, I'd expect to see the canary service pointing to the canary version of the app, and the stable pointing at the stable. The non-existent workload shouldn't be visible.

### What are the steps to reproduce this bug?

1. Install Argo Rollouts on cluster
2. Deploy the Istio Example
3. Send traffic and view Traffic Graph in Kiali

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** v2.6.0
- **Istio version:** 1.25.0
- **Kubernetes impl:** K3S
- **Kubernetes version:** v1.32.3+k3s1
- **Other notable environmental factors:** N/A

Graph Debug: [debug_additional_state.txt](https://github.com/user-attachments/files/19511866/debug_additional_state.txt)

**Comment by jmazzitelli** [comment]
sounds related to some earlier work that was done to support argo - https://github.com/kiali/kiali/pull/5491

**Comment by jshaughn** [comment]
OK, so it sounds like the special work we did to support Istio's original way of handling Argo Rollouts is now out of date, and that they changed things to be what we wanted in the first place :-(.

Looks like we need to redo the handling here.

**Comment by hhovsepy** [comment]
Hi @haughters , can you provide the exact commands of steps how you executed, fo us to replicate the same env and test the solution before releasing?

**Comment by haughters** [comment]
Hi @hhovsepy! Of course, not a problem. I was using the Argo Rollouts demo in order to perform the tests above (all below taken from [their docs](https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/istio/)):

### Install Argo Rollouts
The below creates the namespace, installs Argo's resources and CRDs
```bash
kubectl create namespace argo-rollouts
kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
kubectl apply -k https://github.com/argoproj/argo-rollouts/manifests/crds\?ref\=stable
```

### Install Demo App
Installs an Argo Rollouts Rollout using Istio, using a Gateway and VirtualService to perform the traffic management:
```bash
kubectl apply -f https://raw.githubusercontent.com/argoproj/rollouts-demo/refs/heads/master/examples/istio/gateway.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/rollouts-demo/refs/heads/master/examples/istio/services.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/rollouts-demo/refs/heads/master/examples/istio/virtualservice.yaml
```

Then this Rollout also needs applied:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: istio-rollout
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: istio-rollout
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: istio-rollout
    spec:
      containers:
      - name: istio-rollout
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    canary:
      canaryService: istio-rollout-canary
      stableService: istio-rollout-stable
      trafficRouting:
        istio:
          virtualService:
            name: istio-rollout-vsvc
            routes:
            - primary
      steps:
      - setWeight: 50
      - pause: {}         # pause indefinitely
```

We can check this rollout via:
`kubectl argo rollouts get rollout istio-rollout`
<img width="520" alt="Image" src="https://github.com/user-attachments/assets/0d79941c-e7b2-4534-83a4-f3075c4343c5" />

### Update the image to trigger a Rollout
The below starts a rollout to the 'purple' image. The Rollout will automatically route 50% to this new pod, which should be enough for us to verify the split:
`kubectl argo rollouts set image istio-rollout istio-rollout=argoproj/rollouts-demo:purple`
Then verify the rollout status:
`kubectl argo rollouts get rollout istio-rollout`

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/5a85628d-4c31-4e29-916f-250b146bbcc6" />

### Run traffic to view in Kiali
I've just been testing by curling the gateway in order to simulate some traffic:
```bash
for i in $(seq 1 20); do curl --request GET --url http://localhost:80 --header 'Host: istio-rollout.local'; sleep 1; done
```

This should show the canary/stable split in Kiali:
<img width="670" alt="Image" src="https://github.com/user-attachments/assets/dee45c2e-95b3-4532-b8ee-45a102e43b07" />

Anything else please let me know!
