### ISSUE TITLE
Destination Rule: This host has no matching workloads

### ISSUE THREAD

**Issue by Evesy** [kiali/kiali#837]
**Describe the bug**
Destination Rule host validation appears to work by taking the `host` field, parsing it to just extract the service (e.g. `service` in `service.default.svc.cluster.local`), and then looking for matching workloads with an `AppLabel` that matches.

I don't believe this is required for Istio configuration to be valid, and I can't find anywhere in the Istio docs that say this must be the case (https://istio.io/docs/setup/kubernetes/spec-requirements/)

The example below is a working Istio configuration that fails this validation since the service address does not match up with the `AppLabel` used:

**Destination Rule:**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    app: mmv
    group: delivery-platform
    heritage: Tiller
    release: mmv
  name: mmv
  namespace: mmv
spec:
  host: app
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
```

**Virtual Service:**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: mmv
    group: delivery-platform
    heritage: Tiller
    release: mmv
  name: mmv
  namespace: mmv
spec:
  hosts:
  - app
  - app.mmv.preprod.k8.tld.io
  - admin.mmv.preprod.k8.tld.io
  http:
  - appendHeaders:
      x-envoy-max-retries: "10"
      x-envoy-retry-on: gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: app
      weight: 100
    timeout: 10s
```

**Kiali GET /api/namespaces/mmv/workloads**
```
{
  "namespace": {
    "name": "mmv"
  },
  "workloads": [
    {
      "name": "mmv",
      "type": "Deployment",
      "istioSidecar": true,
      "labels": {
        "RESTARTED_ON": "1544870673",
        "app": "mmv",
        "group": "delivery-platform",
        "version": "e4b45f287714a2db97e2d73372dad9006e9846bb"
      },
      "appLabel": true,
      "versionLabel": true,
      "podCount": 1
    }
  ]
}
```
For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v0.14
Istio: 1.0.5
Kubernetes flavour and version: GKE 1.11.6

**Expected behavior**
If the Destination Rule host matches a Kubernetes service validation should pass
