### ISSUE TITLE
Kiali claims invalid subset definition, and no traffic; despite Istio properly routing to it.

### ISSUE THREAD

**Issue by eddiewebb** [kiali/kiali#8446]
### Describe the bug

using Argo Rollouts canary to control ingress across a stable and canary workload using Subsets of a DestinationRule.

The applications are properly routed, as evidenced by transaction metrics collected by Prometheus, but **Kiali still insists all traffic is flowing only to the stable version.  When looking at the Destination Rule it intermittently suggest neither is valid, or that only the stable is valid.**

### Expected Behavior

If traffic is 50/50 split across 2 workloads I would expect validation to work, and visualization to show the split.

### What are the steps to reproduce this bug?

1. Define a single service with selector `app=myapp`
2. Define two distinct workloads `app=myapp, version=1` and `app=myapp, version=2`
3. Define a `DesitinationRule` using the app label for workload selection
3. Use Argo rollouts, which dynamically appends a `rollouts-pod-template-hash=XXXX` to workload selection

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 2.10.0  ( upgraded from 1.88 with no change)
- **Istio version:** 1.26.0 (upgraded from 1.22.0 with no change)
- **Kubernetes impl:**  EKS
- **Kubernetes version:** v1.30.11-eks-bcf3d70
- **Other notable environmental factors:**
- using Argo Rollouts

#### This subset's labels are not found in any matching host
Screenshot says no workload exists (sometimes just for the canary)

![Image](https://github.com/user-attachments/assets/c1e66a84-13a1-40a3-a575-674d2088d3f3)

Sometimes for both workloads

![Image](https://github.com/user-attachments/assets/82b40006-8b56-41d6-86b1-d081899280fd)

But kubectl confirms matching workload labels do exist

![Image](https://github.com/user-attachments/assets/cad8a15d-4fc5-4cef-913e-68881b1796c0)

#### Kiali Visuals and stats report no traffic, but prometheus is logging them appropriately
I can also manually hit the endpoints and confirm a 50/50 split in version coming back

![Image](https://github.com/user-attachments/assets/e0c58280-a0c4-4244-9470-2b1b7c09f9e1)

Prometheus metrics showing that traffic of ~15 rps is actually split across two workload versions. 
![Image](https://github.com/user-attachments/assets/98b7a334-e20c-4975-b65c-c6fc7e761211)

#### Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: circle-shop-service
  namespace: circle-shop-dev
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: circle-shop
```

#### DestinationRule
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rollout-destrule
  namespace: circle-shop-dev
spec:
  host: circle-shop-service
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: circle-shop
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected with stable rollouts-pod-template-hash value
      app: circle-shop
```

#### VirtualService
```yaml
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: circle-shop-service
  namespace: circle-shop-dev
spec:
  hosts:      
    - "{{ .Values.subdomain }}.demo.{{ .Values.domain }}"
  gateways:
    - {{ .Values.gateway.name }}
  http:
    - name: primary
      route:
      - weight: 100
        destination:
          host: circle-shop-service
          subset: stable
      - weight: 0
        destination:
          host: circle-shop-service
          subset: canary

```

#### Argo ROllout
```yaml
 strategy:
    canary:
      stableMetadata:
        labels:
          canary-status: stable
      canaryMetadata:
        labels:
          canary-status: canary
      analysis:
        templates:
          - templateName: circle-shop-checkout-rate
          #- templateName: circle-shop-success-rate
          - templateName: circle-shop-checkout-count
      trafficRouting:
        istio:
          virtualService:
            name: "circle-shop-service"
            routes:
            - primary
          destinationRule:
            name: rollout-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      
      steps:
      - setWeight: 50
      - pause: {}
```

I hope i've articulated the issue clearly, but please let me know what other details or evidence I should collect.

**Comment by jmazzitelli** [comment]
In your Prometheus screenshot, which metric is that graphing?

**Comment by eddiewebb** [comment]
@jmazzitelli  - it's a custom counter metric the application emits that includes it's own app_version and canary/stable label as informed by that release.



```
# TYPE checkout_count counter
checkout_count{label="stable",app_version="1.2.3-RC145"} 73507 1747850661000
```

Query is just a rate of that counter

```
sum by(label, app_version) (rate(checkout_count{service="circle-shop-service"}[90s]))
```

**Comment by jmazzitelli** [comment]
> it's a custom counter metric the application emits

Right - so that is not what Kiali graphs. Kiali graphs the Istio metrics in Prometheus. So you have to check to see that Istio telemetry has what you expect. If Istio's telemetry is wrong, so will Kiali's graph (since Kiali just graphs what Istio gives it).

So - read this FAQ and check your Prometheus data and see what Istio's telemetry shows: https://kiali.io/docs/faq/graph/#queryprom

```
How do I inspect the underlying metrics used to generate the Kiali Graph?
It is not uncommon for the Kiali graph to show traffic that surprises the user.
Often the thought is that Kiali may have a bug.
But in general Kiali is just visualizing the metrics generated by Istio
...
```

**Comment by jshaughn** [comment]
I think this may be the same issue as reported in https://github.com/kiali/kiali/issues/8284, which is fundamentally an issue in the Istio metric reporting. @hhovsepy , what do you think?

**Comment by eddiewebb** [comment]
@jshaughn  - I agree that looks like the same issue!

**Comment by eddiewebb** [comment]
Oh, but that is closed:

> The fix will be available with upcoming Kiali v2.9

I am on 2.10 and still seeing it.

**Comment by eddiewebb** [comment]
@jmazzitelli  querying `istio_total_requests` matches what I would expect (stable version rate drops while canary climbs, eventually splitting the load)

Furthermore, the validation errors thrown on the Destination Rule would be unrelated to telemetry right?

![Image](https://github.com/user-attachments/assets/564d2648-9a33-4080-809c-0f0fe0ea8d31)

**Comment by jmazzitelli** [comment]
> the validation errors thrown on the Destination Rule would be unrelated to telemetry right?

yes, that seems a separate and distinct issue

**Comment by eddiewebb** [comment]
@jmazzitelli  - do you think it would be covered by https://github.com/kiali/kiali/issues/8224, or should I create a new one for the validation error?

**Comment by jmazzitelli** [comment]
Let's see what @hhovsepy thinks - he's our validations expert and has been dealing with Argo related issues recently.

**Comment by hhovsepy** [comment]
Hi @eddiewebb , thanks for details logging,
yes there are 2  issues here, one for a validation (https://github.com/kiali/kiali/issues/8224 will not cover it), and second is the workload versions shown in Graph , so far let's leave it within this single issue unless we figure out that the cause if issues is different.

This issue https://github.com/kiali/kiali/issues/8284 was mainly resolving the linking problem.
Argo Rollouts support in Kiali side is limited. So we need more input to reproduce those scenarios.

Can you provide the full content of the 'Rollout' file?

**Comment by eddiewebb** [comment]
Thank you @hhovsepy, follows is the full rollout definition.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: circle-shop
  namespace: {{ .Values.namespace }}
  labels:
    app: circle-shop
    version: "{{ .Values.version }}"
  annotations:
    circleci.com/project-id: {{ .Values.project_id }}
    circleci.com/scale-version-enabled: "true"
    circleci.com/restart-version-enabled: "true"
    circleci.com/restore-version-enabled: "true"
    circleci.com/helm-revision-number: {{ .Release.Revision | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: circle-shop
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: circle-shop
        version: "{{ .Values.version }}"
    spec:
      containers:
      - name: circle-shop
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 64Mi
            cpu: 50m
        env:
        - name: SHOP_URL
          value: "https://{{ .Values.subdomain }}.demo.{{ .Values.domain }}"
        - name: CONVERSION_RATE
          value: "{{ .Values.conversion_rate }}"
        - name: LOGIN_WORKING
          value: "{{ .Values.login_working }}"
        - name: APP_VERSION
          value: "{{ .Values.version }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items: 
            - path: "labels" 
              fieldRef:
                  fieldPath: metadata.labels 
  strategy:
    canary:
      stableMetadata:
        labels:
          canary-status: stable
      canaryMetadata:
        labels:
          canary-status: canary
      analysis:
        templates:
          - templateName: circle-shop-checkout-rate
          #- templateName: circle-shop-success-rate
          - templateName: circle-shop-checkout-count
      trafficRouting:
        istio:
          virtualService:
            name: "circle-shop-service"
            routes:
            - primary
          destinationRule:
            name: rollout-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      
      steps:
      - setWeight: 10
      - pause: {duration: 300s}
      - setWeight: 30
      - pause: {duration: 300s}   
      - setWeight: 70
      - pause: {duration: 300s}
      - setWeight: 100
      - pause: {duration: 300s}
```
