### ISSUE TITLE
[Tracing tool] Improve coverage when auth is specified but not required

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#8494]
### What do you want to improve?
The tracing tool doesn't detect valid urls when the auth section is specified, but no authentication is required. 

### What is the current behavior?
When the configuration is the following (With Jaeger): 

```
  tracing:
    enabled: true
    provider: "jaeger"
    auth:
      insecure_skip_verify: false
      password: any
      type: basic
      use_kiali_token: false
      username: internal
    external_url: ""
    internal_url: "http://localhost:16686/jaeger"
```
gRPC (16685) and http (16686) ports are open (port-forward if Kiali is running outside the cluster). 

There is an error: 
`ERR Error creating client grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials)`

And no valid configs are returned.

### What is the new behavior?
Capture the error, try gRPC without credentials, and return valid configurations.
