### ISSUE TITLE
Feature Request: API_NAMESPACES_INCLUDE 

### ISSUE THREAD

**Issue by monkeymorgan** [kiali/kiali#868]
To run Kiali on a multi-tenant cluster it would be preferable to have a whitelist to opt-in to Kiali rather than a blacklist to opt-out. 

At present the owner of the Kiali deployment must use API_NAMESPACES_EXCLUDE to list all namespaces to be ignored, and since new tenants can later be added to the cluster, this must be maintained. One way to solve this would be to add a whitelist API_NAMESPACES_INCLUDE which if defined is processed before the blacklist (API_NAMESPACES_EXCLUDE) in a backwards compatible manner.  

Another strategy is to use a namespace selector to opt-in however that style would clash with the current configuration (it does however allow tenants to opt-in without editing the kiali deployment config). Since that's less consistent with the existing config I propose the following : 

The following still applies: 

```
api:
  namespaces:
    exclude:
    - namespacePattern1
    - namespacePattern2
```
- Kiali considers all namespaces apart from namespacePattern1 and namespacePattern2

However, include can be also be defined : 

```
api:
  namespaces:
    exclude:
    - namespacePattern2
    include:
    - namespacePattern1
```
- Kiali considers (results of namespacePattern1 regex) minus (results of namespacePattern2 regex)

To simply use opt-in : 

```
api:
  namespaces:
    include:
    - namespacePattern1
```
- Kiali considers (results of namespacePattern1 regex) 

This would ease deploying Kiali to clusters using soft multi-tenancy :)
